### ISSUE TITLE
Decide whether or not German version should keep the GLA Barrel Terrorist model + sounds

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#100]
Decide whether or not German version should keep the original GLA Barrel Terrorist model + sounds.
German players may have gotten used to it and may prefer to keep it?
It is located in W3DGermanZH.big file.

[W3DGermanZH.zip](https://github.com/xezon/GeneralsGamePatch/files/7071422/W3DGermanZH.zip)

**Comment by commy2** [comment]
>  German players may have gotten used to it and may prefer to keep it?

Now that's Stockholm syndrome.

**Comment by KaSSaDo** [comment]
I have been playing with German version for all my life and if I ever wanted to change that I could have downloaded an uncut patch, no? Is there a single reason why you would want to change my German version?

**Comment by xezon** [comment]
I am thinking the same way. Game Patch version should not contain any uncut features. We will likely provide an optional feature with language download, which would then contain an improved German version however (removed Robot images and voices).
