### ISSUE TITLE
Some audio lines have humming recorded into them

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1058]
Some audio lines have humming recorded into them.

Example: Data\Audio\Sounds\English\vtromoe.wav

Perhaps cleanup those sounds that are most affected by this.

**Comment by ExiLe-ZH** [comment]
I could try and fix this, I have some audio mixing experience and got a professional daw.

**Comment by xezon** [comment]
I am already on it. Still reviewing English sounds.
