### ISSUE TITLE
Menu improvements master topic

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#106]
We need to get an overview of what we can and want to change in the game menus. There is a lot of room for improvements, because the original game menus are not well polished.

Potential action items:
- Fix ui element position errors
- Reorganize ui element positions
- Remove obsolete ui elements
- Add hidden ui elements (for example AA setting in Options Menu, player list in LAN Lobby)
- Add text elements to help explain functionality, such as "Alternative Mouse Setup" in Options
- Improve textures (for example Zero Hour logo looks bad, score screen does not show accurate faction icons)
- Improve functionality (for example increase list box sizes and limits)

I suggest to take a look at all menu windows and note down all high level action items that become apparent.
We can also look at various other Mods to get inspiration for potential improvements.
We can also check if there is a Mod with menu changes that is suitable to use as a starting point.

**Comment by xezon** [comment]
Main Menu or Options menu should print new game version label confirming the installation of Patch104p. Ideally original version number label (1.00 .. 1.04) is preserved.

**Comment by MTKing4** [comment]
One thing to keep in mind which is the Main menu options' positions, we don't want to brake Gameranger's auto clicker

**Comment by xezon** [comment]
Stubbjax:
> I know a few people who passed on the game due to the fact that left-click was the action button (by default), which was confusing compared to the more standardised right-click in most other RTS games at the time. They didn't realise it could be changed until it was too late.

**Comment by xezon** [comment]
We can make a pass on all WND files and correct WINDOWTYPE erros. See:
https://github.com/xezon/GeneralsControlBar/commit/9abc7697c7ec2ade61e96513e040813c6a3234fb

We can also fix indentations in WND files. See:
https://github.com/xezon/GeneralsControlBar/commit/9d5edaf63978e926a79a91f9cd1fc72021742fad

**Comment by xezon** [comment]
We should add new HeaderTemplates to all SCROLLLISTBOX elements, so that font upscales do not break them.

**Comment by xezon** [comment]
A very common issue report is the "I cannot connect to online" when the wrong IP is selected in the Game Options menu. We could mention this common source of error in the Connection Failed popup and/or in the Connection screen. This way user may be better guided to the cause of the issue.
