### ISSUE TITLE
China ECM tank behaves differently between China factions

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#108]
China ECM tank behaves differently between China factions. Figure out what to do about it.

**Comment by commy2** [comment]
vChina does not auto-attack nearby enemies when idle, only when in Guard mode.

Tank/Nuke/Inf does auto attack the nearest enemy.

See: https://github.com/commy2/zerohour/commit/68befac03dabebf6dee270f63ef78d09bf538196

**Comment by xezon** [comment]
There are different options:
- Make all ECM Tanks behave the same
- Explain this ECM Tank difference in UI Tooltip
- Give ECM Tank slightly different model to signal different functionality

**Comment by Jundiyy** [comment]
I would prefer 2 or 3.
3 would be great actually although might possibly throw some people off? I'd love it though if all agree.

**Comment by Jundiyy** [comment]
I'm not 100% sure as I'm really bad with modelling but I think it's really easy to add extra army colour (housecolour) to units, could add an extra line or 2 going across the front (and back). So that could be a simple 'new model' if we can't get anything else (and it is the way we choose).

**Comment by commy2** [comment]
I'm for making all of them behave the same. Not auto attacking, since that is the one that makes the most sense for this unit, as attacking turns off the jammer.

**Comment by xezon** [comment]
I also prefer to have them all behave the same for consistency sake. They could all behave like the China one, or the other one. Either behaviour would be reasonable.

**Comment by RisingZH** [comment]
Should all behave the same, regardless of faction. Should auto attack enemy unit if idle and player has retaliation mode on (like any other unit would).

**Comment by ExiLe-ZH** [comment]
All should be the same and I prefer china's V behavior, because I feel it's the intended behavior.

The focus of micro'ing a unit should be on what it should be doing, not preventing it from doing something. That's just annoying and takes time away of micro'ing other important units.

Also where "micro" is taken away, new micro needed when wanting to disable units, which can be crucial ones like incoming TT's or sneaky dragons (guard mode could be used). Also mass disabling units still need the same micro.

**Comment by ZekeDlyoung** [comment]
I also vote for all of them acting the same as the vchina one as it offers the most flexibility:
- if you need a missile shield then park it somewhere and leave it alone
- if you need to disable something, just manually tell it to do so, like how artillery works

It will still auto-attack when guarding or doing an attack move anyway

**Comment by Madrageeeeee** [comment]
Agree with Rising here. Auto disable with retaliation on makes sense. 

All the same also makes sense between factions

**Comment by xezon** [comment]
Fixed with
* #631
