### ISSUE TITLE
Re-evaluate the removal of the Heat Haze Effect

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#109]
We removed the Haze Effect from the Microwave Tank and GPS Scrambler to avoid having users run into rendering issues. There is valid critique that this beautiful effect is force disabled. Maybe we can leave it in but help prevent issue in other ways.

**Comment by commy2** [comment]
Iirc, there already is an option in the ingame options menu to disable post processing effects.

**Comment by xezon** [comment]
Yes there is. What we could do is, append some extra text information to it, informing player that enabling it CAN cause graphical issues on some systems. This may help users to identify the solution if their system is affected.

A typical manifestation of the rendering issue is a black world with the Control Bar still visible.

See:
https://www.gamereplays.org/community/index.php?s=&showtopic=1028649&view=findpost&p=10236095

![post-358590-1572251280](https://user-images.githubusercontent.com/4720891/131247656-a2b39663-c19a-43fc-a3bc-bff45c44087c.png)

**Comment by xezon** [comment]
Here is another case where user has this problem:
https://www.gamereplays.org/community/index.php?showtopic=1056620

**Comment by xezon** [comment]
Another way to address this problem, would be a force override in our Patch Loader, that disables Heat Effects in Options.ini always. User must manually disable it in Patch Loader, which educates user about potential bad consequences. This way issue is avoided by default, but if player really wants heat effect, then he can enable it here.

If Heat Effects are disabled by default on fresh game install, then we could also add a new text description (localized) in the Game Options Menu that explains the dangers here. That would be most elegant.

**Comment by ExiLe-ZH** [comment]
Can we edit the default graphical presets of low med high? Then just disable it there instead of overriding it externally?

**Comment by ZekeDlyoung** [comment]
> Can we edit the default graphical presets of low med high? Then just disable it there instead of overriding it externally?

Doesn't work if they have "Disable Dynamic Level of Detail" checked in video options.

**Comment by xezon** [comment]
This is a very good idea if it can be done.

**Comment by xezon** [comment]
Revert of Haze Effect removal has been applied to main branch, because the particle replacement caused serious performance degradation as per TheSuperHackers/GeneralsGamePatch#1519.

* Related to TheSuperHackers/GeneralsGameCode#90
