### ISSUE TITLE
GLA Demo Technical is missing correct suicide animation when moving and suicided with Demo Upgrade

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#110]
When GLA Demo Technical drives and suicides, it will immediately stop, incorrectly turn the destruction model and then just disappear after a moment.

![shot_20210829_143149_2](https://user-images.githubusercontent.com/4720891/131250512-65b4340c-9eae-445b-8dec-a398f9c8fe23.jpg)

**Comment by commy2** [comment]
![shot_20220815_212905_2](https://user-images.githubusercontent.com/6576312/184704029-7d3dca9d-d7bd-4938-a55f-b0f7f4ba8543.jpg)
![shot_20220815_212906_4](https://user-images.githubusercontent.com/6576312/184704036-12f5ac49-4e39-4fff-a176-52f4f3f5c641.jpg)
![shot_20220815_212907_5](https://user-images.githubusercontent.com/6576312/184704038-88ff7222-42d0-4975-88e8-c1f1ba6e5e22.jpg)

Looks good to me.

**Comment by xezon** [comment]
Indeed. Something fixed it and it looks good now.

## Original

https://user-images.githubusercontent.com/4720891/184708158-730c5ca3-a12d-4671-88e5-53f186682b8f.mp4

## Patched

https://user-images.githubusercontent.com/4720891/184708173-80396061-5fd2-4e06-b07f-02d0f76d779c.mp4

**Comment by commy2** [comment]
Was fixed in https://github.com/TheSuperHackers/GeneralsGamePatch/pull/99

**Comment by Jundiyy** [comment]
Makes Demo Tech op
