### ISSUE TITLE
Invent a name for this project

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#112]
Current project name is Generals Game Patch or Patch104p. This is ok for internal use, but we need a better public facing name. Ideally it is descriptive but also catchy to end up in room titles and web search. Name may not contain "Patch". Name may not contain any version number. Could be as simple as a MacOS version name: A word and a year.

**Comment by RisingZH** [comment]
.

**Comment by xezon** [comment]
Patch contents in a nutshell: "Less crashes. Less bugs. Original design. Better AI. Better graphics. More fun: Patch XXX"

**Comment by ZekeDlyoung** [comment]
GenPatch 😛

**Comment by xezon** [comment]
People like things that say "Pro" in it. So maybe **Generals Zero Hour Professional** aka **Generals Zero Hour Pro** aka **Generals ZH Pro** aka **ZH Pro** aka **zhpro**. See it becomes very short - good for chat communications :-)

**Comment by MTKing4** [comment]
Just let it be 1.7 this is as professional as it gets, continuing on the legacy EA left out
For a catchy name you could call it 
**Zero hour Complete Edition** = **ZHCE**
Or **Project Zero hour** = **PZH**
Or **Zero hour Final** = **ZHF**
Last one might be a little grim though
"Pro" is overrated

**Comment by xezon** [comment]
Zero Hour Final 2 Revision 5 Beta 10

**Comment by ZekeDlyoung** [comment]
Zero Hour **_X_**

**Comment by RisingZH** [comment]
Whatever name format you choose I would allow for the possibility of a further patch being released in the future.

**Comment by xezon** [comment]
Generals First Hour
Generals Final Hour
Generals Zero Hour Remastered
Generals Zero Hour Fixed
Generals Zero Hour Pro
Generals Zero Hour +++
Generals Zero Hour Community Edition
Generals Zero Hour 2
Generals Zero Hour 1.10
Generals Zero Bugs
Generals Zero Work
Generals Zero Hour Final
Generals Zero Hour Final Victory

**Comment by MTKing4** [comment]
> Generals Zero Hour Community Edition

I like this one

> Generals Zero Hour 2

This one is alright too

> Generals Zero Hour 1.10

I like having numbers so that we can increment them later on when we do an update, and basically keep it open so if we decided to do an update we can.
This one is good because it allows us to make our numbering from scratch

**Comment by Madrageeeeee** [comment]
I like the ‘pro’ in the title. Also like Zero Hour 2

Perhaps something with ‘elite’?

**Comment by xezon** [comment]
Generals Zero Hour Mad Rage Edition

**Comment by MTKing4** [comment]
Generals Zero Hour Ultimate Edition

**Comment by ReLaX82** [comment]
Pro In title and a Version number.

**Comment by xezon** [comment]
Generals Zero Hour Community Patch
Generals Zero Hour Super Patch
Generals Zero Hour Super Hackers
Generals Super Hour
Generals First Hour
Generals Zero Hour Lite
Generals Zero Hour Refurbished
Generals Zero Hour Dawn
Generals Zero Hour: The Beginning
Generals Zero Hour Pure Ownage
Generals Zero Hour Elite
Generals Zero Hour The Final Rush

**Comment by xezon** [comment]
Generals Zero Hour: Return of the Super Hackers
Generals Zero Hour: China Strikes Back
Generals Zero Hour: China will grow larger
Generals Zero Hour: I will work
Generals Zero Hour 2: Electric Boogaloo
Generals Zero Hour: Balance Patch
Generals Zero Hour: The Great Patch
Generals Zero Hour: The Great Reset
Generals Zero Hour: Professional
Generals Zero Hour: Reloaded

**Comment by MTKing4** [comment]
FinalPatch 1.0
Zero Hour Enhanced Edition
Zero Hour Definitive Edition
Zero Hour New Generation
Final Hour 1.0

**Comment by commy2** [comment]
\> Final

![psdrevisioning-2078335470](https://user-images.githubusercontent.com/6576312/181521444-81d570fe-7a7e-44aa-8141-4bf500dd5508.jpg)

**Comment by ExiLe-ZH** [comment]
I'm not sure what's wrong with 1.04p or 1.04+. 99% of other suggestions aren't any better. It's a simple name, easy to remember and makes clear it wants to be an improved version of the original.

The p in 1.04p could also stand for pro (as in the big PP a.k.a. Pro-Patch edition 😄). But yea "1.04 pro" isn't bad at all.

Otherwise 1.07 is also still good, though it might suggest it carries on from 1.06. Which doesn't have the best name in the community. 

Or we start over again with 1.05? Though then you probably get questions like isn't 1.06 newer and better?

**Comment by xezon** [comment]
Guy1: _"I have Generals Zero Hour 1.04 installed."_
Guy2: _"That is the wrong version. You need 1.04+"_
Guy1: _"Whats the difference?"_
Guy2: _-_

Also good luck ranking that plus symbol on Google and other search engines.

**Comment by ExiLe-ZH** [comment]
> Guy1: _"I have Generals Zero Hour 1.04 installed."_
> 
> Guy2: _"That is the wrong version. You need 1.04+"_
> 
> Guy1: _"Whats the difference?"_
> 
> Guy2: _-_
> 
> 
> 
> Also good luck ranking that plus symbol on Google and other search engines.

True it might be too subtle on the other hand.

1.04 pro already suggests a little better there is a difference?

Though 1.05 or 1.07 is still the clearest.

**Comment by MTKing4** [comment]
Generals Zero Hour Community Edition

**Comment by ElTioRata** [comment]
ZH 1.1

**Comment by xezon** [comment]
Generals Zero Hour OMEGA
Generals Zero Hour SIGMA
Generals Zero Hour Reforged
Generals Zero Hours Played
Generals Zero Shits Given
Generals Zero Fucks Given
Generals Zero IQ
Generals Zero Hour Apocalypse
Generals Zero Hour Nuklear Rising
Generals Zero Hour Dr. Thrax's Revenge
Generals Zero Hour Infinite
Generals Zero Hour Universe
Generals Second Decade

**Comment by ExiLe-ZH** [comment]
> People like things that say "Pro" in it. So maybe **Generals Zero Hour Professional** aka **Generals Zero Hour Pro** aka **Generals ZH Pro** aka **ZH Pro** aka **zhpro**. See it becomes very short - good for chat communications :-)

Me likey too

ZH PRO (PATCH  1.0)

**Comment by ElTioRata** [comment]
Zero Hour Revision (zhrev for short)

**Comment by ZekeDlyoung** [comment]
Zero Hour Community Patch, ZHCP or just CP for short

EDIT: Sample usage:
ZH 1.04 CP 1.0

**Comment by ZekeDlyoung** [comment]
> People like things that say "Pro" in it. So maybe **Generals Zero Hour Professional** aka **Generals Zero Hour Pro** aka **Generals ZH Pro** aka **ZH Pro** aka **zhpro**. See it becomes very short - good for chat communications :-)

Zero Hour Pro Patch, PP for short.

_Big PP ZH Patch!_

**Comment by penfriendz** [comment]
Yeah, ZHPro gets my vote. Pro rules pro players pro this pro that; it conveys how this is good and will increase adoption rate. Which is what we all want.

**Comment by xezon** [comment]
I am ok with Professional or Pro in short. It also worked for the Control Bar Pro Addon.

**Comment by Jundiyy** [comment]
Heatwave

**Comment by ExiLe-ZH** [comment]
ZH Tournament Edition

**Comment by ElTioRata** [comment]
Zero Hour Revamped or Zero Hour Reloaded (ZHR)

**Comment by ReLaX82** [comment]
ZH Community Patch 1.0 as it can also be a fix later on, but we hope not.

**Comment by xezon** [comment]
I am fond of naming the project

**Generals Zero Hour Redcon**

More precisely **Generals Zero Hour REDCON-1** [majorversion.minorversion], where the leading 1 never changes, and majorversion and minorversion are incremented with versions.

Reasons:
1. "Redcon" stands for Readiness Condition in US military, where 1 is the highest alert level https://en.wikipedia.org/wiki/REDCON
2. There is precendent to this terminology in game with Defcon 6 map and it fits into the theme of the game (USA, year 2000 military) https://en.wikipedia.org/wiki/DEFCON
3. Word is short and relatively easy to remember and recognize
4. Word is not used for anything in game, community and other zero hour related content
5. It likely ranks well on search engines with generals, zero hour, command and conquer. When searching for "command and conquer redcon" on google, nothing of relevance is found right now.
6. Players are lazy typers, so acronyms for it will likely become R1, R-1, which are easily recognizable, because there are no or no significant competing acronyms

Opinions?

**Comment by MTKing4** [comment]
I like it, seems fitting the Zero Hour theme, and not a repeated name

**Comment by xezon** [comment]
Generals: United
Generals: Professional
Generals: The Highest Order
Generals: Next Hour
Generals: Total Destruction
Generals: Ultimate Annihilation
Generals: Ultimate Hour
Generals: Ultimatum
Generals: Zero Hour Ultimatum
Generals: "Special Military Operation"

**Comment by ExiLe-ZH** [comment]
1.07

**Comment by fastAiRR** [comment]
Maybe just something simple like ZH+

**Comment by xezon** [comment]
> Maybe just something simple like ZH+

A Disney Plus subscriber I see. If anything, should be multiple pluses. ZH+++

**Comment by xezon** [comment]
How about "Generals Zero Hour: Ultra"?

Appears to be an unused word in Generals and the Modding Community. The closest thing a google search will show is the "Generals Zero Hour: Enhanced" Mod, where "Enhanced" does not translate as much supremacy as "Ultra" does.

"Ultra" in video games typically refers to Ultra graphics settings. For our purposes it would be a short, easily recognizable name to indicate the "Ultra Upgrade" this project aims to provide.

The word "Ultra" implies similar meaning as "Ultimate" does, which would have been a good choice if the C&C Ultimate Collection did not exist.

This term is also conveniently combinable with other words, such as "Ultra Thyme", if we take the step to fork Thyme for our project in the future.

**Comment by penfriendz** [comment]
On second thought I like remastered. It conveys keeping things the same, but better. Other names like ultra sound bombastic, which is not bad for a mod, but I don't really see this as a mod.

**Comment by xezon** [comment]
The issue I have with "Remastered" is that it does not stand well on its own, plus it would be colliding with the C&C Remastered: https://www.ea.com/games/command-and-conquer/command-and-conquer-remastered

What we can also do is borrow names from the latin. So for example "Ultimate" would translate to "Ultima", which - to me - reads very nicely. But then again we have bad luck with name clashes, because EA does actually have an IP with that name: https://en.wikipedia.org/wiki/Ultima_(series)

**Comment by xezon** [comment]
Generals Zero Hour Ultimum
Generals Zero Hour Optimum
Generals Zero Hour Maximum
Generals Zero Hour Dominus

https://dictzone.com/latin-english-dictionary/ultimum
https://latin-dictionary.net/definition/38002/ultimum

"Ultimum" would work. At a first glance this name is used in no context for this or other video games.

**Comment by ElTioRata** [comment]
General Zero Hour Revolution is a good name for me but I think it could be confused with GenEvo. Oh, and there's already a mod with that name.

**Comment by ElTioRata** [comment]
Generals Zero Hour Resistance
Generals Zero Hour Ascension
Generals Zero Hour Upgraded
Generals Zero Hour Augmented
Generals Zero Hour Extended

**Comment by ExiLe-ZH** [comment]
Zero Hour: CE (custom edition)

Ripped from [Halo](https://en.wikipedia.org/wiki/Halo:_Combat_Evolved#Halo:_Custom_Edition) btw.

**Comment by xezon** [comment]
We already had CE in mind for "Community Edition". It is quite a long name though, plus it does not work on its own, just in conjunction with the original title, therefore giving less freedom for promotional text pieces.

**Comment by xezon** [comment]
Ultra Rush

**Comment by MTKing4** [comment]
Dunno why i read that ultra trash :D 

It actually does sound like it

_Altrush_

**Comment by xezon** [comment]
Ultra Trash hahah

**Comment by xezon** [comment]
How about "Super Aurora"?

"Super Aurora for Command and Conquer Generals Zero Hour".

1. Title is easily recognizable on its own.

2. Title sounds super because it contains "Super".

3. Title sounds familiar for Generals universe because it contains "Aurora" unit name.

4. Title sounds acceptable because "Super Something" is typical slang in game live streams, such as "Super Technical" for the Vet 3 fully scrapped GLA Technical, while it does not specifically collide with regular Aurora and Alpha Aurora game unit names.

5. Title is easily recognizable in relation to the team name "The Super Hackers".

6. "Super" title allows to form other titles, such as "Super Thyme" for a fork of Thyme.

7. "Super Aurora" on its own adheres to the EA terms which asks to not use the Command and Conquer brand name(s) for derivative works. See: https://www.ea.com/games/command-and-conquer/command-and-conquer-remastered/modding-faq.

8. "Aurora" term also refers to the polar lights that everyone loves: https://en.wikipedia.org/wiki/Aurora

**Comment by ExiLe-ZH** [comment]
Sounds pretty good, project super aurora.

**Comment by MTKing4** [comment]
Zero Hour Redux

**Comment by xezon** [comment]
I still like Super Aurora.

"Super Lotus" would also work, but has the disadvantage of having a clear name reference in the game, therefore not unique.

**Comment by MTKing4** [comment]
I don't like it, it sounds cheesy, and very similar and can be confused with aurora
Supersonic Aurora ≈ Super Aurora
Very similar, also the the Unit says the word Super a lot in its voice lines

And is also symbolicly a bad unit choice, as the Patch's defining trait is balance while the aurora is the definition of imbalance

**Comment by KaSSaDo** [comment]
I just came here to say that "Super Aurora" sounds very noobish in my opinion. I'd expect a completely imbalanced and trashy mod by the name of "ZH: Super Aurora".

"ZH: Definitive Edition" might be a choice if EA was in charge of that project.
Derivated from that I like:

Generals ZH: Community Edition
Generals ZH: Ultra Edition (could be mixed up with already existing Ultimate Edition)
Generals ZH: Major Edition
Generals ZH: Pro Edition
Generals ZH: Fan Edition
Generals ZH: Super Edition

Or:

Generals ZH: Resurrection

But something like "ZH: Resurrection" or "ZH: Redcon" or "ZH: Ultra" sounds like just another mod. If I hear "ZH: Community Edition" (just an example) I expect much more than just another mod and the whole project is more like a complete overhaul, therefore I like the word "Edition" in title. Just like "Definitive Edition", you know it will be superior to the older version.

**Comment by xezon** [comment]
"Super Aurora" is better than X.com though :D

I think in many cases the good brand name comes from the positive brand image. If I were to suggest to name a new tech company "Apple" when it did not yet exist, then this would raise eye brows, but once "Apple" establishes itself as a pioneer tech company, then "Apple" will shine as a brand name.

"Super Aurora" is a good name imo. "Super Lotus" is also nice.

The advantage is that these work on their own, without Generals Zero Hour pretext.

"Generals Zero Hour Professional" also sounds professional. (Was already mentioned)

**Comment by xezon** [comment]
I see Zeke suggested Zero Hour X. Elon would approve.

**Comment by MTKing4** [comment]
Agree with Kassad, Super Aurora is unfit

I still like this name
Generals ZH: Community Edition

Nothing tops Simplicity and clarity in this situation imo, name doesn't matter as much as having it easier to search and find by casuals who have never heard of us

The name is also not taken, so it's guaranteed that we get the first result

**Comment by xezon** [comment]
EA says
> Do not use EA artwork, logos or trademarks (including game logo treatments, the names
Electronic Arts, EA or "Command & Conquer" or the logos or names) to promote
your derivative Product. However, you may state that your derivative Product is
for Command & Conquer and/or for a specific C&C game or expansion pack in the
franchise (e.g., "Command & Conquer", "Tiberian Dawn", "Red Alert", "Renegade",
"Generals", and/or "Kane's Wrath", as applicable).

"Community Edition" is probably clear enough by its name that it is not an official EA product. "Community Edition" does read quite boring though. It also shortens to a lame "CE" which does not impress.

**Comment by kABUSE1** [comment]
Generals Zero Hour CoRe (Edition), aka **Co**mmunity **Re**(dux/born/built/mastered/loaded) Edition

I like "Core" because it implies how significantly big and essential this patch is.

**Comment by MTKing4** [comment]
> It also shortens to a lame "CE" which does not impress.

Ooooh. CE i like that!

It looks like we already found our acronym for the patch :D

Zero Hour CE 

I like it :D :D :D

**Comment by ElTioRata** [comment]
> Generals Zero Hour CoRe (Edition), aka **Co**mmunity **Re**(dux/born/built/mastered/loaded) Edition
> 
> I like "Core" because it implies how significantly big and essential this patch is.

Why not just call it Zero Hour Essentials? It's a straightforward name.

**Comment by ExiLe-ZH** [comment]
> > Generals Zero Hour CoRe (Edition), aka **Co**mmunity **Re**(dux/born/built/mastered/loaded) Edition
> > I like "Core" because it implies how significantly big and essential this patch is.
> 
> Why not just call it Zero Hour Essentials? It's a straightforward name.

Sounds like a boring windows security update tbh lol, or like a barebone version of something.

**Comment by xezon** [comment]
Man how hard can it be to come up with a name.

**Comment by xezon** [comment]
Generals Zero Hour Super Pro.

**Comment by fastAiRR** [comment]
U guys overthinking this lol. Keep it simple, one word or symbol. 

It was my own suggestion so I have bias, but I honestly like ZH+ or even what Xezon jokingly commented which is ZH+++, because it actually means something.

Simple is always good and easy to remember. 

These are the kind of ideas I would be looking at to form a name (these are trash I know, but just idea points)
- Remastered - I would look for different synonyms of this: https://www.wordhippo.com/what-is/another-word-for/remastered.html#:~:text=%E2%96%B2-,Past%20tense%20for%20to%20amend%20or%20repair,mendedI would then see if any of those can be used, or if I can abbreviate or shorten them.                                                                                                                        - I would also look at symbols, aside from + there isn't much there, but plus does imply something more and better.                        - I would look at adding maybe a letter behind ZH for example just R or X.                                                                                              - I would consider if I could somehow use a unit of time. So what I mean is, zero hour, is like an hour, so could I somehow say something like quarter past ZH, or ZH +1.                                                                                                                                            - I might look at other languages, maybe latin, see if there is something I can use there.                                                                                                                                   
- Also think about colour schemes, a theme, and logo, as in, come up with a brand, not just a name. A logo and strong brand will help for advertising it and getting peoples attention.

**Comment by kABUSE1** [comment]
Generals Zero Hour Forever
Generals Zero Hour Eternal Edition
Generals Zero Hour Black Edition
Generals Zero Hour Ligma
Generals Zero Hour Limitless

**Comment by xezon** [comment]
Generals Zero Hour Legendary Edition
Generals Zero Hour Super Edition
Generals Zero Hour Plus
Generals Zero Hour Everest
Generals Zero Hour Armadillo

**Comment by ElTioRata** [comment]
Zero Hour Renewed
Zero Hour Alliance
Zero Hour United
Zero Hour Advanced

**Comment by xezon** [comment]
Generals Rush Hour

**Comment by ExiLe-ZH** [comment]
> Zero Hour Renewed Zero Hour Alliance Zero Hour United Zero Hour Advanced

Zero Hour United sounds pretty good, meant to unite the community. 

Or Zero Hour - United Assault, to make it sound a bit cooler haha (anyone remembers the COD United Offensive expansion?)

**Comment by xezon** [comment]
Zero Hour Strike

**Comment by kABUSE1** [comment]
+1 for Zero Hour United 

Maybe add another word from other sugggestions to it...
United Strike
United Victory
United Storm
United X
United Resistance
United Planet
United Rage
United Core

**Comment by xezon** [comment]
I do not like "United". It is a war game. There are conflicts.

Zero Hour Final Strike

**Comment by ExiLe-ZH** [comment]
> I do not like "United". It is a war game. 

"United offensive" must be very contradictory then lol.

> There are conflicts.

What about, Zero Hour - Community at war ? 

> 
> Zero Hour Final Strike

This one is pretty good.

Here a few more suggestions:

Zero hour alliance
Zero hour overwatch
Zero hour spearhead 
Zero hour vanguard
Zero hour blitzkrieg
Zero hour invasion
Zero hour rebellion
Zero hour blue falcon
Zero hour checkpoint
Zero hour blackhawk
Zero hour kinetic
Zero hour ballistic
Zero hour echelon
Zero hour uprise
Zero hour revolution
Zero hour revised
Zero hour revolt(ed)
Zero hour resurrected(ion)
Zero hour resurgence
Zero hour defiance

**Comment by kABUSE1** [comment]
> I do not like "United". It is a war game. There are conflicts.

So what, there are also team-matches. Trackmania is one of the most competitive games on earth and certainly won't survive the inevitable heat-death of the universe, yet it's called "Trackmania: United Forever".

Ideally, this patch "unifies" players all around the globe to still play the same game for yet another 20 years.

I don't think we will be able to find a word that pleases all and I don't think somebody will just drop a super-agreeable bomb title here that we all are hyped for.

**Comment by MTKing4** [comment]
Zero Hour: Community Expansion
Zero Hour: Extended Edition
Zero Hour: Devcom

Dev= Development
Com= Community

= Community Development 

I really like Devcom, sounds very professional, unique, iconic (derived from defcon) and actually descriptive of a community patch. What do you guys think?

**Comment by ExiLe-ZH** [comment]
> > I do not like "United". It is a war game. There are conflicts.
> 
> So what, there are also team-matches. Trackmania is on of the most competitive games on earth and certainly won't survive the inevitable heat-death of the universe, yet it's called "Trackmania: United Forever".
> 
> Ideally, this patch "unifies" players all around the globe to still play the same game for yet another 20 years.
> 
> I don't think we will be able to find a word that pleases all and I don't think somebody will just drop a super-agreeable bomb title here that we all are hyped for.

Agree.

Zero Hour - Operation Unity doesn't sound too bad either.

> Zero Hour: Community Expansion Zero Hour: Extended Edition Zero Hour: Devcom
> 
> Dev= Development Com= Community
> 
> = Community Development
> 
> I really like Devcom, sounds very professional, unique, iconic (derived from defcon) and actually descriptive of a community patch. What do you guys think?

DevCom is pretty good too actually.

**Comment by KaSSaDo** [comment]
I have asked ChatGPT to solve this issue. Here are some of the answers:

Feel free to mix and match words from the suggestions below or combine them to create a unique and fitting name for the community patch.

Generals Zero Hour: Unleashed
Generals Zero Hour: Community Update
Generals Zero Hour: Redux
Generals Zero Hour: Battlefield Evolution
Generals Zero Hour: Enhancement Patch
Generals Zero Hour: Operation Reboot
Generals Zero Hour: Unified Tactics
Generals Zero Hour: Superior Warfare
Generals Zero Hour: Collaborative Strike
Generals Zero Hour: Tactical Triumph
Generals Zero Hour: Community Overhaul
Generals Zero Hour: Community Revival
Generals Zero Hour: Frontline Harmony
Generals Zero Hour: Rebirth
Generals Zero Hour: Warlords Unite
Generals Zero Hour: Legacy
Generals Zero Hour: Operation Remaster
Generals Zero Hour: Elite Patch
Generals Zero Hour: Dominance
Generals Zero Hour: Tactical Thunder
Generals Zero Hour: Strategic Supremacy
Generals Zero Hour: Reignited
Generals Zero Hour: Apex
Generals Zero Hour: Tactical Havoc
Generals Zero Hour: Annihilation
Generals Zero Hour: Ignite

And finally I have asked for names that give a nice abbreviation and it came up with:

Generals Zero Hour: REFINED
(REFINED - Reduced Errors, Fine-tuned AI, Improved Original Design, New Graphics, Enhanced Diversity)

Generals Zero Hour: MASTER
(MASTER - Minimized Errors, AI Strengthened, Tweaked Original, Enhanced Graphics, Richer Experience)

Generals Zero Hour: OPTIMA
(OPTIMA - Overhauled, Polished, Tweaked, Improved, Modernized, Ameliorated)

Generals Zero Hour: FLARE
(FLARE - Fewer Lapses, Adjusted Realism, Enhanced AI, Revamped Experience)

Generals Zero Hour: APEX
(APEX - Augmented Performance, Enhanced Experience)

And lots of other suggestions that didn't make any sense.

My favorites:
Generals Zero Hour: Apex
Generals Zero Hour: Redux
Generals Zero Hour: Legacy

**Comment by ElTioRata** [comment]
> I do not like "United". It is a war game. There are conflicts.

I disagree. The name doesn't imply peace between factions but the factions grouping their units to start the conflict.

**Comment by xezon** [comment]
"Generals United" would work but "Generals Zero Hour United" is odd, because the title speaks about the zero hour and then appends united which does not fit afterwards. And I still think terminology that indicates conflict over peace is more approapriate for this type of game. "unity" is more fitting for world builder simulators, where perhaps you build a mega city with other players and unite all efforts in a peaceful environment.

> I have asked ChatGPT to solve this issue.

5000 IQ move.

> Generals Zero Hour: Strategic Supremacy

Supremacy is nice word.

**Comment by MTKing4** [comment]
> Generals Zero Hour: Redux

I have Suggested that name before and i think it's very good as well


___
On a less serious note:

Generals Zero Hour: Manchester United


I really hate that name :DDDD

**Comment by MTKing4** [comment]
~~I think this is the one time in this project where it's okay for someone to be a super dictator and just picks a name and go with it, otherwise we'll never agree on anything~~

Lots of good names here, lots of bad names, i think a good idea to go about it is to filter these names, anything that has less than 2 people liking the name will be disqualified, and see which name the most agree on and go with it, let's start a vote

But we also need to close the suggestions, we have enough names now to choose from

**Comment by xezon** [comment]
Redux is nice and short, but it is already used by other Community Project(s) in the C&C Universe. So I think this is best avoided.

**Comment by KaSSaDo** [comment]
Generals Zero Hour: Supremacy

zh:sup

**Comment by ExiLe-ZH** [comment]
> I have asked ChatGPT to solve this issue. 
> 
> My favorites: Generals Zero Hour: Apex Generals Zero Hour: Redux Generals Zero Hour: Legacy

I reallly like Redux too, too bad it's taken.

My personal favorites from these is Zero Hour Unleashed, it's very good. (Edit: Omg.... https://www.moddb.com/mods/zerohour-unleashed)
I like Zero Hour Reignited very much aswell.

I do not like Zero Hour Supremacy, but I do like Zero Hour Supreme. Why? Because Supreme is more like a simple statement on the title saying it's a superior version. Whereas Supremacy sounds like a general theme which could mean a lot of things, is it about power of authority or the superiority of something else?

**Comment by xezon** [comment]
> Whereas Supremacy sounds like a general theme which could mean a lot of things, is it about power of authority or the superiority of something else?

Zero Hour
https://dictionary.cambridge.org/dictionary/english/zero-hour

> the time at which something, especially some type of military activity, is planned to begin

Supremacy
https://dictionary.cambridge.org/dictionary/english/supremacy

> the highest authority or greatest power

So if you put these together, it means something like "The time at which the military activity with the greatest powers is planned to begin".

**Comment by kABUSE1** [comment]
> I do not like Zero Hour Supremacy, but I do like Zero Hour Supreme. 

+1 on this. Supremacy doesn't sound smooth and I am afraid half the player base wouldn't even be able to type it out.

**Comment by xezon** [comment]
> half the player base wouldn't even be able to type it out

This is a legitimate concern.

**Comment by ExiLe-ZH** [comment]
> > Whereas Supremacy sounds like a general theme which could mean a lot of things, is it about power of authority or the superiority of something else?
> 
> 
> 
> Zero Hour
> 
> https://dictionary.cambridge.org/dictionary/english/zero-hour
> 
> 
> 
> > the time at which something, especially some type of military activity, is planned to begin
> 
> 
> 
> Supremacy
> 
> https://dictionary.cambridge.org/dictionary/english/supremacy
> 
> 
> 
> > the highest authority or greatest power
> 
> 
> 
> So if you put these together, it means something like "The time at which the military activity with the greatest powers is planned to begin".

If you have the IQ to break it down and understand it like this, yea that's pretty cool. But if spelling already is an issue...

Plus people against the patch gonna make jokes about it, calling it the dictators patch whatever.

**Comment by xezon** [comment]
> Plus people against the patch gonna make jokes about it, calling it the dictators patch whatever.

I do not think that is a problem.

**Comment by MTKing4** [comment]
they will just call it short, "Zero Hour Super" which brings us back to a name we didn't like

**Comment by xezon** [comment]
Zero Hour Super Duper Trooper

**Comment by DoMiNaToRuk2** [comment]
1.0xezon

**Comment by ExiLe-ZH** [comment]
Zero Hour Evolved

**Comment by xezon** [comment]
Zero Hour Exile
Zero Hour Domination
👀

**Comment by MTKing4** [comment]
Zero Hour MTKing
Zero Hour Commy

**Comment by xezon** [comment]
We are making real progress here.

**Comment by DoMiNaToRuk2** [comment]
1.41x

**Comment by xezon** [comment]
> I like the ‘pro’ in the title

> Pro In title and a Version number.

> Zero Hour Pro Patch, PP for short.

> Yeah, ZHPro gets my vote.

> I am ok with Professional or Pro in short.

> Me likey too ZH PRO (PATCH 1.0)

Go with Generals Zero Hour Professional [X.Y.Z], Pro in short?

**Comment by MTKing4** [comment]
I don't like pro, sounds cheap and informal, professional is too long and unfit for a name, and in general we should avoid words like pro, tournament edition etc because this patch is meant for everyone, not just pros.

I still think these are best names we have so far, i collected them from all the names that have been mentioned here

Zero Hour: Community Edition
Zero Hour: Community Expansion
Zero Hour: Extended Edition
Zero Hour: Definitive Edition
Zero Hour: Enhanced Edition
Zero Hour: Devcom
Zero Hour: Redux
Final Hour 1.0
Zero Hour: 1.7
Zero Hour: Revised

Last one i just came up with


Imo i think we should avoid going too far with creative names while also staying formal and descriptive of our product. And those names fit the criteria i feel, so it would be great if we just pick one of these and be done with it

**Comment by xezon** [comment]
Yeah Pro, Professional has disadvantages. I still would like a name that can stand on its own. Like Thyme does. The advantage of that is that it would not need to be named Generals Zero Hour Abc-Xyz in all length.

**Comment by ExiLe-ZH** [comment]
@MTKing4 Nothing wrong with "pro", massive brands use it alot.

Btw, don't think your last suggestion is completely new in this topic :D 


Here some real suggestions though:
Zero hour: The Diagonally Oppressed
Zero hour: Mathphobia 
Zero Hour: Mathtopia

**Comment by xezon** [comment]
> Zero hour: The Diagonally Oppressed
> Zero hour: Mathphobia

LOL

**Comment by fastAiRR** [comment]
Patchy McPatchface

**Comment by kABUSE1** [comment]
Zero Hour Updog

Advantages:
- We finally have an answer to the question "What's updog?"
- It's funny
- Unique & easy to type
- Could be merged with Thyme to form "Up-thyme".

**Comment by MTKing4** [comment]
> Nothing wrong with "pro", massive brands use it alot.

Yeah true, but the reason I don't like it here is because it doesn't represent our product best, especially when we're trying to bring every noob to play, pro could scare them off maybe, or at least sounds like game was balanced as per pros demand only to become symmetrical/boring etc, and that noob requests have been probably ignored, I'm just guessing here not sure how it would be perceived, but i think these thoughts are likely to happen

> Btw, don't think your last suggestion is completely new in this topic :D

Yeah i know, i derived it from Revision, it's just that my version is better :P

**Comment by xezon** [comment]
> Zero Hour Updog

https://www.urbandictionary.com/define.php?term=Updog

> Though most of these symptoms sound positive, one negative symptoms will occur, a UPDOG victim will forever stay a virgin.

:eyes:

**Comment by xezon** [comment]
Generals Zero Hour Fatality

**Comment by MTKing4** [comment]
Someone needs to be a Dictator here

I Vote for myself to pick the Project's name

**Comment by ExiLe-ZH** [comment]
What about?

Zero Hour: Community Remaster
Zero Hour: Community Remastered

**Comment by ExiLe-ZH** [comment]
Don't think we're allowed to call it an actual Remaster without community in the name.

**Comment by xezon** [comment]
"Community Remaster" is better than "Community Edition" in my opinion.

Community is a quite long and boring word. Perhaps there is a shorter one with similar meaning?

**Comment by xezon** [comment]
"Super Remaster" there we go :-)

**Comment by MTKing4** [comment]
I think if there's one thing we can conclude from this issue topic is that Xezon really likes the word "Super" :›

**Comment by MTKing4** [comment]
Community Remaster Sounds good for me.

**Comment by kABUSE1** [comment]
Just to point this out again, Community Remaster can be shortened to CoRe, which is kinda cool

**Comment by xezon** [comment]
> I think if there's one thing we can conclude from this issue topic is that Xezon really likes the word "Super" :›

Yes. Because it would be nice to create product names where the author is implicitly recognizable. It strengthens the brand if all work we produce is high quality.

"Super Thyme" by "The Super Hackers"
"Super Remaster" by "The Super Hackers"
"Super German Uncut" by "The Super Hackers"
"Super Hotkey Editor" by "The Super Hackers"

**Comment by xezon** [comment]
> Just to point this out again, Community Remaster can be shortened to CoRe, which is kinda cool

Super Remaster > SURE!

**Comment by ElTioRata** [comment]
_Zero Hour: Super Revision_ works for me.

**Comment by ExiLe-ZH** [comment]
> I think if there's one thing we can conclude from this issue topic is that Xezon really likes the word "Super" :›

Zero Hour : Super Uncensored!

> Just to point this out again, Community Remaster can be shortened to CoRe, which is kinda cool

That's pretty cool actually!

**Comment by MTKing4** [comment]
> Just to point this out again, Community Remaster can be shortened to CoRe, which is kinda cool

Can be Confused with with our Core and Optional bundles though

And yes Xezon, if you really like it that much we can go with it, just wanna get this over with :D

But..

Zero Hour: Super Patch

Sounds nicer and lighter on the tongue :D

**Comment by xezon** [comment]
I am ok with Super Patch. Two 5 letter words. Easy to understand.

**Comment by xezon** [comment]
Zero Hour: Super Edition

**Comment by ExiLe-ZH** [comment]
Super patch is also fine
Or the other one: zh supreme

**Comment by xezon** [comment]
So go with "Super Patch" then? May read a bit lame right now but I think in long run its fine if it can establish itself as just that.

**Comment by MTKing4** [comment]
Yeah go for it, i think that's it, good name

Also shortenes for
Zero Hour SP
Which is also cool and quite unique

**Comment by xezon** [comment]
Ok Super Patch then yes?

"The Super Hackers present Super Thyme and Super Patch for Generals: Zero Hour."

**Comment by penfriendz** [comment]
1.41 or 1.41x sounds good to me

**Comment by MTKing4** [comment]
> Ok Super Patch then yes?
> 
> "The Super Hackers present Super Thyme and Super Patch for Generals: Zero Hour."

Yep, go for it

Can't believe we finally agreed on something :D

**Comment by xezon** [comment]
It is miracle.
