### ISSUE TITLE
Are patriot drops an issue

### ISSUE THREAD

**Issue by ReLaX82** [TheSuperHackers/GeneralsGamePatch#1124]
Lazer has the best option to drop a pad and can follow up with a lazer Tank as well.

Same applies to vUSA where Pad can follow up by Paladin.

Both are most effective vs China except Infantry.

Yet I like this diversity it should be tested in mid patch versions and final Version if this is an issue overall. I think it should be a good option which is just as strong as usual playing style like no eco or dual wf.

**Comment by xezon** [comment]
China already has better Dozer Movement and Door Times which should help against early USA drops.

**Comment by ReLaX82** [comment]
Yes, once a 1st basic patch version is out, it should be tested.

**Comment by xezon** [comment]
Close?

**Comment by fastAiRR** [comment]
I did no eco patriot drops extensively here, https://www.gamereplays.org/community/index.php?showtopic=1038001
I don't always follow with a tank though, do sometimes. TBH its not easy to pull this off, one mistake and u fck it. You also need to pay for power, and enemy going rax hurts. 

dont break it please.
