### ISSUE TITLE
Combat Cycle Experience Values & Requirements are insanely high

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1147]
```
Object GLAVehicleCombatBike
  ExperienceValue       = 50 50 100 150    ;Experience point value at each level
  ExperienceRequired    = 0 200 400 800  ;Experience points needed to gain each level

Object GLAVehicleCombatBikeRocket
  ExperienceValue       = 50 50 100 150    ;Experience point value at each level
  ExperienceRequired    = 0 200 400 800  ;Experience points needed to gain each level

Object GLAVehicleCombatBikeTerrorist
  ExperienceValue       = 50 50 100 150    ;Experience point value at each level
  ExperienceRequired    = 0 200 400 800  ;Experience points needed to gain each level

Object Chem_GLAVehicleCombatBike
  ExperienceValue       = 50 50 100 150    ;Experience point value at each level
  ExperienceRequired    = 0 200 400 800  ;Experience points needed to gain each level

Object Demo_GLAVehicleCombatBike
  ExperienceValue       = 50 50 100 150    ;Experience point value at each level
  ExperienceRequired    = 0 200 400 800  ;Experience points needed to gain each level
```

Now compare that to Techs:

```
Object GLAVehicleTechnicalChassisOne
  ExperienceValue         = 25 25 50 100    ;Experience point value at each level
  ExperienceRequired      = 0 50 75 150  ;Experience points needed to gain each level
```

Or Quads/Gats/Vees (all the same):

```
  ExperienceValue = 50 50 100 150    ;Experience point value at each level
  ExperienceRequired = 0 100 150 300  ;Experience points needed to gain each level
```

It's obvious that Rebel/RPG bikes don't have the same killing potential or survivability as the units named above.

DemoBikes should probably stay the same though as they're trading units.

**Comment by commy2** [comment]
I would keep all bike XP consistent including Demogen Bikes. The riders can be changed and these values would stick per bike, not per rider.

**Comment by xezon** [comment]
Looks to me that Combat Bike XP should be closer to Infantry than Vehicles, because realistically we expect the damage to be what the Infantry does.

**Comment by ExiLe-ZH** [comment]
@commy2 
> I would keep all bike XP consistent including Demogen Bikes. The riders can be changed and these values would stick per bike, not per rider.

RPG and regular Terrorist Bikes can't be produced from the factory, why can it be tweaked separately in INI?

If this is true, then the only problem would be low XP for Jarmen on a bike (or Hijacker)?

@xezon 
> Looks to me that Combat Bike XP should be closer to Infantry than Vehicles, because realistically we expect the damage to be what the Infantry does.

To me it looks fair to make the Bike itself grant 10xp, this would mean:
- 15+10= 25xp for normal RebelBike (same as Technical).
- 25+10= 35xp for ToxRebelBike.
- 20+10= 30xp for TerroristBike.
- 20+10= 30xp for RPGBike.
- DemoBike is just a completely different animal, shouldn't touch this one imo.

I would change the Requirements similar to infantry indeed, bikes barely offer extra firepower and protection (if any at all):
- (Tox)RebelBike 0 40 60 120
- RPGBike 0 100 200 400

**Comment by xezon** [comment]
Is it possible to set experience depending on Rider type? I would have assumed it is one setting for all.

**Comment by commy2** [comment]
> why can it be tweaked separately in INI?

Because the XP values are properties of the Bike, not the Rider.

> Is it possible to set experience depending on Rider type?

No, that was my point. You can tweak the bikes of each faction, not each rider.
But making Demogen Bikes level up slower or giving more experience would be very strange, because that would apply for any of the other riders on Demogen Bikes, even if the Terrorist is replaced with a Jarmen.
I think giving them Hero requirements and yields would be the safest bet. Bike yields don't matter overall as far as I can tell, because these are not units you're going to mass produce like Quads or Techs.

**Comment by ExiLe-ZH** [comment]
> > why can it be tweaked separately in INI?
> 
> Because the XP values are properties of the Bike, not the Rider.
> 
> > Is it possible to set experience depending on Rider type?
> 
> No, that was my point. You can tweak the bikes of each faction, not each rider. But making Demogen Bikes level up slower or giving more experience would be very strange, because that would apply for any of the other riders on Demogen Bikes, even if the Terrorist is replaced with a Jarmen. I think giving them Hero requirements and yields would be the safest bet. Bike yields don't matter overall as far as I can tell, because these are not units you're going to mass produce like Quads or Techs.

In real games the only units you would want to replace the rider with is a Hijacker (stealth only), Saboteur (gla/stealth only) or Jarmen. I agree Jarmen on a bike giving off less XP is strange, but for Demo this would remain the same, which is coincidentally also the better Jarmen.

Demobikes don't level up lol and 0 200 400 800 for the only replacement being Jarmen is ridiculous aswell.

Wish we could make standard RebelBikes a bit more spammable with good XP values and better pricing. Singleplayer Campaign suggests this is a thing.

**Comment by commy2** [comment]
I see all kinds of riders on Bikes. Saboteur, Hijacker, Jarmen. The rarest are probably Demo Rebels as well as RPGs.

Rebels already deal extra damage when on a bike, roughly 3 times more due to higher damage per bullet and larger clip size. Even Jarmen reloads 25% faster on a Bike. 
For whatever reason, RPGs don't. They are the same on and off Bike, which is unfortunate.

> Demobikes don't level up lol

Demogen Bikes are just Bikes of Demo General. They can carry other units than Terrorists, even if that is the default. They level up exactly like the other factions bikes.

**Comment by commy2** [comment]
Bike:
  ExperienceValue       = 50 50 100 150    ;Experience point value at each level
  ExperienceRequired    = 0 200 400 800  ;Experience points needed to gain each level

Jarmen:
  ExperienceValue     = 50 50 100 150    ;Experience point value at each level
  ExperienceRequired  = 0 100 200 400  ;Experience points needed to gain each level

I think Bike should match Jarmen. Meaning that the requirements should be halved, and the yields be left alone.

**Comment by xezon** [comment]
Matching Jarmen is the safe option indeed.

**Comment by ExiLe-ZH** [comment]
> I see all kinds of riders on Bikes. Saboteur, Hijacker, Jarmen. The rarest are probably Demo Rebels as well as RPGs.
> 

I did exactly mention this? ^^ But more detailed per faction.

> Demogen Bikes are just Bikes of Demo General. They can carry other units than Terrorists, even if that is the default. They level up exactly like the other factions bikes.

Also mentioned Jarmen is the only worthy replacement incase of Demo, but that the requirement is still too high (double).

> I think Bike should match Jarmen. Meaning that the requirements should be halved, and the yields be left alone.

It is indeed the safest, but still sad for Rebels, RPGs and Sabos :(

Maybe price is the way to make them happy.

**Comment by ExiLe-ZH** [comment]
> For whatever reason, RPGs don't. They are the same on and off Bike, which is unfortunate.

Can't we replace weapon with Stinger type?

**Comment by commy2** [comment]
> Can't we replace weapon with Stinger type?

You mean replace the projectile to use Stinger tracking like Tox? Sure, that is possible.
It never made sense for Tox RPG though and wouldn't here either.

**Comment by ExiLe-ZH** [comment]
> > Can't we replace weapon with Stinger type?
> 
> You mean replace the projectile to use Stinger tracking like Tox? Sure, that is possible. It never made sense for Tox RPG though and wouldn't here either.

Probably doesn't make too much sense, just trying to think of a low-impact buff. It seems to be a build-in weapon though, so you could imagine it's not his own rpg. Or that he simply uses different projectiles (stored in the bike somewhere lol).

Could maybe build-in 2 rocket launchers, 1 on each side like the machineguns, but that's probably a shitton of modding work.

Or keep the machineguns and add the rpg to it, for some reason the machineguns disappear when switching passenger. Problem with this logic is that hijackers, saboteurs and workers should also have the mg.

**Comment by Jundiyy** [comment]
I don't think it would hurt to give the the RPG a small buff, perhaps faster reload, more range or just more damage? Doesn't need any super model work on it.
Or we can just leave it, it's not biggie. They are faster at travelling, which is also a good thing, although easier for tanks to kill.

**Comment by Stubbjax** [comment]
> I don't think it would hurt to give the the RPG a small buff, perhaps faster reload, more range or just more damage? Doesn't need any super model work on it. Or we can just leave it, it's not biggie. They are faster at travelling, which is also a good thing, although easier for tanks to kill.

How about doubling the clip size? Would tie in nicely with the unit's 'hit-n-run' theme and make the $800 value + rider swap micro slightly more reasonable.

https://user-images.githubusercontent.com/11547761/189022531-4ed78ff9-23f2-4ea3-9b13-0c37c86f4e41.mp4

```
DelayBetweenShots = 100
ClipSize          = 2
ClipReloadTime    = 1000
```

**Comment by MTKing4** [comment]
> How about doubling the clip size? Would tie in nicely with the unit's 'hit-n-run' theme and make the $800 value + rider swap micro slightly more reasonable.
> 
>  RPG_BIKE.mp4 
> ```
> DelayBetweenShots = 100
> ClipSize          = 2
> ClipReloadTime    = 1000
> ```

I like this

**Comment by xezon** [comment]
I do not like this. If I was playing this and I would not know this is intentional, I would assume it is a glitch.

**Comment by Stubbjax** [comment]
Would you assume x3 is a glitch as well?

https://user-images.githubusercontent.com/11547761/189048753-04afa193-b403-4353-916d-5ef84b68c291.mp4

**Comment by xezon** [comment]
The simpler method is to just have it launch a bigger rocket with more damage. That also allows to fine tune better instead of having a hard 2 times damage cap.

**Comment by Stubbjax** [comment]
> That also allows to fine tune better instead of having a hard 2 times damage cap.

The clip size doesn't actually result in a direct x2 or x3 buff, as the delay between shots is added to the total volley duration. This is why the bike shoots slower despite the same 1000ms reload in the first video. The respective clip reload time can also be tweaked just as easily.

> The simpler method is to just have it launch a bigger rocket with more damage.

Whether it's simpler is debatable. It would certainly feel odd / inconsistent if these rockets applied different damage despite the same visuals / sounds, and adjusting those attributes is definitely more complex. It is also more interesting to fire a volley of rockets, especially as it ties in with the bike's 'hit-n-run' design and overall design of the GLA, and has different implications / effectiveness against things like PDL.

**Comment by xezon** [comment]
If firing 2 rockets, then preferably the bike has 2 rocket slots, just like the Rocket Buggy has multiple to fire its rockets from.

**Comment by Jundiyy** [comment]
I didn't exactly imagine the 2 as a volley, I understand why xezon said he might see it as a glitch. Should be more of a gap between or even no clip size, just a faster reload.

**Comment by Stubbjax** [comment]
Halving the reload duration from 1000ms to 500ms seems like the simplest approach.

**Comment by xezon** [comment]
Reducing reload time would be fine yes. Whether or not it needs to be halved is unclear to me.

**Comment by ExiLe-ZH** [comment]
Feeling the same xezon and jundiyy.

better reload time or range would be cool, double rocket is kinda strange.
