### ISSUE TITLE
Auto-Repair acts like small armor upgrade

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1174]
A unit is actively repaired when getting shot at. The longer it takes to kill a unit, the more it can repair itself. Higher HP units will benefit more naturally.

This applies to Junk Repair and the Repair Bay (aswell as Veterancy?).

### Proposal:
Eliminate the issue by adding a slight delay after receiving damage before Auto-Repair kicks in (A second or two could be enough).

**Comment by commy2** [comment]
This doesn't seem like an issue at all, but just how passive repair works. Neither Junk Repair nor Repair Bays are considered overpowered.

All these passive repair abilities also heal absolute amounts, so they do not stack with health bonuses like from veterancy either. If there is a repair type that needs looking at, it is (subliminal) propaganda.

**Comment by ExiLe-ZH** [comment]
I would claim that both are pretty overpowered. I feel they surely change engagements, like Quads with AP Bullets and Junk Repair are quite nasty. I don't have statistical data for it though.

To me it just makes more sense that vehicles don't get insta repaired while getting shot at.

**Comment by commy2** [comment]
Quads are nasty, because they shoot 2.2 times faster when vetted. Otherwise they are fine.

**Comment by Jundiyy** [comment]
This shouldn't be touched. There isn't any flaw with the upgrade.

**Comment by Stubbjax** [comment]
> I would claim that both are pretty overpowered.

This surely has to be the first time anyone has claimed this in the entire history of Zero Hour. 😄

**Comment by xezon** [comment]
Touching this would impact Humvee play, as player would observe a delay in repair which can potentially be perceived as being frustrating. I am closing this for.

**Comment by ExiLe-ZH** [comment]
It affects every single unit, Humvee aren't affected by this in a special way?
