### ISSUE TITLE
Rebel ambush mixes hijacker with vgla and stealth

### ISSUE THREAD

**Issue by KrewGR** [TheSuperHackers/GeneralsGamePatch#1182]
Level 1 can contain 1 hijacker and 3 rebels
Level 2 contains 2 hijackers and 6 rebels
Level 3 contains 3 hijackers and 12 rebels

This would bring vgla ambush competitive with tox and demo ambush. 

This opens up the strategy to steal units if well microed.

**Comment by ExiLe-ZH** [comment]
Sounds very OP, 

Level1 can potentially steal 2 Overlords at once with jarmen snipe.

Level2 3 Overlords.

Level3 4 Overlords

Currently 1 overlord snipe steal already changes battles.

**Comment by KrewGR** [comment]
> Sounds very OP, can potentially steal 4 overlords at once with jarmen snipe.

Tox and demo ambush erase triple that in the blink of an eye. The GP ambush is flat out useless.

**Comment by Jundiyy** [comment]
Whilst I understand your comparison, it's not the way to look at it.
The question should be, 'how balanced is GLA at the moment?' I'd say quite balanced.
And second question could be (in most cases), how well does it compare with original game? 

GLA already does quite well overall, does it need a buff? Nope. Especially not a bigger one, maybe at the most, the respawn could be reduced by a bit. 

All GLAs play out quite well vs all factions. Stealth being number 1 for many and it has a simple Ambush compared to Tox and Demo.

**Comment by KrewGR** [comment]
but vgla plays the weakest out of all of them. Demo and Tox rebel ambush counters anything on the ground super effectively, while vgla doesn't. If anything, you should nerf demo and tox ambush if you won't buff the normal ambush. NO ONE used normal rebel ambush. they need some sort of mechanic change to include relevance, else it's just an eye sore when you open up your GP.

Chinas will inevitably get a buff, so I don't think its overall going to be OP you need really good micro to select the right units to hijack. Hijackers also don't have stealth with vgla.

**Comment by ExiLe-ZH** [comment]
Level 1 is meta vs Overlords with Jarmen snipes, in other matchups GLA plays with CashBounty level 3, which makes a huge economical difference in aggressive games.

You're completely right Demo/Tox Ambush are completely OP, but higher levels are trade offs vs Bounty. 

VGLA performs very well currently, actually even better than Demo on Semi+ level. Stealth (which also lacks OP ambush) and especially Tox both perform better.

```cs
Armies Winrate
-------------------------
1.  Air -----  60% G:405 W:243 L:162 
2.  Inf -----  60% G:435 W:259 L:176 
3.  Tox -----  56% G:463 W:261 L:202 
4.  Stealth -  56% G:506 W:285 L:221 
5.  GLA -----  52% G:536 W:278 L:258 
6.  USA -----  52% G:496 W:259 L:237 
7.  Laser ---  51% G:411 W:209 L:202 
8.  Demo ----  49% G:445 W:217 L:228 
9.  Tank ----  45% G:453 W:205 L:248 
10. SWG -----  42% G:437 W:182 L:255 
11. Nuke ----  40% G:379 W:153 L:226 
12. China ---  36% G:480 W:172 L:308 
-------------------------```

**Comment by Jundiyy** [comment]
For GLA it could make sense (especially with visible Hijackers), whilst it is weaker than the rest of the GLAs, it still plays out at 50% or more in the overall army win rate.

> If anything, you should nerf demo and tox ambush

Preferably less nerfing as possible with this patch, better to buff. 

>if you won't buff the normal ambush.

Remember, there is no 'you' in this patch, it's all we, that's right, Krew is also part of the patch :) your opinion matters just as much as any other that's helping out.

I will add, GLA and Stealth Ambush is usually used when combining an attack, or a Jarmen snipe, unlike Tox and Demo.
Hence why you will usually see a level 1 a lot of the time, level 2 is a lot less. And then players go for bounty.

**Comment by KrewGR** [comment]
Then perhaps just give level 2 and 3 vgla hijackers.

Jarmin snipe combo with level one isn't exclusive to vgla or stealth. 

In my opinion, when you actually simulate what would likely happen, most chinas will have a blob of unit mixes with the ovies. Jarmin will snipe a unit. Rebels will be deployed in the blob to take sniped unit. If the gla is lucky, the hijackers will find an extra 1, MAYBE 2 units to take among the carnage of the China blob shooting at any rebels or hijackers. China will likely have an ovie upgraded with gatlings, along with many units mixed with it.

If you have camo upgrade with vgla, the upgrade becomes more worth as now china will have to have a stealth detection unit in the mix. Further more, if the China blob moves, they will run over any hijackers in the way that are not microed.

This change just make perfect sense to me, as now, if USA tanks is becomes meta, it may also be worth getting level 1-3 rebels.

Gla vs gla would open the option too, being able to take scorps, buggies and quads.

**Comment by ExiLe-ZH** [comment]
Should Stealth get this too then?

**Comment by KrewGR** [comment]
> Should Stealth get this too then?

Very likely it would play well, but we would have to test that before official release, as those hijackers are always stealthy. All though, I still don't see it being OP with stealth.

**Comment by ExiLe-ZH** [comment]
What about a dozer steal though. That'd be MEGA OP. 

Unless we can fix power spam, but most likely not possible.

Even then it's just a simple click to steal a whole Tech Tree and potentially hunt a player, if he doesn't have a CC for whatever reason.

Also a Saboteur would be OP, can reset a SW or CC every 4 minutes.

**Comment by KrewGR** [comment]
By the time you get the GP for ambush, cc will likely be placed down already. I do agree that the power spam is entire too fast with gla. Maybe slow that down a little.

Including saboteur would be op, I agree. If you can resent USA cc faster than the USA gp can be used up, it could be massively abused. 

If anything has the potential to be abused, it should not be added. Saboteur can be mixed with a gla bike, which is perfect as is to recent CC and SW.

**Comment by ExiLe-ZH** [comment]
> If anything has the potential to be abused, it should not be added. 

This is how I feel about Hijackers. I'm open towards new creative ideas though, that's why I also gave Saboteurs a thought but came to the same conclusion very fast.

Unfortunately level 2/3 Ambush for Stealth/GLA are useless (over Cash Bounty), but I don't think the ideas are a good solution.

**Comment by KrewGR** [comment]
Then perhaps add RPGs in the mix of the ambush.

**Comment by ExiLe-ZH** [comment]
Definitely sounds more in check, could do the same with USA Ranger drop.

**Comment by ReLaX82** [comment]
What about adding rocket soldiers to make it an option also for other fight like supporting insude a battle?

**Comment by Stubbjax** [comment]
Being able to instantly spawn Hijackers anywhere on the map is a recipe for disaster. It would change the dynamic far too much from 1.04 and amplify the abilities in the wrong way.

The reason Rebel Ambush + Demolitions is typically banned in rule-based games is because it is absolutely outrageous that $10,000+ of stuff can be destroyed in the blink of an eye, with almost no chance for counterplay. Destructive powers / abilities should always provide the opponent with some opportunity for anticipation / avoidance / denial, and otherwise feel incredibly frustrating and unfair to play against. The specialised ambush variants unfortunately ignore this rule, and are very poorly considered / designed. (A far better design would be if the Suicide ability had an initial cooldown like the capture upgrade, so that opponents had some time to react. The Toxin variant could just spawn fewer Rebels.)

Hijacker ambushes would also severely skew any GLA vs USA / China game where a GLA can snag a dozer / power before the opponent can even react to the ambush. And it would certainly break 2v2v2 games, where dozer shopping plays a large role. Additionally, it would make investing a skill point into Hijackers even more useless (if that's even possible) when it comes to vGLA.

Don't forget that Cash Bounty is also more preferable in 1.04 because it does not require a fully built CC to activate. Such a change may take away some of Bounty's appeal and have an impact on where points are invested. Any changes to the Camouflage upgrade may also make ambushes more viable for vGLA.

**Comment by xezon** [comment]
Adding Hijacker to Ambush is nice thought, but as outlined above too risky.

**Comment by xezon** [comment]
Toxin & Demo Ambush continue here:
* #1184
