### ISSUE TITLE
USA Humvee has significantly longer sink time than other vehicles

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1183]
USA Humvee has significantly longer sink time than other vehicles.

https://user-images.githubusercontent.com/4720891/189884359-3d72e993-ea11-46d0-bb6f-5d5e01728fb5.mp4

**Comment by ExiLe-ZH** [comment]
tanks are weightier xD

**Comment by commy2** [comment]
I also notice that Sentry Drone scrap goes into orbit.
