### ISSUE TITLE
China Gattling Tank spin up times are inferior to Generals

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1185]
Reference:
* #1175

**Rising**:
> On a slight tangent, has changing how 'spinning up gats' works been discussed anywhere (eg force firing the ground before attacking)? On ccg it can be done very effectively (probably too much) but on ZH the spin doesn't last long enough to really do anything. I think it could be a pretty cool change; increases micro potential (always good) and makes gats better defensively (to counter no eco's/tech rpgs).

| Object                  | Shots to Spin Level 2 | Shots to Spin Level 3 | Spin timeout (s) |
|-------------------------|-----------------------|-----------------------|------------------|
| Generals Gattling Tank  | 3                     | 6                     | 2                |
| Zero Hour Gattling Tank | 2                     | 6                     | 1                |

| Object                         | Spin Level 1 DPS | Spin Level 2 DPS | Spin Level 3 DPS |
|--------------------------------|------------------|------------------|------------------|
| Original Quad Cannon (Vet 0)   | 75               |                  |                  |
| Original Quad Cannon (Vet 1)   | 165              |                  |                  |
| (#1055) Quad Cannon (Vet 1)    | 120              |                  |                  |
| Original Gattling Tank (Vet 0) | 37.5             | 75               | 112.5            |
| Original Gattling Tank (Vet 1) | 49.5             |                  | 123.75           |

### Proposal 1

Increase spin timeout.

**Comment by xezon** [comment]
Note that a spinned Gatling + Vet 1,2,3 will always lose vs Quad Vet 1,2,3 and just be an equal match with change #1055.

This means spin up is very important for China Gatling.

**Comment by commy2** [comment]
The Gat also runs into ROF wonkiness when combined with Propganda/Subliminal Propganda.

Not to mention what happens with the Minigunner, which is additionally affected by Horde/Nationalism and Fanatism, which are all separate ROF boosts.

**Comment by KrewGR** [comment]
I'm in huge favor of this change. Coming from ccg to ZH was frustrating most when counting vee spam because migs are so expensive, and the gat was an equal counter to rockvees on ccg. If this is changed along with the retargeting bug with the drones, china gat micro will actually pay off.

**Comment by MTKing4** [comment]
I think having spin timeout like in ccg is the only change that is needed for the gat for it to be good, meaning we shouldn't be messing with it's XP requirements if we do this, which i think is a superior change to that and less likely to cause balance problems between chinas

**Comment by ExiLe-ZH** [comment]
if 2000ms proves to be a little too much, then 1500 could also be tested.
