### ISSUE TITLE
Buggies Wreckages inside Tunnels will fly into the air when Player Surrenders

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#1191]
[Buggy Wreckage](https://youtu.be/eMUx50pJFbg?t=1135)

Needs Testing.

**Comment by xezon** [comment]
Does not look like a practical issue that needs attention.

**Comment by MTKing4** [comment]
Why not? It's a visual bug, didn't you already do something similar? With outpost radar flying into the air when dying?

Maybe at least open it so that we gather more opinions first before deciding to close.
