### ISSUE TITLE
Combat Cycle Can Move Without a Rider if Both Evacuate and Move Command Were Issued Consecutively

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#1193]
[Rebel Bike Stunt](https://youtu.be/uBwFIB8y1HI?t=170)

Needs Testing

Commy
> It's supposed to die. Not supposed to move I guess, but Bike in general keeps all properties of the last rider, even after dismount. This why Demo Bike blows up when Terrorist leaves.

MTKing
> I think what happened was caused by lag, where he gave two orders, one evac, and one move, and the order was delivered to both the rebel and the rebel with the bike, but he already dismounted, so it went on its own

Commy
> Could be. Dismount and move order at the same frame.
Don't think excessive lag is necessary as this game is very sluggish for input in multiplayer anyway.

---
This loosely _(or not loosely)_ relates to demo bikes detonating after Evacuation Order

Vovin
> terrorist is rider 5, someone at EA thought bikes should explode if they are rider 5 
because the rider sets the status, and bikes die when the rider leaves
so the bike commits suicide, basically
and since the last status was rider 5, its dies with rider 5 modules

Vovin

> removing the FireWeaponWhenDeadBehavior with STATUS_RIDER5
will make the bike no longer explode

Commy
> Rider 5 = The Terrorist on a bike uses RIDER_5 flags.

**Comment by xezon** [comment]
Can we close this? Does not look like a problem that needs our attention.

**Comment by MTKing4** [comment]
It's a visual bug, I'm adding all these in so that we might decide to fix them later on and so they don't get lost

Also i think by the explanation above, i think it essentially means one could send an empty demo bike to detonate on an enemy and still keep the terrorist alive, so you could say that's a way it can be abused

**Comment by commy2** [comment]
Executable bug.
