### ISSUE TITLE
Tank Locomotor Idea

### ISSUE THREAD

**Issue by KrewGR** [TheSuperHackers/GeneralsGamePatch#1201]
The discussion on the China dozer locomotive prompt an idea that I think will be very welcomed within ZH, and that is the abilities that many units would love if they could drive backwards. Perhaps focusing on behavior issues similar to the gat spin up, retargeting bug with gat/quad, and China dozer back up really are the better and safer changes we could make that would allow for my unit viability and counters to overpowered metas such as the rockvee spam. I propose that tank viability would greatly increase if tanks could move backwards just like the vees and techs. The benefit greatly outweighs the potential problems as the change would open up opportunities for players to increase the effectiveness of weaker units by paying more attention to micro-options instead of changing the firepower/strength of the unit. Spending more APM on micro has always been a risk vs reward choice, as that time could be spent looking at flanks for sneaky attacks, or opponents deciding to fight 2 different battles at once. Furthermore, the change is so skill based, that if it was to actually reward a player highly, it would not be because of imbalance, but rather of pure skill. Micro opportunities I think should always be given options to preform, and tanks being able to back up might actually be a great start to them finding a place in the faster unit meta.

Crusader/Paladin/Microwave: These units having the ability to back up will give players a bit easier time to deal with tunnel popping spam vs defensive glas, especially because tanks soak more damage than lighter faster units. They find a role in being cannon fodder for the harder hitting rockvees. Backing up allows enemy units to fall for more kiting traps so that more units can find firing angles when locking on to the microed tanks. With the paladin buff discussion, I worried that crusader tanks would be obsolete, but with this micro change, it seems that crusaders vs most China factions would be a decent option, especially vs China Tank gen and Nuke as crusaders are a cheaper choice.

Battlemaster/overlords/ECM: Apart from China nuke, I think China can desperately use these new locomotors as China tank units almost never pay off before death. Once again, perhaps it could slightly help with rockvee spam, but not by much. I can see tank battles happening more often within the unit mixing with this change though. The overlords are especially going to change the micro style of the battlefield, as their ability to soak damage is far better than any other unit, so backing up would drag rockvees in closer to the China blob for more firepower. I only worry for china Nuke tank because the speed combined with the locomotor would likely be overwhelmingly powerful. We would have to discuss more about that.

Marauder/Scorp: The Marauder would be the best to benefit this buff as it requires a GP and the turret cannot turn. I believe this unit would be most viable vs tank spam vs any faction if it can get the scrap. scorps can now have the ability to win scorp on scorp spam in gla mirrors, which can possible give a little more openness to these units that isn't a buggy

Gat/quad: I am not sure if these units should be able to back up, as the other behavior changes already dramatically help them counter vee spam. Testing would have to be done more than usual to see if it is both a benefit and fair. 

We can also look at other locomotors if needed such as turret rotation speed, and acceleration. 

I have some experience in modding ini script, so I will have to spend some time to remember how, and then test these changes myself. I will likely need a volunteer to simulate battle with these new changes for testing.

**Comment by xezon** [comment]
Note that changes to Locomotor can have huge gameplay impact. For example allowing units to back up vs Humvees can make big difference in how battle engagements are played, for better or worse.

We recently had big discussion about seemingly innocent backwards drive for China Supply Truck.
* #435

NProject Mod adds reverse gear to many vehicles.

It is very risky to make big changes, other than slight tweaks that do not change overall movement capabilities.

**Comment by KrewGR** [comment]
we should test a lot of simulations.

**Comment by RisingZH** [comment]
If you try and reverse a troop crawler it will often do a retarded 360. What's with that.

**Comment by ExiLe-ZH** [comment]
We can always test, it's interesting for sure, although VERY controversial. Many will dislike such a change.

**Comment by xezon** [comment]
I made two locomotor change proposals here to mainly improve visuals and feeling.

* #1138
* #1139

No one has yet tested it or gave feedback.

**Comment by KrewGR** [comment]
I will change all the units locomotives we are curious about for testing purposes and simulate as much as we can with those changes to figure out what would be best, including the troop crawler. 

I left comments on the locomotors for bus and BT.

**Comment by xezon** [comment]
You can also test NProject Mod. It has all locomotors changed in one way or another. For example tanks will have smoother accelerations.

**Comment by KrewGR** [comment]
I am actually having trouble remembering how to even get the INI changes working. Perhaps im doing it wrong.

Where do I download Nproject?

**Comment by xezon** [comment]
https://www.moddb.com/mods/nproject-mod

**Comment by KrewGR** [comment]
So, I have downloaded the mod, and checked it out. Very intersting. The issue I am having is actually seeing any changes I make on the INI. 

On xcc, I opened INIZH.big, then found the locomotive file and extracted that into programs/orgingames/zerohour/data/english and saved it there. 

Then opened the file itself where note pad is used to edit and save anychanges. Anything I am doing wrong here?

**Comment by xezon** [comment]
We edit INI directly here in this project and build with build scripts:
https://github.com/TheSuperHackers/GeneralsGamePatch/tree/main/Patch104pZH/Scripts

Git Repository can be cloned with Git Client.

**Comment by KrewGR** [comment]
Ah, well then, I think this may be way above my skill set. I am not experienced with any of this.

**Comment by KrewGR** [comment]
I found the locomotors on here, and I'd assume I could just copy what I see on the nproject INI code on to the github patch script builder.

**Comment by KrewGR** [comment]
By some miracle, I have indeed figured it out, and it turns out you really can just copy Nproject INI code on to the ZH edit INI code to replicate unit behavior. Neat stuff.

**Comment by xezon** [comment]
Can we close this? I do not think we plan to make any big locomotor changes in the near future. I checked vehicle locomotors just recently and only found odd setups with Battle Bus, Bomb Truck and Troopcrawler.

**Comment by ExiLe-ZH** [comment]
Still be interested to have a testbranch where every single unit has reverse

**Comment by xezon** [comment]
In NProject every unit has reverse as far as I could tell. It looks really funky when the China Dozer drives backwards to build his things :D

**Comment by xezon** [comment]
Closing for the time being.
