### ISSUE TITLE
USA Sentry Drone is immune against toxins

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1203]
USA Sentry Drone is immune against toxins. Toxin General cannot attack it with Rebels, Tunnels and Tractors. Is this a problem?

**Comment by Jundiyy** [comment]
Please don't fix, will make USA super nerfed... 😂 

On a more serious note, I don't think this is a problem. Each unit to their own.

**Comment by ExiLe-ZH** [comment]
Cool little pro I didn't even know about, but not exactly sure why? 

I guess it makes it good at sneaking passed Tox Tunnels, harassing Tox Supplies (similar to Ambulances) or denying Toxin from grabbing/stealing oils? Does MG do enough damage to stop a Toxin Tractor from reaching a Garrison?

Don't see direct reason to nerf it though.

**Comment by MTKing4** [comment]
Good feature, don't remove

**Comment by KrewGR** [comment]
Seems intentional like the ambo.

**Comment by commy2** [comment]
> Seems intentional like the ambo.

Why? Makes no sense. Same for Firebase. Immunity prevents units from clicking targets. E.g. Toxin Tractor/Tunnel/Rebel cannot engage at all. Even tanks and buildings other than Firebase can be clicked.

**Comment by Stubbjax** [comment]
The sense can be derived from the fact that a Sentry Drone has no pilot to infect.

**Comment by commy2** [comment]
Neither has a Gatling turret or an empty Internet Center, or a snipped Battlemaster, all of which can be targeted by poison weapons.

**Comment by Stubbjax** [comment]
Yeah, unmanned units don't make as much sense. So you're simply suggesting a 1% damage modifier rather than 0% to make them at least targetable? How about the Ambulance?

**Comment by commy2** [comment]
Probably 50% to match TruckArmor / Humvee. Or at least 25% to match TankArmor.

FireBase should be 1% though like any other building.

**Comment by Stubbjax** [comment]
Agree with Firebase. But it equally doesn't make sense that a bio weapon is affecting an unmanned vehicle.

**Comment by commy2** [comment]
That's game design though. "Toxin" really is just a stand in for any sort of chemical weapon like acid. Don't think about it too much.

**Comment by Stubbjax** [comment]
Exactly, and I find the more interesting design is that they are resistant / immune.

**Comment by ExiLe-ZH** [comment]
I also think it kinda makes sense that an unmanned vehicle is resistant vs radiation or chemicals, like NASA drones on Mars are also made to be more resistant vs these kinds of treats. Shouldn't look too much into realism though.

Higher instead of full immunity would also be fine I guess? Maybe tune so that Tox Rebel does same damage as a normal Rebel. 

Although I don't see the current state as being problematic. Plus it's nice to have, can this stupid drone have a some nice things atleast lol?

**Comment by Jundiyy** [comment]
I'd prefer to add radiation immunity than remove tox one.

**Comment by ReLaX82** [comment]
I think its a bug.

**Comment by xezon** [comment]
Sentry Drone cannot crush infantry, so the immunity is less consequential for early Worker harassment around a Tunnel Network. And Toxin General is quite good vs USA, so maybe this immunity is ok to compensate for its stronger Toxin Tunnel vs other USA units?

**Comment by xezon** [comment]
Close?

**Comment by xezon** [comment]
We made Sentry Drone better with change

* #1162

There is only one other unit that is immune against toxins, and that is the GLA Toxin Tractor.

**Comment by MTKing4** [comment]
Close
