### ISSUE TITLE
PropagandaCenter can only be build after the Warfactory

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1213]
StrategyCenter can be build after either the WarFactory or Airfield, should this be the case for the Prop aswell?

Both buildings ofcourse got their pros and cons, but is that relevant in this comparison?

**Comment by xezon** [comment]
Removing Airfield Prerequisite from Strategy Center would be nerf for Airforce mostly.

**Comment by ExiLe-ZH** [comment]
If we want to go that route, it would nerf SW BO's aswell. He sometimes goes for DualSup+Airfield+Oilgrab into quick Strat build. Or EMPs + Airfield into quick Strat in teamgames.

My proposal was to diversify China's Build Order options though. It allows for an Helix opening into quick Prop e.g.

**Comment by xezon** [comment]
Yea. It would be buff for Infantry General mostly.

**Comment by Jundiyy** [comment]
Allowing Chinas to build Propaganda Centre after Airfield might not make the biggest of differences. They would still need to make a WF to use the Prop - You don't get any high-tech units at the AF. At the most it can make a Lotus and Hackers.
For Nuke, this would make a difference as they can get to Nuke Migs through a different route.

**Comment by commy2** [comment]
It not unlocking anything for AF is probably the reason for this. I think it is a neat faction difference.

Although with ZH it does unlock Subliminal for Helix with Speaker Tower I suppose.

**Comment by MTKing4** [comment]
Didn't we discuss this before and agreed that it's a good change to build prop from AF?

**Comment by ExiLe-ZH** [comment]
Wasn't that the IC?

**Comment by MTKing4** [comment]
Yeah, you're right. #833 
don't mind me

**Comment by ReLaX82** [comment]
As it opens more options and downsides I think are small I would say yes, can be done after AF.

**Comment by RisingZH** [comment]
Think you would want to test this. I think it would be inf who would use this most to go lixes + super lotus. Can see it being pretty op on maps with a few oils on, especially vs nuke and vchina.

**Comment by ExiLe-ZH** [comment]
Definitely needs testing, on high level aswell. Need to know how such builds can be executed efficiently. 

Problem with testing such changes is predictability though, the new possible builds might look less strong when enemy can anticipate.

I still predict it won't be too OP, usually the best Lix follow up are ground units to counter the anti-air units the opponent has been spamming.

**Comment by Stubbjax** [comment]
Not sure about this one. As others have pointed out, this would benefit Infantry General more than the other Chinas, which could be taking things in the wrong direction.

I can imagine Inf mid in 3v3s going lix + prop, safely capping oils with Lotus and then training Super Hackers (Internet Centre is now available here as well) while they harass; which would add some nice strategic diversity, but be arguably too powerful.

The benefits (and unknown implications) of such a change don't seem to outweigh the risks, and the overall "maintain original gameplay" principle feels like a stronger position in this case.

**Comment by xezon** [comment]
Can we close this?

**Comment by ExiLe-ZH** [comment]
Lol don't jump to conclusions so fast.

First of all, rushing hackers is bad strategy all around. It isn't faster either, airfield takes long to build.

Like I already mentioned aswell, best follow up after Lix is ground, if you casually tech up and make lotus etc. the enemy might be able to just walk into your base with his anti-air and you got no counter.

Secondly, it might help nuke most, he can then do same BO as SW, where he supports with unupgraded Migs while he rushes the Nuke Silo. Sounds most viable in teamgames.

**Comment by MTKing4** [comment]
I don't see how building super lotus and hackers when you only have lixes and infantry making inf OP

It's a very far stretch to say the least, inf units are slow and vulnerable to so many things (migs, Snipers, Tractors, Dragons, AA Units) and lixes can be wrecked by the same anti infantry units (Gats, Quads, Vees) 

This change couldn't be more safe i mean come on :D it doesn't have all that much impact, since inf will need wf if he needs to win anyway, when was the last time you saw inf own without wf?

**Comment by Stubbjax** [comment]
> First of all, rushing hackers is bad strategy all around. It isn't faster either, airfield takes long to build.

`Barracks → Airfield → War Factory → Prop` is an extremely common Infantry General build order in 3v3s. Removing the War Factory from the sequence will open up potential for a faster Prop. The implications of this are unknown. Whether early Super Hackers are a good or bad strategy is too subjective. I've seen it work effectively many times, despite the War Factory requirement and worse Hackers. Regardless, the fast(er) Lotus may be the bigger factor.

> Like I already mentioned aswell, best follow up after Lix is ground, if you casually tech up and make lotus etc. the enemy might be able to just walk into your base with his anti-air and you got no counter.

Allies ideally take care of this.

> Secondly, it might help nuke most, he can then do same BO as SW, where he supports with unupgraded Migs while he rushes the Nuke Silo. Sounds most viable in teamgames.

This is not viable in 1v1 and Nuke is already formidable in 3v3s. Tactical Nuke MiGs are also a huge pain in the ass and certainly don't need any incentivizing. If anything they could do with a nerf.

Anyway, I'm still not convinced. The provided examples are clear changes to traditional gameplay and don't seem to fix anything or directly address any problems.

**Comment by ExiLe-ZH** [comment]
> > First of all, rushing hackers is bad strategy all around. It isn't faster either, airfield takes long to build.
> 
> `Barracks → Airfield → War Factory → Prop` is an extremely common Infantry General build order in 3v3s. Removing the War Factory from the sequence will open up potential for a faster Prop. The implications of this are unknown. Whether early Super Hackers are a good or bad strategy is too subjective. I've seen it work effectively many times, despite the War Factory requirement and worse Hackers. Regardless, the fast(er) Lotus may be the bigger factor.
> 

I know I've seen it alot in low skilled games, but it's bad and that's not subjective. You literally give up your ability to fight when going for Hackers instead of maxing production. That means you can't attack/defend and give up on map control easier, effectively making the game 2v3. Out of all options you have this is the worst strategical choice you can make.

Incase China/Inf/Nuke goes for Lixspam with a faster Lotus, then the only advantage is the ability to disable/steal enemy units/buildings/money. Early oilcap with RGs/MGs is more efficient with this build.

> > Like I already mentioned aswell, best follow up after Lix is ground, if you casually tech up and make lotus etc. the enemy might be able to just walk into your base with his anti-air and you got no counter.
> 
> Allies ideally take care of this.

Yes, like it always was in 3v3. Inf rushing Prop doens't change anything here, he would still need WF to produce Tier 2 stuff. 

> > Secondly, it might help nuke most, he can then do same BO as SW, where he supports with unupgraded Migs while he rushes the Nuke Silo. Sounds most viable in teamgames.
> 
> This is not viable in 1v1 and Nuke is already formidable in 3v3s. Tactical Nuke MiGs are also a huge pain in the ass and certainly don't need any incentivizing. If anything they could do with a nerf.
> 

It indeed isn't viable in 1v1 and it's true Nuke can be very good teamgames, but also often is very mediocre (when facing USA's), like a mid USA could just drop a full Vee or 2 early on and Nuke is dead. 

It's just very risky to skip any "good" units. It's a passive/defensive build that only pays off when your mates don't die, this is not guaranteed and even if your mates don't die, the passiveness allows for the enemy to take the map, in which case it still can be very hard to win with Nuke Migs.

> Anyway, I'm still not convinced. The provided examples are clear changes to traditional gameplay and don't seem to fix anything or directly address any problems.

The only thing it does is diversy the build orders and make the options on par with USA. It's a question of "why not" and there's no need to immediately write it off without having proof it's OP.

If it proofs to be, sure then remove the option.

**Comment by xezon** [comment]
It opens more strategic possibilities for China Infantry General mostly, because of its strong Helix build/rush. Therefore this change is undesired. For other China's this change is less consequential. China Tank and China Nuke need Warfactory anyway.

**Comment by ExiLe-ZH** [comment]
Summary.

Pros:
- Faster Lotus.
- Faster Nuke Silo (good for Nuke).

Cons: 
- Delaying/skipping WF = Leaving you vulnerable vs Anti-Air units. (Can't make 2nd tier units without WF anyway).
- Lotus oilgrab slower/less efficient than early RG/MG (especially on oil heavy maps).

My conclusion:
- It's a different BO but overall more risky and less efficient for all China's except potentially Nuke.
- No reason to remove this option from USA either?

**Comment by MTKing4** [comment]
Agree with exile here
