### ISSUE TITLE
Investigate pilot + transport inconsistencies

### ISSUE THREAD

**Issue by Stubbjax** [TheSuperHackers/GeneralsGamePatch#126]
Pilots will sometimes rank up a transport and other times enter it instead. Seems to be tied to movement delta / update - if colliding with the vehicle on a particular frame or when pathing distance is 0.

https://user-images.githubusercontent.com/11547761/131453671-0dbcc4ea-ecb4-4c94-b606-79e733bd32c7.mp4

https://user-images.githubusercontent.com/11547761/131453843-81e2b347-5b7a-40da-b568-61086debf55b.mp4

**Comment by FiReArM-ZH** [comment]
I did some research on this.
Pilot vets vee only of vee is not moving. If moving, he takes a slot in vee.

Didn't test for full vee yet. Will do tomorrow

**Comment by ExiLe-ZH** [comment]
check second video above, vee is stationary

**Comment by FiReArM-ZH** [comment]
> check second video above, vee is stationary

Well, when I tried for 15-20 times in last few days, it was always like what I mentioned

**Comment by Stubbjax** [comment]
> Pilot vets vee only of vee is not moving. If moving, he takes a slot in vee.
> Well, when I tried for 15-20 times in last few days, it was always like what I mentioned

It's not always like this though. If the Humvee is moving, there is still a chance of ranking up.

I mentioned this in the initial description, but I will elaborate further. I'm not exactly sure how SAGE processes movement / collisions, but what I suspect may be happening is that a pilot only ranks up a vee if the pilot has a positive movement delta for the current frame (the rank logic may be processed at the end of movement logic). If a vee processes its movement first and collides with a pilot, then the collision / enter event is immediately executed before the pilot has calculated its movement, and thus no ranking occurs. This would explain why it only happens while a vee is moving, or if a pilot is close enough to the vee to immediately collide with no movement delta.

**Comment by xezon** [comment]
It could be related to an internal state of target vehicle that does not translate well to observable world.

**Comment by commy2** [comment]
https://github.com/TheSuperHackers/GeneralsGamePatch/pull/1220/files

This forbids `NO_GARRISON` flag objects from entering Humvee. `NO_GARRISON` is unique to Pilot and makes him unable to enter civilian buildings, Tunnels and (iirc) Bunkers. Cursor still appears and it promotes the Humvee when entered. Can you try to reproduce the issue on this branch?
