### ISSUE TITLE
GLA power spam is overpowered

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1278]
GLA's unit-production / building-construction with power is stupidly imbalanced.

Any fixes/clean workarounds possible?

### Proposal 1

Implement faction specific floating point power modifiers for INI script in Thyme.

**Comment by ExiLe-ZH** [comment]
What if GLA spawns with power by default (lowest value possible) where he can not go low power without having power-hungry China/USA structures? We can then double all production times individually.

A problem with this is that if a China/USA teammate surrenders without power/dozer, GLA would now to have sell all power-hungry buildings, otherwise his production will be slow. I guess it's the same thing for other factions, but those can build new reactors when they're not hunted themselves.

**Comment by xezon** [comment]
We cannot fix this because INI scripts do not allow for faction specific power rules.

**Comment by ExiLe-ZH** [comment]
Not so fast lol.

It's good to have a brainstorm topic. 

And have you read my idea even?

**Comment by xezon** [comment]
Touching this is highly controversial and I would strongly advise against it.

**Comment by ExiLe-ZH** [comment]
Isn't it controversial in itself already when we need tournament rules? 

Even with the rules there's drama about it every single tourny.

**Comment by Jundiyy** [comment]
There are only 3 states.
No power = slowest build
Low Power, but have some power = faster build
Power = fastest build

https://youtu.be/6DOca1DVAA4

I don't think you can achieve the GLA trick you want.
And yes, seems quite controversial.

**Comment by ExiLe-ZH** [comment]
Oh that's interesting, didn't know there was a difference between no power and low-power. 

So currently standard GLA production is based on no power right? Does that mean that his production will be faster but not the fastest with low-power?

If that's the case, can't we make GLA spawn on low-power (without the annoying warning voice) and readjust all values to match the original values again? With this change the jump from _low-power_ to _power_ is a smaller speed bonus than _no-power_ to _power_ right?

**Comment by Jundiyy** [comment]
Yes, low power is still slower than power but not a lot. So if we set GLA to somehow start with low power, then it gained power, it would only get a little boost. 

Don't know what workaround there would be, you'd have to have some power showing in the bar, which would be odd for GLA. 
And if you remove the EVA sound, which is possible as far as I know, then it would also be removed if GLA was actually on low power after gaining power.
So it took a Dozer, made some usa/China buildings, lost power, is now in low power mode, but there would be no announcement.

**Comment by ExiLe-ZH** [comment]
A kinda dirty fix would be to make all gla buildings require a tiny bit of power (values that aren't visible in the power bar). But yea, then we'd have remove the voice, which like you said also removes important warnings.

There isn't a way to add a new powerstate exclusively for gla is there?

**Comment by commy2** [comment]
Power is handled in integers. The lowest amount of power > 0 is 1.

**Comment by xezon** [comment]
Can we close this?

**Comment by Jundiyy** [comment]
For me, it's fine to close. If Exile wants more ideas, up to him.

**Comment by ExiLe-ZH** [comment]
With my limited knowledge the only other thing I could think of is increasing doortime and decreasing production time so that power has less influence on the total production time. But it's not a very clean way of doing it.

It can be closed for now, further ideas can always be posted here.

**Comment by xezon** [comment]
We need less issue reports, not more ;)

**Comment by ExiLe-ZH** [comment]
It's ok, it's not growing as fast as before and it will only slow down more with time. 

It's also important we collect and discuss every single issue (that matters) in the game, it's the goal of the project.

**Comment by xezon** [comment]
Requires code feature(s).

**Comment by xezon** [comment]
* Duplicate of TheSuperHackers/GeneralsGameCode#94
