### ISSUE TITLE
AI Stealth GLA can build Demo Bikes (in Singleplayer)

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#131]
AI Stealth GLA can build Demo Bikes (in Singleplayer).
Reported by Pinguxo.

**Comment by Jundiyy** [comment]
Should this be fixed? The AI would only build it because it was scripted in the 'team' section. It's part of their unit list.

**Comment by xezon** [comment]
I don't think it is necessary to change this.
