### ISSUE TITLE
GPS Scrambled Worker for Stealth General is OP

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#1330]
Should we do anything about this insane combo?
It offers no counterplay and its impact is devastating to the enemy building stealth tunnels with stealth workers

[Example of it affecting the outcome of an otherwise lost game](https://youtu.be/Wi4CTDuMLk0) 
### Proposal 1
Stealth Workers don't benefit from GPS Scrambler

### Proposal 2
All Workers don't benefit from GPS Scrambler

### Proposal 3
All Workers and Dozers don't benefit from GPS Scrambler

**Comment by Jundiyy** [comment]
No, leave as is.

**Comment by MTKing4** [comment]
Your reasoning?

**Comment by Jundiyy** [comment]
It's not bugged, is powerful no doubt, but no need to change things which are not broken. As Rage has said in the past, it's part of what makes this game fun.

**Comment by MTKing4** [comment]
Never said it was a bug, but it's unbelievably unfair and it deserves a discussion imo

**Comment by xezon** [comment]
I think what makes it so good is that Tunnels have stealthed scaffolds, not Workers being stealthed.

**Comment by MTKing4** [comment]
changing scaffolds' behavior will probably be more controversial than simply making workers unstealthable, those are much rarer to happen

**Comment by Jundiyy** [comment]
> Never said it was a bug, but it's unbelievably unfair and it deserves a discussion imo

Welcome a discussion, I have nothing else to add since I think the way it is, is fine. Many things are powerful and op but part of the fun.

Wrong topic but Stealth Defence Tunnels when rebuilding should be stealthed as well. Them not being stealthed seems like a bug.

**Comment by ExiLe-ZH** [comment]
It's strong no doubt, but isn't completely uncounterable. Don't see reason to nerf it.

1. Using GPS scrambler can be heard by enemy, he should be aware of a possible stealth worker tactic. Player can and should anticipate by setting up stealth detection at key locations.
2. Scaffolds are seen for a split second when placed down, allows player to react before tunnel gets up.
3. Upon completion RPGs can be seen for a second, allows player to react before more tunnels are build. Game isn't always instantly over when one tunnel gets up.

**Comment by xezon** [comment]
Can we close this?

**Comment by xezon** [comment]
* Related #1148
