### ISSUE TITLE
Review China Infantry Minigunner sounds

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1331]
Review China Infantry Minigunner sounds. Anti Air firing sound likely needs to be different than Ground firing sound, otherwise distinction is lost.

**Comment by commy2** [comment]
No such distinction exists for Patriot Battery, Laser turret, Raptor, MiG, Missile Defender, Tank Hunter, Tunnel Defender, Stinger Site, Quad Cannon, Tow Vee, Gatling Tank, Gatling Gun or Gatling Overlord either.

**Comment by xezon** [comment]
I checked. It did sound odd to me, because I expected deep Gattling sound, not light Machine Gun sound.

**Comment by MTKing4** [comment]
I'd like to have that back too yes, minigunner used to be recognized when attacking air units, it doesn't have to be the gatling sound explicitly though, sound shifting sounded nice

**Comment by xezon** [comment]
Anti Pro:
> a few bugs have ended up improving the game almost by mistake. A low-key but prime example of this is infantry mini-gunners and the sound they make when firing at air units (the bug being that they use the sound from a gat tank instead of the mini-gunner's normal ground-firing sound). When I tested the most recent patch the bug was 'fixed' and it made it impossible to know that a mini-gunner was firing at an air unit, very annoying.

Dominator:
> Mini gunner shooting up should keep that gat sound IMO

ReLaX:
> This one should get a different Sound as its an important one.
