### ISSUE TITLE
GLA Quad Cannon, China Gattling Tank, Gattling Turret, has no recoil and muzzle flash on ground attack

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1332]
GLA Quad Cannon, China Gattling Tank, Gattling Turret, has no recoil and muzzle flash on ground attack

**Comment by xezon** [comment]
Some of the issues were tackled in this change already, however it should probably be redone in isolation.

* #1222

**Comment by commy2** [comment]
Issue does not apply to Helix Gatling Gun or Minigunner.

**Comment by commy2** [comment]
done

**Comment by ExiLe-ZH** [comment]
video examples? :)

**Comment by commy2** [comment]
Gatlings:

https://user-images.githubusercontent.com/6576312/194762649-2570885b-ddc2-46ed-88cf-a6ce1987212b.mp4

**Comment by commy2** [comment]
Quad Cannon:

https://user-images.githubusercontent.com/6576312/194764236-2064b105-d900-46f2-b27f-2cd6951f70c4.mp4

Note that these are already in the game, but only work when aiming at airborne units.

**Comment by ExiLe-ZH** [comment]
Nice work! ❤️
