### ISSUE TITLE
Beacons have limit of 3 per player

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1363]
Not sure if it's due to performance reasons, but the limit of 3 is way too low and it can mess up team play when you need to beacon quickly. Now to mark SW's for yourself you could set bookmarks but it's not as precise.

**Comment by MTKing4** [comment]
I think this is an executable/engine issue

Usually advanced RTS games make Beacons auto delete themselves after a period of time, but that wouldn't be so helpful for our game would it ^^

Think one useful feature is to have a button that auto removes all beacons on the map, so you don't have to go monkey mode looking for all beacons to delete, but that i think is for thyme to add

**Comment by kajxqeirscl** [comment]
I think everyone will be happy if it was changed to 5 for example. Don't see why people would complain about such change. pretty sure if there aren't like 80 beacons on the map it won't cause performance issues.

**Comment by xezon** [comment]
Is it possible to assign sell hotkey to "Delete Beacon" button? It may be.

**Comment by Jundiyy** [comment]
It already has a key, the delete button.

**Comment by ExiLe-ZH** [comment]
gotta find and select first and the key being on the other side of the kb doesn't make it very practical (probably can be changed in commandset.ini), but as standard might aswell move the mouse and click.

**Comment by commy2** [comment]
multiplayer.ini

MultiplayerSettings
  StartCountdownTimer = 5
  MaxBeaconsPerPlayer = 3

I don't know if it is functional. Also note the StartCountdownTimer.

Swap these values.

**Comment by Jundiyy** [comment]
I think Contra Mod did play around or look at the beacons, but don't know why it wasn't changed. Can ask Predator.
And yes, lower countdown timer is good imo.

@ Exile.
I was simply reminding that there was a key. And tbh I do use the key lol.

**Comment by kajxqeirscl** [comment]
> I think Contra Mod did play around or look at the beacons, but don't know why it wasn't changed. Can ask Predator. And yes, lower countdown timer is good imo.
> 
> @ Exile. I was simply reminding that there was a key. And tbh I do use the key lol.

Lower countdown timer isn't good imo. 5 seconds gives you enough time to say glhf for example which I like.

**Comment by MTKing4** [comment]
> Beacons have limit of 3 per player

Pretty sure there's a global limit as well is there not?

**Comment by ReLaX82** [comment]
If limit can be 5, do it!
