### ISSUE TITLE
Balancing between AF and Laser, SW and USA

### ISSUE THREAD

**Issue by ReLaX82** [TheSuperHackers/GeneralsGamePatch#1403]
Its obvious why AF has this vast advantage.
The question is, can we just change these 3 matchups without changing others?

I think yes, if anyhow possible coding wise.
What do you think about an upgrade effecting all MD missiles?
It should nullify or significant weaken the pld effect on MD missiles on chinooks only maybe.
It will then help vs Combat Chinook Rushes and usual MD drop wars early game.

Making this upgrade available somewhere, possibly supply or Rax can be an option, name, price, BT to be discussed.

What do you think?

**Comment by xezon** [comment]
Issue report is too broad. Cannot generate work from this.
