### ISSUE TITLE
GLA Terrorist suicides when killed by USA Patriot

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1423]
GLA Terrorist suicides when killed by USA Patriot. Fix suicide setup.

**Comment by commy2** [comment]
EXPLODED death flag

**Comment by commy2** [comment]
This happens in 1.04 for all Terrorists, except the Demo Terrorist.

https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Object/GLAInfantry.ini#L1440

Terrorist fires explosion weapon when, among others, run over (CRUSHED), killed by Paladin PDL (LASERED), Dragon Tank (BURNED) or any EXPLODED type weapon (Tow Missile, but not Humvee gun, Rocket Buggy, any rocketeer infantry, Scrap 2 Technical [but not the others]) etc.

**Comment by commy2** [comment]
Also note that while the Terrorist does deal damage, the unit is not flung into the air, except when he blows himself up. Deals same damage anyway. Also note that 1.04 Toxin Terrorist is completely broken as far as which death weapon is used, so ignore that one when testing this issue.

**Comment by xezon** [comment]
As designed.
