### ISSUE TITLE
China Tank Hunter has wrong "exploded" animation

### ISSUE THREAD

**Issue by MavroGada2** [TheSuperHackers/GeneralsGamePatch#1451]
Tankhunter has animation for "exploded" type of death in CCG. Every animations still same  in Zero Hour but devs add " AliasConditionState = DYING RUBBLE " below to "DYING" state. Because of that when TH killed by explosion, he's flying with standard death animations.

https://user-images.githubusercontent.com/103841664/200197433-051d2829-0843-4e53-8a1f-acd17409d10a.mp4

Here's the CCG version;

https://user-images.githubusercontent.com/103841664/200197665-a56362e2-aa16-4263-9fb5-5e0a62dca9f4.mp4

No other infantry have that.

**Comment by xezon** [comment]
Thank you for excellent report.
