### ISSUE TITLE
China Hacker has wrong death voices

### ISSUE THREAD

**Issue by MavroGada2** [TheSuperHackers/GeneralsGamePatch#1454]
CCG has different voice format than Zero Hour. All infantry voices are in "; *** AUDIO Parameters ***"  and all "SlowDeathBehaviors" has same "FX_GIDie" what i've seen so far, which is null fx  in CCG FXlist.ini . They changed that in Zero Hour, all death sounds are in Fxlist.ini.

I think they made this mistake during the change.
They put the "RedGuardVoiceDie" to "FXList FX_HackerDie".

ZH:

https://user-images.githubusercontent.com/103841664/200200502-34d1d48d-466b-4bb7-80ad-803a733b519f.mp4

CCG:

https://user-images.githubusercontent.com/103841664/200200510-6526d03f-eed2-4030-a335-36210a6aaf33.mp4

**Comment by Stubbjax** [comment]
I noticed this a while ago but found the real Hacker death screams to be abhorrent and better left the way it is.

**Comment by xezon** [comment]
I like the hacker screams.

**Comment by ExiLe-ZH** [comment]
I like ccg voices better too

**Comment by commy2** [comment]
I like it when the Hacker uses the Hacker voice and the Red Guard uses the Red Guard voice.
