### ISSUE TITLE
Investigate whether or not USA Ambulance clears up toxins correctly

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#146]
Investigate whether or not USA Ambulance clears up toxins correctly. Control fire for it works fine but Clear Toxin ability rarely works. Reported by Dominator.

**Comment by xamorish** [comment]
Using Clear Toxin ability near the spot where an Anthrax Bomb landed works perfectly fine. Same goes for toxin clouds that SCUD missiles leave after explosions. Tested both scenarios on a custom map.
