### ISSUE TITLE
USA Helicopters are too steady in the air

### ISSUE THREAD

**Issue by MavroGada2** [TheSuperHackers/GeneralsGamePatch#1465]
Helicopters except Helix are too steady in the air.

Helix has a few extra parameters which making it more "fluid" than other Helis. These parameters no effect on original movements they are just adding "animations".

Original:

https://user-images.githubusercontent.com/103841664/201501590-cc26e9b6-2582-4ee1-87a8-e4ba1c0d8b8e.mp4

I added same parameters with same values to USA Helis.(I reduced Chinook's values a little)

New:

https://user-images.githubusercontent.com/103841664/201501731-f7b57ca2-1432-4559-879d-394c26de5cbf.mp4

Chinook Original:

https://user-images.githubusercontent.com/103841664/201501744-59fe023a-8c63-40d5-a3e0-0d294e819630.mp4

Chinook New:

https://user-images.githubusercontent.com/103841664/201501757-8e754cf4-3048-4b82-9e57-fc7836931339.mp4

Comanche Original:

https://user-images.githubusercontent.com/103841664/201501767-9455cfc0-1a29-47ee-a211-d8c98a31eb85.mp4

Comanche New:

https://user-images.githubusercontent.com/103841664/201501773-04b0193b-1c96-425c-b70e-6c66f2a4a55e.mp4

Helis from default zoom:

https://user-images.githubusercontent.com/103841664/201501794-93c9ffae-6d4e-4bc1-aa6f-59fb3bebde57.mp4

**Comment by xezon** [comment]
I like this. It makes sense that they all display a little bit of sway. Makes it look a bit more natural and consistent with Helix Helicopter. This is purely cosmetic right? What do the INI setups look like?

**Comment by MavroGada2** [comment]
> This is purely cosmetic right? 

Yes. I tested with extreme values ​​just to be sure of everything. Edited Comache can shoot same time like Original Comanche with the same position. Mobility have to same because all values are same about speed, acceleration, turn rate, etc. but tested anyway.  

Test Video;

Shooting:


https://user-images.githubusercontent.com/103841664/201528421-d481be5a-be1d-4be7-91dd-93ab824c2acb.mp4

Mobility:


https://user-images.githubusercontent.com/103841664/201528436-1c2894c0-10b1-4d9b-a0e3-b65e057af0b6.mp4




> What do the INI setups look like?

[Loco.txt](https://github.com/TheSuperHackers/GeneralsGamePatch/files/9997520/Loco.txt)

**Comment by ExiLe-ZH** [comment]
A little sway looks nice.

Lol your pilots are drunk MTKing, sent them home 😄

**Comment by KrewGR** [comment]
I like this. The animation makes sense, and feel way more natural

**Comment by MTKing4** [comment]
> A little sway looks nice.
> 
> Lol your pilots are drunk MTKing, sent them home 😄

Why me 😄 

@MavroGada2
Mobility Test video shows that rocket positions are static and not linked to the model, so that would mean they would be off by a little at least when swaying, is there a way to link them to the model?

I might be imagining things but i think we at one point discussed making its fireports to its side wings, or maybe that was GenEvo, i don't even know anymore

Edit: maybe we discussed that for rocket pods, as it has no rockets on sides before upgrade

**Comment by ExiLe-ZH** [comment]
> > A little sway looks nice.
> 
> > 
> 
> > Lol your pilots are drunk MTKing, sent them home 😄
> 
> 
> 
> Why me 😄 

I thought you posted that video lol, guess the avatar made me think that :D

**Comment by MTKing4** [comment]
You should know me from my control bar 😛

**Comment by MavroGada2** [comment]
> > A little sway looks nice.
> > Lol your pilots are drunk MTKing, sent them home 😄
> 
> Why me 😄
> 
> @MavroGada2 Mobility Test video shows that rocket positions are static and not linked to the model, so that would mean they would be off by a little at least when swaying, is there a way to link them to the model?
> 
> I might be imagining things but i think we at one point discussed making its fireports to its side wings, or maybe that was GenEvo, i don't even know anymore
> 
> Edit: maybe we discussed that for rocket pods, as it has no rockets on sides before upgrade

@MTKing4 I think model is static too. What we see is not the same as what actually happened. Because of it's just cosmetic, I don't think we can do anything. Bullets are coming from same position with main rockets btw. What we see is just fx.

This is what we see:

https://user-images.githubusercontent.com/103841664/201855921-46584846-2ea1-46cc-8e25-29f327cf6852.mp4

Whats actually happening:


https://user-images.githubusercontent.com/103841664/201856737-b0b58524-c0ab-4d3f-88bd-bb057eacb747.mp4

**Comment by MTKing4** [comment]
> I think model is static too. What we see is not the same as what actually happened. Because of it's just cosmetic, I don't think we can do anything. Bullets are coming from same position with main rockets btw. What we see is just fx.

Yes I'm aware of that, normal rockets and MG shooting from the same spot but rocket pods shoot from wings

From what i can see is that rocket positions is linked to game code, which i assume is in INI, and MG and your movement edit linked to model and animation, in normal inanimated model, rocket position will align with model all the time, but with this edit it might be off a bit, don't like that personally, but i wonder how much off it is.

**Comment by xezon** [comment]
looks fine

https://user-images.githubusercontent.com/4720891/201985345-be19afdf-cc5a-4274-9c27-bc391992fffa.mp4

**Comment by MTKing4** [comment]
these are rocket pods, I'm talking about the default rockets

**Comment by xezon** [comment]
can you test it or no?

**Comment by MTKing4** [comment]
Will test it

**Comment by xezon** [comment]
Looks fine too.
