### ISSUE TITLE
Worker With Supply Plays Wrong Animation When Blown Up

### ISSUE THREAD

**Issue by MavroGada2** [TheSuperHackers/GeneralsGamePatch#1468]
When worker is carrying supply and building while it has supply, it plays wrong blown up animation.  Using mine detector while have supply is ok.

For fix delete "AliasConditionState =  DYING CARRYING" under   "ConditionState = DYING" .

Original:

https://user-images.githubusercontent.com/103841664/201549092-1c005f94-d62d-4766-9362-1a5c72a4b5a4.mp4

Fixed:

https://user-images.githubusercontent.com/103841664/201549116-ad98b93a-d38d-4a14-a48b-2dcbd1e54c5d.mp4

Original Builder:

https://user-images.githubusercontent.com/103841664/201549136-0cfc496a-1d57-4959-8866-177107fd24a2.mp4

Fixed Builder:

https://user-images.githubusercontent.com/103841664/201549148-ca5675b4-27fe-4a6d-a92e-89dc8cf6593c.mp4

**Comment by MTKing4** [comment]
I'm not sure why is it considered a wrong animation, he flies a bit less because he's carrying something?
If not, what is that animation meant for?

**Comment by ExiLe-ZH** [comment]
Im confused, I can't tell the difference.

**Comment by MavroGada2** [comment]
> 



> I'm not sure why is it considered a wrong animation, he flies a bit less because he's carrying something? If not, what is that animation meant for?

He flies exact same height. Animations no effect  on "SlowDeathBehavior" . It's wrong because It's just flies with standard dying animation when have supply



> Im confused, I can't tell the difference.


Worker with supply is using standard dying animation when blow up.

**Comment by MavroGada2** [comment]
> Im confused, I can't tell the difference.

Worker with supply blow up with standard death animation.

**Comment by commy2** [comment]
> I'm not sure why is it considered a wrong animation, he flies a bit less because he's carrying something?

The corpse being thrown into the air is not the animation. That happens regardless when blown up. The difference is the animation the corpse plays. The correct one is where the corpse spins around. The wrong one is where the corpse collapses on the "ground". Being flung into the air, while the body plays the collapsing animation is broken.

**Comment by MTKing4** [comment]
Yes i noticed, the backflip is the right animation, the flying part made it hard to notice the other animation was just the worker lying on its back animation

**Comment by commy2** [comment]
This broke the normal death animation (not blown up, but shot) while carrying. He now sinks into the ground without falling over.
