### ISSUE TITLE
Comanche Looks Weird For 1.5 Seconds When It Hits The Ground

### ISSUE THREAD

**Issue by MavroGada2** [TheSuperHackers/GeneralsGamePatch#1478]
Title.

It looks "less weird" in CCG with effects appropriate to the situation(hit the ground, final blow up) of the comanche.

But particle effects  changed in ZH and It looks weird when waiting for final blow up.

CCG:

https://user-images.githubusercontent.com/103841664/203530544-b1e42c4e-35f2-4926-b228-59b0a0959960.mp4

ZH:

https://user-images.githubusercontent.com/103841664/203531790-3491e0e8-f0b3-4b73-bb3f-bf1a380c62d1.mp4

Without Delay:

_**Deleted "DelayFromGroundToFinalDeath     = 1500"**_

https://user-images.githubusercontent.com/103841664/203532484-0703598f-a21c-4e71-818e-f0fefcd7099a.mp4

**Comment by xezon** [comment]
I suspect particle effects were fixed with
* #809

As for explosion delay, we can remove if that makes it look better as well. Should test on Patch first.

**Comment by commy2** [comment]
I like the CCG one the best. I suspect it's broken in ZH due to the particle bug. Would need to double check if that is already fixed in patch.

**Comment by xezon** [comment]
I tested in main branch. Particles show properly. The explosion delay is weird, because essentially it explodes twice: once on impact and then once more with a delay.

**Comment by xezon** [comment]
Helix and Chinook explode on impact just once.
