### ISSUE TITLE
Selecting all Aircrafts (W) selects Spectre Gunship

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#148]
Selecting all Aircrafts (W) selects Spectre Gunship. Check if this can be changed.

**Comment by alanblack166** [comment]
Add IGNORES_SELECT_ALL KINDOF to solve the issue.

**Comment by commy2** [comment]
This is not obvious to me that it would be an improvement if taken out. Consider playing as vUSA in a 1v1 game. You likely will build not a single air unit, but you will be able to quickly select your Spectre using W.

**Comment by xezon** [comment]
This was reported by Mad Rage, one of the best players in this game. This report makes sense, because when you have air units and you press WW (2xW), then you would not want your planes + Spectre selected.
