### ISSUE TITLE
Toxin(tunnel) nullifies Demo Bike damage

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1482]
https://www.youtube.com/watch?v=oHxpVEROfjk&t=538s

**Comment by xezon** [comment]
I think we fixed that already.

**Comment by commy2** [comment]
This only happens after the Demolitions upgrade and this only happens when the Tunnel had been upgraded with Anthrax Gamma. It has been fixed in patch already: https://github.com/TheSuperHackers/GeneralsGamePatch/pull/104
