### ISSUE TITLE
Sometimes Aurora Alpha fuel bomb does not happen after initial bomb it dropped on target

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#15]
Sometimes Aurora Alpha fuel bomb does not happen after initial bomb it dropped on target. Fixable?

Haubibban:
> Put a unit behind the tall structure and order Alpha to attack it from opposite side

**Comment by xamorish** [comment]
Also happens with the regular Fuel Air Bomb superpower aka DaisyCutter that gets delivered by a USA bomber.
