### ISSUE TITLE
Demo_GLAVehicleBattleBusDeathWeaponDummySuicide does not work

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1501]
Demo_GLAVehicleBattleBusDeathWeaponDummySuicide does not work. It applies no damage and no particle effects.

**Comment by commy2** [comment]
Probably need to reverse these changes: https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini#L22432-L22450

I don't think particle beam resistance will matter if the dummy only lives one frame.

**Comment by xezon** [comment]
I confirm, ActiveBody + DestroyDie makes it work.

**Comment by xezon** [comment]
There is a Radar Alert event on Battle Bus suicide.

**Comment by xezon** [comment]
I had to remove Demo_GLAVehicleBattleBusDeathWeaponDummy. For some reason this causes double death explosion. I do not know where the other death explosion comes from, but that fixed it.

**Comment by commy2** [comment]
Remove from where? The dummy is necessary for the Bus to damage enemies.

**Comment by xezon** [comment]
Removed from BattleBusSlowDeathBehavior. From there it applied damage twice. Why, I do not know.
