### ISSUE TITLE
Booby Traps can be pushed around by Nuke Migs/Nuke Carpet Bombers

### ISSUE THREAD

**Issue by Battlefieldkille** [TheSuperHackers/GeneralsGamePatch#1502]
After watching some 1v1s on youtube I noticed that if a rebel Booby Traps a building, it can be pushed around by Nuke Mig's missiles/Nuke Carpet Bomber's bombs. This does not happen by other nuclear blasts.
Demo Jarmen/Burton charges arent affected by this.

https://www.youtube.com/watch?v=JT4hLWHQ6M0
Both Booby Traps are dispersed by Nuke Carpet Bomber.
One on the left demonstrates that if an enemy tries to enter a Booby Trapped building while its further away from the original position; it wont detonate. The other one on the right just shows that it can be tossed around like a football by Nuke Migs.
[BoobyTrap.zip](https://github.com/TheSuperHackers/GeneralsGamePatch/files/10232207/BoobyTrap.zip)

**Comment by xezon** [comment]
I tried adding following KindOf to Object BoobyTrap: INERT IMMOBILE UNATTACKABLE DRAWABLE_ONLY

It did not fix the problem.

**Comment by xezon** [comment]
I also tried different body type:

```
  Body = StructureBody ModuleTag_01
    MaxHealth = 3.402823E+38
    InitialHealth = 3.402823E+38
  End
```

And different Armor type:

```
Armor InvulnerableAllArmor2
  Armor = DEFAULT         0%
  Armor = UNRESISTABLE    0%
End
```

**Comment by xezon** [comment]
Removing the Physics module appears to fix it.

```
  ;Behavior = PhysicsBehavior ModuleTag_02
  ;  Mass = 5
  ;End
```
