### ISSUE TITLE
Overcharged China Reactor damages quicker than Dozer Repair

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1509]
Overcharged China Reactor damages quicker than Dozer Repair.

### Proposal 1

Damage overcharged reactor less.

**Comment by xezon** [comment]
Exile:
> It's convenient how you never have to go offline as China, but it requires you to build another already more expensive reactor. You need 2 dozers, 1 for repair, another for building a new one. Otherwise without repair the self-destruction goes super quickly and it's very costly if it does self-destruct (or the enemy gives the last poke at low hp), that requires you to make another one, that's already $2K.

**Comment by xezon** [comment]
I think it is deliberate that Reactor damages quicker than Repair. This way there is a definite time limit and it cannot be abused for infinite duration. The overcharge is meant to fix temporary power outage. It is not meant to make new Reactor build obsolete. We can still take a look at how long it takes for Reactor to suicide from overcharge with and without Repair and see if it is reasonable duration to begin with.

My current instinct tells me that it is ok as is, though I would need to check to make sure.

**Comment by MTKing4** [comment]
Reduce damage or make it equal to repair, i lean towards making it equal to repair

**Comment by ExiLe-ZH** [comment]
It's most likely delibrate indeed and I'm not sure if the reactor should stay at full HP forever when repaired, but slowing down destruction rate might be justified.

**Comment by HeissesFeuer** [comment]
I don't think this needs to be changed, it never really posed any problem I don't think.
As xezon said, it's most probably deliberate. that way you  have to make another power plant soon.  which makes sens to be honest since you are overheating the reactor to produce more energy.
I say keep it as is, it doesn't make sens for the dozer to be repairing it faster.

**Comment by xezon** [comment]
I tested times.

* Overcharge Suicide Time: 33 seconds
* Overcharge Suicide + Repair Time: 99 seconds

Max 33 seconds for overcharge is not bad. 99 seconds for overcharge is pretty good. This does not look in need of touching.

Close?

**Comment by HeissesFeuer** [comment]
Yes I think so, it is fine as it is already.

**Comment by ExiLe-ZH** [comment]
I wanted to revisit this, there's two things:

1. Overcharge provides +5 (+9 Nuke), this may not be sufficient to temporarily replace a destroyed reactor (base building provides +10, Nukle +18).

2. 33 seconds doesn't give alot of slack when you don't have any Dozers (but have a CC). When you instantly queue a Dozer, build a new Reactor and turn off Overcharge instantly aswell, your old Reactor will have about 15% HP left. An easy pick off for the enemy, such situation can easily cost you the entire game as you can never recover.
