### ISSUE TITLE
China Bomber Plane has same sound loop with China Cargo Plane

### ISSUE THREAD

**Issue by MavroGada2** [TheSuperHackers/GeneralsGamePatch#1517]
China Bomber and Cargo Plane have same sound loop(propeller sound) unlike their USA counterparts.

**Comment by xezon** [comment]
Can you elaborate?

**Comment by MTKing4** [comment]
Correct. China Bomber Should have the Bomber Sound Loop not the Cargo Plane Sound loop


https://user-images.githubusercontent.com/83613147/210901461-0d947188-fa41-46f4-8bb3-99377c53fb8c.mp4

**Comment by xezon** [comment]
Ok. Should be fairly easy to fix then.

**Comment by fastAiRR** [comment]
Random, but, Burton and the sentry drone have the same machine gun sound file.
