### ISSUE TITLE
Outpost wont shoot buildings

### ISSUE THREAD

**Issue by fastAiRR** [TheSuperHackers/GeneralsGamePatch#1518]
There is a bug where outposts wont shoot enemy buildings. They shoot 1 volley of rockets and then stop, guard mode doesnt work either. You need to evac the men and shoot the building. 
I think the bug is present for all china outpost except china infantry.

**Comment by xezon** [comment]
Already fixed with
* #4

Thanks for reporting.

**Comment by fastAiRR** [comment]
ah ok thanks
