### ISSUE TITLE
Game performance gets slower over time

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1519]
* Similar to #946

Reproducible on map

https://github.com/TheSuperHackers/GeneralsGamePatch/tree/main/Maps/Any/!TestAllFactionsBuildingsUnitsPromo

**Comment by xezon** [comment]
I narrowed it to USA Microwave. Just build a bunch of them and wait.

What did we do to Microwave?

![shot_20230106_194754_1](https://user-images.githubusercontent.com/4720891/211078726-ad4f4766-7849-46f4-b3e5-bec0cd80de2b.jpg)

**Comment by MTKing4** [comment]
Texture improvements, other than that idk

**Comment by xezon** [comment]
@commy2 
Any ideas?

**Comment by xezon** [comment]
Possibly related to particles. When frame rate is low, many particles no longer spawn, perhaps because more priority effects use up all particle slots.

![shot_20230128_205942_1](https://user-images.githubusercontent.com/4720891/215288331-7b1cc135-4992-4a21-b60c-349a8a29e073.jpg)

**Comment by xezon** [comment]
Ok I think I found the offending change.

**Comment by xezon** [comment]
For some reason the `MicrowaveFlare` effect never despawns. It is essentially a broken effect. Here it is being visualized. Investigating...

![shot_20230128_215621_2](https://user-images.githubusercontent.com/4720891/215290777-9eb4b82c-72b7-45ec-8d0b-a51197bcffa3.jpg)

**Comment by xezon** [comment]
Ok it is `SystemLifetime = 0`. Zero appears to be synonymous for infinite. Setting it to 1 fixes it.

![shot_20230128_215839_1](https://user-images.githubusercontent.com/4720891/215290863-15f6cdbe-8c54-47a6-9900-8dd7ba056991.jpg)

**Comment by xezon** [comment]
In my understanding, `SystemLifetime = 0` is only ok if the parent object is short lived. If lifetime is uncapped, then particle will spawn every frame and live forever.

On quick inspection, there are at least 2 suspicious effects:

JetBurning
WaterSpraySplash

**Comment by commy2** [comment]
Which commit introduced this?

**Comment by xezon** [comment]
> Which commit introduced this?

39f063905bdefcadece7f0249f87901913f03682
