### ISSUE TITLE
USA Strategy Center Bombardment Gun does not attack reliably

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1521]
* Related to #1212

USA Strategy Center Bombardment Gun does not attack reliably. It may not attack targets on its own.

**Comment by xezon** [comment]
Observations:

Placing Strategy Center Gun next to enemy defenses will make it auto attack the structures. Giving manual attack order on an enemy structure will stop the firing. It will not longer auto attack anything. Force firing the ground always works.

**Comment by ThePredatorBG** [comment]
Try removing `AutoChooseSources = PRIMARY NONE` from the WeaponSet.

**Comment by xezon** [comment]
> Try removing `AutoChooseSources = PRIMARY NONE` from the WeaponSet.

Already did. It worked.
