### ISSUE TITLE
Match observer can delete all player beacons

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#153]
Match observer can delete all player beacons. Likely code issue. Investigate.
Does INI have any control over beacon creation?
Hiding "Delete Beacon" button for Observer would help. In ControlBarPro Addon this button is removed for Observer only.

**Comment by xamorish** [comment]
`CommandButton.ini`:
![image](https://user-images.githubusercontent.com/89276291/131916812-06cbdc3a-f39b-4868-821b-59c06dde80eb.png)

`PLACE_BEACON` seems like a hardcoded command inside the game's engine. So i doubt INI can have control over that.
Removing this button for Observers might solve the issue.

**Comment by FiReArM-ZH** [comment]
I don't think that will solve completely.
Observer can select the beacon and press delete to remove it

**Comment by xezon** [comment]
According to user Stazzz, Observer can remove beacon, but it will not disappear globally, just for Observer himself. That is sound logic and requires no attention.

**Comment by commy2** [comment]
> Observer can remove beacon, but it will not disappear globally, just for Observer himself. 

This is not true in my experience. The beacon is deleted for anyone, thus the Obs can actually influence the game by deleting beacons of the player.

**Comment by Stubbjax** [comment]
I just tested this and it only deletes the beacon for the observer.

**Comment by xezon** [comment]
So I close it again? 🤣
