### ISSUE TITLE
Anti Air units have difficulties targeting USA Humvee or its Drone as they alternate between these two targets

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#154]
Anti Air units have difficulties targeting USA Humvee or its Drone as they alternate between these two targets. Very apparent with Quad.

**Comment by Jundiyy** [comment]
Not sure if this is a problem? Do the units not attack the closest unit first unless ordered, so if the drone is in closer ranger (which it does happen whilst it's flying around) then the AA will target them first?

Also, if counted as aircraft would you still be able to GPS Scrambler them in team games? Or even as GLA/Stealth in 1v1s after you snipe?
Currently you can use GPS on the drones or the Humvee without it's Drones and you will get stealthed Drones.

**Comment by xezon** [comment]
That's a good point about the GPS Scramble. I am not sure if this issue needs addressing. But I do recall seeing odd behavior with Quad Cannon when clicking the Humvee. The Quad still targets the drone and keeps alternating targets until the Humvee is in definite shoot range. Still the Quad will suffer, because the Quad Turret takes some time to re-target from Drone to Humvee.

**Comment by xezon** [comment]
Enlima29:
> like I said, drones are legit target for AA weapons since the beginning
AA units often getting distracted by them because their AA weapon range usually much further than their ground weapons
in scenario where a blob of both vehicles and drones were inside AA units ground weapon range proximity, the AA units will try to pick target randomly (unless ordered specifically by player) so there are chances they will target the drones. when this happen usually the player will issue an order to attack another vehicles
thus when the AA unit managed to destroy a drone parent vehicle it had chance to attack the said parent vehicle's drone that is immediately shutting down and falling to die from heightdie module, and when that happen the AA will continue to pick another target after the drone died
this moment is what makes the AA "twitches between the drone and vehicle target"
it's weird if players were fine with scout drones being damage soak but not fine if AA got distracted by drones in general
this is just how SAGE targeting works, there is just no way creating target priority list for weapons to make unit prefer attacking certain kind of target over another, only which weapon against which kind of target

Zeke:
> Fixing it could also be potentially a big change as it involves tweaking the mood check attack rate for each unit/unit type. And/or adding NOTWHILEATTACKING to AutoAcquireWhenIdle = Yes

**Comment by xezon** [comment]
This issue should already be fixed with
* #285
