### ISSUE TITLE
GLA Terrorist Infantry Gets Disabled By Lotus

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#1558]
Lotus Disabled a Demo bike Evacuating at the same moment as it is being disabled Causing the terrorist to be disabled as well

[Footage](https://youtu.be/f-ppw-fpl0k&t=9m5s)

Replay was not found

Needs Testing

**Comment by xezon** [comment]
Needs a repro.

**Comment by MTKing4** [comment]
After thorough testing, this doesn't seem to happen on a zero-lag game, so it has to be an issue caused by lag

This is the best i could get: 
(Also for some reason i can't force fire disable owning bikes when out of range, ECM doesn't move)

https://user-images.githubusercontent.com/83613147/212779810-b85e9e96-460f-421b-8e5d-3c5520ef7584.mp4

**Comment by xezon** [comment]
Likely code issue. Does not look like a big problem. Can close. Dig back up when so needed.
