### ISSUE TITLE
China Inferno Cannon shell hit does not always play sound

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1561]
China Inferno Cannon shell hit does not always play sound.

https://user-images.githubusercontent.com/4720891/213012753-3c77c1b4-8204-4b2a-962e-705e9c5d5537.mp4

**Comment by xezon** [comment]
Does not appear to be a problem with `AudioEvent ExplosionFire` and `WeaponFX_InfernoTankShellDetonation`. I tested various changes and nothing fixed it. Investigating `InfernoTankShell` projectile next.

**Comment by xezon** [comment]
Looks like the issue originates from

```
Weapon InfernoCannonGun
  ProjectileObject = InfernoTankShell
  ProjectileDetonationFX = WeaponFX_InfernoTankShellDetonation
End

Object InfernoTankShell
  Behavior = DumbProjectileBehavior ModuleTag_09
    DetonateCallsKill = Yes
  End
  Behavior = FireWeaponWhenDeadBehavior ModuleTag_07
    DeathWeapon   = SmallFireFieldCreationWeapon
    StartsActive  = Yes
  End
End
```

The effect assigned by `ProjectileDetonationFX` does not work reliably on death of the Dumb Projectile. As instead, if the effect is spawned through the `DeathWeapon` of the projectile object, then it works reliably.

**Comment by xezon** [comment]
Dumb Projectile Objects with this issue:

* InfernoTankShell
* InfernoTankShellUpgraded

Dumb Projectile Objects without this issue:

* Nuke_BattleMasterTankShell
* Nuke_OverlordTankShell
* SpectreHowitzerShell
* RangerFlashBangGrenade
* ScorpionTankShell
* MarauderTankShell
* GenericTankShell
* BattleMasterTankShell
* OverlordTankShell
* NukeCannonShell
* NeutronCannonShell
* GLAAngryMobMolotovCocktailProjectileObject

Dumb Projectile Objects without sound:

* GLAAngryMobRockProjectileObject

Untested:

* USSBenderGunShell

**Comment by xezon** [comment]
Looks like InfernoTankShell's are the only Dumb Projectiles with a `HeightDieUpdate` module.

**Comment by xezon** [comment]
Removing the `HeightDieUpdate` module from `InfernoTankShell` fixes this issue.

It also fixes this issue:
* #963

**Comment by MTKing4** [comment]
Very nice
