### ISSUE TITLE
USA Tomahawk Missile changes rotation before hit

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1574]
USA Tomahawk Missile changes rotation before hit.

![shot_20230121_095830_24](https://user-images.githubusercontent.com/4720891/213862083-69d0fa0e-1ba0-4e3b-b7ef-f4698c542cf6.jpg)

![shot_20230121_095830_25](https://user-images.githubusercontent.com/4720891/213862086-70c3a897-b990-492d-9825-b90334ee7247.jpg)

**Comment by ExiLe-ZH** [comment]
That's with most if not all projectiles? 

Tank shells for example also go face down just before impact, especially when a tank is shooting at short distances it looks really stupid how fast the shell curves down, like it's artillery.

**Comment by xezon** [comment]
SCUD Missile does not appear to do this.
