### ISSUE TITLE
Enable 60 fps.

### ISSUE THREAD

**Issue by samosaphile** [TheSuperHackers/GeneralsGamePatch#1604]
Currently online matches are limited to 30 fps internally by the sage game engine. See these repo's for example implementations:

https://github.com/storyboardcreativity/ra3-net-client

https://github.com/MetaIdea/SageMetaTool

Might increase the chances of mismatches occurring(?) I think everyone has pc capable of running this game mostly 60 fps these days, at least in 1v1 matches for sure.

**Comment by xezon** [comment]
This is a feature request, not a problem per se. Covered by

* TheAssemblyArmada/Thyme#275
