### ISSUE TITLE
Some tanks show muzzle flash upon death

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1605]
Some tanks show muzzle flash upon death. Reproducible with Nuke Battlemaster, Nuke Overlord. Not reproducible with Regular Battlemaster, Regular Overlord.

Potentially related to `FireWeaponWhenDeadBehavior` module. When Isotope Stability upgrade is acquired, then issue is no longer reproducible with Nuke Battlemaster, Nuke Overlord.

https://user-images.githubusercontent.com/4720891/214953508-94590e2f-6355-4613-9a8a-cef4571731cf.mp4

**Comment by xezon** [comment]
Possible cause for this is RUBBLE ConditionState missing a HideSubObject for a specific sub state.

**Comment by commy2** [comment]
I don't think the RUBBLE state is needed. You can just hide it on the DEFAULT state. The animation overwrites the explicit hide.

**Comment by xezon** [comment]
I have fix for it.

**Comment by xezon** [comment]
Affects all Battlemasters, Overlords, Demo Scorpion, Demo Marauder. Anything else?

**Comment by xezon** [comment]
I have troubles fixing this on Demo Scorpion. For some reason keeps showing Muzzle flash on death when doing same fix as for Overlords. There are multiple Condition States.

**Comment by commy2** [comment]
HideSubObject of the muzzle flash section.

**Comment by xezon** [comment]
I tried that with Battlemasters first, but it does not work.

**Comment by xezon** [comment]
Ok I think I got it.
