### ISSUE TITLE
Toxin Terrorist dying with toxin doing a T pose

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#1620]
Video Here: [T pose](https://youtu.be/uqiKxWtQLw8&t=8m50s)

Needs Testing

**Comment by xezon** [comment]
Requires Repro.

**Comment by MTKing4** [comment]
i couldn't get a repro of this, maybe the terrorist needs to be an enemy unit

**Comment by xezon** [comment]
Re-open if there is a repro for Patch. I have never seen this in regular game, and this could potentially be caused by faulty or modified game install of the video presenters.

**Comment by Stubbjax** [comment]
I had this issue previously. This happens when Generals is not patched.

![image](https://cdn.discordapp.com/attachments/879608758853054487/895678372343074866/unknown.png)

**Comment by xezon** [comment]
Faulty setup then.
