### ISSUE TITLE
AFG Carpet Bomb doesn't always turn sideways after dropping the bomb

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#1622]
Video: [A Straight Carpet](https://youtu.be/VUPaUWdxYI0&t=21m10s)

Needs Testing

**Comment by commy2** [comment]
See: https://github.com/commy2/zerohour/issues/82

> Call in the Carpet Bomber as Airforce General such that the Bomber flies in diagonally to the map's north-south or west-east axes.

https://github.com/commy2/zerohour/commit/83eda199f73c0d15d8b07b5d08cb9d2977548b7c

**Comment by commy2** [comment]
TurnRate(Damaged) is roughly 6 times smaller for other big planes. B2 essentially uses the TurnRate of a small plane (Raptor/ Mig etc.)

**Comment by xezon** [comment]
What is the expectation here? Bomber always needs to turn? Why?

**Comment by MTKing4** [comment]
Consistency, it should either always turns or never, as damage is being delivered at varied locations each time making it hard to predict where it'll be

But comparing it will other bombers, they all turn at the end, so naturally you would want the same for this one as well

**Comment by ExiLe-ZH** [comment]
Not only the turn influences the area of impact, but also the speed, which depends on the angle (the whole diagonal thing). Diagonally the area of impact is much more spread out, inflicting less damage on singular structures.

**Comment by xezon** [comment]
The movement speed is Thyme fix only.

**Comment by commy2** [comment]
> What is the expectation here? Bomber always needs to turn?

Imo, it should turn, just like China Carpet turns when ordered diagonally. It just should not do a 90 degree turn in half a second.

Check the TurnRate changes [here](https://github.com/TheSuperHackers/GeneralsGamePatch/issues/1622#issuecomment-1416760786).

**Comment by MTKing4** [comment]
After testing it seems that AFG carpet natural pathing is the straight line and weirdly for no apparent reason at some locations does the turning, I tested multiple locations and different corners but only 1 or 2 spots where I got either slight or drastic turn, but i couldn't understand why and what is causing the turns to happen, one thing for sure it's not the edges of the map though.

I also tested China and China Nuke Carpets and those seem to be consistent always doing the turn, the turn angle and timing of the turn might be varied it seems a bit but mostly it's fine.

https://user-images.githubusercontent.com/83613147/216787466-fcac8174-7153-4bd2-aea8-9ed78158429e.mp4

**Comment by xezon** [comment]
> Imo, it should turn, just like China Carpet turns when ordered diagonally. It just should not do a 90 degree turn in half a second.
> 
> Check the TurnRate changes [here](https://github.com/TheSuperHackers/GeneralsGamePatch/issues/1622#issuecomment-1416760786).

Was this not already addressed with #1084 ?

I think this report is about the lack of turning under certain circumstances. I still do not understand the problem of the absence of turning. The argument was consistency, but I do not understand why this matters. Whether or not plane turns depends on where it comes from and where it goes to. The only thing that matters is it hitting its target with bombs.

#1084 already reduces turning. And with Thyme we fix diagonal movement. With those 2 changes the big problems are gone, no?

**Comment by MTKing4** [comment]
> > What is the expectation here? Bomber always needs to turn?
> 
> Imo, it should turn, just like China Carpet turns when ordered diagonally. It just should not do a 90 degree turn in half a second.
> 
> Check the TurnRate changes [here](https://github.com/TheSuperHackers/GeneralsGamePatch/issues/1622#issuecomment-1416760786).

~but china carpet always turns even when ordered in a straight line, i just tested today~

**Comment by MTKing4** [comment]
I just realized that it's already a known issue that AFG Carpet only Turns in diagonal paths, but also the severity or existence of the turn relies on the angle, only a perfect angle will give that 90 Degree turn, the rest are either a slight turn, or none at all, even if it's technically diagonal, and the video above shows that

~More Importantly this doesn't happen in neither china or nuke carpets, they always turn regardless of the angle~

Acutally nevermind, the Nuke and China Carpet behave exactly the same as the AFG Carpet,  while they do turn themselves in a straight line, they only turn slightly and only after dropping the bombs, meaning the bomb locations are pretty much unchanged,

and in diagonal movement, they have the same issue of spreading bombs further apart + the turning ofcourse, i assume that is to be fixed with the diagonal bug fix, otherwise there don't seem to be a problem here

**Comment by commy2** [comment]
> Was this not already addressed with https://github.com/TheSuperHackers/GeneralsGamePatch/pull/1084 ?

Yeah, search function couldn't find it.

**Comment by ExiLe-ZH** [comment]
If everyone likes the B2 to turn same like China Bombers, then it should happen with any plane including the SDZ Cargo Plane after drop off :D

**Comment by xezon** [comment]
Should we kill the turning entirely?

**Comment by commy2** [comment]
Nah, it looks neat. I think it is something that goes on its own once/if you fix diagonal movement.

**Comment by xezon** [comment]
So we can close this report?

**Comment by MTKing4** [comment]
Maybe, I'm not sure.

I think the pros of straight line is predictability and more in the player's control and the cons being not as interesting.

And pros of turning looks cool and cons is randomness and terrible for planned attacks

**Comment by MTKing4** [comment]
You can close
