### ISSUE TITLE
GLA Scorpion Tank loses Scorpion rockets in RUBBLE state

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1655]
GLA Scorpion Tank loses Scorpion rockets in RUBBLE state.

https://user-images.githubusercontent.com/4720891/217936036-05108e4a-c604-4d50-8dbc-5c9920c5aa40.mp4

**Comment by MTKing4** [comment]
Also treads are moving when tank is sinking

**Comment by xezon** [comment]
Perhaps the Treads can be fixed by setting Locomotor to work when dead.
