### ISSUE TITLE
GLA Scorpion RUBBLE state does not work correctly with 2 Scorpion rockets

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1656]
GLA Scorpion RUBBLE state does not work correctly with 2 Scorpion rockets.

Note: Scorpion Rocket upgrade was researched AFTER 2 scraps were collected.

https://user-images.githubusercontent.com/4720891/217936472-4339e881-ba5a-4760-b588-87c32a416537.mp4

**Comment by commy2** [comment]
Also visible, but unrelated, the threads are turning on the wreck.
