### ISSUE TITLE
Laser guided air missiles do not follow the laser path

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1668]
Laser guided air missiles do not follow the laser path. They curve above.

![shot_20230211_135806_2](https://user-images.githubusercontent.com/4720891/218260184-b09d3de8-73b3-480c-95ce-d29a1bc0ed0f.jpg)

**Comment by commy2** [comment]
Why would they follow the laser?

**Comment by xezon** [comment]
Because when targeting at non-elevated height, then rockets fly on exact path of laser beam.

**Comment by xezon** [comment]
I looked at `MissileDefenderMissileLocomotor` and `MissileDefenderMissile` and I see nothing that suggests how to tweak fly path. Possibly driven entirely by code. Either way, changing flight path would also carry risk of flight duration changes and therefore affect game state.

**Comment by ExiLe-ZH** [comment]
oh is this caused by the new missile particle fx?

**Comment by Stubbjax** [comment]
No, but perhaps highlighted by it. I believe coincidence was being confused with intent.

**Comment by ExiLe-ZH** [comment]
I've never seen missiles curve like that in 1.04, guess I just never noticed?

**Comment by Stubbjax** [comment]
https://user-images.githubusercontent.com/11547761/218289563-ff2d84fb-3cf3-400c-964e-30cd92bcb380.mp4

**Comment by MTKing4** [comment]
They always curved like that
