### ISSUE TITLE
China Overlord/Helix Gattling Cannon does not give XP to host vehicle

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1686]
* Related to TheSuperHackers/GeneralsGamePatch#917
* Related to TheSuperHackers/GeneralsGamePatch#1687
* Related to TheSuperHackers/GeneralsGamePatch#1685

China Overlord/Helix Gattling Cannon does not give XP to host vehicle for kills.

**Comment by Stubbjax** [comment]
This issue is already described [here](https://github.com/TheSuperHackers/GeneralsGameCode/issues/87). The Overlord Gattling Cannon _does_ transfer xp to the host vehicle.
