### ISSUE TITLE
Crates dropped on USA Supply drop zone sometimes land next to the zone at random

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#17]
Check whether or not USA Supply drop zone drop offs should scatter as much as they currently do.

![post-199071-1635771399](https://user-images.githubusercontent.com/4720891/139690312-88e8b23b-27a3-4a75-85a8-3008d5b53542.jpeg)

**Comment by djchikito** [comment]
You could correct the error that supply bonuses fall outside the delivery areas and have to be sent for manual collection.

**Comment by ReLaX82** [comment]
If possible, yes.

**Comment by Jundiyy** [comment]
There is benefit but at the same time it would also change the way team games are played when on low income. As you can pass money on and would be a lot harder or not possible to do if fixed.
Of course the other argument is that players have to manually collect, which is extra work.
But again, as USA you get the most money with secondary economy and even more after the upgrade.

**Comment by RisingZH** [comment]
I would fix.

**Comment by ExiLe-ZH** [comment]
would fix too

**Comment by Stubbjax** [comment]
> 
> 
> There is benefit but at the same time it would also change the way team games are played when on low income. As you can pass money on and would be a lot harder or not possible to do if fixed.
> Of course the other argument is that players have to manually collect, which is extra work.
> But again, as USA you get the most money with secondary economy and even more after the upgrade.

If a player wants to give their ally money, they can still do so by selling off the SDZ as soon as the cargo plane spawns, which is cleaner as it is then based on more intentional / skillful gameplay and less a coincidence of faulty and unreliable behaviour.

**Comment by MTKing4** [comment]
Fix it

**Comment by ReLaX82** [comment]
Realistically is what we have on 1.04, but its unsecure 2nd eco.

So, fix it.

**Comment by xezon** [comment]
Should check if this still happens in Patch.

**Comment by xezon** [comment]
With change

* #1390

the chance of hit miss appears to have been removed or reduced. Boxes no longer bounce off nearby structures.

The new cargo boxes also hit the very center of the Supply Drop Zone more accurately as opposed to the legacy boxes, indicating that the reduced length of movement or reduced number of boxes is beneficial to the drop accuracy.

## Original

![shot_20230116_130915_2](https://user-images.githubusercontent.com/4720891/212677005-b8f9c2ac-c9e7-4c99-84d8-7ebf28fc35a3.jpg)

## Patched

![shot_20230116_131124_1](https://user-images.githubusercontent.com/4720891/212677501-5a50446a-7fd1-4d28-b93a-4520587c4d67.jpg)

![shot_20230116_131345_2](https://user-images.githubusercontent.com/4720891/212677518-b89244a9-14cc-4561-bf5c-534c9a31b492.jpg)

Closing, until there are new repro steps to make boxes miss the target.
