### ISSUE TITLE
GLA Scud Storm does not reload completely after firing sequence was interrupted

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1701]
GLA Scud Storm does not reload completely after firing sequence was interrupted. Stop key is used to interrupt.

https://user-images.githubusercontent.com/4720891/218556461-4d9ffeec-2818-4654-82f3-9f57b62b0602.mp4

**Comment by ExiLe-ZH** [comment]
how do you / can it even be interrupted?

**Comment by xezon** [comment]
With Stop key.

**Comment by ExiLe-ZH** [comment]
lol didn't know, why is this even a feature lol, for missclick?

**Comment by commy2** [comment]
It's a bug. The game is full of them.

**Comment by MTKing4** [comment]
> lol didn't know, why is this even a feature lol, for missclick?

You missed goldfish's video, you actually fire less rockets the next time the scud is ready 😄
