### ISSUE TITLE
Lasered Missiles Have Missing Sound Effect

### ISSUE THREAD

**Issue by MavroGada2** [TheSuperHackers/GeneralsGamePatch#1776]
There are ```GenericMissileDisintegration``` titles in fxlist,ocl and soundeffect. Some reason sound effect one not used in fx.

### Original:

https://user-images.githubusercontent.com/103841664/226336732-c282378d-5e72-41bf-98e3-b2aa4fda38e4.mp4

### New:

https://user-images.githubusercontent.com/103841664/226336808-b310a795-2ea4-4f91-a713-becbc22fe851.mp4

**Comment by xezon** [comment]
Could you share test map please?
