### ISSUE TITLE
Tank Paradrop Delivers Wrong Location to Tanks

### ISSUE THREAD

**Issue by MavroGada2** [TheSuperHackers/GeneralsGamePatch#1779]
Tank Paradrop is using same ```PreOpenDistance``` with infantry paradrop without ```ParachuteDirectly``` (guided parachutes). Because of that, they are parachuting further back. ```ParachuteDirectly = Yes``` causing sloppy situation. It's the best not using it.

### Original:

https://user-images.githubusercontent.com/103841664/226494768-472213ae-84e4-42c7-b712-670ec6f5510e.mp4

### Fixed:

https://user-images.githubusercontent.com/103841664/226494860-ad0bcfff-2d27-4909-b461-7b979345b5fc.mp4

**Comment by Battlefieldkille** [comment]
Damn, didnt even realize how tragic the og drop is
