### ISSUE TITLE
GLA Workers can act poorly when collecting supplies in a boxed setup

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#178]
GLA Workers can act poorly when collecting supplies in a boxed setup. GLA workers will walk around the entire supply stash to drop off the package on the other side. All other collecting GLA Workers will wait for this one Worker to complete his drop-off.

**Comment by RisingZH** [comment]
Don't think I would change this, it's a result of only one unit being able to collect at one time and players not leaving enough space (human error).

**Comment by Jundiyy** [comment]
Yup agree.
