### ISSUE TITLE
China Tank Paradrop has snappy physics

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1781]
China Tank Paradrop has snappy physics. Flight path of parachutes does not look smooth.

### Original Tanks

https://user-images.githubusercontent.com/103841664/226494768-472213ae-84e4-42c7-b712-670ec6f5510e.mp4

### Original Money Crates

https://user-images.githubusercontent.com/4720891/196511579-9352fbaf-3d4f-41e2-8a33-9edfaa058c1e.mp4

**Comment by MavroGada2** [comment]
They are using different parachutes and parachutes are using different locomotors but their locomotor parameters are same. Crates parachutes opens earlier but key difference is ```ParachuteDirectly```. Problem with ```ParachuteDirectly``` is it causes units to getting into each other. I tried change ```DropOffset``` of each plane but it is not working looks like.

**ParachuteDirectly = Yes**

https://user-images.githubusercontent.com/103841664/226602110-530464d8-ada1-4939-bcb5-9b329ed06213.mp4

**Comment by xezon** [comment]
Does that mean it cannot be fixed properly with original game?

**Comment by MavroGada2** [comment]
I couldn't find any solution other than one with obvious side effects.
