### ISSUE TITLE
Demo charge ticking sound is loud and makes hidden bomb presence obvious

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1793]
Demo charge ticking sound is loud and makes hidden bomb presence obvious.

Explore whether or not sound volume and radius needs reduction.

**Comment by commy2** [comment]
This is talking about Burton / Demo Jarmen / USA04 Agent, right?

**Comment by xezon** [comment]
Yes.

**Comment by xezon** [comment]
kABUSE:
> If you were a Mr. Burton highly trained super stealth secret agent rambo dude trying to take out a target, would you add a beeping sound to your remote bombs? It makes no sense that they beep and it makes them entirely useless. It would be a lot better if the remote bombs did not beep. The timed bombs can still beep, as they have other advantages (aka not disappearing when burton is killed). Maybe add just an initial beep. The remotely triggered bombs are not overpowered at all. Players exclusively use timed bombs, as they have the advantage of still going off if Burton dies, 
so giving a reason to actually use remote bombs could be interesting.

MTKing:
> It is visibility feature, Burton is overpowered enough having to deploy bombs unannounced i think the tick sound is justified to at least give the opponent a chance to respond by selling, it make sense gameplay wise. Now Imagine a tickless bomb burton will plant all over your base and destroy it all at once without you even realizing. China struggles a lot vs Burton, with little stealth detection, no announcement on placements, and now no ticking sound will give the player very little chance to detect it, as opposed to how lotus is detected when capturing for example. I think the beeping sound is fine for remote bombs. I think of it like a RF signal beeper, not a time ticker.

Exile:
> I like the idea of removing the sound from the remote charge, beeping makes sense as a timer. Timed charge is indeed mostly preferred because there is less risk. The initial sound + short reveal does not make it overpowered I think. There are only few cases now where the remote is preferred, for instance when planting the charge on a truck from a mined supply.

xezon:
> Burton is a pretty good Hero unit already. Removing the bomb sound would be a significant buff. Lotus also makes noises when attacking buildings. I am open to exploring reduction of beep sound, so it is not as obvious and requires a bit more player care to detect. So for example sound can be quieter, and less audible radius. If my memory does not fail me, original bomb ticking sound is quite loud and has generous radius, so it is almost always spotted.

**Comment by xezon** [comment]
The audible range is definitely too much. It is also quite loud, especially because the beep sits on a mostly unchallenged sound frequency.

https://user-images.githubusercontent.com/4720891/230437408-4f4c85e7-1e9d-4317-8f7e-03d8278f9f4e.mp4

**Comment by xezon** [comment]
```
AudioEvent DefaultSoundEffect
  Volume = 100
  Priority  = high
  MinVolume = 40
  Control = random
  Limit = 4
  MinRange = 175.00
  MaxRange = 800.00
  PitchShift = -0 0
  Type = ui player
End

AudioEvent BombTickTimed
  Sounds      = icoltima icoltimb icoltimc
  Control     = random
  Limit       = 3
  VolumeShift = -10
  Volume      = 65
  Priority    = low
  Type        = world shrouded everyone
End

AudioEvent BombTickRemote
  Sounds      = icolbeep
  Control     = interrupt
  Limit       = 3
  Volume      = 65
  Priority    = low
  Type        = world shrouded everyone
End
```
