### ISSUE TITLE
GLA Booby Trap upgrade tooltip text has inaccurate information

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1794]
GLA Booby Trap upgrade tooltip text has inaccurate information.

It says: "Rebels can place booby traps on buildings and neutral units"

Booby traps cannot be placed on neutral units (vehicles).

**Comment by kABUSE1** [comment]
I think to many it is unclear what the boopy trap even does.

You can booby-trap all friendly and neutral buildings. So your teammates buildings, your own buildings and civilian buildings.
You can even booby-trap base defenses. Heck, you can even booby-trap a demo trap lmao (https://www.youtube.com/watch?v=ieLKsTrgONk).

You can booby-trap civilian buildings only if they are currently unmanned or manned by yourself or your team mate.

Booby-traps explode if:
- booby-trapped civilian building is manned by enemy or destroyed
- booby-trapped friend or own building is captured or destroyed

Reflecting this all in the message might be overkill tho, lol
