### ISSUE TITLE
All USA Vees slot transport reduced from 5 to 3?

### ISSUE THREAD

**Issue by KrewGR** [TheSuperHackers/GeneralsGamePatch#1803]
Thoughts on this? Would it break anything? Would the community hate it?

This is assuming we don't nerf anything else about the rockvees power.

**Comment by MTKing4** [comment]
Far beyond project's scope, the idea is to make less visible changes

**Comment by xezon** [comment]
We cannot do this. 5 slots are as designed. One of the Humvee voice lines also says "Got room for five".
