### ISSUE TITLE
Tank speed balancing

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1809]
Unit | Speed / Acceleration | Upgraded | 
-- | -- | -- 
Overlord / Emperor | 20/15 | 30/30
(Tank) Battle Master | 25/1000 | 35/1000
(Laser) Crusader / Paladin | 30/1000 | - 
Scorpion / Marauder | 40/1000 | - 
Quad Cannon | 40/1000 | - 
Gatling Tank | 40/1000 | - 
Dragon Tank | 40/1000 | - 
Nuke Overlord | 40/30 | - 
Nuke Battle Master | 45/1000 | - 

Battle Masters and especially Overlords (Emperors) are painfully slow, a huge part of why they suck, Battle Masters often are often easily outflanked by Dragon Tanks, while they're supposed to be the counter unit. Overlords are extremely easy targets for Terror Techs.

40/1000 seems to be the standard most units and BM's/Overlord seem to be the outliers. Would a small buff like 27.5 be justified?

**Comment by xezon** [comment]
Speed increase would help China a lot. Speed of 27.5 would break the speed step size of 5 which all units adhere to if I am not mistaken. It should be 30 then.

Also, it is odd that upgraded Overlord is 30 only while Battlemaster is 35. Would it not be better if they upgraded to the same speed?

**Comment by commy2** [comment]
Vast majority of Chinese units move at 40. Would be neat if at least with Nuclear Tanks, BM reached 40 speed, although it might be op, idk.

**Comment by MTKing4** [comment]
I doubt 40 speed would make it op, it's already underused, and that upgrade is quite an investment and very lategame, i think we can get away with increased speed for both BMs and Ovies

**Comment by xezon** [comment]
Battle Master base:30 upgraded:40
Overlord base:30 upgraded:40

?

**Comment by MTKing4** [comment]
Base for both ~25~ 30 , but yeah Upgraded to 40

Nuke BM will still be faster at 45 speed
~And Nuke Ovie will still be faster to respond/rotate with faster Acceleration at 30 
compared to normal ovie at 15~

Maybe 40 is too much for ovie idk, 35 is good as well

**Comment by ExiLe-ZH** [comment]
The only thing why I still doubted the 30 speed, is the combination of changes we made to China, like Stealth might even struggle a bit vs Tank BM spam. Remember the faster building dozer for faster truck rush and less Elite BM XP.

That said, I just compared the BM with the Crusader ingame, the difference is pretty minor actually.

**Comment by ExiLe-ZH** [comment]
Upgraded, I think BM to 40 and Ovie to 35 is fine. Nuke BM and Ovie are still faster then indeed.

Considering the investment, it's pretty sad BM's are still slower than any other standard unit in the game.

**Comment by MTKing4** [comment]
Ok so it should look like:

Unit | Base | Upgraded | 
-- | -- | -- 
Battle Master | 30 | 40
Overlord / Emperor | 30 | 35

**Comment by xezon** [comment]
Wouldn't this make more sense then? It looks odd to me if Overlord just gets +5 and Battle Master +10 for the Upgrade.

| Unit | Speed | Speed Upgraded | 
| ---- | ----- | -------------- |
| Battle Master      | 30 | 40 |
| Overlord / Emperor | 25 | 35 |
| Nuke Battle Master | 45 | -  |
| Overlord / Emperor | 40 | -  |

**Comment by MTKing4** [comment]
They already give +10 and +5 to BM and Ovie Respectively in 1.04

It checks out even though it's a bit weird but the idea is that vanilla counterparts are always the same speed and the difference comes after the upgrade (which Nuke General has by default)

**Comment by MTKing4** [comment]
And then Nuke BM will still be +5 Faster than VBM
And Nuke Ovie still +5 Faster than Vanilla Ovie

**Comment by xezon** [comment]
I can see that the Original has the same Upgrade discrepancy. I would like to challenge this discrepancy.

**Comment by ExiLe-ZH** [comment]
> Wouldn't this make more sense then? It looks odd to me if Overlord just gets +5 and Battle Master +10 for the Upgrade.
> Unit 	Speed 	Speed Upgraded
> Battle Master 	30 	40
> Overlord / Emperor 	25 	35
> Nuke Battle Master 	45 	-
> Overlord / Emperor 	40 	-

Yea the Overlords top speed doesn't need to be as fast as a Crusader, I think the 15 acceleration is what hurts most, could buff that to 20 instead, or 25 if that's not enough.

**Comment by xezon** [comment]
The actual Overlord speed is 20, not 25.

**Comment by ExiLe-ZH** [comment]
I just noticed that indeed, I used value from Locomotor Tank_OverlordLocomotor assuming that was the Emperor.

**Comment by xezon** [comment]
This would be my proposal for China Overlord for starters #1813

**Comment by ExiLe-ZH** [comment]
That should make the case a little easier. I think this could be the sweetspot:

Unit | Speed / Acceleration | Upgraded
-- | -- | --
(Tank) Battle Master | 30/1000 | 40/1000
Nuke Battle Master | 45/1000 | -
Overlord / Emperor | 25/20 | 35/30
Nuke Overlord | 40/30 | -

The Overlord and Emperor will both receive a slight top speed and acceleration buff (pre-upgrade).

Another important value is the turnrate, which is 60 for the Overlord/Emperor (pre- and post upgrade) and 80 for the Nuke Overlord. Not sure if these need adjustments.

**Comment by xezon** [comment]
We had discussion about Battlemaster here 
* #819

**Comment by xezon** [comment]
Proposal for Battlemasters: #1815

**Comment by MTKing4** [comment]
> This would be my proposal for China Overlord for starters #1813

The Same should be applied to Emperor

> I do think that it's fine to do the same buff to the Emperor, it's rather identical to Overlord Minus the Vet1 and the free prop which only improve it by a margin

**Comment by xezon** [comment]
I do not think the Emperor needs to be faster because

a) It is the strongest Tank in the game
b) We gave it the Subliminal Messaging bonus, so it is even stronger now
c) Tank General is more competitive than China already

It is a driving Propaganda Tower essentially. Mixed with Autoloader Battlemasters likely deadly efficient. If it drives around to fast, opponents will struggle.

**Comment by ExiLe-ZH** [comment]
a) In a direct 1v1 vs other tanks it might be the strongest but it says nothing about it's effectiveness in actual games, it's actually rather easy to deal with for many factions, not only that, producing those can even backfire as they're so easily captured and can not in retreat when in danger.

b) Other Overlords also have subliminal messaging with selfhealing, including the Nuke Overlord, which is by far the most effective version, exactly due to it's speed and used quite in bit in actual games.

c) Tank General is more competitive due to other factors, Emperors barely contribute to the more positive winrate, if at all. Mainly the Gats, Dragons and BM's make the difference. 

Other Overlords are also driving Propaganda Towevers (subliminal changes nothing here), the only difference is the price, we can look into the pricing as counter. But yes, Tank BM's are extremely strong and used alot in games, however you didn't show the same balance concerns with this change: https://github.com/TheSuperHackers/GeneralsGamePatch/pull/1815

**Comment by xezon** [comment]
> You didn't show the same balance concerns with this change.

The Tank Battlemaster is essentially the same unit, except for having Vet1 or Vet2 on spawn. Therefore speed discrepancy would not be plausible here.

**Comment by ExiLe-ZH** [comment]
> > You didn't show the same balance concerns with this change.
> 
> 
> 
> The Tank Battlemaster is essentially the same unit, except for having Vet1 or Vet2 on spawn. Therefore speed discrepancy would not be plausible here.

With the knowledge Elite veterancy makes all the difference balance wise, it strikes me as odd that this buff is so easily considered in comparison.

My point is, Tank BM's are bigger gamechangers than Emperors, with less cons, especially after XP reduction. Nobody will even consider slow Emperors anymore after these two changes, why not buff them too?

Furthermore, while Tank is more competitive vs GLA and USA, it suffers vs other China's (in longer games). It needs something late game and Emperors are the only units that are just a little less vurnerable vs Nuke Cannons.

**Comment by xezon** [comment]
We can revert Tank Battlemaster speed back to 25 if you think it is not ok to buff. I do not feel strongly about it, as Tank likely still is good with slower Battlemasters.

As for faster Emperor, you need to come up with convincing Rationale. I have not seen it yet. Emperor is very good unit, especially now with Subliminal Messaging and grouped with Battlemasters which benefit greatly from Subliminal + Autoloader + Vet2 + Nationalism.

**Comment by ExiLe-ZH** [comment]
> We can revert Tank Battlemaster speed back to 25 if you think it is not ok to buff. I do not feel strongly about it, as Tank likely still is good with slower Battlemasters.
> 
> 
> 
> As for faster Emperor, you need to come up with convincing Rationale. I have not seen it yet. Emperor is very good unit, especially now with Subliminal Messaging and grouped with Battlemasters which benefit greatly from Subliminal + Autoloader + Vet2 + Nationalism.

BM change needs to be tested in several matchups, I think it will be ok, difference between BM and Crusader doesn't feel that drastic in 1.04. 

Emperor change is less impacting on balace and therefor easier to accept imo.

**Comment by MTKing4** [comment]
Have to Agree with Tim here, BMs have more impact on the battlefield

Furthermore, Tank is strongest at the Early stages, by the time they get Emperors or the nuke upgrade they're already facing a well established enemy where tank general losses against most of the times, whether it be Vs Nuke Cannons/Infernos of Chinas, SnD USA, or a Turtling GLA

**Comment by xezon** [comment]
Battlemaster and Overlord movements have been dealt with. This report can be closed.

**Comment by ExiLe-ZH** [comment]
Emperor was not dealt with though, still the same old clunky unit :( BM's will be favored even more now. 

I'm sure it will not hurt.

**Comment by MTKing4** [comment]
agree with Exile, Emperor should get the same treatment
