### ISSUE TITLE
Horde bonus for China Gattling Tank

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1811]
So apparently EA didn't consider Gatling Tanks to be main battle units, however we all know how the meta evolved. Still though, the current extra firepower over Quads is only a small advantage versus the versatility of Quads. The Quad mobility with GLA's Tunnel Network system, their ability to level buildings quickly and potential to vet up much faster far outweighs this pro. Even to the point that GLA can win by just spamming Quads, often still winning direct mass engagements.

By introducing Horde Bonus for Gatling Tanks, GLA has to be far more careful taking direct engagements, not only that but he also most likely has to mix in Scorpions or Marauders for positive engagements. This again will make Air unit transitions from China more effective, making the matchup dynamics more interesting.

Also versus USA it could potentially help versus pure Humvee spam and they might have to mix in Crusaders. That said, Super Weapon and Airforce might struggle vs Tank with this change, if they play standard dual supply.

**Comment by xezon** [comment]
Technically is likely possible.

**Comment by xezon** [comment]
With proposal #1055 vetted Quads and Gattlings would be on par. With Horde Bonus that would likely shift in favor of Gattlings throughout. Is this desired?

**Comment by ExiLe-ZH** [comment]
This potentially could be desirable yes. Would require GLA to mix in Tanks and play smarter.

**Comment by ReLaX82** [comment]
Needs testing vs Stealth.

**Comment by commy2** [comment]
Gatling tank is not very suited for Horde Bonus. Horde Bonus raises Rate Of Fire. A vet 3 Propaganda Gatling tank already fires every frame, which is the cap.

**Comment by xezon** [comment]
Close
