### ISSUE TITLE
Stealing cash with GLA Saboteur plays UI withdraw sound

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1823]
Stealing cash with GLA Saboteur plays UI withdraw sound. But stealing cash with China Black Lotus does not.

It appears that module(s)
```
  Behavior = SabotageSupplyCenterCrateCollide SabotageTag_05
    BuildingPickup  = Yes
    StealCashAmount = 1000
  End
```

plays back
```
AudioEvent MoneyWithdraw
  Sounds = ucreddna
  Control = random
  Limit = 3
  Volume = 30
  Priority    = low
  Type = ui player
End
```

Is likely hardcoded behaviour.

**Comment by MTKing4** [comment]
Ideally both should Play the sound

**Comment by xezon** [comment]
It depends whether or not sound is local. Withdrawal sound effects should not be audible to the enemy, because it would break the sneaky gameplay aspect of these units.

**Comment by commy2** [comment]
But the Saboteur plays a laugh effect globally when shutting down a building. It seems intentional.

**Comment by penfriendz** [comment]
Yes, I think the sound for saboteur cash steal can go.

**Comment by xezon** [comment]
I just tested it. There even is an EVA voice saying "Hackers are stealing cash". This makes the whole exercise very obvious.

**Comment by xezon** [comment]
Interestingly, this only happens in Patch, because of these fixes:

```
; Patch104p @bugfix xezon 09/05/2023 Fixes misspelled filename. (#1940)
DialogEvent EvaGLA_CashStolen
  Filename = egcashs.wav
  Volume= 90
End

; Patch104p @bugfix xezon 09/05/2023 Fixes misspelled filename. (#1940)
DialogEvent EvaChina_CashStolen
  Filename =  eccashs.wav
End

; Patch104p @bugfix xezon 09/05/2023 Fixes misspelled filename. (#1940)
DialogEvent EvaUSA_CashStolen
  Filename =  eucashs.wav
End
```

We can explicitly disable it to get rid of the sounds again.

**Comment by xezon** [comment]
On top of the withdraw sound, there also is a radar event which can be jumped to with space bar and a text "Enemy infiltration detected".

![shot_20230913_103619_1](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/160c3c33-f84d-4daf-971e-1d36029fe79c)

**Comment by MTKing4** [comment]
Removing it would be a design mistake imo, having an ability that has zero counterplay is bad, player shouldn't feel like he has no control over denying this, besides it's pretty stealthy already, the sound is very minuscule and can be easily go unheard with battles, and about the notification let me tell you that i didn't know about it for years while playing, this is how stealthy it already is, don't make it too easy to abuse by the owning player, the current setup is good.

**Comment by MTKing4** [comment]
Also losing cash without any visual or sound feedback is awful and a frustrating experience

**Comment by ImTimK** [comment]
If silent cash steal is fine for lotus then it should be fine for saboteurs aswell, it can only be used once after all. A sound notification after the fact isn't needed, you just got to be ready and aware when having a stealth as opponent.

There's also plenty of counterplay, usa has alot of stealth detection, china can mine buildings.

**Comment by MTKing4** [comment]
The sound and notification are useful the next time the enemy sends a saboteur, you're not going to spend extra cash and attention on a problem you haven't even noticed.
Also saboteur is available for GLA as well, not just stealth

**Comment by ImTimK** [comment]
That's my point, it should be a repeatable tactic versus unaware players. Imo you don't deserve clear and loud notification for failing at predicting/stopping enemy tactics. Or if you look from it from the other player's perspective, being punished for being succesful.

**Comment by MTKing4** [comment]
It's not really loud nor clear though, it can be easily missed, and it's not like knowing about it will eliminate repetition, you see people get their heroes Detected and lost all the time but they rebuild them and find other ways in, bottom line is if it's cost-effective, people will rebuild it and find ways in somehow.

Personally, i don't like the idea of losing money with no visual feedback, it's the same as not notifying you when your base is under attack or when lotus is capturing your buildings, you don't deserve a loud notification, you should should be a better player and notice it on your own, it's a regression.

**Comment by xezon** [comment]
The sound indeed is quiet. It is the radar event, text and sound combined that will likely make it obvious though. If player misses it, then he is not paying attention to game.

**Comment by commy2** [comment]
It's good that it's obvious. Players need feedback about what's going on in the game. The money counter is constantly moving due to supplies and secondary eco. Having to monitor the money counter and doing the > < math constantly is unreasonable and not enjoyable gameplay. Destructive super powers and attacks on the flanks also triggers radar events and eva messages. They were deliberately added for the Saboteur, because there would be no "under attack" radar event otherwise.

**Comment by ImTimK** [comment]
> The sound indeed is quiet. It is the radar event, text and sound combined that will likely make it obvious though. If player misses it, then he is not paying attention to game.

Could just make the sound a bit louder.

I don't get why it got to be much more obvious than Lotus cash steal, equalizing it is fine though, Lotus steal process takes longer and has more visual clues.
