### ISSUE TITLE
Overlord hulk auto-attack bug

### ISSUE THREAD

**Issue by kABUSE1** [TheSuperHackers/GeneralsGamePatch#1826]
All overlords and emperor overlords produce a weird hulk object that will be auto-attacked by enemies. Situational this can make a difference in battle.

https://user-images.githubusercontent.com/47530719/230798589-a68772b4-35fe-47d9-8ee9-6facff249449.mp4

**Comment by xezon** [comment]
This was fixed with #257

**Comment by commy2** [comment]
It's the barrel debris AI shoots at. It can take 1 hit as it has 1 single health point and no armor. Once it is destroyed, AI stops targeting it. Even though the debris is "destroyed", visually it still bounces around until the lifetimer runs out (it is not deleted when destroyed and has no visual change either).
