### ISSUE TITLE
USA and China vehicles cannot cause and collect scrap crates

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1827]
USA and China vehicles cannot cause and collect scrap crates when owned by a GLA player. Should they?

**Comment by MTKing4** [comment]
I'm not sure about this, it certainly would be nicer if they did, but it also buffs a GLA with power + the inconsistency that non GLA Units can cause and collect Scrap (Money i Assume) while not being able to when they are the main faction (or get something else if we decide about that)

**Comment by xezon** [comment]
Closing this for now. Perhaps would be ok to apply this buff if at the same time we apply nerf for TheSuperHackers/GeneralsGameCode#94. But it is also ok to just leave as is. GLA is strong enough after stealing other faction tech, thanks to the power bonus.
