### ISSUE TITLE
China Overlord Gattling turns too slow

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1849]
From survey comments:

> gattlings from overlords turn way too slow into the right direction, making them almost useless against fast aircraft.

**Comment by xezon** [comment]
### ChinaTankOverlordGattlingCannon

```
Object ChinaTankOverlordGattlingCannon

  Behavior = AIUpdateInterface ModuleTag_03
    Turret
      ControlledWeaponSlots = PRIMARY SECONDARY
      TurretTurnRate      = 60   ; turn rate, in degrees per sec
      TurretPitchRate     = 60
      AllowsPitch         = Yes
    End
    AutoAcquireEnemiesWhenIdle = Yes
  End
```

### ChinaHelixGattlingCannon

```
Object ChinaHelixGattlingCannon

  Behavior = AIUpdateInterface ModuleTag_03
    Turret
      ControlledWeaponSlots = PRIMARY
      TurretTurnRate      = 60   ; turn rate, in degrees per sec
      TurretPitchRate     = 60
      AllowsPitch         = Yes
    End
    AutoAcquireEnemiesWhenIdle = Yes
  End
```

### ChinaGattlingCannon

```
Object ChinaGattlingCannon

  Behavior = AIUpdateInterface ModuleTag_06
    Turret
      ControlledWeaponSlots = PRIMARY SECONDARY
      TurretTurnRate      = 180   ; turn rate, in degrees per sec
      TurretPitchRate     = 180
      AllowsPitch         = Yes
      FiresWhileTurning   = Yes
      NaturalTurretPitch  = 45 ; this keeps it aimed half way between land and sky
      MinIdleScanInterval   = 250    ; in milliseconds
      MaxIdleScanInterval   = 250   ; in milliseconds
      MinIdleScanAngle      = 0       ; in degrees off the natural turret angle
      MaxIdleScanAngle      = 360     ; in degrees off the natural turret angle
    End
    AutoAcquireEnemiesWhenIdle = Yes ;ATTACK_BUILDINGS; defensive weapon
    MoodAttackCheckRate        = 250
  End
```

### ChinaTankGattling

```
Object ChinaTankGattling

  Behavior = AIUpdateInterface ModuleTag_03
    Turret
      ControlledWeaponSlots = PRIMARY SECONDARY
      TurretTurnRate      = 180   ; turn rate, in degrees per sec
      TurretPitchRate     = 180
      AllowsPitch         = Yes
      FiresWhileTurning   = Yes
      NaturalTurretPitch  = 45 ; this keeps it aimed half way between land and sky
                               ; since you never know from whence cometh danger
    End
    AutoAcquireEnemiesWhenIdle = Yes NotWhileAttacking
    MoodAttackCheckRate        = 250
  End
```

**Comment by xezon** [comment]
So essentially ChinaGattlingCannon and ChinaTankGattling turn 3 times as fast as ChinaTankOverlordGattlingCannon and ChinaHelixGattlingCannon.

**Comment by ExiLe-ZH** [comment]
The Overlord version deserves to perform a little better imo, $1200 is quite expensive vs only a $700 gat tank, but ofcourse you have no stealth detection then. 

The thing is that the Helix and Overlord versions have to be treated equally and I'm not sure how much room there is to buff the Gatlix? Overall it seems more effective than the Overlord version.

**Comment by xezon** [comment]
For reference, here is also the Overlord gun turret turn rate:

```
  Behavior = TransportAIUpdate ModuleTag_03
    Turret
      TurretTurnRate = 60 ; turn rate, in degrees per sec
      ControlledWeaponSlots = PRIMARY
    End
    AutoAcquireEnemiesWhenIdle = Yes
  End
```

Perhaps it would be worthwhile to test with a Gattling Turret Turnrate of 90. That would already be a 50% improvement, half as fast as Gattling Tank and Gattling Cannon (building).

**Comment by MTKing4** [comment]
think these are more appropriately comparable vs the Static Defense Gatling Turret, since they're basically a mobile identical version of them

**Comment by xezon** [comment]
In Original, the regular Overlord has Turn Rate 60 and Gattling Cannon has Turn Rate 60. This creates awkward situation where Gattling Turret will try to keep aim on vehicle turn, but cannot keep up, so it will eventually just fire a few rounds.

This does not happen with Nuke Overlord (Turn Rate 80), nor with patched Overlords (Turn Rate 70, #1813, #1854), because the vehicle turn rate is larger than that of the turret.

Increasing Gattling Turret Turn Rate above vehicle Turn Rate should give tangible performance boost.

## Original, Vehicle Turn Rate 60, Gattling Turn Rate 60

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/565a2ea6-afde-459a-aae8-77f01fc269b4

**Comment by xezon** [comment]
## Vehicle Turn Rate 70, Gattling Turn Rate 90

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/5b638233-4853-405b-b88a-ef14260dd5a0

**Comment by xezon** [comment]
Increasing Gattling Turn Rate above Vehicle Turn Rate will definitely make it snappier. In combat situations where the tank needs to turn it will perform better accordingly.

Do we want this?

**Comment by MTKing4** [comment]
I like this, turn rate 90 looks good, but not too good since won't shoot at full rate which is also a good thing

Next should be the gatlix as well

**Comment by xezon** [comment]
Actually above videos are useless. When engaging enemy units the main turret will likely also rotate, so Gattling Cannon can catch up, because it can then turn with 60 + 60 degrees per second, which is faster than 70 and 80 chassis turn rate.

**Comment by xezon** [comment]
Is not clear to me if Gattling Turret needs to be faster. We already increased Overlord movement speeds with #1813, #1854. Adding more improvements could be too much. The Overlord is meant to more sluggish than other units.

**Comment by commy2** [comment]
Unless balance really requires it, the turn rate should be the same as the stationary Gatling gun.

**Comment by MTKing4** [comment]
Actually i just tested, the main issue is not the Gatling turret speed, the problem is that Gatling turret waits until the whole tank is facing the air unit before shooting, while it does shoot a shot or two during the tank turn, i managed to find out that there are sometimes where it doesn't shoot at all until both the tank and it's turret be all facing the enemy unit along with the Gatling turret, meaning the gatling turret has always been reaching the target first, but doesn't shoot until it's fully aligned, which is why it sucks vs air

**Comment by xezon** [comment]
> Gatling turret waits until the whole tank is facing the air unit before shooting

Can you retest in Patch? I suspect this was already fixed.

I am unable to observe issues with Plane attacks. The Turret is quick enough to keep up with plane speeds and kill them.

**Comment by commy2** [comment]
> I suspect this was already fixed.

Yes, that should be fixed by https://github.com/TheSuperHackers/GeneralsGamePatch/pull/313

**Comment by xezon** [comment]
Closing this for now. Overlords are already performing better.
