### ISSUE TITLE
ECM weapon sound effect doesn't correctly loop

### ISSUE THREAD

**Issue by kABUSE1** [TheSuperHackers/GeneralsGamePatch#1857]
Ongoing ECM attacks that you teleport the camera into will play the sound as if the ECM just started attacking. As long as you move the camera away only so far that the ecm weapon loop is still audible it will not happen.

https://user-images.githubusercontent.com/47530719/232909805-85058750-97ee-443f-8c21-cd6aaae5ce21.mp4

**Comment by xezon** [comment]
Duplicate of TheSuperHackers/GeneralsGameCode#166

**Comment by kABUSE1** [comment]
Sorry about the duplicates, lmao I am trying my hardest to find existing issues before creating a new one
