### ISSUE TITLE
Blown up vehicle wrecks freeze in mid air

### ISSUE THREAD

**Issue by Battlefieldkille** [TheSuperHackers/GeneralsGamePatch#1898]
![untitled](https://user-images.githubusercontent.com/69215350/235730348-64895f6f-2d06-4121-ac05-99b9f91ede93.png)
Unlike blown up infantry, the vehicles that get blown up by large explosions will result in a vehicle wreck freezing in mid air which then sinks and disappears, this looks very odd and ugly.
I understand that if we were to make it so that vehicle wrecks keep flying until they hit the ground and then sink would mean the game has to process that which in turn is "costly".

[FrozenWrecks.zip](https://github.com/TheSuperHackers/GeneralsGamePatch/files/11375698/FrozenWrecks.zip)
I created the map so you can see the issue faster, take the alpha aurora and destroy the nuke cannons.

**Comment by xezon** [comment]
Perhaps this is already fixed in Patch or some pending Pull. I did make a pass on wreck physics settings.

```
  ; Patch104p @tweak xezon 29/01/2023 Enable kill when resting.
  Behavior = PhysicsBehavior ModuleTag_03
    Mass = 50
    AllowBouncing = Yes
    KillWhenRestingOnGround = Yes
  End

  ; Patch104p @tweak xezon 29/01/2023 Change MinLifetime from 0, MaxLifetime from 0.
  Behavior = LifetimeUpdate ModuleTag_04
    MinLifetime = 1500   ; min lifetime in msec
    MaxLifetime = 1600   ; max lifetime in msec
  End
```

I think Lifetime needs to be sufficient long. It is currently set to 1500 to 1600 ms for most wrecks.

**Comment by Battlefieldkille** [comment]
> Perhaps this is already fixed in Patch or some pending Pull. I did make a pass on wreck physics settings.
> 
> ```
>   ; Patch104p @tweak xezon 29/01/2023 Enable kill when resting.
>   Behavior = PhysicsBehavior ModuleTag_03
>     Mass = 50
>     AllowBouncing = Yes
>     KillWhenRestingOnGround = Yes
>   End
> 
>   ; Patch104p @tweak xezon 29/01/2023 Change MinLifetime from 0, MaxLifetime from 0.
>   Behavior = LifetimeUpdate ModuleTag_04
>     MinLifetime = 1500   ; min lifetime in msec
>     MaxLifetime = 1600   ; max lifetime in msec
>   End
> ```
> 
> I think Lifetime needs to be sufficient long. It is currently set to 1500 to 1600 ms for most wrecks.

If its fixed, then we are fine.

**Comment by xezon** [comment]
I did not touch physics of Nuke Cannon hulk, but the issue definitely no longer happens in Patch, so something fixed it. Closing.

https://user-images.githubusercontent.com/4720891/236899023-19100d4b-5f6a-4947-af12-3ad5638bd76f.mp4
