### ISSUE TITLE
Tox Rebels cause excessive amounts of lag

### ISSUE THREAD

**Issue by kABUSE1** [TheSuperHackers/GeneralsGamePatch#1984]
The tox rebel weapon causes immense lag.

Unlike the laser turret lag, the lag is also present when you move the camera away from them, so it most likely is not a visual thing, but something that has to do with tox collision detection. Possibly the tox "beam" has some weird collisions or is made of an illogical amount of smaller collision objects.

In the example videos you can see the fps going from ~260 to 19.

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/47530719/f7f4d3d7-42a0-41d7-bd41-e357b2e47d45

This is especially bad if tox rebels fight other tox rebels or buildings, as they take forever to die.

**Comment by xezon** [comment]
This is the same as TheSuperHackers/GeneralsGameCode#124, no?

**Comment by kABUSE1** [comment]
Ah, yes seems like it. Should have thought of that, I only searched for tox rebels.

Should probably me merged.
