### ISSUE TITLE
Damaged vehicle showing smoke particles while inside a chinook

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#1990]
### Damaged Dozer in the left Chinook, empty damaged Chinook to the right

![Screenshot (6)](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/83613147/5766f335-0fad-4316-b16b-c98c4032cd4d)

[Video](https://youtu.be/dkkj-Q-z-tQ&t=3m13s)

Imo i think all visual Glitches should be fixed, including this, right now a damaged Chinook and a full health chinook will look very similar as both are smoking

MTKing

> it makes it look like the chinook is damaged, that can cause confusion, also looks weird, a chinook is at full health but it's smoking

xezon

> I do not think that is a problem. Visually the Chinook looks ok.

**Comment by xezon** [comment]
Do other damaged vehicles smoke in Chinook (and Helix)?

**Comment by MTKing4** [comment]
yes, all that emit smoke have that with chinook and helix

**Comment by xezon** [comment]
Ok in that case I maintain my opinion on this. Vehicles smokes inside Transporter. The smoke has to go somewhere.
