### ISSUE TITLE
Change Scud Storm missile damage?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1992]
All Scud Storms have the same firing sequence, but the damages and ranges per missile can vary.

## Stats

| Weapon                          | Primary Damage | Primary Radius | Sec. Damage | Sec. Radius |
|---------------------------------|----------------|----------------|-------------|-------------|
| ScudStormDamageWeapon           | 500            | 50             | 150         | 200         |
| ScudStormDamageWeaponUpgraded   | 500            | 50             | 200         | 200         |
| Chem_ScudStormDamageWeaponGamma | 550            | 50             | 200         | 200         |
| Demo_ScudStormDamageWeapon      | 600            | 75             | 150         | 200         |

## Observations

* Toxin to Anthrax Beta does not increase primary damage, but secondary damage, whereas Anthrax Beta to Anthrax Gamma increases primary damage, but not secondary damage.
* Demo Scud Missile has best primary damage, but does not have best secondary damage.

## Proposal 1

Weapon | Primary Damage | Primary Radius | Sec. Damage | Sec. Radius
-- | -- | -- | -- | --
ScudStormDamageWeapon | 500 | 50 | 150 | 200
ScudStormDamageWeaponUpgraded | 500 | 50 | 150 (-50) | 200
Chem_ScudStormDamageWeaponGamma | 500 (-50) | 50 | 150 (-50) | 200
Demo_ScudStormDamageWeapon | 600 | 75 | 150 | 200

## Proposal 2

Weapon | Primary Damage | Primary Radius | Sec. Damage | Sec. Radius
-- | -- | -- | -- | --
ScudStormDamageWeapon | 500 | 50 | 150 | 200
ScudStormDamageWeaponUpgraded | 500 | 50 | 200 | 200
Chem_ScudStormDamageWeaponGamma | 500 (-50) | 50 | 250 (+50) | 200
Demo_ScudStormDamageWeapon | 600 | 75 | 150 | 200

## Proposal 3

Weapon | Primary Damage | Primary Radius | Sec. Damage | Sec. Radius
-- | -- | -- | -- | --
ScudStormDamageWeapon | 500 | 50 | 150 | 200
ScudStormDamageWeaponUpgraded | 500 | 50 | 175 (-25) | 200
Chem_ScudStormDamageWeaponGamma | 500 (-50) | 50 | 200 | 200
Demo_ScudStormDamageWeapon | 600 | 75 | 150 | 200

## Proposal 4

Weapon | Primary Damage | Primary Radius | Sec. Damage | Sec. Radius
-- | -- | -- | -- | --
ScudStormDamageWeapon | 500 | 50 | 150 | 200
ScudStormDamageWeaponUpgraded | 500 | 50 | 175 (-25) | 200
Chem_ScudStormDamageWeaponGamma | 500 (-50) | 50 | 200 | 200
Demo_ScudStormDamageWeapon | 550 (-50) | 75 | 175 (+25) | 200

## Proposal 5

Weapon | Primary Damage | Primary Radius | Sec. Damage | Sec. Radius
-- | -- | -- | -- | --
ScudStormDamageWeapon | 500 | 50 | 150 | 200
ScudStormDamageWeaponUpgraded | 525 (+25) | 50 | 175 (-25) | 200
Chem_ScudStormDamageWeaponGamma | 550 | 50 | 200 | 200
Demo_ScudStormDamageWeapon | 600 | 75 | 150 | 200

**Comment by xezon** [comment]
Anything that needs to be done here?

**Comment by commy2** [comment]
Just some things to add:

- For clarity, "secondary damage" above does not refer to the poison clouds, but the Scud Missiles.
- Anthrax Gamma does not change the damage of the poison cloud.

green cloud | blue cloud | pink cloud
-|-|-
2.0 dmg/500 msec | 2.5 dmg/500 msec | 2.5 dmg/500 msec 

- Rate Of Fire AI bonuses apply to the Scud Storm, which means that easy AI Scud Missiles fire slower, hard AI Scud Missiles fire faster.

**Comment by xezon** [comment]
For puddle damages we have separate report here:
* #799

Does Toxin General need the stronger Scud Storm? On first sight I would not mind changing Scud Storm to this:

### Proposal 1

| Weapon                          | Primary Damage | Primary Radius | Sec. Damage | Sec. Radius |
|---------------------------------|----------------|----------------|-------------|-------------|
| ScudStormDamageWeapon           | 500            | 50             | 150         | 200         |
| ScudStormDamageWeaponUpgraded   | 500            | 50             | 150 (-50)   | 200         |
| Chem_ScudStormDamageWeaponGamma | 500 (-50)      | 50             | 150 (-50)   | 200         |
| Demo_ScudStormDamageWeapon      | 600            | 75             | 150         | 200         |

Reason being, Regular GLA Scud Storm is already much better than both Nuke Missile and Particle Cannon, as shown here in this Pull:

* #871

However, it would be a considerable Nerf. But perhaps that is perfectly OK, given the strength of the Scud Storm.

Perhaps should also check if Scud Launcher Missiles get more damage on Anthrax Upgrades, to see if original Scud Storm Missiles are an outlier.

**Comment by MTKing4** [comment]
I would also be ok with nerfing gamma scud storms, as they're the most devastating to a a china IC

**Comment by ExiLe-ZH** [comment]
Perhaps it makes more sense for the Gamma Scud to have increased secondary damage (250) instead of primary damage?

**Comment by xezon** [comment]
> Perhaps it makes more sense for the Gamma Scud to have increased secondary damage (250) instead of primary damage?

The upside of this approach would be that we would not touch ScudStormDamageWeaponUpgraded (Anthrax Beta Scud Storm) and keep a buff for the upgrades, so the applied damage reduction would be less drastic.

### Proposal 2

| Weapon                          | Primary Damage | Primary Radius | Sec. Damage | Sec. Radius |
|---------------------------------|----------------|----------------|-------------|-------------|
| ScudStormDamageWeapon           | 500            | 50             | 150         | 200         |
| ScudStormDamageWeaponUpgraded   | 500            | 50             | 200         | 200         |
| Chem_ScudStormDamageWeaponGamma | 500 (-50)      | 50             | 250 (+50)   | 200         |
| Demo_ScudStormDamageWeapon      | 600            | 75             | 150         | 200         |

**Comment by MTKing4** [comment]
How's that damage reduction? You're still doing 750 total damage, also secondary damage has more radius so it's effectively a buff not a nerf

Maybe just decrease primary damage without changing secondary damage 

Where is the secondary damage applied btw?

**Comment by xezon** [comment]
It is also not clear to me whether or not it is a buff/nerf. The damage redistribution means that the extra 50 damage is applied at a different area, so the missiles deal less point damage but deal more area damage. Given that the secondary radius is 150 (200-50) vs primary radius 50, one could conclude that Proposal 2 is a buff.

We could also do this, which would be a definite nerf, but not as drastic as the first table:

### Proposal 3

| Weapon                          | Primary Damage | Primary Radius | Sec. Damage | Sec. Radius |
|---------------------------------|----------------|----------------|-------------|-------------|
| ScudStormDamageWeapon           | 500            | 50             | 150         | 200         |
| ScudStormDamageWeaponUpgraded   | 500            | 50             | 175 (-25)   | 200         |
| Chem_ScudStormDamageWeaponGamma | 500 (-50)      | 50             | 200         | 200         |
| Demo_ScudStormDamageWeapon      | 600            | 75             | 150         | 200         |

**Comment by MTKing4** [comment]
Yeah that's what i had in mind

**Comment by ExiLe-ZH** [comment]
My preference is not to touch Beta Scud, but if proposal 2 effectively is a buff (?), then proposal 3 could still be considered.

**Comment by xezon** [comment]
We can do lab test and evaluate numbers.

**Comment by xezon** [comment]
The original Anthrax Gamma Scud Storm is strong enough to kill Superweapon. The Anthrax puddle kills the structure.

![shot_20230609_151330_6](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/f441de21-76a0-4118-98f2-41e7f581383a)

**Comment by xezon** [comment]
To gauge secondary damage buff, we test against a line of Overlords and read their damages after Scud Storm hit and Anthrax Puddles.

![shot_20230609_153553_29](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/c93f1bf1-0035-45b4-8472-d62b9c87d777)

![shot_20230609_153609_30](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/9e2a9684-ecc7-425b-becb-f3611351eb86)

## Original regular Scud Storm vs Overlord Line

7 Overlords survive
damages left: 2%, 29%, 45%, 85%
damages right: 87%, 16%, 16%

## Original  Anthrax Beta Scud Storm vs Overlord Line

5 Overlords survive
damages left: 2%, 39%
damages right: 75%, 21%, 21%

## Original Anthrax Gamma Scud Storm vs Overlord Line

5 Overlords survive
damages left: 2%, 39%
damages right: 87%, 21%, 21%

**Comment by xezon** [comment]
## Proposal 2 Anthrax Gamma Scud Storm vs Overlord Line

5 Overlords survive
damages left: 2%, 48%
damages right: 93%, 25%, 25%

**Comment by ExiLe-ZH** [comment]
So secondary damage has more impact than primary damage on overall performance?

Then proposal 2 is a no go.

**Comment by xezon** [comment]
Scud Storms vs 204 Overlords Grid

![shot_20230609_161043_2](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/44761880-c0d2-483a-ab99-e067d8dc9769)

![shot_20230609_161134_3](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/ec9647ec-e83e-4f2c-8600-7043aabcd7f8)

## Regular Scud Storm vs 204 Overlords

64 Overlords killed
08 Overlords badly damaged

## Anthrax Beta Scud Storm vs 204 Overlords

65 Overlords killed
17 Overlords badly damaged

## Proposal 2 Anthrax Gamma Scud Storm vs 204 Overlords

70 Overlords killed
18 Overlords badly damaged

**Comment by ExiLe-ZH** [comment]
And original gamma scud vs 204 lordies?

**Comment by xezon** [comment]
I think next test is most representative.

Scud Storms vs 9 Scud Storms.

![shot_20230609_170227_25](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/a3c831d5-2d1d-4f6c-99fa-3f4ac0529544)

![shot_20230609_170235_26](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/2b525bad-cb1e-4163-abe4-2b179fc5f6c9)

## Regular Scud Storm vs 9 Scud Storm

| Target                | Structure Damage | Hole Damage |
|-----------------------|------------------|-------------|
| Scud Storm 1          | 42%              |             |
| Scud Storm 2          | 56%              |             |
| Scud Storm 3          | 49%              |             |
| Scud Storm 4          | 70%              |             |
| Scud Storm 5 (Center) | 92%              |             |
| Scud Storm 6          | 63%              |             |
| Scud Storm 7          | 42%              |             |
| Scud Storm 8          | 50%              |             |
| Scud Storm 9          | 36%              |             |
| Combined              | 500%             |             |



## Anthrax Beta Scud Storm vs 9 Scud Storm

| Target                | Structure Damage | Hole Damage |
|-----------------------|------------------|-------------|
| Scud Storm 1          | 49%              |             |
| Scud Storm 2          | 62%              |             |
| Scud Storm 3          | 56%              |             |
| Scud Storm 4          | 74%              |             |
| Scud Storm 5 (Center) | 92%              |             |
| Scud Storm 6          | 68%              |             |
| Scud Storm 7          | 49%              |             |
| Scud Storm 8          | 56%              |             |
| Scud Storm 9          | 44%              |             |
| Combined              | 550%             |             |


## Anthrax Gamma Scud Storm vs 9 Scud Storm

| Target                | Structure Damage | Hole Damage |
|-----------------------|------------------|-------------|
| Scud Storm 1          | 51%              |             |
| Scud Storm 2          | 66%              |             |
| Scud Storm 3          | 58%              |             |
| Scud Storm 4          | 80%              |             |
| Scud Storm 5 (Center) | 100%             | 0%          |
| Scud Storm 6          | 73%              |             |
| Scud Storm 7          | 52%              |             |
| Scud Storm 8          | 59%              |             |
| Scud Storm 9          | 44%              |             |
| Combined              | 583%             |             |


## Demo Scud Storm vs 9 Scud Storm

| Target                | Structure Damage | Hole Damage |
|-----------------------|------------------|-------------|
| Scud Storm 1          | 63%              |             |
| Scud Storm 2          | 90%              |             |
| Scud Storm 3          | 63%              |             |
| Scud Storm 4          | 90%              |             |
| Scud Storm 5 (Center) | 100%             | 0%          |
| Scud Storm 6          | 81%              |             |
| Scud Storm 7          | 46%              |             |
| Scud Storm 8          | 81%              |             |
| Scud Storm 9          | 63%              |             |
| Combined              | 677%             |             |


## Proposal 2 Anthrax Gamma Scud Storm vs 9 Scud Storm

| Target                | Structure Damage | Hole Damage |
|-----------------------|------------------|-------------|
| Scud Storm 1          | 56%              |             |
| Scud Storm 2          | 68%              |             |
| Scud Storm 3          | 62%              |             |
| Scud Storm 4          | 78%              |             |
| Scud Storm 5 (Center) | 93%              |             |
| Scud Storm 6          | 73%              |             |
| Scud Storm 7          | 57%              |             |
| Scud Storm 8          | 63%              |             |
| Scud Storm 9          | 52%              |             |
| Combined              | 602%             |             |

**Comment by xezon** [comment]
## Superweapon Area Damage VS 64 GLA Black Markets

| Weapon                                  | Num Destroyed | Num Damaged | Num Undamaged |
|-----------------------------------------|---------------|-------------|---------------|
| Original GLA SCUD Storm                 | 17            | 40          | 7             |
| Original Anthrax Beta GLA SCUD Storm    | 24            | 33          | 7             |
| Original Anthrax Gamma GLA SCUD Storm   | 23            | 34          | 7             |
| Original Demo GLA SCUD Storm            | 20            | 37          | 7             |
| Proposal 3 Anthrax Beta GLA SCUD Storm  | 21            | 36          | 7             |
| Proposal 2 Anthrax Gamma GLA SCUD Storm | 27            | 30          | 7             |

**Comment by xezon** [comment]
## Superweapon Area Damage VS 144 USA Supply Drop Zones

| Object                                  | Num Destroyed | Num Damaged | Num Undamaged |
|-----------------------------------------|---------------|-------------|---------------|
| Original GLA SCUD Storm                 | 32            | 30          | 82            |
| Original Anthrax Beta GLA SCUD Storm    | 48            | 30          | 66            |
| Original Anthrax Gamma GLA SCUD Storm   | 48            | 30          | 66            |
| Original Demo GLA SCUD Storm            | 33            | 26          | 85            |
| Proposal 3 Anthrax Beta GLA SCUD Storm  | 43            | 35          | 66            |
| Proposal 2 Anthrax Gamma GLA SCUD Storm | 55            | 22          | 67            |

**Comment by xezon** [comment]
According to these results, the Anthrax Gamma Scud Storm is the best Scud Storm in the game. It can take out a Superweapon in one shot and has more area damage than the Demo Scud Storm. I do not think Proposal 2 is a good alternative, as the area damage is increased noticeably, making it even better against scattered targets. I would not mind Proposal 3, because the performance jump between regular Scud Storm and Anthrax Beta Scud Storm is quite significant.

**Comment by ExiLe-ZH** [comment]
Professional lab tests+++++ 

Good to have all these different targets tested, because it gives better insight on performance differences.

It's quite clear now how increased secondary damage literally makes the damage radius better (making it better vs medium HP buildings in it's outer radius). Whereas increased primary damage makes up for more destructive power in the center (better vs singluar high HP structures).

I'm not sure if I like the original setup, it's non-transparant even for us veteran players. Proposal 2 is also a bit too overpowered raduis wise. 

I think simplification and better balance is possible here, what about this?

### Proposal 4

Weapon | Primary Damage | Primary Radius | Sec. Damage | Sec. Radius
-- | -- | -- | -- | --
ScudStormDamageWeapon | 500 | 50 | 150 | 200
ScudStormDamageWeaponUpgraded | 500 | 50 | 175 | 200
Chem_ScudStormDamageWeaponGamma | 500 | 50 | 200 | 200
Demo_ScudStormDamageWeapon | 550 | 75 | 175 | 200

It's proposal 3 but with altered Demo Scud, the original seems overpowered vs singular high HP structures (kills another Scud + Hole, just the Scud would be good enough), but at the same time it's radius sucks and it's non-upgradable. This proposal hopefully strikes a more happy medium?

Perhaps can be simplified further by making Demo Scud's primary radius 50 (same as the rest) and it's secondary damage 200.

**Comment by xezon** [comment]
I do not know yet what to do with Demo Scud Storm. It is not a threat to the linked Internet Center buff.

It looks like we agree on the Anthrax Beta and Anthrax Gamma Scud Storm changes, Proposal 3. I have added 2 data points for them above.

I can prepare Pull for that.

**Comment by ExiLe-ZH** [comment]
Here another take:

## Proposal 5

Weapon | Primary Damage | Primary Radius | Sec. Damage | Sec. Radius
-- | -- | -- | -- | --
ScudStormDamageWeapon | 500 | 50 | 150 | 200
ScudStormDamageWeaponUpgraded | 525 (+25) | 50 | 175 (-25) | 200
Chem_ScudStormDamageWeaponGamma | 550 | 50 | 200 | 200

**Comment by xezon** [comment]
> For Beta and Gamma, another take on proposal 3 is this

This would not solve the OP'ness of the Gamma Storm.

**Comment by ExiLe-ZH** [comment]
True, forgot for a moment the antrax still causes after damage.

**Comment by xezon** [comment]
It is not clear to me if we need to change Demo Scud at all. It is very strong against point targets, but it has no Anthrax and no other perks.

Stealth Scud Storm has Camo Netting + Anthrax Beta.

Toxin Scud Storm has Anthrax Gamma.

Each of these have some unique perks which make them interesting.

**Comment by ExiLe-ZH** [comment]
> Each of these have some unique perks which make them interesting.

This is true.

So I guess proposal 3 is still best if we want to preserve this.

**Comment by ExiLe-ZH** [comment]
Added all proposals to main post.

**Comment by MTKing4** [comment]
i think just proposal 3 should do, but has it been tested vs Internet Center does the cloud Disappear before the building is destroyed? does it still kill the hackers?

**Comment by xezon** [comment]
I think we are good. Close?

**Comment by ExiLe-ZH** [comment]
Okiii
