### ISSUE TITLE
GLA Angry Mob and Aircraft cannot be GPS scrambled

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1998]
GLA Angry Mob and Aircraft cannot be GPS scrambled.

**Comment by ImTimK** [comment]
Think designed like so on purpose, imagine these units would be quite OP.

**Comment by xezon** [comment]
Planes maybe. As for Angry Mob, it is odd. Overlords and Humvees are arguably much better units, and they can be GPS scrambled too. I suspect Angry Mob was rather a technical limitation than a design decision.

**Comment by ImTimK** [comment]
I feel mobs especially would be strong, they can take down structures so fast when sneaked into a base.

**Comment by MTKing4** [comment]
They're literally shouting all the time, how's that supposed to be stealthed

As designed, no need to change

**Comment by commy2** [comment]
placid mob
