### ISSUE TITLE
Hero units give little kill XP

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#2025]
Hero units give little kill XP

```
ChinaInfantryBlackLotus
  ExperienceValue = 50 50 100 150 ;Experience point value at each level

AmericaInfantryColonelBurton
  ExperienceValue = 50 100 100 150  ; Experience point value at each level

GLAInfantryJarmenKell
  ExperienceValue = 50 50 100 150  ;Experience point value at each level
```

## Proposal 1

Raise all Heros to 75 100 150 300.

## Proposal 2

Raise all Heros to 75 100 150 200.

## Proposal 3

Make Burton 50 50 100 150 only.

## Proposal 4

Raise all Heros to 75 75 125 175.

**Comment by xezon** [comment]
So, which numbers?

**Comment by MTKing4** [comment]
I'm not sure why this needs changing

**Comment by xezon** [comment]
It was raised in #718 by Exile:

> I would like to further discuss this change because there might be a few solid reasons why the original values are higher than other hero's.
> Maybe all hero's are simply too low, because Burton and Jarmen become tough to stop aswell when vetted up (they rely more on this than Lotus).

We can close if there is nothing else to do.

Though what I find odd is that Burton gives 50% more reward from Vet 1 than Jarmen Kell (and Lotus).

**Comment by commy2** [comment]
Make Burton 50 50 100 150. That's the regular progression for infantry.

**Comment by ExiLe-ZH** [comment]
I think proposal 2 is fair.

**Comment by xezon** [comment]
Proposal 2 also makes sense to me on first sight because the current XP does not do them justice in relation to the other units. Heros cost around 1500, have long build times and can exist just one at a time.

We can probably calculate a fair kill XP reward for them by averaging the kill XP reward of other units based on their build cost and build times.

**Comment by xezon** [comment]
Ok so what do? Proposal 1, 2, 3, 4 or nothing?

**Comment by MTKing4** [comment]
Proposal 3 for me

**Comment by ReLaX82** [comment]
2 seems fine.
