### ISSUE TITLE
GLA Toxin Tractor spray puddle stays very long very quickly

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#2048]
```
  Behavior = FireOCLAfterWeaponCooldownUpdate ModuleTag_13
    WeaponSlot            = SECONDARY
    ConflictsWith         = Chem_Upgrade_GLAAnthraxGamma Upgrade_Veterancy_HEROIC
    OCL                   = OCL_PoisonFieldUpgradedMedium
    MinShotsToCreateOCL   = 4
    OCLLifetimePerSecond  = 10000
    OCLLifetimeMaxCap     = 180000
  End
```

It will take 800 ms of spraying to trigger the lasting puddle.

And for every second sprayed the puddle will last an extra 10000 ms (10 seconds). So it takes just 18 seconds of spraying to have that puddle stay 3 minutes. 👀 

Anything we want to do about this?

**Comment by ExiLe-ZH** [comment]
It's the exact purpose of the weapon right?

**Comment by xezon** [comment]
The Tractor sprayer itself does damage already. The puddle afterward the spraying is more like a bonus. The Sprayer puddle progression just looks like a lot to me, because it grows so fast. We can leave as is, because Sprinkler is not really considered OP originally, however, we did slightly buff the toxin puddle with #2023 and #2012.

**Comment by ExiLe-ZH** [comment]
It isn't very common for the sprayer to inflict direct damage, because it really has to get close to the enemy. In most matches the sprayer is only used in gla mirrors when sneaked into supply lines, to kill the workers and deny mining for a while.

**Comment by xezon** [comment]
Oh and with #2023 we fixed the bug where the dead Toxin Tractor would remove its own puddle, which inevitably makes the puddle much more potent now.

I think it would be no mistake to investigate this design.

**Comment by MTKing4** [comment]
I think it is ok, the main purpose of the contamination ability is for the long lasting puddle, not to kill units with the sprinkler itself
