### ISSUE TITLE
GLA Hijacker respawns when USA vehicle is destroyed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#206]
GLA Hijacker respawns when USA vehicle is destroyed. Is this as designed? Should we do anything about it? Likely not a problem with spy drones and filled humvees all around.

**Comment by commy2** [comment]
This is intentional. Usually USA vehicles drop Pilots, but for vehicles with the HIJACKED flag set, instead a Hijacker with the same veterancy is created.

**Comment by commy2** [comment]
This is also why no Hijacker is dropped from destroyed US Dozers: Dozers are not set up to drop Pilots since they are not meant to vet up.
