### ISSUE TITLE
USA Paladin's PointDefenseLaserUpdate does not target new infantry after a kill reliably

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#2070]
The USA Paladin's PointDefenseLaserUpdate does not target new infantry units after a kill reliably. It takes several seconds before shooting again for no apparent reason. When not killing a target, then it has no problem switching targets.

```
  Behavior = PointDefenseLaserUpdate ModuleTag_07
    WeaponTemplate        = PaladinPointDefenseLaser
    PrimaryTargetTypes    = BALLISTIC_MISSILE SMALL_MISSILE
    SecondaryTargetTypes  = INFANTRY
    ScanRate              = 500
    ScanRange             = 120.0
    PredictTargetVelocityFactor = 3.0
  End
```

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/3d51ba70-6c95-4ee1-9367-fec5ad5058b4

**Comment by commy2** [comment]
Looks like it is aiming at the flaming body.

**Comment by commy2** [comment]
Could try giving FlamingInfantry this new HumanArmorNoLaser armor:

```ini
Armor HumanArmorNoLaser
  Armor = CRUSH             200%    ;humans are easily crushed ["I'm crushing your head"]
  Armor = ARMOR_PIERCING    10%     ;humans don't get hit by tank rounds.
  Armor = INFANTRY_MISSILE  10%
  Armor = FLAME             150%    ;humans don't like fire
  Armor = PARTICLE_BEAM     150%    ;humans don't fare well against orbital beams...
  Armor = SNIPER            200%
  Armor = LASER             0%     ; @patchnote blah blah
  Armor = HAZARD_CLEANUP    0%      ;Not harmed by cleaning weapons
  Armor = KILL_PILOT        0%      ;Jarmen Kell uses against vehicles only.
  Armor = SURRENDER         100%    ;Capture type weapons are effective only against infantry.
  Armor = SUBDUAL_MISSILE   0%
  Armor = SUBDUAL_VEHICLE   0%
  Armor = SUBDUAL_BUILDING  0%
End
```

**Comment by commy2** [comment]
Seems like `PointDefenseLaserUpdate` ignores the UNATTACKABLE flag or at least glitches out on that.

Ideally, that would be fixed in engine.  Also would be neat if `PointDefenseLaserUpdate` had a `ForbiddenTargetTypes`, in which case UNATTACKABLE could be added.

**Comment by commy2** [comment]
~~This is likely not (as much of) an issue in 1.04, because the flaming body would be just shot down by 1 strike, and then the next target would be chosen (I think). Sorry for spam.~~ Rewatching the evidence, it is as much of an issue in 1.04.

...

Rewatching the video, the PDL actually shoots down the FlamingInfantry and kills it (thus it no longer shoots at it, note that the object has no module to delete the object upon kill, it just remains a 0 hp zombie). This is more evidence that UNATTACKABLE is ignored. Lets hope the PDL considers 0% Armor as a forbidden target.

**Comment by xezon** [comment]
I was not as concerned about the FlamingInfantry attack, but I can try your suggestion.

**Comment by commy2** [comment]
I am pretty sure that is the issue. The PDL logic does not expect the target to linger after death, so when the flaming body is killed (by 1 shot), the PDL fails to switch targets. This is not an issue for normal weapons. That it ignores UNATTACKABLE is a secondary bug.

**Comment by xezon** [comment]
I tested with `InvulnerableAllArmor` and that did not fix it.

Next I tested `HighlanderBody` and that did not fix it.

Next I tested removing `INFANTRY` KindOf and that fixed it.

**Comment by commy2** [comment]
I do not know what side effects removing that KindOf has. Maybe none.
