### ISSUE TITLE
Add more test maps

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#210]
Add more test maps.

Examples:
- Map that grants a lot of cash, promotions
- Map that gives access to other faction command centers
- Map that continually spawns practice target
- Map that has various terrain slope variations
- Map that spawns various particles
- ...

Test map does not necessarily need to be all in one. There can be different maps for different test cases.

Test maps can be added here:
https://github.com/xezon/GeneralsGamePatch/tree/main/Maps

**Comment by MTKing4** [comment]
Promotion test maps

https://www.gamereplays.org/community/index.php?act=Attach&type=post&id=866336

+ Made for testing promotions for all 12 armies
+ Cash
+ Targets

**Comment by xezon** [comment]
Closing this, as we have test maps for various things already and add new ones when necessary.
