### ISSUE TITLE
Key mappings are hard to read in texts

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#2115]
Key mappings are hard to read in texts. Uppercase characters at begin of words are ok, but lowercase characters can be difficult to see.

## Ok

![shot_20230715_154935_2](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/2345bf27-5ef4-46f4-8ea6-5c38fe5347f0)

## Not good

![shot_20230715_154800_1](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/e5c857c2-5893-4006-8c69-6b8d905561ce)

**Comment by xezon** [comment]
At this point I am contemplating to streamlining this to how it is done for Korean and Chinese, with trailing key mapping in parentheses, such as

"Chemical Suits (&I)"

This writing has 3 advantages:

1. Key mapping is always uppercase and therefore larger and better to see
2. Key mapping is always at the end of the name, making it easier to look for
3. Key mapping never needs to be bound to the characters of the words

**Comment by commy2** [comment]
Looks like the bold text messes with the kerning.

**Comment by ExiLe-ZH** [comment]
I also did all my hotkeys like that

Humvee [&V]

**Comment by MTKing4** [comment]
Agreed, it would be better if the Key is written outside of the Name

**Comment by xezon** [comment]
Parentheses before letter looks a bit tight.

![shot_20230722_182004_1](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/bad2bf09-c7e6-4150-b2a2-4d43af58975f)

**Comment by xezon** [comment]
Perhaps just a small dash will do. Makes the key look lean.

![shot_20230722_182433_1](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/e98f0656-a86a-4573-bfa9-de32db54be6b)

**Comment by xezon** [comment]
Or a double dash. Puts it a bit further away from the text and avoids confusion with those writings that have a dash between words such as "Patriot-Batterie".

![shot_20230722_182759_1](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/57684160-6dbe-41a5-8f49-aa4eb9dc1edf)

**Comment by xezon** [comment]
I think the single dash looks fine. Opinions?

**Comment by MTKing4** [comment]
You can't space out the brackets?
What about Square Brackets?

**Comment by ExiLe-ZH** [comment]
I use square brackets, looks the best imo and doesn't have the spacing problem I'm pretty sure.

Dash looks ok too, it's all preference I guess.

**Comment by xezon** [comment]
Squared brackets looks equally tight. Spaced out parentheses look weird because the distance is large. Perhaps needs a half space character.

**Comment by xezon** [comment]
Thin space also looks odd. The problem is the spacing is never really uniform, and also varies on different resolutions. The dash so far looks most gracious with all letters and resolutions.

**Comment by xezon** [comment]
We can also add a bigger square between title and key. The motivation here was to clarify that it is a button mapping, though it does not clarify it much more than a dash either.

1024x768

![shot_20230723_074257_2](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/9978a068-4d09-42d4-bb10-e5b333a15b97)

1920x1080

![shot_20230723_074217_1](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/e9ea9040-3e57-488e-816a-29d2376d5a75)

**Comment by xezon** [comment]
I think the square is a bit risky. Probably better to stick to ascii character.

**Comment by xezon** [comment]
Tilde letter perhaps. It has a bit more visual footprint than the dash (minus) symbol and definitely absent from the title text.

1024 x 768

![shot_20230723_084746_1](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/733a917f-b1c3-40b2-aab6-574174d0b62b)

1920 x 1080

![shot_20230723_084816_2](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/83ad531c-8818-4a72-b94f-39b0364b2e5f)

**Comment by xezon** [comment]
I think I will go with the tilde for now.

1. It is an ascii character
2. It takes a bit more space and is more visible than the dash
3. It is a unique character not used in any title texts
4. It is perfectly centered height-wise on various resolutions, contrary to the dash, parentheses and brackets 
5. It does not make the key letter look cramped, contrary to the parentheses and brackets

**Comment by xezon** [comment]
Upon further review, the tilde has too much of a visual impact.

I have a better idea. We can use colon (:). This makes it consistent with the tool tip texts, Cost: 2000, Power Requires: 1, etc. So visually it fits in the existing design.

1024 x 768

![shot_20230723_103258_2](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/354c4d5f-facb-4392-b354-36017ffb5bfb)

1920 x 1080

![shot_20230723_103212_1](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/1a4f8cfd-347a-43fd-9b01-07509bc25a60)

**Comment by ExiLe-ZH** [comment]
I like dash better than tilde, tilde looks too busy. 

What would look the most clean is if the info box was diplayed like so:

```
Nuclear Reactor

Hotkey: R
Cost: 1000

Discription blaba.

Requirements blabla.
```

However most likely requires an entire overhaul.

One advantage the original setup has is how it may help with memorization, making it extra clear how the hotkey came to be and links with the objects name. Perhaps another way to improve the original is to add an underscore, besides the yellow color?

**Comment by ExiLe-ZH** [comment]
Oh colon looks good too.

**Comment by MTKing4** [comment]
Colon looks a bit weird in a headline text
Maybe clearfying it better like so would be better:
Hotkey: R
That would make the most sense

**Comment by xezon** [comment]
Hotkey: R on extra line is not possible.

**Comment by MTKing4** [comment]
Put it on the headline? A bit spaced out from the name though if possible, we don't want it merging with the name

**Comment by xezon** [comment]
I don't like that. It becomes to long. Original text format also does not specify that the yellow character is a button mapping. So in that regard nothing has changed.

The only thing I can offer for Core bundle pack is to generate in-text key mapping. But for optional pack I definitely would like to keep trailing button mapping because it has more advantages.

**Comment by MTKing4** [comment]
Well i definitely think trailing button is better for core and optional packs, on second thought i can live with the colons choice it's fine
