### ISSUE TITLE
Rockets Emerge From Below Bunker, Possibly Colliding With Terrain And Destroying Bunker

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#2126]
### 1.04

If a Bunker is filled with rocketeers, some rockets will spawn from the center of the Bunker and if the terrain is rough, they will hurt the Bunker. This is jank.

- Bunker (xChina and Inf) only have 4 FIREPOINT's. The rest default to 0,0,0.

### Remedy

- add FIREPOINT05 ... FIREPOINT08 (FIREPOINT05 ... FIREPOINT13 for Inf) to 0,0,z=7,697. This provides enough slots from the center of the building such that the rocketeers don't have to fire from the wrong side of the Bunker.

**Comment by commy2** [comment]
Gallery:

![shot_20230721_122307_6](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/6576312/1a4267b3-69de-41e6-a71d-bcf1f5035324)
Minigunner 1 and 2 fire from proper positions. Minigunner 3 to 10 fire from below the Bunker.

---

![shot_20230721_122341_7](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/6576312/a81a37b4-2c58-44e8-b13b-0982bb8942d6)
It is safe to put 2 Tank Hunters inside a Bunker, even on rough terrain, because two fireports will (pretty much) always be closer to the enemy than the default position below the Bunker.

---

![shot_20230721_122402_10](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/6576312/4c3bc3b2-1def-45d5-9d66-3199d4a081a9)
The third Tank Hunter will begin firing from below the Bunker and damage it.

**Comment by xezon** [comment]
This is tragic.

**Comment by commy2** [comment]
It doesn't have to be this way.

![shot_20230721_130850_1](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/6576312/671b4a0e-6597-4af1-821e-87e9075f50cd)

With additional firepoints at (0,0,z>0), the shots now don't spawn from below the Bunker and avoid the terrain - no more self kills.

**Comment by xezon** [comment]
Other than adding more fire ports to models, this needs fixing from code side. Spawning rockets at 0,0,0 should really only be the last resort. It would be better if fire ports are used multiple times to avoid spawning at 0,0,0.

**Comment by commy2** [comment]
Fireports should be used even if they are further away from target than 0,0,0. That way, no double usage is required either as long as the model has more firepoints than the object has slots.

That is how it works for TransportContain already.

---

Fallback probably shouldn't be 0,0,0, but 0,0,z, where z is at least roughly the height of the RPG-Soldier/TD/MD muzzle. That avoids the issue mostly and looks better already.

---

Weapons without the SELF flag in RadiusDamageAffects generally should not damage the object the weapon user was contained in. They don't damage the user, so why should they damage the container?

**Comment by commy2** [comment]
Fixed by https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2133
