### ISSUE TITLE
Add A Crush Button

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#2135]
What do you guys think of a crush button? Instead of having to click behind the unit like a maniac you just hit a button then click on the unit, all the other C&C games have that built in, Examples RA2/YR, RA3, C&C3

It reminds me of that frustrating situation when trucks and dozers keep moving around the workers and never actually crushing them.

Xezon
> That could make crushing perhaps a bit too easy
> It's nice that player can try to evade a crush

MTKing

> They can probably still evade it, because the issue is with those units' locomoters, it just means that you don't have to get stuck there microing forever to crush the unit and affect your build order.

**Comment by ExiLe-ZH** [comment]
Too easy indeed, micro like this is what makes the game fun and interactive, not just watch stuff happen. 

The only time where it's actually annoying is with minigunners because it requires too much precision with their tiny hitboxes (smaller than their visual model), though this is already fixed I believe?

**Comment by MTKing4** [comment]
I think the too easy argument is wrong, it didn't make RA games any easier, it's just a frustrating mechanic, and adding a button to it a quality of life improvement that makes the gameplay richer for it, where a player can focus on more important matters rather than having to babysit the dozer/truck to do the job, it's like if you needed to keep clicking on the enemy unit to attack it or it will not shoot, I wouldn't consider that positive micro, more like counteractive micro

**Comment by xezon** [comment]
You can put way points to move zig zag over target infantry.

**Comment by MTKing4** [comment]
You can't predict where the player is going to move next, waypoints won't work

**Comment by xezon** [comment]
Jundiyy

> I don't think we should add a crush button. Always getting a crush is too easy. And gives the defending player no option to get away, unit will automatically follow the other unit in all directions. Right now, defending player can get away.

**Comment by ExiLe-ZH** [comment]
> I think the too easy argument is wrong, it didn't make RA games any easier, it's just a frustrating mechanic, and adding a button to it a quality of life improvement that makes the gameplay richer for it, where a player can focus on more important matters rather than having to babysit the dozer/truck to do the job, it's like if you needed to keep clicking on the enemy unit to attack it or it will not shoot, I wouldn't consider that positive micro, more like counteractive micro

ZH is better than any (cnc) RA title, micro management is one of the biggest contributing factors.

I don't get how it's frustrating either lol, if you got normal hand-eye coordination (and some ability to predict movement) it isn't hard to crush a slower unit, but there's atleast some chance for the defending player to save his.

But if you want to this far, why not add guard-crush-mode aswell? For the ultimate lazy boomer crushfest experience.

**Comment by MTKing4** [comment]
> ZH is better than any (cnc) RA title, micro management is one of the biggest contributing factors.

that is just your opinion, and not like only ZH has micro, you should try RA3, a different kind of beast, and if anything it's more micro-intensive than ZH, but there it's actual micro, not this babysitting.

> I don't get how it's frustrating either lol, if you got normal hand-eye coordination (and some ability to predict movement) it isn't hard to crush a slower unit, but there's atleast some chance for the defending player to save his.

i never said it wasn't feasible, it's just that having that feature improves the game's quality of life

> But if you want to this far, why not add guard-crush-mode aswell? For the ultimate lazy boomer crushfest experience.

now you're just blowing it out of proportion, it's a reasonable request to make, a way to revolutionize a 20 year old game with user-friendly up-to-date features that players nowadays will appreciate, if you think about it, things like this will draw more players to the game.

**Comment by ExiLe-ZH** [comment]
You experiencing manual crushing as a frustrasting babysit mechanic is completely your opinion aswell. 

Never heard anyone complain about it, if anything I bet it's fun/satisfying for most players.

Nothing personal but it's a really big noob suggestion lol.

**Comment by MTKing4** [comment]
> You experiencing manual crushing as a frustrasting babysit mechanic is completely your opinion aswell.

This isn't my experience, i handle crushing just fine, but i know it can be improved, hundreds of players already use this mechanic from other games and find it great, are they all wrong?

> Nothing personal but it's a really big noob suggestion lol.

Of course you say that, when your only Competitive RTS Experience comes from just one game you wouldn't know anything about RTS mechanics other than your own, in truth, you're uninformed and outdated so there's no point arguing with you.

**Comment by ExiLe-ZH** [comment]
> > You experiencing manual crushing as a frustrasting babysit mechanic is completely your opinion aswell.
> 
> This isn't my experience, i handle crushing just fine, but i know it can be improved, hundreds of players already use this mechanic from other games and find it great, are they all wrong?
> 
> > Nothing personal but it's a really big noob suggestion lol.
> 
> Of course you say that, when your only Competitive RTS Experience comes from just one game you wouldn't know anything about RTS mechanics other than your own, in truth, you're uninformed and outdated so there's no point arguing with you.

I've never heard anyone call it a frustrating babysit mechanic untill you made this topic.

It doesn't even matter what game X and Y have, we're talking about ZH and the people who love it.

It isn't only me who will never accept such huge changes to core mechanics, it will upset many if not the vast majority of ZH players aswell.

Also because it has massive effect on balance, like Dozer drops and Truck rushes becoming uncounterable, now how is that fun? (oh and combine that with Truck reverse aswell lol).

Look, I'm not saying it's wrong to try and learn from other games, but there's simply no reason to change this stuff. It isn't what the patch promised to do either.

**Comment by xezon** [comment]
We rejected Truck Reverse.

**Comment by MTKing4** [comment]
I understand the concerns about this change and I'm well aware of the balance implications of such change, which is why I'm not persuing it as hard, just don't like to see my point being invalidated by just saying it is a noob mechanic, it is not a noob mechanic and it will not make the game any easier

I will say though that it will require more balance changes to counteract this change for GLA, and since we're going for the least changes possible we can let this one pass

**Comment by Battlefieldkille** [comment]
On the other hand, some units do have crush voice lines, no?

**Comment by commy2** [comment]
All CCG ground vehicles have them. None of the ZH have them.
