### ISSUE TITLE
Demogen Demolitions Battle Bus no longer explodes when killed

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#2161]
After this commit https://github.com/TheSuperHackers/GeneralsGamePatch/commit/c365514211591781b9245226bf9e5e263aa18483, the Battle Bus with Demolitions upgrade no longer explodes when killed.

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/6576312/edae5d1a-0d87-4ffa-9b6e-cb503d58f4a5

In 1.04, it explodes, but deals no damage. It worked correctly after https://github.com/TheSuperHackers/GeneralsGamePatch/pull/102. I am unsure what the issue was that https://github.com/TheSuperHackers/GeneralsGamePatch/commit/c365514211591781b9245226bf9e5e263aa18483 solved. I did not notice any double explosions previously.

**Comment by xezon** [comment]
If I remember correctly there were 2 death explosions with Demo Bus. So I removed one of them and left the other. It worked for the tests I did. Perhaps I did not catch a special constellation.

**Comment by commy2** [comment]
Hmm, if I undo the commit, it looks like this:

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/6576312/4257786c-9b4d-4407-90c4-9b1eaad5f789

No explosion on first death. No explosion if deleted due to no passengers in second life, explosion when killed on second death.

Is there a double explosion?

Seems all borked now. This worked once :/

What is the expected behavior for the Bus? When should it demo-explode and do damage?

**Comment by xezon** [comment]
Yes only explosion on final death. I think first death is not supposed to have explosion.

**Comment by commy2** [comment]
Is it supposed to explode when evacuated in second life? That's when the bunker dies, even if health is left.

**Comment by xezon** [comment]
Not sure. What does it do currently?

**Comment by commy2** [comment]
death | version | damage?
--- | --- | ---
suicide | 1.04 | no, Bus disappears
suicide | main | no, fake explosion
first | 1.04 | no
first | main | no
second | 1.04 | yes (small damage)
second | main | no
second empty | 1.04 | yes (small damage)
second empty | main | no

**Comment by xezon** [comment]
Ok. Perhaps need to re-add the small damage then. Needs testing that it does not trigger 2 explosions though.

**Comment by commy2** [comment]
It doesn't work for suicide either in main branch. Explosion happens, but no damage is dealt.
