### ISSUE TITLE
Stunwalking infantry displays wrong death animation

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#2174]
When an Outpost is popped, passenger may be forced to walk. If they die in this state, they display a frozen walk animation instead of the proper death animation.

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/6576312/a520fb11-628f-4c6d-86ee-f02d36739e31

This seems to be because the engine forces them to walk, which applies MOVING flag. They are MOVING and DYING, which is not supposed to happen. Because MOVING is always defined first, they use that animation instead of the death one.

Solution is to go through all the infantry units in the game and add AliasConditionState DYING MOVING under DYING state.

**Comment by xezon** [comment]
Oh nice.
