### ISSUE TITLE
Player cannot build new GLA Jarmen Kell if Jarmen on Combat Cycle was hijacked by Hijacker

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#218]
Player cannot build new GLA Jarmen Kell if Jarmen on Combat Cycle was hijacked by Hijacker. This lasts until the Jarmen is evacuated from the Combat Cycle. Reported by Goldfish.

**Comment by alanblack166** [comment]
Only real solution would be to make Hijackers unable to hijack Combat Cycles.

**Comment by ReLaX82** [comment]
Does the Jarmen not die when hijacked on bike?

**Comment by commy2** [comment]
> Does the Jarmen not die when hijacked on bike?

No, he remains trapped inside the Bike, until the player that hijacked the Bike releases him by either evacuating the bike or by putting a different unit on it (giving control of Jarmen back to the player funnily enough).

I think hijacking mechanics combined with Combat Bike are so broken, that best case would be to not allow hijacking Combat Bikes at all. Logically, the Hijacker would kill the rider anyway, thus meaning that you should receive a Hijacker on a Bike. That's probably not feasible without engine changes though. I'll take a look at what I can do with this.

**Comment by xezon** [comment]
Making Hijacker unable to steal Combat Bike sounds ok to me.
