### ISSUE TITLE
Incorrect power level strings

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#2214]
Incorrect power level strings. In German language.

![power1](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/0a8f634b-0a5b-4324-b868-93176219e44a)

![power2](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/804a06b6-2895-42da-a46b-8ae6c847d6b3)

**Comment by commy2** [comment]
Not only doesn't it do its job, it even lies about it.

**Comment by xezon** [comment]
I think there is also another bug in German where it will not show player Win Loss on player name hover in GameSpy lobby.
