### ISSUE TITLE
Broken civilian exploded death animations

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#2221]
This PR: https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2074/files added "missing" death modules to infantry, including civilians. Many of these civilians do not have any "flailing in the air" death animations, so with those new modules, it now looks like they're jumping into the air upright when exploded, which looks very very wrong.

Propose deleting the EXPLODED death modules that apply FlingForce/FlingPitch, since no supporting animation exists.

**Comment by commy2** [comment]
```ini
;-------------------------------------------------------------------------------
ObjectCreationList OCL_AmericaVehicleDozer
  CreateObject
    ObjectNames = MogadishuFemaleCivilian01
    Count = 10
    Disposition = ON_GROUND_ALIGNED
    Offset = X:0 Y:0 Z:0
  End
  CreateObject
    ObjectNames = MogadishuFemaleCivilian02
    Count = 10
    Disposition = ON_GROUND_ALIGNED
    Offset = X:0 Y:0 Z:0
  End
  CreateObject
    ObjectNames = MogadishuMaleCivilian01
    Count = 10
    Disposition = ON_GROUND_ALIGNED
    Offset = X:0 Y:0 Z:0
  End
  CreateObject
    ObjectNames = MogadishuMaleCivilian02
    Count = 10
    Disposition = ON_GROUND_ALIGNED
    Offset = X:0 Y:0 Z:0
  End
  CreateObject
    ObjectNames = MogadishuMaleCivilian03
    Count = 10
    Disposition = ON_GROUND_ALIGNED
    Offset = X:0 Y:0 Z:0
  End
  CreateObject
    ObjectNames = GLAInfantryTunnelDefender
    Count = 10
    Disposition = ON_GROUND_ALIGNED
    Offset = X:0 Y:0 Z:0
  End
End
```
into OCL.ini to test.

**Comment by commy2** [comment]
have exploded anims:

MogadishuMaleCivilian03
MogadishuFemaleCivilian02

do not have them:
MogadishuMaleCivilian01
MogadishuMaleCivilian02
MogadishuFemaleCivilian01

**Comment by xezon** [comment]
Oh nice catch. Indeed I did not test this. I just assumed it would work.
