### ISSUE TITLE
China Internet Center has little armor

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#223]
Evaluate whether or not China Internet Center should have more armor. It can be killed easily. Reported by Dominator.

### Proposal 1
Reduce price. For example from 2500 to 2000.

### Proposal 2
Increase structure health. For example from 2500 to 3000.

### Proposal 3
Reduce cash update delay bonus. For example from 1800 to 1600.

### Proposal 4
Increase various armor types. For example reduce EXPLOSION damage from 70% to 50%.

### Proposal 5
Increase hacker slots. For example from 8 to 10.

### Proposal 6
Allow to build 2 Hacker Centers at half cost with 4 slots each. Allows to spread out hackers. Only possible if 4 slot center does not violate some Campaign mission that requires 8 slots for it.

### Proposal 7
Allow regular Infantry, such as Tank Hunters, to garrison in order to help defend the structure.

**Comment by commy2** [comment]
It can be one shoted by a Particle Cannon, which is really bad. It even has special armor against particle beams, yet dies anyway.

**Comment by Jundiyy** [comment]
I don't think it should be changed. We have lowered the price already to make it more attractable.

**Comment by xezon** [comment]
![expendables](https://user-images.githubusercontent.com/4720891/132137567-7eb79bce-10e1-4095-8e0a-e4186e7390e4.jpg)

**Comment by Jundiyy** [comment]
Also the Internet Centre is not a weak building, it's stronger than many out there. It can survive a Particle Cannon if being repaired, around 20%/25%, unlike most buildings (not including CC/SW), without repair it dies but not instantly, other buildings are just shredded. Also survives a direct shot from a Nuke.
Don't think it's right to say it's weak.

**Comment by MTKing4** [comment]
A slight HP increase should be considered,  just to get rid of _"just one click and POOF! your second eco gone"_ strategy

**Comment by ExiLe-ZH** [comment]
@Jundiyy You sure it survives when you keep moving the particle cannon? 

But yea, I personally prefer HP improvement over price reduction, because it's just a mega balance flaw of the game imo.

**Comment by Stubbjax** [comment]
> 
> 
> @Jundiyy You sure it survives when you keep moving the particle cannon?
> 
> But yea, I personally prefer HP improvement over price reduction, because it's just a mega balance flaw of the game imo.

Moving the beam has no additional effect. A single beam will be just enough to destroy an Internet Center if absolutely no repairing takes place. A single level 3 A-10 strike will also destroy it.

Regardless, I think this structure needs to be buffed somehow. Below are what I believe could be some appropriate adjustments to make (not necessarily all) to help give the structure more value / viability:
```
1. Reduce price from $2500 to $2000.
2. Increase HP from 2500 to 3000.
3. Reduce cash update delay bonus from 1800 to 1600.
4. Increase various armour types, e.g. reduce EXPLOSION damage from 70% to 50%, etc.
5. Increase slots from 8 to 10.
```
1. It feels bad that China has to fork out a whopping $2500 just for a bit of protection on their late game economy. Putting that extra $500 towards another hacker could make quite a difference.

2. Could be controversial, as many players are precisely aware of the firepower required to destroy them - maybe even more so than the price. Changing it might be too big of a disruption to normal / expected gameplay. However, it would be much nicer if they didn't just die to singular Generals Power strikes and required more coordination to destroy.

3. A shorter duration before your investment is returned. Hackers would also rank up faster. Increases risk vs reward, which is a nice dynamic to amplify.

4. Potentially a more flexible way of adjusting health, as individual damage resistances can be tweaked accordingly.

5. Giving protection to an extra two Hackers could make the price more justifiable. Would likely need to be in combination with other option(s), as this increases the structure's target value for the opposition.

I would also probably replace the War Factory with the Propaganda Center as the prerequisite for construction. It never made sense to gain access to the Internet Center via the War Factory, as Hackers require a Propaganda Center to construct anyway.

**Comment by xezon** [comment]
> I would also probably replace the War Factory with the Propaganda Center as the prerequisite for construction. It never made sense to gain access to the Internet Center via the War Factory, as Hackers require a Propaganda Center to construct anyway.

I do not recommend this. There is no need for this. It is a legitimate scenario that a China player could lose a Propaganda Center under fire but still had some hackers around that he could build a Hacker Center for without rebuilding the Propaganda Center.

**Comment by Stubbjax** [comment]
> 
> I do not recommend this. There is no need for this. It is a legitimate scenario that a China player could lose a Propaganda Center under fire but still had some hackers around that he could build a Hacker Center for without rebuilding the Propaganda Center.

I think you're overstating its legitimacy here. The same thing can be said if a player loses their War Factory but still has a Propaganda Center. Besides that, is it not an entirely valid strategy to eliminate a player's tech building to deny them access to second-tier units / structures? For me, it makes more intuitive sense for it to be tied to the Propaganda Center.

Nevertheless, I don't consider this particular aspect of the design to be of great importance and wouldn't mind if it is left the way it is - especially as it is what players are already used to.

**Comment by xezon** [comment]
> I think you're overstating its legitimacy here. The same thing can be said if a player loses their War Factory but still has a Propaganda Center. Besides that, is it not an entirely valid strategy to eliminate a player's tech building to deny them access to second-tier units / structures? For me, it makes more intuitive sense for it to be tied to the Propaganda Center.

You are right my argument makes no sense looking at it this way.

**Comment by Jundiyy** [comment]
There is also the scan ability from the IC, needing to tech up first would mean a later scan.

1. Is more simple of a change. Currently we have cheaper Hackers, which are also trained faster and also a cheaper IC. So far the change has been good for 1.04+. More test games with this should be considered. Another thing which could be done alongside is make the build time faster, so it doesn't take as long to get it back up. 

2. As already mentioned above, hp change would already be a change for players. I still don't see the building as weak when compared to most buildings. People expect more which is why it feels weak. This change would probably be last in the list for me. Maybe Hackers would need to have a higher price to balance as they are cheaper now. 

3. I did think of this, it would mean Hackers paying back for the IC quicker and also vetting up quicker, probably not noticeable to most without paying attention to the IC. Although then would Inf Gen be given a small buff as well? I do think this is a safe change but also means a much better return, $10 Hackers would be seen more and be throwing money out 10% faster than they currently do in the IC (which is already 10% faster than normal). 
4. This one is similar to 2, so similar answer.
5. This one...it's not as much as a change as the other 2, although it visually shows you a change so could be a reason for complain, probably prefer over the 2 and 4 at this moment.

**Comment by MTKing4** [comment]
Speaking of IC scan, i think a numerical/visual countdown timer should be added to sat hack II so players can actually plan their strategies and prepare for the scan beforehand would be really useful

**Comment by Jundiyy** [comment]
That's quite a nice thought. Maybe the satellites can be edited to do a full rotation for every scan. So you can tell when you'd get the scan. Not sure I'd like a number over it. Maybe a number/timer when clicking on it could work.

**Comment by MTKing4** [comment]
It's one or the other is fine

**Comment by ExiLe-ZH** [comment]
2500HP just makes no sense... AT ALL. With hackers it's worth like $8k!
Not only are you losing this huge investment when it gets destroyed, but in most cases also a big chunk of future income, so the damage is much greater (multiplied a few times probably).

3000HP sounds more reasonable to me as it would be the same as the Strat Center with Hold the Line or a Palace without Fortified Structures.

And that's still relatively weak, like an Arms Dealer already has 2000HP, with Fortification that's 3000HP?

**Comment by Jundiyy** [comment]
HP could be a way but I just don't see it as good at the moment. 
My concern, it would become a very very hard bunker to kill, China would become the only faction without worrying about 2nd eco going down. Surviving a Particle Cannon whilst being repaired, or an A 10 strike and so on. Markets are taken down by general powers and so are drop zones (if built), sometimes you see 2 or 3 Markets go down at once. 
China IC in the back of the base, many GPs wouldn't get through or get the damage out before going down (as it's stronger) and the IC would survive, eventually giving Chinas money worth more than 4 Black Markets.

Looking at 1.04+ Beta 3 (last release on GR) and not the original.

With the new changes already, Hackers + IC = $6150, we have already seen Hackers being built during games (by those that read the changelog), IC being used. Hackers have also be seen spread out on the map, being cheaper and built faster. 
Of course all the eco from the IC can go down in one go, just like 2 or 3 Markets can, but as they say, "don't put all your eggs in one basket", You wouldn't have Hackers only in the IC in 1.04+, they can be placed outside as well in safe spots. Being cheaper means you are not at as big of a loss. 

We can always try the HP way but in return we would probably need to increase the Hacker/IC price again or perhaps the Build Time. 
Will still think over it some more.

**Comment by MTKing4** [comment]
> China IC in the back of the base, many GPs wouldn't get through or get the damage out before going down (as it's stronger) and the IC would survive, eventually giving Chinas money worth more than 4 Black Markets

Don't forget that gla tunnels/sneak attack with busses/quads can wreck it very easily, and USA Genpower combos can easily penetrate defenses with spectre/carpet/Moab so i don't think that's a valid point, they say not to put the eggs in one basket, but in reality it's probably the safest and the most effective way to protect hackers if not for the 1 shot kill, while the ones outside can literally die to everything jarmen/snipers/genpowers/anthrax/any other unit

For me personally i would probably never build hackers in a competitive game if I can't secure them in an internet center, not worth the risk even when cheap, $6150 can change the game's outcome

**Comment by Jundiyy** [comment]
I won't disagree the ones outside can die a lot easier but I am talking about 1.04+ Beta 3 here. And what has been tried.

I did think of the Sneak Attack when writing that up but having a stronger IC would mean Sneak Attacks would not be as problematic, you would have more time to react hence why I didn't mention it. Same for the Gen powers you have mentioned, at the back many will be shot down before they get there and the ones that reach won't do as much damage once it's stronger depending on what they are, Carpet/A10/Spectre.

Just what I have already seen in 1.04+ plus thinking of the extra health that is given and the outcome. As mentioned before, if Hacker prices or IC is reverted with IC + HP up then it might end up being a stable change.

Maybe more tests as Chinas vs other armies with the current build will reveal how good it currently is or not and then we can see if the extra hp is actually needed.

**Comment by MTKing4** [comment]
That's the whole point, giving china a chance to react

I don't mind reverting hackers build speed to the original, think that would balance it out

**Comment by ExiLe-ZH** [comment]
> I won't disagree the ones outside can die a lot easier but I am talking about 1.04+ Beta 3 here. And what has been tried.
> 
> I did think of the Sneak Attack when writing that up but having a stronger IC would mean Sneak Attacks would not be as problematic, you would have more time to react hence why I didn't mention it. Same for the Gen powers you have mentioned, at the back many will be shot down before they get there and the ones that reach won't do as much damage once it's stronger depending on what they are, Carpet/A10/Spectre.
> 
> Just what I have already seen in 1.04+ plus thinking of the extra health that is given and the outcome. As mentioned before, if Hacker prices or IC is reverted with IC + HP up then it might end up being a stable change.
> 
> Maybe more tests as Chinas vs other armies with the current build will reveal how good it currently is or not and then we can see if the extra hp is actually needed.

It’s pretty good in beta 3, but I’d personally prefer to revert internet center price and do the HP thing. Or even revert hackers too to some extent if needed.

It’s just not satisfying as is and I would feel bad if I could kill Excals second eco with one cheapshot.

**Comment by xezon** [comment]
China late game economy is very bad in 1.04. Easy to kill and expensive. Keep in mind, Internet Center can be built once only. Changing internet center will therefore only have limited impact when there are more than 8 hackers in player arsenal.

**Comment by MTKing4** [comment]
> It’s pretty good in beta 3, but I’d personally prefer to revert internet center price and do the HP thing. Or even revert hackers too to some extent if needed.

Reverting hackers to normal cost is ok (make them 625 to all and 675 for inf maybe) but not the internet center's cost, it should remain 1500, don't forget that with the old cost it makes it harder to get to the scan abilities

**Comment by Jundiyy** [comment]
@MTKing4 one or the other would surely need to change, IC is currently $1750, not $1500 in Beta 3, the upgrades are quite cheap compared to original, you save $1500 if you upgrade both. Also Inf Hackers having more price than standard wouldn't be good. You still need to be able to make them and pay off, too expensive and they would take a longer to pay off. 

@xezon I am comparing to Beta 3, in which China 2nd eco is a lot better, not comparing to 1.04. This can be seen if played, it would be nice if players tried it out first to see the difference as China is a lot more flexible with the change and more forgiving if Hackers are lost. More than 8 hackers are also built.

But anyway, we can try the hp way if most want to, then some prices/times should be reverted, although this would mean that China is not as flexible anymore as Beta 3. It would mean all eggs in one basket, so China would have a nice strong economy as one full IC gives 10% more than 2 Markets at the start (Hackers/Markets are similar in price) and if they get vet (which a stronger IC should give) you would have 120% more than what 2 Markets give, ($1200 vs $2630). Hence the fear of a strong bunker. But if lost then not as easy to recover from, unlike in Beta 3 (flexibility).

Option 3 could also be a stronger IC including Beta 3 Hacker/IC changes, but that might be op as it would be a strong bunker with flexibility to China.

Anyway, let's see what others have to say, then we can try the hp way if it is the way.

**Comment by MTKing4** [comment]
> Also Inf Hackers having more price than standard wouldn't be good. You still need to be able to make them and pay off, too expensive and they would take a longer to pay off.

They start as vet1, and stealthed meaning the make more money while being harder to kill, so increasing the investment cost by a little compensates for that imo

More cost = more reward

Seems logical to me

**Comment by Kesanov** [comment]
Easy fix for china second eco: Allow hackers to hack in bunkers.

Just kidding.


------
The problem with china eco is that hackers are easy to kill (classic general powers + anthrax & snipers).
I don't think that buffing IC HP will fix it, as you are still limited to those 8 slots.
Possible solution would be limiting those slots to 4 and allowing china to build multiple internet centers.

However, that would be a pretty significant change, which we want to avoid.

**Comment by ExiLe-ZH** [comment]
If there's 1 redesign that makes the most sense then it's making all hackers stealth, but the patch promised and will not redesign balance in such way. 

The price reduction and increased production speed of hackers already gave china a good boost, which even seemed to play out evenly with USA in the 1v1 pro test games. 

That said, giving a small 500HP boost over a cheaper internet center is acceptable imo and has my preference, if that's the only such change in this patch.

**Comment by commy2** [comment]
In my project, I made the Hackers go invisible while standing / hacking (but not moving) as soon as they reach vet 1, but behave normally before that. This way, the enemy still has time to scout it and go into offensive.

However, that is a "big change" and I don't advocate for it.

**Comment by FinAminToastCrunch** [comment]
I think all factions should use China inf hackers. Its so stupid that China has a nonexistent late game. I don't see why there is a discussion about the internet center. It should surely have its health buffed.

**Comment by commy2** [comment]
Can't have a change without discussing it first^^

**Comment by commy2** [comment]
https://user-images.githubusercontent.com/6576312/136677344-3ccf120f-5691-40c6-8061-5921b75ea217.mp4

**Comment by commy2** [comment]
https://user-images.githubusercontent.com/6576312/136684981-f58d6b51-ca6b-4937-9932-2e6aa3ef4b76.mp4


https://user-images.githubusercontent.com/6576312/136684985-c7d890b3-5b45-417a-9961-499ffc0b2ab3.mp4

**Comment by xezon** [comment]
If I am not mistaken we only have these 5 proposals from Stubbjax. Added to opening post for visibility.

**Comment by commy2** [comment]
I am for proposal 2. The Internet Center should have at least enough health to survive a Particle Cannon or triple A10 Strike or full Spectre attack.

I don't know how increasing the slots would help. That is just increasing the risk factor of the building. Reducing price helps the player rebuilding a destroyed Internet Center, but if really 8 Hackers were killed by a free superpower, then the damage is already done anyway.

**Comment by xezon** [comment]
Proposal 2 aka increased healths does read good on paper indeed.
Proposal 5 is good for China's opponents, as they can kill even more hackers with one blow.

**Comment by Jundiyy** [comment]
Increasing hp is quite a risky one imo. If it is increased, it should be done so that a level 3 Artillery, A10 or Spectre can still take out an IC. Otherwise you'd have a very strong bunker which you can't take out at all, especially placed at the back of the base. Whereas Markets and SDZs can be taken out all day long.

The Particle Cannon vs IC looks fine. If you have a Dozer there to repair, even for a very short time, the IC will survive. So the Armour vs PC doesn't need changing.

**Comment by MTKing4** [comment]
I think the price should be $1000, building has no purpose other than a house for hackers you already payed for and some money sink sat hacks. 

As for HP, make it strong enough that it needs to be combed with 2 gen promotions or 2 super weapons, usas can afford that anyway and gla's mobility and superweapons are already too powerful and can easily reach the IC one way or another.

This can't be compared to markets or SDZs, this is china's entire economy, you shouldn't kill it as easily.

**Comment by commy2** [comment]
Investment wise, a full IC is worth 3 BMs or 3 SDZs. Those can be spread out to avoid a wipe by superpower. Internet Center can't.

**Comment by xezon** [comment]
Added Proposal 6: Allow to build 2 Hacker Centers at half cost with 4 slots each. Allows to spread out hackers. Only possible if 4 slot center does not violate some Campaign mission that requires 8 slots for it.

**Comment by commy2** [comment]
There is this comment in the code of the InternetCenter:

  ;*******************************************************************************************************************
  MaxSimultaneousOfType = 1 ; *** Kris: DO NOT INCREASE THIS NUMBER -- UNLESS YOU WANT TO INTRODUCE A LOT OF BUGS! ***
  ;*******************************************************************************************************************

I do not know what this means, but it always made me hesitant to allow more than 1 (even though the supposed bugs would appear anyway due to faction sharing).

**Comment by Jundiyy** [comment]
$1000 with super hp doesn't sound right. Reminds me of the Detention Camps in CCG, cheap, big buildings that could be used to protect important structures. If it has a lot more hp that even a level 3 (3 GP points) can't destroy, price should be higher, since it's going to totally protect your Hackers for a super long time, or maybe to the end of the game. 

I don't agree that it should be your entire income, players should always try to expand and become bigger. Yes it will be a safe income but shouldn't be the entire.

And allowing multiple ICs would sound great, but not for ZH at its current stage. Might throw people off. Of course, if there are multiple ICs then price and hp needs to be looked at.

**Comment by xezon** [comment]
The Jundiyy: "Just don't change anything to fix this problem" :D

**Comment by Jundiyy** [comment]
Lol, no I didn't say that. But I don't agree with it being so strong. Not saying it shouldn't be stronger.

**Comment by MTKing4** [comment]
> price should be higher, since it's going to totally protect your Hackers for a super long time, or maybe to the end of the game

Maybe $1500 not more

> I don't agree that it should be your entire income, players should always try to expand and become bigger. Yes it will be a safe income but shouldn't be the entire.

It is your only safe one, most other hackers are vulnerable to attacks and even having to move constantly is also a downtime for them not hacking, most people would do less if they could rely on the IC completely, but yes of course more is better. But IC is something to fall back on

> And allowing multiple ICs would sound great, but not for ZH at its current stage. Might throw people off. Of course, if there are multiple ICs then price and hp needs to be looked at.

I'd love it if we were able to do that, it'll solve all our problems, have it take only 4 hackers with no build limit, in that case price should be similar like $1500 but hp would be weaker, maybe as strong as a bm

**Comment by ExiLe-ZH** [comment]
> > And allowing multiple ICs would sound great, but not for ZH at its current stage. Might throw people off. Of course, if there are multiple ICs then price and hp needs to be looked at.
> 
> I'd love it if we were able to do that, it'll solve all our problems, have it take only 4 hackers with no build limit, in that case price should be similar like $1500 but hp would be weaker, maybe as strong as a bm

Making all hackers stealth when hacking (could be from vet1) would feel less mod'ish, Inf would still have always-stealth vet1 hackers from the get go, which is quite an advantage.

**Comment by MTKing4** [comment]
> > > And allowing multiple ICs would sound great, but not for ZH at its current stage. Might throw people off. Of course, if there are multiple ICs then price and hp needs to be looked at.
> > 
> > 
> > I'd love it if we were able to do that, it'll solve all our problems, have it take only 4 hackers with no build limit, in that case price should be similar like $1500 but hp would be weaker, maybe as strong as a bm
> 
> Making all hackers stealth when hacking (could be from vet1) would feel less mod'ish, Inf would still have always-stealth vet1 hackers from the get go, which is quite an advantage.

They still die easily and not hard to detect, as you can hear their sounds and drop anthrax there, see this game
https://youtu.be/Hj1uxk7C-TA

Speaking of which, i think we need a report for that, stealth hackers can be heard when hovering over them.

**Comment by ExiLe-ZH** [comment]
> > > > And allowing multiple ICs would sound great, but not for ZH at its current stage. Might throw people off. Of course, if there are multiple ICs then price and hp needs to be looked at.
> > > 
> > > 
> > > I'd love it if we were able to do that, it'll solve all our problems, have it take only 4 hackers with no build limit, in that case price should be similar like $1500 but hp would be weaker, maybe as strong as a bm
> > 
> > 
> > Making all hackers stealth when hacking (could be from vet1) would feel less mod'ish, Inf would still have always-stealth vet1 hackers from the get go, which is quite an advantage.
> 
> They still die easily and not hard to detect, as you can hear their sounds and drop anthrax there, see this game https://youtu.be/Hj1uxk7C-TA
> 
> Speaking of which, i think we need a report for that, stealth hackers can be heard when hovering over them.

Yea the sound is a complete giveaway and silly design.

**Comment by ZekeDlyoung** [comment]
> There is this comment in the code of the InternetCenter:
> 
> ;******************************************************************************************************************* MaxSimultaneousOfType = 1 ; *** Kris: DO NOT INCREASE THIS NUMBER -- UNLESS YOU WANT TO INTRODUCE A LOT OF BUGS! *** ;*******************************************************************************************************************
> 
> I do not know what this means, but it always made me hesitant to allow more than 1 (even though the supposed bugs would appear anyway due to faction sharing).

This has to do with the Sat Hack powers, tho I don't remember exactly what the bugs are.

Some mods do add smaller Internet Center type buildings to help improve China sec eco, example: https://www.moddb.com/mods/nproject-mod/images/chinese-spy-post#imagebox

So there is that option.

**Comment by xezon** [comment]
### Proposal 7
Allow regular Infantry, such as Tank Hunters, to garrison in order to help defend the structure.

**Comment by ExiLe-ZH** [comment]
I think with the Nuclear Missile Change this definitely needs revisiting, the resistance vs different types of weapons seems off.

- Particle damages it down to ~15%, ~45% when actively repaired (Particle can be moved to kill Dozer ofcourse).
- Nuclear Missile and Scudstorm both 1 shot when aimed on top, but it seems that the Nuke has a better damage radius when aiming next to the IC. See pics:
![Command   Conquer - Generals Screenshot 2022 08 14 - 21 48 51 08](https://user-images.githubusercontent.com/32326277/184553012-b648c110-7da6-41b0-90ae-6736a328af76.png)
![Command   Conquer - Generals Screenshot 2022 08 14 - 21 48 54 05](https://user-images.githubusercontent.com/32326277/184553017-45dd80a5-e208-4f47-bfa6-a7cc77b50912.png)
![Command   Conquer - Generals Screenshot 2022 08 14 - 22 00 34 17](https://user-images.githubusercontent.com/32326277/184553021-fbbc57ec-428b-4309-a680-ded9d3b84940.png)
![Command   Conquer - Generals Screenshot 2022 08 14 - 22 00 39 25](https://user-images.githubusercontent.com/32326277/184553026-d4c50824-b721-41ae-9f73-c9391a24a46d.png)
Nuke was slightly further away, yet HP on IC got lower.

**How it should be?**
Overall health should be increased so that the IC JUST survives vs any SW.
Fire resistance should be less so that the Particle deals equal damage as Nuke/Scud.

**Comment by Jundiyy** [comment]
Yep, I think I'm okay with that. Health increased/Armour change so a super weapon leaves it on very low health. PC doesn't need to be changed since it can just finish it off, but if repaired (even for a second) then it can't.
Although Scud Storm does more damage out of all the super weapons, so it should drop the hp lower than the Nuke imo.

I still think a level 3 Arty/A10/Spectre should be able to take it out. Even if the Hackers survive.

Price should be looked at carefully now since the IC will be stronger, gives a much bigger boost to Hackers and Hackers also vet up a bit faster.

**Comment by commy2** [comment]
Since Satellite I was fixed and Satellite II is now a manual ability, I see no technical reason to keep the 1 max limit.
Although I personally would keep it at 1, because I'm a purist.

**Comment by xezon** [comment]
Having multiple Internet Centers could be quite OP though, because of the Hacker speed buff it applies (20% faster hacking).

**Comment by Jundiyy** [comment]
Well, if we really do want it, we can revert some other changes to compensate. But I am with commy here, keeping it to 1.

**Comment by ExiLe-ZH** [comment]
> PC doesn't need to be changed since it can just finish it off, but if repaired (even for a second) then it can't. 
> 

That's weird, I found that the Particle damages it down to ~15% HP, ~45% when actively repaired (Particle can be moved to kill Dozer ofcourse). the patch already changed something?

![Command   Conquer - Generals Screenshot 2022 08 14 - 22 46 58 48](https://user-images.githubusercontent.com/32326277/184554340-7c4d9aff-5bc3-4912-a0a7-c4cbbed51a1c.png)
![Command   Conquer - Generals Screenshot 2022 08 14 - 22 47 19 63](https://user-images.githubusercontent.com/32326277/184554344-f2783cdb-48a2-45b5-ada4-756598112797.png)

> I still think a level 3 Arty/A10/Spectre should be able to take it out. Even if the Hackers survive.
> 

Think it should only JUST survive, exactly same like SW. These powers can't kill such value from other factions either.

**Comment by xezon** [comment]
I can not recall touching anything for Particle Cannon damage and Internet Center armor.

**Comment by commy2** [comment]
IC has 2500 health on current main and in 1.04. No armor changes for StructureArmorInternetCenter either.

Make sure to conduct all tests vs medium AI. If easy or hard AI is present, the player as well as the AI may obtain health and rate of fire buffs/nerfs.

**Comment by MTKing4** [comment]
> Having multiple Internet Centers could be quite OP though, because of the Hacker speed buff it applies (20% faster hacking).

We can always revert that buff and make it have multiple ICs, reduce its HP,  Price, and allow only 4 hackers

I think that would be the ideal solution, to Spread the risk of having all eggs in one basket.

**Comment by penfriendz** [comment]
I would really like for it not to get one shot by powers. It's something that, despite me having played for decades, I have never gotten used to and always struck me as unfair and Illogical.

**Comment by ReLaX82** [comment]
General issue is that China only has maximum 8 secured hackers which is really bad late game. Other hackers die instantly vs anything.

GLA has the best 2nd, USA is in between as the zones have lower HP. In fact I find USAs 2nd the best overall.

I would increase ICs HP for sure so that its worth to spend this money and its secure. Factor 1.5 maybe?

Make hackers better vs radiation also.

**Comment by ExiLe-ZH** [comment]
> IC has 2500 health on current main and in 1.04. No armor changes for StructureArmorInternetCenter either.
> 
> Make sure to conduct all tests vs medium AI. If easy or hard AI is present, the player as well as the AI may obtain health and rate of fire buffs/nerfs.

I tested on MTKing's General Promotions Test Map by capping the Tank's CC. Can not change AI difficulty.

I also just tested 1.04, result is exactly like Jundiyy claimed.

!! So the patch does change something.

**Comment by xezon** [comment]
Maybe error in test. I can check myself later.

**Comment by ExiLe-ZH** [comment]
> Maybe error in test. I can check myself later.

Maybe yea,

It's strange though, can't think of a factor that changes the results between 1.04 and patch.

Conditions (map) are the same and results are consistent (ran it multiple times).

Edit: Maybe it's a conflict in my patch build, same how GUI changes don't work correctly.

**Comment by xezon** [comment]
Well for starters your game install is not clean. Your images show Control Bar Pro, which is not part of Game Patch, so it is unclear what modifications you have that could potentially interfere.

**Comment by commy2** [comment]
[Bug with glitched Particle Cannon vs Internet Center interaction has been fixed.](https://github.com/TheSuperHackers/GeneralsGamePatch/pull/912) Now behaves the same in main branch as it does in 1.04.
Please proceed discussion.

**Comment by xezon** [comment]
Can we perhaps agree that there should be no single (unstoppable) Superweapon and Generals Power that can kill a 100% health Hacker Center (without nearby Dozer) in one attack? There always needs to be a combination of attack to take it down fully.

If we can agree on that, then we can find the right settings to tweak accordingly.

Unstoppable Powers are:

* USA Particle Cannon
* China Nuke Missile
* GLA Scud Storm
* China Artillery
* GLA Demo Rebel Ambush (they explode and deal damage on mines?)
* ... ?

**Comment by MTKing4** [comment]
Spectre + level 2 A10

**Comment by xezon** [comment]
Spectre and A10 can be stopped.

**Comment by MTKing4** [comment]
then i guess Alphas

**Comment by xezon** [comment]
Internet Center armor is stronger now against Explosion, Particle beam and Aurora bomb.
