### ISSUE TITLE
China Tank vs China Nuke balance

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#2347]
Does anything need to be done with China Tank vs China Nuke?

ReLaX says:
> You might give Tank-Hunters a unique status, so that they are not or less vulnerable vs nuke radiation. Might also think about the same for outposts. Might increase effectiveness of Migs against Nuke-Units as well, but that can break the idea of the faction. What about Nuke shells of the nuke cannon giving less power, not sure if that is even possible.

### Proposal 1

Increase radiation armor of China Tank Hunters.

### Proposal 2

Increase effectiveness of Migs against Nuke Battlemaster and Nuke Overlord.

### Proposal 3

Decrease damage of Nuke Cannon.

**Comment by xezon** [comment]
My 2 cents: Do nothing. Tank General already got a number of fixes and buffs:
* #236
* #412
* #768
* #1815
* #1854

Pending fixes and buffs:
* #1704
* #1844

Proposal 1 would be a perk to be expected for Infantry General, not Tank General.

Proposal 2 would have to apply in general for all China. Why would Tank Generals Migs be better than other Migs?

Proposal 3 is not so nice for China, because Nuke Cannon sucks a bit. Is slow and expensive.

**Comment by penfriendz** [comment]
100% do nothing imo.

The solutions are also bad hacks but that didn't influence my decision to comment do nothing.

**Comment by ExiLe-ZH** [comment]
The proposals don't convince me that tank vs nuke will be improved significantly or exclusively.

The matchup is surely better already with the already implemented changes that xezon mentioned. In the early game Tank should have more chance with the speedier BM's. In the mid/late game Emperor spam could be pretty powerful, they're quite resistant against Nuke Shells (more so with self-healing). Overall Nuke will get promoted less quick aswell.

**Comment by MTKing4** [comment]
Don't see anything necessary to change atm, do nothing

**Comment by xezon** [comment]
Closing.
