### ISSUE TITLE
China Nuke Superweapon is ineffective against GLA buildings

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#237]
China Nuke Superweapon is ineffective against GLA buildings. The missile deals good damage on the center of the impact, but because the Nuke blast is singular, the GLA buildings will just blow down to their hole, regardless of the health they have remaining.

GLA SCUD Storm and USA Particle Cannon do not have this design issue.

See also #235

**Comment by commy2** [comment]
The nuke damage logic is kind of complicated. There is an inner radius where some constant damage is dealt, and then there is an outer radius where damage gradiately decreases to 0 depending on the distance from the inner radius.

https://github.com/commy2/zerohour/commit/9d28d9a33df4b4bc98055cf3fb795183f7261256

With some math magic, one can use the 6 blast phases the engine already provides to graduately deal damage from blast center to blast circumference in steps, thus destroying holes (and also Battle Buses) - in such a way that the damage as function from the position stays the same.

**Comment by ZekeDlyoung** [comment]
Based on my own experiments with my mods, I found that having a constant radius is better than a growing radius, but I agree with dividing the single blast into multiple blasts

**Comment by MTKing4** [comment]
Divide 1 blast into multiple blasts

**Comment by Madrageeeeee** [comment]
Think there is an issue with all factions. The damage is does seems very random. Sometimes it will destroy many buildings and sometimes it does hardly any damage. It often felt a bit like hit or miss. 

This isnt for gla structures only i feel. The damage dealt to the buildings always felt very random and not predictable

**Comment by commy2** [comment]
That's because it decreases with range. There is an inner range where damage is flat. Outside the inner radius, the damage decreases to 0 proportionally.

**Comment by xezon** [comment]
I reported a new issue for the comment provided by Rage
Issue #280
