### ISSUE TITLE
Make Unit Queues not Reserve Money Until they Start getting produced

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#2386]
Unit build Queues are largely underused by pros because they reserves the money which make them inefficient, because that money could be spent elsewhere on more important things like expanding, making unit build Queues mostly useless because pros will end up queuing one unit only at a time

It should be changed in a way so that the next unit in the queue don't take money until it reaches its turn to build, that way you can queue up to 9 units without having to worry about your money

The only downside i can think of for this change is that you can no longer deny a lotus cash hack by adding units to your build Queues, but you can still deny it other ways, like adding multiple scaffolds to reserve money to lower the cash steal.

This is a feature request that should be considered when we have the ability to implement it, i.e after thyme.

**Comment by penfriendz** [comment]
This isn't a simple change and it does not necessarily improve the game. A starcraft 2 mod tried it.

https://illiteracyhasdownsides.com/2017/12/31/axiom-mod-review/

The relevant section is practically the first issue the guy raises and he explains why it may not be a good idea much better than I can.

I disapprove.

**Comment by xezon** [comment]
> Theme I: Trading one complexity for another

> Axiom makes many changes to the base StarCraft II experience, so I’ve organized its feature set into several themes. The first theme refers to Axiom features that attempt to streamline gameplay and reduce complexity, but which ultimately trade one complexity for another. From my perspective these changes make the gameplay experience substantially worse – in the best case, they’re net-zero.

> Let’s start with the new economy. In traditional StarCraft II, players pay for everything up-front – before you can start construction of a command center, you need to pay four hundred minerals. Axiom instead uses a pay-as-you-go system in which payment for items occurs as they’re being constructed. This shifts focus to revenue- and cost-per-second – the net total is displayed under a player’s minerals and vespene gas.

> The rationale for this change is the avoidance of “dead money”. In traditional StarCraft II, when a player queues 5 marines at a barracks, they pay two hundred and fifty minerals. However, only one marine is produced at a time. This means there are two hundred minerals worth of underutilized production. With Axiom, you’re only ever spending money on items that are actively being produced. In addition, players can begin construction of any building or unit at anytime, theoretically allowing them to focus on what they should build rather than the nuts and bolts of how much things cost.

> The downside of the pay-as-you-go-economy is that it introduces a new complexity: overbuilding. In Axiom, if you commit to spending more per-second than you have – and you don’t have a mineral and gas bank – all of your production deadlocks and nothing gets produced. This requires you to either wait for everything to finish (which can take ages) or cancel items until your net-income is greater than zero. Naturally, this never happens in the base game, where everything is paid for upfront.

> There are a couple of problems with this. First, it sounds obvious that your costs shouldn’t exceed your revenue, but it’s surprisingly tricky to get right. If you’re in the middle of a fight, frantically queue up a bunch of what you need, and suddenly discover that your production is deadlocked, it can feel really frustrating. Axiom encourages players to focus on what they’re constructing rather than the nuts and bolts of how much things cost, meaning you’re incentivized to make this kind of mistake.

> Second, cancellation is jarring because it mixes together different macromanagement design patterns. Axiom’s Universal Command Bar allows players to construct anything from anywhere, meaning they don’t have to go home to macro. But cancellation means going back to in-production items and canceling them manually, the same process as the base game. It’s really confusing to need to know two ways of doing things instead of one.

> The overbuilding problem might be a relatively minor issue, but it’s worth noting that the dead money benefit is also small. Only higher-league players play the game with enough precision to necessitate that level of economic efficiency. In other words, Axiom trades a minor advantage for a minor disadvantage. But the disadvantage – overbuilding – affects everyone, not just higher-level players. In fact, lower-league players have much less understanding of how much things cost, making it easier for them to overbuild.

> This is a theme I see throughout Axiom, which I’ll label professional perspective bias. Axiom frequently looks at StarCraft from the angle of top-tier competitive play and then designs accordingly. I don’t find this surprising given that high-level players were [part of](https://www.reddit.com/r/starcraft/comments/75hz2k/tbs_mod_release_date/do6hrtj/) the playtesting team. The problem here is that complexity is relative to your goal – nuances like dead money simply don’t matter for most players, whereas accidentally building more than you can afford affects everyone.

**Comment by MTKing4** [comment]
> This isn't a simple change and it does not necessarily improve the game. A starcraft 2 mod tried it.
> 
> https://illiteracyhasdownsides.com/2017/12/31/axiom-mod-review/
> 
> The relevant section is practically the first issue the guy raises and he explains why it may not be a good idea much better than I can.
> 
> I disapprove.

This is not the same feature that I'm requesting, I'm not asking to change to a streaming economy, you will still pay up front for buildings and Units, the only difference is that for units you only pay for the first unit in the queue

This is not an economy overhaul, meaning you won't have halfbaked Units like in the article, the only possible deadlock that can happen is if you don't have enough money for the next unit, it'll wait until you have it and spends it, which pros already do now, they wait and waste precious time spam clicking till they have enough money to build.

Also btw who are you ingame? I don't recognize your name

**Comment by xezon** [comment]
Ok. Your proposal is better than the Red Alert 3 design. I suspect such feature can be implemented without too many complications. Can be exposed as setting in GameData.ini. Whether players will like it is unclear. Perhaps they do.

**Comment by penfriendz** [comment]
So, let's say you queue up two different units, one from (say) a wf and another from an airfield. Two gatts and two migs.
The first gat and mig produce as normal. You now don't have enough money for a both a gatt and mig. I suppose the gat builds first because it costs less. Actually, you wanted the mig more, so you have to go back and cancel the gat.

The cancellation problem still exists, and I'm not sure it's better than the dead money problem. But yes, it's not so bad.

I'm still kind of against it because it's a significant change to the game - I think far more than a unit change tbh.

**Comment by ImTimK** [comment]
This removes an element of macro management, the moment your production facility is up you can queue 9 techs or vees and don't have to worry about anything. I don't like this. 

It's a skill to keep a steady production when the income is limited.
