### ISSUE TITLE
GLA Saboteur ability button has no practical use

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#2389]
GLA Saboteur ability button has no practical use. The primary attack already performs the saboteur action without pressing that button.

**Comment by penfriendz** [comment]
Worse than no practical use - actually broken. I would attach a file but it's larger than 10MB - posted in discord instead.

**Comment by xezon** [comment]
We can probably just remove the button.

**Comment by xezon** [comment]
Brooks (penfriendz)
> I click and use keyboard shortcut to try to get it to sabotage something. Then I click on the War Factorty with left or right click: nothing happens - it is actually broken. Hijacker button works.

FireArm
> Inf hacker buttons too serve no purpose other than hacking but i think it's good to keep them to let players know that inf hackers have disable ability

kABUSE
> I don't get it, what version has this been tested on? works just fine for me. I wouldn't remove the command button as it is the perfect place to put info of what the ability even does.

**Comment by xezon** [comment]
kABUSE
> I wouldnt remove the command Button. Instead we should add Info Text for each use case of the ability, as it is the most complex ability in the entire Game with three different actions that can be triggered

MTKing
> We can add the info we need on the unit tooltip. We do not have to keep a useless button just for its tooltip.
Something like:
Sabotage Vs:
Refinery: Steals 1K cash
Power Plant: shuts down power for x Seconds
Superweapon: resets timer
CC: resets timer on all Abilities

kABUSE
> The tooltip is better positioned on the ability itself.
Unit description should be something less specific like:
Sabotages buildings
Stealthed, weak against scouts
Can climb

> Point being, in a singleplayer mission for example you might have only a saboteur and no barracks. Not sure about text length limits on tooltips, might also be an issue to fit everything into unit desc.

> And this is actually also an issue: Depending on scripting method, removing button will break some old maps. There are two methods of scripting units to hunt using ability. One of them will break (use command button on named object vs. hunt using command ability)

**Comment by Float1ngFree** [comment]
It should be operational, but primarily it serves as a tooltip placeholder for what's the unit is capable of:

![tooltips](https://github.com/TheSuperHackers/GeneralsGamePatch/assets/17320562/e52a9914-8b3f-4276-a43d-f8048c62a435)

I have similar description in Build unit tooltip, but once it is built, no one will want to go back to barracks and read what it's capable of, right? So you click on unit and see what it can do.

**Comment by xezon** [comment]
Tested with both Saboteurs. Worked. Closing.
