### ISSUE TITLE
Investigate if China Satellite Hack II could get a cooldown timer in UI

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#241]
China Satellite Hack II triggers automatically. But player does know when. This is inconvenient when trying to plan attack for it. USA Satellite works better in that regard, because it is a Generals Power and can be activated on demand. Investigate if something could be done.

**Comment by ExiLe-ZH** [comment]
If it just shows the timer as genpower ability (but still auto activated) that would be good if even possible.

**Comment by ExiLe-ZH** [comment]
Another thing that might be helpful is adding a sound effect when it activates, like happens with gla if you make a radar van.

**Comment by Cryoblooded** [comment]
maybe make it like contra mod u can activate it manually as you like, like the strategy center

**Comment by DoMiNaToRuk2** [comment]
Yes please do this. Much needed
