### ISSUE TITLE
USA Humvee TOW Missile looks different when shooting at airborne targets

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#2421]
USA Humvee TOW Missile looks different when shooting at airborne targets.

**Comment by Float1ngFree** [comment]
Because it is using a PatriotMissile object with ridiculous 10s missile fuel time. Need to make a separate object with adequate stats.

**Comment by xezon** [comment]
Yes. The first step is to create a new object with the same Patriot projectile setup but Humvee missile model. As for tweaking any of the projectile parameters, we need to see carefully, because it affects gameplay.

The large fuel time report is covered with
* #966
