### ISSUE TITLE
Toxin Tunnel tries to target Fuel Air Bomb

### ISSUE THREAD

**Issue by Stubbjax** [TheSuperHackers/GeneralsGamePatch#249]
This is a very minor issue and is likely just a simple case of adding an `UNATTACKABLE` tag somewhere.

https://user-images.githubusercontent.com/11547761/132639403-99c4e5d8-a47f-4fb9-b1b9-72bda61e7f02.mp4

**Comment by xezon** [comment]
It looks cute though :-)

**Comment by xezon** [comment]
@commy2 
Is this fixed by the debris attack fixes you already submitted?

**Comment by commy2** [comment]
No, but it is likely a very similar issue. Will take a look at it and see what else may be affected by this.
