### ISSUE TITLE
Discuss whether or not defense structures (Firebase, Patriot, Gattling, Bunker, Tunnel, Stinger) should block unit sight

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#25]
Units behind defensive structures cannot attack units in front of structure. Should this be changed or not?

**Comment by Jundiyy** [comment]
Nope, there isn't a need for this change and it's too much of a change, also doesn't feel normal to shoot through a building.

**Comment by JoKeRZH429** [comment]
Too much of a change imo & as Jundiyy said, it would look weird

**Comment by ReLaX82** [comment]
Leave it.
