### ISSUE TITLE
Problematic laser tanks

### ISSUE THREAD

**Issue by mrCorat** [TheSuperHackers/GeneralsGamePatch#2522]
Laser tanks - unique unit for  laser general. And in game realities it should give unique gameplay for this general. The nearest in gameplay style is vanilla USA. But there is some properties that makes gameplay in vanilla more preferable, then laser general:

1. Laser tanks requires energy (harder to play by tank spam)
2. No artillery (harder to break huge defense and the longest strike distance have rocket defenders).

And by first property we can't spam much laser tanks, so in any case opponent spam, especially in tanks, better then for laser general. But it core gameplay (included in general physics).
That's why I propose to increase strike distance for laser tanks (more then rocket defenders, less than artillery). I think distance of rocket buggy more real.

**Comment by xezon** [comment]
We have report for USA Laser Tank here along with some proposals.
* TheSuperHackers/GeneralsGameCode#139

I have copied your proposal into TheSuperHackers/GeneralsGameCode#139 and will close this as duplicate, because the subject is similar.
