### ISSUE TITLE
China Nuke Missile does not apply sufficient damage when buildings have a certain distance to the core of the explosion

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#280]
China Nuke Missile does not apply sufficient damage when buildings have a certain distance to the core of the explosion. Reported by Mad Rage.

> The damage is does seems very random. Sometimes it will destroy many buildings and sometimes it does hardly any damage. It often felt a bit like hit or miss. This isnt for gla structures only i feel. The damage dealt to the buildings always felt very random and not predictable

**Comment by commy2** [comment]
Closing as duplicate of https://github.com/TheSuperHackers/GeneralsGamePatch/issues/846, which contains more information.
