### ISSUE TITLE
Nuke China Battlemaster can kill GLA Demo Trap with one shot

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#305]
Nuke China Battlemaster can kill GLA Demo Trap with one shot. Is this a bug or as designed?

**Comment by Madrageeeeee** [comment]
Does a tank battlemaster kill it in 1 shot too? 

Dont think this is too much of a problem tbh. Making it 2 shots or more will only making it more of a micro hassle for nuke and the gla still has to be careful of moving their worker away from the trap anyway. 

Dont think this change will add much to the gamr apart from making the overall play a bit more slow.

And think the slow aspect of 1.06 was one of the main drawbacks. 

I would keep one shot kill on trap for nuke.

**Comment by DoMiNaToRuk2** [comment]
Agree if tank can kill it in one shot too then nuke should too.

or maybe ChinaV is better comparison

**Comment by ECBVovin** [comment]
The tank does not one shot it. The Demo Trap is detonating because its enemy owns the radiation/toxin pool. Add KindOf CLEANUP_HAZARD to the Demo Trap's ignored target types to fix.

**Comment by commy2** [comment]
This should be classified as bug now.

Repro:


https://user-images.githubusercontent.com/6576312/135610257-5c0a16cc-c11d-426d-bf11-82d82d49bc3d.mp4
