### ISSUE TITLE
GLA Toxin Terrorists apply less damage after Gamma Upgrade is acquired

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#31]
GLA Toxin Terrorists apply less damage after Gamma Upgrade is acquired.

Related Terrorist issues:
* TheSuperHackers/GeneralsGamePatch#26
* TheSuperHackers/GeneralsGamePatch#30
* TheSuperHackers/GeneralsGameCode#37
* TheSuperHackers/GeneralsGamePatch#502
* TheSuperHackers/GeneralsGamePatch#503
* TheSuperHackers/GeneralsGamePatch#504

## Proposal 1
Change Toxin Terrorist damage from 700 to 500 before Gamma Upgrade.

## Proposal 2
Change Toxin Terrorist damage from 500 to 700 after Gamma Upgrade.

**Comment by commy2** [comment]
This is very closely related to or rather identical to the bug here: https://github.com/xezon/GeneralsGamePatch/issues/30

**Comment by Jundiyy** [comment]
Wouldn't be the end of the world to fix as they are not used as often by the time you get rank. Although would change something on oil based maps.

**Comment by Madrageeeeee** [comment]
Yeah think the terrorists just need to deal the same amount of damage with or without gamma. 

Wont affect gameplay too much since terrorists arent used that much anyway once palace / gamma is in play like Jundiy said

**Comment by xezon** [comment]
Added 2 proposals to opening post. I am fine with both, but would prefer Toxin Terrorist deal same damage as regular Terrorists (Proposal 1), because Toxin General does not need as good Terrorist. It already got many other perks.
