### ISSUE TITLE
Colonel burton and Demo Jarmen don't notify the enemy when being revealed while placing bombs  

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#322]
this is an inconsistency with other commando units like black lotus giving a spoken notification to the enemy when capturing buildings, burtons, on the other hand, are extremely frustrating to deal with and can turn a china player's life a living hell for not only not getting notified but also has no indication which building has a bomb planted on it resulting in selling your whole base, demo jarmens have that as well but the chances of that happening is smaller

Discuss what can we do about this?

**Comment by Stubbjax** [comment]
I don't see any inconsistency. The notification for having a building captured applies globally, regardless of who is doing the capturing, whereas the other special abilities; Snipe, Knife Attack, Cash Hack and Demo Charge, do not.

The idea behind of most of these abilities is covert infiltration - the utility of which mostly stems from inattentive opponents. Adding notifications for them would significantly limit their worth and would reduce the skill differentiator between an attentive and inattentive player.

**Comment by commy2** [comment]
I'd argue that it would be better if Capture Buildings did not trigger EVA either, but I am not ready for that "big change" in this patch.

**Comment by xezon** [comment]
I don't think this an issue. Burton is Hero unit and placing bomb in covert is one of his main purposes.

**Comment by xezon** [comment]
As designed.
