### ISSUE TITLE
"Build Scorpion Tank"-Button Misspelling

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#327]
The name of the button to build the Demo General's Scorpion Tank is misspelled.

Compare:
```
Chem_Command_ConstructGLATankScorpion
Demo_Command_ConsturctGLATankScorpion
```

Demo Scorpion reads "Consturct".

I am not fully certain changing this will not mess with AI or some mission or something other I am not thinking of. If this is a free change however, I'd do it.

**Comment by Jundiyy** [comment]
I'd presume it would make a difference, when making fun maps, you use the Command Buttons and every letter has to match, otherwise it's not detected.
When scripting AI, Command Buttons are also used so should have the same problem.

**Comment by commy2** [comment]
There're lots of changes that would break heavily map.ini scripted maps. We can't guarantee either way that these work after the patch, which is why the patch must be toggleable easily.
Can you elaborate on commandbutton usage for AI scripting? This is about .scb files I presume.

**Comment by Jundiyy** [comment]
We have reverted the command set changes, I think that's the only problem I saw to break map.ini maps?
Everything else has been changed within the units/building code, so the unit might act a bit different but should work.

I was actually referring to AI per map, I suppose it would also count for the general AI as well.
For example you make a mission map, you want the AI to use a GP somewhere, so you'd order the CC to use the Command Button for that GP. If we change the name, I doubt it would change in WB.
There is already a small problem with Command Buttons in WB and we have to remove the invisible character before using a Command Button. So if a letter is changed, I'd presume it would also result in the button not working.

**Comment by xezon** [comment]
Where is `Demo_Command_ConsturctGLATankScorpion` referenced other than in INI itself?

**Comment by xezon** [comment]
I suggest just add an Alias comment and be done with it.

**Comment by kABUSE1** [comment]
This is a funny one.

As others pointed out this can mess with some custom maps that remove command buttons by addressing them by their native name. There is a drop-down list referencing all command-buttons as they are referenced on ini level. So the demo scorpion command button will be misspelled in that drop down list as well.

![grafik](https://user-images.githubusercontent.com/47530719/236461532-7c24507f-4a74-4f78-8060-b063659e68a7.png)

So people who created a map and selected the command button using that dropdown list will now have that spelling error engraved into the map file and if you fix the spelling error on ini level, this script logic will break. Others might have put the command button name in by hand, ignoring the dropdown spelling error, adding a bug to their map that they are not even aware of,

However, I can literally not think of any map that changes the buildablity of DEMO scorpion tanks. There are some I can think of that disable demo arms dealers, but none I can think of where you are allowed to build demo arms dealer but for some reason not allowed to build demo scorpions.

This is also the case for all singleplayer missions. I can't think of any singleplayer content possibly being affected by this.

I am sure you are safe to fix this without further precautions. Just check that fixed scorpion command button still works as intended.

**Comment by MTKing4** [comment]
Maybe leave the fix for thyme when we can fix the misspelling in WB?
