### ISSUE TITLE
Supply stashes have damage effects but don't take any damage

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#35]
Supply stashes should not have damage effects.

**Comment by commy2** [comment]
What is meant by damage effects? Sparks when hit? If so, seems fine to me. Maybe making them "UNATTACKABLE" is wanted though, because they can't be killed anyway.

**Comment by xezon** [comment]
When shooting stash it looks and sounds as if structure is attacked. I suspect it should look like attacking Terrain if they cannot be destroyed.

**Comment by commy2** [comment]
Can you elaborate? When I tried doing that, my RPG missiles would phase right through the building and only hit the ground below the Supply.

**Comment by xezon** [comment]
Video

https://user-images.githubusercontent.com/4720891/184468587-100e1edb-d328-4e61-94b7-610b721da52c.mp4

**Comment by commy2** [comment]
I don't see it. That explosion noise is from the Tank Hunter rockets. When they fire in synch, they destroy each other (doesn't change damage, projectile keeps flying).

**Comment by xezon** [comment]
I think the main concern is the audio. Check again. There is very distinct difference.

**Comment by commy2** [comment]
Ah, yeah, that is a different noise from what I was thinking of:

https://user-images.githubusercontent.com/6576312/184476532-c545c3b6-38ad-4cbc-aeb4-9b5f1e304fb2.mp4

The issue is StructureDamageFXNoShake.
