### ISSUE TITLE
Boss General does not benefit from the Reinforcement Pad

### ISSUE THREAD

**Issue by Jundiyy** [TheSuperHackers/GeneralsGamePatch#363]
Currently the Boss General will not receive any units after capturing the Reinforcement Pad.

The fix would be to give it a unit, but which?

These vehicles can be currently made from her War Factory
- Paladin Tank
- Gatling Tank
- Dragon Tank
- Avenger
- Overlord Tank
- Tomahawk
- Demo Bike
- Rocket Buggy
- Sentry Drone

The Paladin, Gat, Dragon, Tomahawk and Demo Bikes could be easily used as they are common units for other factions. (Paladin = Crusader for USA.)
Or we can make it a bit more interesting and use a random unit for the Boss since it is the Boss. The Paladin, Gat and Dragon were used for the GameReplays tournament, players would randomly get 1 of the 3 units.

Of course, this might not be desirable as RTS + luck don't go together. Thoughts?

**Comment by commy2** [comment]
Paladin, but kinda weird since you get it even without the Science.
Overlord would look silly.
Idk, i'd say Dragon Tank for the Dragon Rank general...

**Comment by MTKing4** [comment]
something not too strong, standard unit and fitting to the Chinese background of the boss General persona = Gatlin Tank

**Comment by Jundiyy** [comment]
Dragon Tank does seem like a nice fit but at the same time Gat fits 'standard'.
🤔 
Although, it is Boss so do we need to go standard? 😂
