### ISSUE TITLE
USA Hellfire Drone and Scout Drone do not grant XP on kill

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#398]
USA Hellfire Drone and Scout Drone do not grant XP on kill.
USA Battle Drone gives 10 XP.
USA Sentry Drone (vehicle) gives 50 XP.

See also:
* #397

**Comment by commy2** [comment]
Spy Drone (genpower) also gives 0 XP.

**Comment by Jundiyy** [comment]
I think the Sentry Drone shouldn't be included in this, it's a drone but not a vehicle drone that has a parent. The GP Drone shouldn't as well, it's not the same thing.

In CCG, the Battle Drones gave xp and the Scout Drones didn't (as far as I remember), the logical reasoning would be that the Battle Drone attacks and the Scout Drone doesn't.
I presume they forgot to add it to the Hellfire Drone in ZH, unless they planned to reverse it and remove it from the Battle Drone.

I think all 3 suggestions make sense but number 1 seems best.
Although saying that, number 2 would nerf Humvees a bit as it would grant more xp whilst fighting them (xp per drone).

So we could
1. Add xp to the Hellfire Drone.
2. Add for all drones.
3. Remove for all drones.

**Comment by xezon** [comment]
@Generalcamo suggested to create a document with units and XP values to get an overview over XP distribution.

**Comment by Madrageeeeee** [comment]
The hellfire drone is also quite expensive remember. So killing a vee with hellfire would be a 1200 dollar kill (or 1350 for swg). 

And perhaps to consider: does killing the vee and thereby the hellfire also grant you xp for both? 

Xp for sentry drone kill makes sense. 

Perhaps its nice to give xp for drone kills but not give xp for a drone kill if only the parent vehicle is killed?

**Comment by commy2** [comment]
Killing the parent vehicle does not give XP for the drone, and I think it is good that way.
