### ISSUE TITLE
Should all tech buildings give xp? 

### ISSUE THREAD

**Issue by Jundiyy** [TheSuperHackers/GeneralsGamePatch#406]
Currently 3 Tech Buildings give xp:
Repair Bay
Repair Pad
Reinforcement Pad

The following do not:
Oil Derrick
Oil Refinery
Hospital
Artillery Platform

Should xp be added to all or removed?

**Comment by Madrageeeeee** [comment]
Dont have too much of an opinion on this although i do feel the reinforcement pad is a weird building

it has total crapp hp, for some factions it gives crapp units and it gives tons of xp when killed. Seems not right.

if anything i would perhaps make the artillery platform give xp.

On the other hand: what i like about the capture buildings if that they are a ‘free extra’ if you take the effort to capture them.

Giving hp formkilling them takes away from them being a nice extra since they may now vet up your opponent.

**Comment by Jundiyy** [comment]
Do agree with the Reinforcement Pad, would feel too much of a change I think but I would prefer it to have more hp or drop off per minute (which is the case of some mods), that way you at least get something out of it before it is destroyed. Quicker drops or it lasts longer.

Another thing which is quite a big change is to give fair units to all armies, we did discuss this in the old 1.04+ discord server and Legionnaire thought of the following:

all USA: Ambulance
all GLA: Quad
all China: Dragon Tank

But we didn't do this as it's quite a big change and thought it could be done near the end once the patch has a bigger following.

-------------

And yea, also felt xp for Artillery Platform made sense, even if other ones don't have it.

I don't mind both ways although I think it can be more fun with them giving xp as they also become a tactical reason to destroy (allow enemy to capture first and destroy straight after) and also have to be thought over a bit more before capturing as they could be destroyed a second later.

**Comment by RisingZH** [comment]
Should be consistent, so either all do or all don’t. 

I can see an argument for both sides and have no strong feelings either way, I think it would be least impactful to remove the xp from the ones that currently do.

**Comment by xezon** [comment]
Current state in 'main' branch is all XP from tech buildings is removed.

**Comment by xezon** [comment]
Above I wrote on main branch XP was removed. Which change was this?

**Comment by Jundiyy** [comment]
This topic was to ask if xp should be added to all tech buildings or not. I do feel it's nice that they give xp, perhaps not 200, maybe 50. Adds more fun to the game.

**Comment by commy2** [comment]
@xezon https://github.com/TheSuperHackers/GeneralsGamePatch/pull/308/files

**Comment by Pekaman** [comment]
I would say giving military tech buildings like arty platform and reinforcement pad should give xp and all others being civilian should not give xp.

**Comment by fastAiRR** [comment]
there was a cool game I watched once where Scuba had nothing left but had something like 4,999 xp lmao. He capped a building and got 5 star, it was pretty nice. If I remember correctly

**Comment by commy2** [comment]
This issue is about them granting XP when destroyed. They will grant XP for being captured regardless, because that is just a property of basic Infantry / Black Lotus that applies to all buildings equally.

**Comment by penfriendz** [comment]
I am strongly against tech buildings giving xp. They're often placed in contested areas and capturing them can be a net negative. In my mind there should only be a reward for taking the risk to capture them in the first place.

**Comment by xezon** [comment]
Giving reward for kill would encourage players to destroy these buildings more often. With no kill reward, there is less incentive for kill and Tech buildings may be contested for longer periods of time, which makes the game richer for it.

**Comment by MTKing4** [comment]
Remove XP Reward

**Comment by xezon** [comment]
Tech Buildings grant no XP for kill like any other Civilian structure.

**Comment by MTKing4** [comment]
This is a mistake, Why close? This issue is proposing one of two solutions and we agreed on one, removing XP, there are tech buildings that need that feature removed

**Comment by MTKing4** [comment]
You can change the title for the issue i guess to "Remove XP Reward" and then follow it up with a proper PR

**Comment by xezon** [comment]
This was done already
* #308
