### ISSUE TITLE
Fix USA Spectre to be selectable by Q (Select All Units)

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#41]
Fix USA Spectre to be selectable by Q (Select All Units)

Add `IGNORES_SELECT_ALL` to `KindOf`

**Comment by Madrageeeeee** [comment]
This also goes for WW (select all aircraft) super annoying. If ‘w’ would select it while in screen that could be ok, so you can readjust the turret but it doesnt make sense you select the gunship when not even having it in your screen. This screws up your targeting of the gunship and makes your raptors useless for you cant target units when you have selected the gunship

**Comment by commy2** [comment]
Was already fixed: https://github.com/xezon/GeneralsGamePatch/pull/181
