### ISSUE TITLE
China Black Lotus does not get XP for attacking vehicles

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#416]
China Black Lotus does not get XP for attacking vehicles. Lotus will get XP for Cash Hack and Building Capture however. Lotus practically never reaches Vet 1, 2 or 3 in any regular Multiplayer match.

Note: GLA Jarmen Kell gets no XP for Vehicle attack either.

See also:
* #399
* #415

**Comment by commy2** [comment]
You could disable one vehicle out of reach of your enemy and grind on it infinitely. Would not change this.

**Comment by commy2** [comment]
According to Jundiyy, Lotus passes XP to the player as well, meaning that the above tactic could be even worse.

**Comment by Jundiyy** [comment]
Maybe a misunderstanding, she passes xp over for the ones she receives for only. So she gets it for cap building and cash hack and so does the player.

Coming to this issue itself, I don't think it's a needed one.
Would prefer to keep original if not needed. 
Although not totally against it as well.

-----
Edit: okay so you meant if we enable xp for vehicle hack then the player will get it.

**Comment by Stubbjax** [comment]
> 
> 
> You could disable one vehicle out of reach of your enemy and grind on it infinitely.

Which would require a lot of micro / attention as well as an inattentive opponent. Players can already achieve the same effect with GLA buildings by continuously destroying them to a hole and letting them rebuild. Nobody really has time for these things at the highest levels of gameplay where a change like this really matters.

**Comment by xezon** [comment]
That would be similar to abusing the GLA Sneak Attack for Neutron attacks. It's a valid point. See
* #361

**Comment by Madrageeeeee** [comment]
Wouldnt change really, not a big problem of the game i feel

**Comment by MTKing4** [comment]
Could we implement it for testing anyway to see how effective it is? With the jarmen addition as well

**Comment by commy2** [comment]
Will do.

**Comment by ExiLe-ZH** [comment]
What is even the advantage of a vetted Lotus? Only giving off more XP when shes killed?

**Comment by xezon** [comment]
More health and self heal I think. Maybe faster capture too?

**Comment by ZekeDlyoung** [comment]
Not faster capture, just more health and auto-heal

**Comment by xezon** [comment]
Would it be possible to change capture times on veterancy?

**Comment by ExiLe-ZH** [comment]
> Would it be possible to change capture times on veterancy?

That would make Super Lotus OP though if vet 2 & 3 make her even faster

**Comment by xezon** [comment]
Depends how fast. 3 Star Jarmen also shoots faster right?

**Comment by ExiLe-ZH** [comment]
> Depends how fast. 3 Star Jarmen also shoots faster right?

It's gonna be faster than currently and that's too fast. 

Currently it's already hard to react in time if alot is going on, with some lag it's sometimes impossible to sell off your buildings even, even if you respond instantly.

Or you need to nerf current speed, but not a fan of that.

**Comment by xezon** [comment]
Personally I never had issues selling vs Lotus. But that may be just me then.

**Comment by ExiLe-ZH** [comment]
> Personally I never had issues selling vs Lotus. But that may be just me then.

Guess you haven't experienced a mrs super lotus in your base under laggy circumstances then?

Or regularly play opponents who challenge your multitasking skills? 

Trust me, it can be hard and stressy and any faster would be OP.

**Comment by ZekeDlyoung** [comment]
No need to argue about it, as it is not really possible since capture building is an ability not a weapon

**Comment by xezon** [comment]
This was addressed. Black Lotus now gains XP with vehicle attacks.
