### ISSUE TITLE
Hijackers can be run over by Migs that are leaving the air field.

### ISSUE THREAD

**Issue by MSK0306** [TheSuperHackers/GeneralsGamePatch#419]
Potentially other stealth units may be run over too, must be checked.

**Comment by Stubbjax** [comment]
All aircraft can hit all infantry (aside from heroes), which makes sense. I don't see how this is an issue?

**Comment by commy2** [comment]
Aircraft also run over infantry when they are shot down and crash onto them.

**Comment by xezon** [comment]
Thank you for your issue report. Wont fix.
