### ISSUE TITLE
GLA Terrorist suicide particle effects looks more spectacular in Generals

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#424]
**Generals**
![sshot005](https://user-images.githubusercontent.com/4720891/135156299-b13192c4-b026-4dcc-b25b-6fa8d45246fa.jpg)

**Generals Zero Hour**
![sshot004](https://user-images.githubusercontent.com/4720891/135156363-5388178b-8a2b-499c-9445-2a8ab2447f8b.jpg)

**Comment by xezon** [comment]
Note: The terrorist model is irrelevant to the particle.

**Comment by Madrageeeeee** [comment]
Think they are both kinda cool

**Comment by Generalcamo** [comment]
From what I can tell: The `HotPillarArms` particle called in `WeaponFX_SuicideDynamitePackDetonation` is missing in ZH. Investigating now.

**Comment by ExiLe-ZH** [comment]
ccg explosion looks better to me aswell

**Comment by xezon** [comment]
Related to 
* #543
