### ISSUE TITLE
USA Colonel Burton uses Sentry Drone fire sound instead of Burton fire sound

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#446]
USA Colonel Burton uses Sentry Drone shooting sound instead of Burton shooting sound.

**Comment by MTKing4** [comment]
This one i like, vgen sound is much better and makes more sense to have

**Comment by kajxqeirscl** [comment]
I see no reason to not fix this. Why is this not done already?
