### ISSUE TITLE
GLA Saboteur can be used to detect Fake GLA Markets

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#455]
GLA Saboteur can be used to detect Fake GLA Markets. Should GLA Saboteur be able to steal cash from GLA Black Market and USA Supply Drop Zone?

**Comment by commy2** [comment]
This does not work with the Stealth General Saboteur, since he cannot enter any Fake buildings. As reverse though, that is how you can tell apart fake and real factories, supplies and command centers as Stealth General.

**Comment by Madrageeeeee** [comment]
think that sounds like a nice trick to tell them apart. Not really abusable in competitive matchplay id say. and if you do take the effort its a nice trick.

allowing them to steal cash from secondary eco kinda makes sense and increases their usefulness

**Comment by commy2** [comment]
Fixed by the combination of https://github.com/TheSuperHackers/GeneralsGamePatch/pull/547 and https://github.com/TheSuperHackers/GeneralsGamePatch/pull/544.

**Comment by ExiLe-ZH** [comment]
> think that sounds like a nice trick to tell them apart. Not really abusable in competitive matchplay id say. and if you do take the effort its a nice trick.
> 
> allowing them to steal cash from secondary eco kinda makes sense and increases their usefulness

In team games it could be quite useable I would say, it just costs $800 to do so, but it would help your USA (or China) mate alot to determine where Genpowers should be used.
