### ISSUE TITLE
Fix USA Sentry Drone attack issues

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#46]
When ordering one or more Sentry Drones to attack an enemy unit, they often just don't attack at all. Or move straight to the enemy unit without firing at the first possible chance.

**Comment by commy2** [comment]
The Sentry Drone has an invisible deploy mode similar to the Nuke Launcher. It takes 1 second of standing still to transition between movement mode and attack mode, and by clicking fast, you can get stuck deploying and undeploying in a loop.

One way to fix this is to reduce the deploy time (e.g. 500 msec) which from messing around with it feels much better.
See https://github.com/commy2/zerohour/commit/a67c0d3c14817d149ed27d12891dbe8d5aa56f2b

Another option is to remove the packing time completely.

**Comment by commy2** [comment]
Closing as duplicate of https://github.com/TheSuperHackers/GeneralsGamePatch/issues/862. The newer issue contains more information.
