### ISSUE TITLE
Should the LAN Countdown of 5 seconds be decreased?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#461]
Should the LAN Countdown of 5 seconds be decreased? Multiplayer Game Room has no Countdown at all. Maybe Network does not need one either?

**Comment by Haubibban** [comment]
Note: minimal possible countdown for LAN is 1 second. Making it 0 will cause massive game instability during map transfer.

**Comment by RisingZH** [comment]
I think it is good as it is, just gives people a little more time to get ready.

**Comment by leex279** [comment]
Why they need time to get ready if they already accepted? But I think 3 would be a good standard.

**Comment by FinAminToastCrunch** [comment]
Leave it be.
