### ISSUE TITLE
Should the Multiplayer Disconnection Timeout of 60 seconds be increased?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#462]
Should the Multiplayer Disconnection Timeout of 60 seconds be increased? Is there any benefit to prolonged or shortened waiting times?

**Comment by EnigmaZift** [comment]
Prolonged disconnection timers give a longer window to people reconnecting. However I think a minute is already pretty massive, and if you haven't reconnected in a full minute, chances are you're fully disconnected. As always, you can just vote them out if you want.
There might be more to it than that but that's my 2c

**Comment by RisingZH** [comment]
I think something like 40 secs is sufficient, a minute can already be very painful (if you know someone has aborted out of gameranger for example). Certainly wouldn’t increase.

**Comment by leex279** [comment]
I´m with RisingZH here. Think 60 sec is to much. Often other players just dont kick and its annoying waiting that long. Also for me I cant remember someone coming back after more then 20 seconds.
