### ISSUE TITLE
Should China Helix with Gattling Cannon be able to attack air units?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#463]
Should China Helix with Gattling Cannon be able to attack air units? In Zero Hour 1.04 it can attack and kill air units, but only when it is perfectly angled towards enemy air craft. This behaviour currently has been removed via:
* #284

https://user-images.githubusercontent.com/4720891/135819645-90fc754b-45b9-4830-a03c-818096bdb9c0.mp4

**Comment by MTKing4** [comment]
It's also important to note that helix is shooting from the bottom of its hull not from the Gatling itself, if this change ever makes the cut, this should be fixed as well

**Comment by ExiLe-ZH** [comment]
Didn't even know it could do this haha. I'm not sure if this will the hurt the balance though or whether it changes the game too much?

It would be nice to give the Gatlix a broader purpose. Right now it's only used for early game rushes and stealth detection. Would be funny if it could battle stealth Commanches :D (it detects stealthy air units too?), this kinda breaks the single unit spam meta as AFG needs Raps then aswell. That said, China's anti-air capability is already proficient. 

It might also be OP when it can target Chinooks, like I can imagine BO's where China goes WF+AF and harasses both supplies, which might be hard to counter before Tow-Missiles.

I'd like to test this though.

> It's also important to note that helix is shooting from the bottom of its hull not from the Gatling itself, if this change ever makes the cut, this should be fixed as well

Would like to see this fix aswell, but isn't it done to prevent targeting bugs? It already sometimes bugs out if a unit is right beneath the Lix.

**Comment by commy2** [comment]
> it detects stealthy air units too?

Yes, Helix Gatling will detect any stealthed units, including Stealth Fighters and AFG Stealth Comanches.

**Comment by MTKing4** [comment]
> Would like to see this fix aswell, but isn't it done to prevent targeting bugs? It already sometimes bugs out if a unit is right beneath the Lix.

wouldn't call it a bug, more like the unit is out of shooting angle of the Gatling cannon, also it only shoots like that when bugged like in the vid above, it shoots properly in normal conditions

**Comment by MTKing4** [comment]
btw also i feel like this change would be consistent with the inf helix change, since then both will be able to target air units = more viable and less unfair for the other chinas vs inf

**Comment by xezon** [comment]
@ImTimK
China needs buffs compared to 1.04.

@MTKing4 
Good point regarding making it able to compete with Infantry Helix.

**Comment by ExiLe-ZH** [comment]
> @ImTimK China needs buffs compared to 1.04.
> 

1.04p changes already do that by making already existing meta strategies more efficient (for weaker armies like China V).

I’m not excluding these kind of changes right off the bat, but the outcome is unpredictable and possibly meta changing. Which can bring it’s own complications.

Again, we can test this, but the first point I mentioned is the preferred approach of balancing things.

**Comment by EnigmaZift** [comment]
My opinion: Fix it. It's clearly intentional and not working correctly.
-Enigma

**Comment by xezon** [comment]
The change by commy2 technically works well. Helix can attack air units. However it is quite strong in its current form. The attack range is very high.

Enlima29:
> In ZH the Overlord and Helix Gatling addons still use the same weapons as the Gatling Turret defense, no wonder the ranges are fanstastic. I already reduced gatling addons weapon ranges in my mod, that's why I thought it's fine. For helix gatling AA specifically, I think the impact feels greater because they use the gatling building AA range while attacking from the air as well. So Gatling addons weapon need some nerfs regardless.

> AA ranges:
> MD, RPG, tankhunter -> 175
> avenger -> 300
> quad -> 350
> gat.tank -> 350
> patriot -> 350 (450 if relayed)
> gat.cannon -> 400
> stinger -> 400

> I think it greatly changes the game dynamic because there were no real air-to-air weapons in the game beside the fighter jets weapons. Even they have great ranges because they are constantly moving around quickly, so they need such range to make their combat function properly. Same goes with AA weapons, because they are meant to target the fast moving aircrafts. Choppers however, were able to move and station on the air more freely than the planes, and in vGen there is only sole comanche that is the combat helicopter that cannot attack air. When ZH introduced Helix with overlord-like gatling addon this brings the issue I guess.

I think the proposed changes to Infantry Helix and Gattling Helix should be tested well and considered for balancing. This could be the Buff China needs to have better chances vs USA. Vs GLA this Helix Change is irrelevant. USA is very strong vs China. With Helix being able to attack Chinooks, it can add new opportunities for China to harass more efficiently and force USA to be more cautious. It may even force USA to build some Raptors, which is good for unit diversity and would get away from the One Army - One Vehicle spam idiom.

But yeah, the ranges, right now, look too high. Minigunner Helix and Gattling Helix probably should have a bit smaller ranges.

**Comment by commy2** [comment]
Minigunner -> 350 (465.5 if inside Bunker, Civilian Building or Helix)
Humvee Tow Missile -> 320 (384 if Search & Destroy)
Avenger -> 300 (360 if Search & Destroy)

Note that Stinger Sites, due to their slave logic, only engage at 400 range after any air target moved into range of 225 first. Then they actually have 400 range until they switch targets to a ground unit again.

**Comment by commy2** [comment]
Another note, Overlord Gatling may have 400 range, but the Overlord only has 200 shroud clearing (even after the Gattling turret upgrade), so the full range can only be used when scouting units like Tank Hunters (400 shroud clearing) or LOutposts (500 shroud clearing) are nearby.

Helix on the other hand has 600 shroud clearing, so it can make full use of all the range by itself.

**Comment by Stubbjax** [comment]
> 
> Note that Stinger Sites, due to their slave logic, only engage at 400 range after any air target moved into range of 225 first. Then they actually have 400 range until they switch targets to a ground unit again.

Also note that Minigunners do the same thing.

**Comment by commy2** [comment]
Not entirely. Only when inside buildings or units; and by manual targetting, you can make them shoot anyway, which is not allowed for Stinger Sites.

**Comment by Stubbjax** [comment]
> 
> 
> Not entirely. Only when inside buildings or units; and by manual targetting, you can make them shoot anyway, which is not allowed for Stinger Sites.

I've observed minigunners standing on the ground and not picking up aircraft targets until they're basically within their ground attack radius.

**Comment by xezon** [comment]
Which makes me wonder if this is desired design. Should we have a separate report for that? Aka should units have an engage range much shorter than the attack range?

**Comment by ExiLe-ZH** [comment]
> Which makes me wonder if this is desired design. Should we have a separate report for that? Aka should units have an engage range much shorter than the attack range?

Deliberate design right? AA would otherwise be OP where it starts shooting incoming air from long range, or if you make the range shorter then returning air units get away easier. Messing with this will change the whole balance.

**Comment by RisingZH** [comment]
I don’t think I would consider this a bug, as the gattling cannon is underneath the helix it seems logical that it wouldn’t be able to shoot air units.

I think I would need to play quite a lot of games with this change to give an informed opinion on whether it is beneficial for gameplay however my initial thought is that it wouldn’t be (being too op vs migs being one reason).

**Comment by MTKing4** [comment]
@RisingZH we have made some tests regarding gatlixes and minigunner helix Targeting air units, please check #573 for the test footage when you can (just click on the number it will lead you there)

**Comment by xezon** [comment]
I would like to go ahead and submit a functional Helix Anti Air Gattling to main branch. The Anti Air range should be reasonable, so it does not outgun Jets before they can shoot. The damage output should be reasonable as well, so that it does not shred a full Helix with 5 Rocket Men quicker than the 5 Rocket Men do. Whether or not this change is any good, we will have to see in testing. Now is the time to test. For GLA this change has no relevance. It will make China better against USA. And it will also impact China vs China gameplay.

**Comment by Jundiyy** [comment]
I don't think it should be done. Having Helix shooting air units is quite some change.

**Comment by ExiLe-ZH** [comment]
I predict BIG meta change vs USA, where you gonna see Gatlix and fast Tow Missile builds in every single game.

I'd still like to test this, but it might make the MU very one dimensional.

**Comment by xezon** [comment]
If the change makes it unplayable we can revert. We can also give Helix Gattling Cannon lower damage vs Air, so it takes long to kill Chinook.

**Comment by Jundiyy** [comment]
Whilst I do see it as an advantage for China, I just think it's too much of a change from original game. Don't think we should go down this route.

**Comment by xezon** [comment]
Helix can attack Air units in Original game. So this is nothing new.

**Comment by Jundiyy** [comment]
That isn't a reasonable answer, I can't really believe that answer from yourself. It can attack, but it's not used for it, and if someone did, it would be counted as bug abuse. 
How can we say this is not something new?

If the bug was common knowledge to all and was being used, then we could say it's not something new and code it to work properly.

**Comment by xezon** [comment]
You make reasonable argument. However, factually Helix can destroy Aircraft in Original Game. Now, it cannot anymore. We essentially made China weaker because of it.

The proposal here is to implement it properly, and then test if it play any good or not.

I understand you have concern, and I share concern, however I want to look at practical evidence, not theory.

**Comment by ExiLe-ZH** [comment]
> You make reasonable argument. However, factually Helix can destroy Aircraft in Original Game. Now, it cannot anymore. We essentially made China weaker because of it.
> 
> 
> 
> The proposal here is to implement it properly, and then test if it play any good or not.
> 
> 
> 
> I understand you have concern, and I share concern, however I want to look at practical evidence, not theory.

In earlier patches? Not in ccg, lix is zh unit only?

**Comment by xezon** [comment]
In Zero Hour 1.04 helix can kill air. See video in first post here.

**Comment by Jundiyy** [comment]
@ImTimK, No, he means in this version, 1.04, but it's a bug. It can happen automatically but rare as the conditions are harder, can also force it to happen.

@xezon I understand your point, I get why you're proposing it, but I think it doesn't make China weaker because it's something which they can't do anyway, meaning against the rules.
Not the best example, but Scud Bug weakens GLA if we don't allow it, but we know it's a bug and they aren't meant to be doing it.

In this case, this is also a bug, it's not meant to happen, so China isn't weakened at all. Since they are not allowed/meant to do it.

**Comment by ExiLe-ZH** [comment]
> In Zero Hour 1.04 helix can kill air. See video in first post here.

Saw video already, didn't convince me it's an intended feature.

Vee machine gun also sometimes shoots air units.

**Comment by MTKing4** [comment]
@Jundiyy @ImTimK

We have already made thorough testing commy and i, check #573 if you haven't already.

I think there's no harm in testing it in actual matches and see how it goes, we can talk all day, but nothing's more concrete than a practical test.

**Comment by Jundiyy** [comment]
Nothing to do with testing. You're not understanding. I'm not talking about balance here.
It's a new feature, new because it's not allowed and not meant to be in the game, and now we are making it part of the game.
We might as well add in many features and say, 'let's try them, they might make x y and z better'.

We should stick to original game as much as possible, and giving Helix anti air isn't. This isn't a needed thing.

**Comment by MTKing4** [comment]
> Nothing to do with testing. You're not understanding. I'm not talking about balance here. It's a new feature, new because it's not allowed and not meant to be in the game, and now we are making it part of the game. We might as well add in many features and say, 'let's try them, they might make x y and z better'.
> 
> We should stick to original game as much as possible, and giving Helix anti air isn't. This isn't a needed thing.

This doesn't go against my argument, we did agree that we'd try everything and willing to do anything to improve the game, even new features, and this is not the only feature that has been suggested, but none of them mean they'll be in the game, implementing this is not only a balance test, it is an acceptability test as well, if people like the new change, who are we to deny them that?

**Comment by MTKing4** [comment]
Just want to be clear here, i don't mind not having this in the game and i understand jundiyy's point and it is a valid one, I'm just interested to see how will people perceive this and what kind of impact will it have on the game, because i think it might be positive.

**Comment by RisingZH** [comment]
Would be fun to test but feel like this would just turn cvu into dual af gatlix spam.

**Comment by MTKing4** [comment]
> Would be fun to test but feel like this would just turn cvu into dual af gatlix spam.

This will already happen vs inf, because inf helix can now target air units manually after the mini gunner bug fix here #342

**Comment by Jundiyy** [comment]
> Just want to be clear here, i don't mind not having this in the game and i understand jundiyy's point and it is a valid one, I'm just interested to see how will people perceive this and what kind of impact will it have on the game, because i think it might be positive.

Yep same, I'm only saying no because of wanting to keep it as original as possible, otherwise if it was another patch which was freestyle or a mod, I would warmly welcome it. That is why I do play mods/other patched, because I do enjoy new things, I actually prefer newer things.

And yes, agree to try things, but I wouldn't agree to new features that are off. The IC scan for example, it's basically the same thing but with a button, hence I don't mind it.

But yea, I think we've both explained enough lol, I don't have anything else to add.

**Comment by MTKing4** [comment]
> > Just want to be clear here, i don't mind not having this in the game and i understand jundiyy's point and it is a valid one, I'm just interested to see how will people perceive this and what kind of impact will it have on the game, because i think it might be positive.
> 
> Yep same, I'm only saying no because of wanting to keep it as original as possible, otherwise if it was another patch which was freestyle or a mod, I would warmly welcome it. That is why I do play mods/other patched, because I do enjoy new things, I actually prefer newer things.
> 
> And yes, agree to try things, but I wouldn't agree to new features that are off. The IC scan for example, it's basically the same thing but with a button, hence I don't mind it.
> 
> But yea, I think we've both explained enough lol, I don't have anything else to add.

This just reminded me, this was a response to minilix being able to target air units manually after the minigunner bug, so this change wasn't out of the blue.

If it was up to me, if gatlix can't have this advantage, then so shouldn't the minilix, because either of them WILL change the Air meta.

**Comment by Jundiyy** [comment]
I wouldn't want Minilix to have this as well tbh.

**Comment by MTKing4** [comment]
It has been merged to main, discuss here #357 
Also check #342 and #573

**Comment by ExiLe-ZH** [comment]
> > Would be fun to test but feel like this would just turn cvu into dual af gatlix spam.
> 
> This will already happen vs inf, because inf helix can now target air units manually after the mini gunner bug fix here #342

He means dual airfield gatlix spam vs usa, which I also think what the meta might become (or wf+af).

**Comment by ExiLe-ZH** [comment]
Another thing that it might become OP is vs Comanches. Only need 1 in your (mate's) base if outer perimeters are well sealed vs Raptor counter.

**Comment by MTKing4** [comment]
> > > Would be fun to test but feel like this would just turn cvu into dual af gatlix spam.
> > 
> > 
> > This will already happen vs inf, because inf helix can now target air units manually after the mini gunner bug fix here #342
> 
> He means dual airfield gatlix spam vs usa, which I also think what the meta might become (or wf+af).

I know what he meant, I'm saying that a similar thing will happen with inf regardless of this change, because inf lixes can now target air units

**Comment by MTKing4** [comment]
> Another thing that it might become OP is vs Comanches. Only need 1 in your (mate's) base if outer perimeters are well sealed vs Raptor counter.

That would be considered a counter then would it? ^^
Vs OP Comanches, you'd need something to take out the gatlix before going in, actually good point. I like that :)

**Comment by ExiLe-ZH** [comment]
> > > > Would be fun to test but feel like this would just turn cvu into dual af gatlix spam.
> > > 
> > > 
> > > This will already happen vs inf, because inf helix can now target air units manually after the mini gunner bug fix here #342
> > 
> > 
> > He means dual airfield gatlix spam vs usa, which I also think what the meta might become (or wf+af).
> 
> I know what he meant, I'm saying that a similar thing will happen with inf regardless of this change, because inf lixes can now target air units

Which matchup do you mean with what exact BO change? I don't understand the correlation?

**Comment by MTKing4** [comment]
Inf Vs USAs
Inf Lix can now target Air units, you can Have minigunners in it, and click on the chinook and it will take it down. That was introduced with #357

**Comment by ExiLe-ZH** [comment]
> > Another thing that it might become OP is vs Comanches. Only need 1 in your (mate's) base if outer perimeters are well sealed vs Raptor counter.
> 
> That would be considered a counter then would it? ^^ Vs OP Comanches, you'd need something to take out the gatlix before going in, actually good point. I like that :)

So you realize how much that changes things right? Like you don't even need Gats or Quads to defend your base, just 1 unit that detects and kills the Commies and all you need to do is prevent that Rap of flying into your base. Which isn't a difficult task at all, especially if your base is quite big.

**Comment by ExiLe-ZH** [comment]
> Inf Vs USAs Inf Lix can now target Air units, you can Have minigunners in it, and click on the chinook and it will take it down. That was introduced with #357

Yea that's true, Inflix might become overly effective vs USA's.

**Comment by MTKing4** [comment]
> > > Another thing that it might become OP is vs Comanches. Only need 1 in your (mate's) base if outer perimeters are well sealed vs Raptor counter.
> > 
> > 
> > That would be considered a counter then would it? ^^ Vs OP Comanches, you'd need something to take out the gatlix before going in, actually good point. I like that :)
> 
> So you realize how much that changes things right? Like you don't even need Gats or Quads to defend your base, just 1 unit that detects and kills the Commies and all you need to do is prevent that Rap of flying into your base. Which isn't a difficult task at all, especially if your base is quite big.

Yes it does change change things quite a bit, but you do have King Raptors though, and it's air we're talking about, with so many choices, Promotions taking down defenses etc, also one Combat Chinook can take it down btw, so you could have that comboed with your commies to counter the Gatlix, but still, only test can tell, since this is an uncharted territory.

**Comment by ExiLe-ZH** [comment]
You guys gonna like this one: 

Give Comanches Anti-Air Machinegun/Rockets aswell :D

**Comment by MTKing4** [comment]
> > Inf Vs USAs Inf Lix can now target Air units, you can Have minigunners in it, and click on the chinook and it will take it down. That was introduced with #357
> 
> Yea that's true, Inflix might become overly effective vs USA's.

Yes, it's even beats gatlixes by a mile, since btw, gatlixes do have a weakness, coming to them from the side, where the orientation of their gatling is on the wrong side, and constantly kiting it away makes it very easy to take down. Proven by tests

**Comment by MTKing4** [comment]
> You guys gonna like this one:
> 
> Give Comanches Anti-Air Machinegun/Rockets aswell :D

They're already strong enough though :D
And all USAs are in general. Chinas are not, with few options

**Comment by ExiLe-ZH** [comment]
> > > > Another thing that it might become OP is vs Comanches. Only need 1 in your (mate's) base if outer perimeters are well sealed vs Raptor counter.
> > > 
> > > 
> > > That would be considered a counter then would it? ^^ Vs OP Comanches, you'd need something to take out the gatlix before going in, actually good point. I like that :)
> > 
> > 
> > So you realize how much that changes things right? Like you don't even need Gats or Quads to defend your base, just 1 unit that detects and kills the Commies and all you need to do is prevent that Rap of flying into your base. Which isn't a difficult task at all, especially if your base is quite big.
> 
> Yes it does change change things quite a bit, but you do have King Raptors though, and it's air we're talking about, with so many choices, Promotions taking down defenses etc, also one Combat Chinook can take it down btw, so you could have that comboed with your commies to counter the Gatlix, but still, only test can tell, since this is an uncharted territory.

In fact it just happened in a 3v3 I played, where Excal made Bunkerlixes as Commie Counter (+ few Gats & Outposts for detection spread around aswell). Raps and Commies had no chance to do anything. 

Now Gatlixes make that strat a whole lot easier, don't even need Outposts either. How are Raps gonna kill multiple?

**Comment by MTKing4** [comment]
> > > > > Another thing that it might become OP is vs Comanches. Only need 1 in your (mate's) base if outer perimeters are well sealed vs Raptor counter.
> > > > 
> > > > 
> > > > That would be considered a counter then would it? ^^ Vs OP Comanches, you'd need something to take out the gatlix before going in, actually good point. I like that :)
> > > 
> > > 
> > > So you realize how much that changes things right? Like you don't even need Gats or Quads to defend your base, just 1 unit that detects and kills the Commies and all you need to do is prevent that Rap of flying into your base. Which isn't a difficult task at all, especially if your base is quite big.
> > 
> > 
> > Yes it does change change things quite a bit, but you do have King Raptors though, and it's air we're talking about, with so many choices, Promotions taking down defenses etc, also one Combat Chinook can take it down btw, so you could have that comboed with your commies to counter the Gatlix, but still, only test can tell, since this is an uncharted territory.
> 
> In fact it just happened in a 3v3 I played, where Excal made Bunkerlixes as Commie Counter (+ few Gats & Outposts for detection spread around aswell). Raps and Commies had no chance to do anything.
> 
> Now Gatlixes make that strat a whole lot easier, don't even need Outposts either. How are Raps gonna kill multiple?

Do you have the replay for that? Would be nice to analyze that. But yeah i don't disagree, if done correctly it's hard to counter, Unless a new meta evolves and finds a way.

**Comment by ExiLe-ZH** [comment]
> > > > > > Another thing that it might become OP is vs Comanches. Only need 1 in your (mate's) base if outer perimeters are well sealed vs Raptor counter.
> > > > > 
> > > > > 
> > > > > That would be considered a counter then would it? ^^ Vs OP Comanches, you'd need something to take out the gatlix before going in, actually good point. I like that :)
> > > > 
> > > > 
> > > > So you realize how much that changes things right? Like you don't even need Gats or Quads to defend your base, just 1 unit that detects and kills the Commies and all you need to do is prevent that Rap of flying into your base. Which isn't a difficult task at all, especially if your base is quite big.
> > > 
> > > 
> > > Yes it does change change things quite a bit, but you do have King Raptors though, and it's air we're talking about, with so many choices, Promotions taking down defenses etc, also one Combat Chinook can take it down btw, so you could have that comboed with your commies to counter the Gatlix, but still, only test can tell, since this is an uncharted territory.
> > 
> > 
> > In fact it just happened in a 3v3 I played, where Excal made Bunkerlixes as Commie Counter (+ few Gats & Outposts for detection spread around aswell). Raps and Commies had no chance to do anything.
> > Now Gatlixes make that strat a whole lot easier, don't even need Outposts either. How are Raps gonna kill multiple?
> 
> Do you have the replay for that? Would be nice to analyze that. But yeah i don't disagree, if done correctly it's hard to counter, Unless a new meta evolves and finds a way.

https://gentool.net/data/zh/2022_07_July/29_Friday/%5bOoE%5dExCaL_3B4432E8102C/21-55-04_3v3_HuMMi_OoEExCaL_EXSquad_SUPExiLe_SUPRezno_akaGoaTs.rep

**Comment by MTKing4** [comment]
Ok i just checked the replay and here are my points:

1. Air was in unwinnable situation regardless of the lixes, He was Hunted, with No airfields, only commies and vs Two players with CCs and hundreds of gats and outposts, yet despite all that, commies alone did soo much, taking out expansions etc, so imagine if he wasn't hunted. So unless you want commies to be a one trick pony, there was no way Air could win.

2. Lixes barely did anything, it was more of a scare away kind of thing, and lixes were waay to slow to respond anyway, commies were just going elsewhere and taking out tons of stuff, so it's easy to kite away from them, highly unlikely that they would die to lixes when they are much faster.

4. It seems that Excal is already doing this strat, which is nice, meaning we're not really reinventing the meta :D

5. Gatlix reveal range is way too small, much smaller than its AA range, so that will mitigate the absolute ownage of the commies.

6. In current meta, one could do 1 bunkerlix and 1 gatlix, it will serve the same purpose, but evidently with this replay it wouldn't work, because they are too slow with a very small reveal radius, not to mention the gatling cannon orientation problem if it could shoot air units.

7. Gatlixes are really expensive costing $3200, and easy to kill Vs Air a lot of the times, so it's a big and risky investment serving the whole purpose of just scaring away the commies.

8. To summerize, i don't think gatlixes will counter commies after all, because of all the above points mentioned.

**Comment by ExiLe-ZH** [comment]
> Ok i just checked the replay and here are my points:
> 
> 
> 
> 1. Air was in unwinnable situation regardless of the lixes, He was Hunted, with No airfields, only commies and vs Two players with CCs and hundreds of gats and outposts, yet despite all that, commies alone did soo much, taking out expansions etc, so imagine if he wasn't hunted. So unless you want commies to be a one trick pony, there was no way Air could win.
> 
> 
> 
> 2. Lixes barely did anything, it was more of a scare away kind of thing, and lixes were waay to slow to respond anyway, commies were just going elsewhere and taking out tons of stuff, so it's easy to kite away from them, highly unlikely that they would die to lixes when they are much faster.
> 
> 
> 
> 4. It seems that Excal is already doing this strat, which is nice, meaning we're not really reinventing the meta :D
> 
> 
> 
> 5. Gatlix reveal range is way too small, much smaller than its AA range, so that will mitigate the absolute ownage of the commies.
> 
> 
> 
> 6. In current meta, one could do 1 bunkerlix and 1 gatlix, it will serve the same purpose, but evidently with this replay it wouldn't work, because they are too slow with a very small reveal radius, not to mention the gatling cannon orientation problem if it could shoot air units.
> 
> 
> 
> 7. Gatlixes are really expensive costing $3200, and easy to kill Vs Air a lot of the times, so it's a big and risky investment serving the whole purpose of just scaring away the commies.
> 
> 
> 
> 8. To summerize, i don't think gatlixes will counter commies after all, because of all the above points mentioned.

You aren't wrong about most points but those are just situational circumstances, we're trying to learn the general concepts of balance/strats from the replay. Regardless of winning position etc. the Lixes can't be touched by either Commies/Raps with this strat.

So with point 2 you're missing the point, scaring those Commies away is the exact purpose and it is very effective. Bunkerlix strat is obviously more expensive too, need rax, outposts etc. Do the math.

So yea Gatlixes are obviously the better choice overall if they could target Comanches, they can actually kill Commies too in a chase unlike Bunkerlixes since missiles don't have this range (unless we change all this too, game will change alot then).

Plus they detect stealth aswell. How big exactly is detection range anyway?

If you want to balance around this, then the Commies targeting Air units wouldn't even be that bad of an idea. Normal Machinegun is very weak (compared to Gatling) and could lock the missile targeting behind the Laser Guided Missiles Upgrade. Then it becomes more about a numbers and micro game.

**Comment by MTKing4** [comment]
> the Lixes can't be touched by either Commies/Raps with this strat.

Raptors weren't utilized in that fight, there were multiple instances of the lixes being on the edge of the base, sort of like you bating them out, and suicide raptors on them, it will be cost effective.

> So with point 2 you're missing the point, scaring those Commies away is the exact purpose and it is very effective. Bunkerlix strat is obviously more expensive too, need rax, outposts etc. Do the math.

I'm aware of that, but the main strength was with the big army, and air not having anything against that because he was Hunted with nothing but air units. I'm sure this would've been a lot different if he wasn't. 

> Plus they detect stealth aswell. How big exactly is detection range anyway?

About 2 Squares i think, someone could fact check that.

> If you want to balance around this, then the Commies targeting Air units wouldn't even be that bad of an idea. Normal Machinegun is very weak (compared to Gatling) and could lock the missile targeting behind the Laser Guided Missiles Upgrade. Then it becomes more about a numbers and micro game.

It might make sense from a Consistency prospective, but I don't think Air needs more buffs

**Comment by xezon** [comment]
So there is a Replay from the best Zero Hour player, where Helixes caused a lot of damage, and now we debate whether or not China is OP against USA Airforce? Did I get that right?

**Comment by MTKing4** [comment]
They didn't do much damage, they merely repelled stealth Comanches with the help of an enormous army and defences,

The stealth Comanches were the ones with the biggest damage infliction, only they couldn't finish the game.

**Comment by ExiLe-ZH** [comment]
Actually what about the inverted scenario? The offensive maneuver where China finds ways to pick off the Raps, now Gatlixes can enter the base and wreck havoc. Collection and all production can all be denied and once this happens Air is helpless on it's own. 
Could also combine this with a Gat army push and a couple of Flamers.

Anyway, ofcourse it's all theory and it needs testing how effective everything really is, I'm not against testing, already mentioned this. But it's good to theorize beforehand so all these potential scenarios can actually be tested.

**Comment by MTKing4** [comment]
TowVees usually do well against lixes, especially in mass

**Comment by ExiLe-ZH** [comment]
> TowVees usually do well against lixes, especially in mass 

Air should only go 1 thing, either fly or ground, it's most efficient. Unless he's mega big and got the skills to micro both.

Btw, it's all just team scenario, 1v1 Air wouldn't go Commmies vs China anyway.

**Comment by MTKing4** [comment]
> > TowVees usually do well against lixes, especially in mass
> 
> Air should only go 1 thing, either fly or ground, it's most efficient. Unless he's mega big and got the skills to micro both.
> 
> Btw, it's all just team scenario, 1v1 Air wouldn't go Commmies vs China anyway.

Ah we're talking in a team senario, yes, but then you have multiple airfields spread apart with raptors. Honestly there's too much to take into account with team games is hard to judge wether something is broken or not. Better to see results in games.

**Comment by xezon** [comment]
AFG Humvee spam = win
AFG Raptor spam = win
AFG Comanche spam = win
AFG Chinook spam = win

China Helix spam = not ok :)

**Comment by xezon** [comment]
I am closing this. It is too risky. China has gotten many other fixes and perks already. China will be happy regardless.
