### ISSUE TITLE
GLA Palace with Fortified Structure upgrade is missing many fireports on back and sides

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#471]
GLA Palace with Fortified Structure upgrade is missing many fireports on back and sides. This issue has been fixed in NProject Mod.

**Comment by commy2** [comment]
This is not just with Fortified Structures. It also happens on SNOW maps.

**Comment by xezon** [comment]
Enlima29
> I did some rearrangement in the ini file code structures for cleaner, orderly, and easier readability (hopefully), maybe that's why the git detected so many changes there. On top of that, in case of palace codes, I have implemented several other fixes beside the fortified+garrison fireport issues there, especially those changes that also implemented to the other structures like missing conditionstates, wrong particle bones, aliasing unnecessary/ambiguous conditionstates, etc.

**Comment by commy2** [comment]
I double checked both INI files and could not find any missing ParticleSysBone tokens. I do agree that the model condition setup is simpler and in some cases less ambiguous, but I can't see any actually visible changes a rearrangement like this would cause for the end user.
