### ISSUE TITLE
Demo GLA Terrorist dies on mines without applying damage

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#502]
Demo GLA Terrorist dies on mines without applying damage. Other GLA Terrorists apply suicide damage when walking over mines. Reported by Dominator.

Related Terrorist issues:
* TheSuperHackers/GeneralsGamePatch#26
* TheSuperHackers/GeneralsGamePatch#31
* TheSuperHackers/GeneralsGamePatch#30
* TheSuperHackers/GeneralsGameCode#37
* TheSuperHackers/GeneralsGamePatch#502
* TheSuperHackers/GeneralsGamePatch#503
* TheSuperHackers/GeneralsGamePatch#504

## Proposal 1
Apply damage.

**Comment by xezon** [comment]
This needs to be fixed.

**Comment by commy2** [comment]
This is not just minefields:

vGLA, Tox, Stealth:
> DeathTypes = NONE +SUICIDED +CRUSHED +SPLATTED +LASERED +BURNED +EXPLODED

Demo
> DeathTypes = NONE +SUICIDED

Mines cause "EXPLODED" death. So does other stuff though like Nuke Mig missiles, Black Napalm Mig missiles, Rocket Buggy missiles, Comanche missiles and about 200 other weapons (exaggerated).

Fixing this for minefields would also fix it for all other mentioned weapons.

**Comment by xezon** [comment]
Ok then this issue in implicitly fixed with the change I just made, but we can make explicit separate PR for this straight away.

**Comment by commy2** [comment]
The issue is adressed in this PR: https://github.com/TheSuperHackers/GeneralsGamePatch/pull/316

**Comment by xezon** [comment]
Thanks. That we should commit first then.
