### ISSUE TITLE
Demo GLA Terrorist can be crushed by vehicle without applying suicide damage

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#503]
Demo GLA Terrorist can be crushed by vehicle without applying suicide damage. This only happens when the terrorist unit is actively attacking a different target.

Related Terrorist issues:
* TheSuperHackers/GeneralsGamePatch#26
* TheSuperHackers/GeneralsGamePatch#31
* TheSuperHackers/GeneralsGamePatch#30
* TheSuperHackers/GeneralsGameCode#37
* TheSuperHackers/GeneralsGamePatch#502
* TheSuperHackers/GeneralsGamePatch#503
* TheSuperHackers/GeneralsGamePatch#504

## Proposal 1
Make Demo GLA Terrorist explode on crush like all other Terrorist types.

## Proposal 2
Make all GLA Terrorist types explode with less damage. This way behaviour is consistent cross faction and Jeeps and other units can still try to crush but take a bit of damage while doing so.

**Comment by Madrageeeeee** [comment]
It should be noted as well that terrorists from other factions (apart from demo general) self detonate when getting hit with a tank shell and not when getting hit with bullets (vees / quads). I do think a tow missile hit (last hit) makes them explode as well. 

Airplane hits also make them explode (except for the gun of choppers / helixes).

**Comment by xezon** [comment]
Added 2 proposals. I am fine with both. Proposal 2 must be checked if technically possible.
