### ISSUE TITLE
Particles may not render at all if their Alpha min max values are zero

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#543]
Particles may not render at all if their Alpha min max values are zero.

Reported by Enlima29:
> Particle System with zero values is a bit broken. Zero values for initial alpha or color wont scale/change properly, if it is supposed to change on later iteration. Values must be 0.01 at least. This causes some particles to not render correctly while still counting towards the total particle count. Stalker from Operation Firestorm Mod (NLS Discord Server) may have more information on this.

Example
Bad:
```
  Alpha1 = 0.00 0.00 1
  Alpha2 = 1.00 1.00 5
```

Good:
```
  Alpha1 = 0.01 0.01 1
  Alpha2 = 1.00 1.00 5
```

Note:
Alpha1 = [min value] [max value] [frame time]

**Comment by xezon** [comment]
Stalker (Andi):
> The following particlesystems don't work ingame:
> 
> **airCarrierHotPillarArms**
> **SpectreHotPillarArms**
> **BuggyNewExplosionArms**
> **HotPillarArms**
> **airCarrierJet01Explosion**
> **BarrelExplosion**
> **airCarrierExplosion2**
> **ArmExplosionSmall01**
> **airCarrierJetExplosion1**
> **airCarrierJetExplosion2**
> **airCarrierJetExplosion3**
> **MammothTankExplosionArms**
> **FireBaseHowitzerPillarArms**
> 
> These particlesystems all have 2 things in common:
> They have AttachedSystems
> Their Color1 = R:3 G:0 B:0 0 
> 
> They don't show up ingame at all.
> Change Color1 to Color1 = R:6 G:6 B:6 0 to fix them.
> 
> Easier way: Replace ALL occurences of "Color1 = R:3 G:0 B:0 0" to "Color1 = R:6 G:6 B:6 0"

> And I also know that a lot of ALPHA particleSystems which fade in from Alpha = 0 don't work either
> e.g. NukeShockwave
> It is fixed if you replace Alpha = 0 with Alpha = 0.01

**Comment by Madrageeeeee** [comment]
haha its kind of hilarious from a developer standpoint how broken this game was left behind and with how many glitches, bugs and  what not :D

Kind of cool you guys are completely deconstructing it and seeing whatsup. 

Good job

**Comment by xezon** [comment]
Stalker (Andi):
> I suspected this to be some numerical issue when interpolating between color/alpha values

> A lot of ALPHA particle systems (i.e. Transparency is determined by the texture's alpha channel and the specified alpha values) will not render at all if they start off from Alpha1 = 0.00 0.00 (having them fade in). As described, a workaround is to set the initial alpha value to a very low number (i.e. 0.01). This should visually not make a big difference and will cause the particles to show properly.

> It's similar for ADDITIVE particles (i.e. Transparency is determined by color; black = transparent) when fading in from black/zero
Again the solution is to use a dark, but not entirely black initial value

> I remember there was another issue with particles fading out, where they wouldn't properly fade to black/invisible, but I don't know any examples for that one.
