### ISSUE TITLE
China Troop Crawler and China Outpost do not grant XP on kill

### ISSUE THREAD

**Issue by EnigmaZift** [TheSuperHackers/GeneralsGamePatch#549]
Have not checked this with ALL troop crawler variants, but the default vanilla China Troop Crawler has no XP values attached whatsoever. Killing it does not provide XP, which is probably unintentional.

**Comment by Jundiyy** [comment]
It's the same for all Troop Crawlers and Outposts. I think it would be intentional as they don't attack but the units inside do, so you get xp from them only.

**Comment by commy2** [comment]
Counterpoint: Battle Bus gives 50 XP. Combat Chinook gives 60 XP.

Even units like Ambulance (50), normal Chinook (50) and Supply Truck (50) give XP. Dozers and Workers don't give any XP however.

Troop Crawler drops 8x Red Guard alive worth 5 XP each though (40), while Outpost drops 2x Tank Hunter worth 20 XP each (also 40).

**Comment by xezon** [comment]
It would make China weaker if the transport units gave XP. We should be careful about nerfing China, because it needs buffs instead.

**Comment by EnigmaZift** [comment]
8x Red Guards are already providing much less XP than they are worth, and then Crawler provides literally none. It's just a little bit weird, but I can understand not changing it.

**Comment by commy2** [comment]
Maybe we could add the entries and set them to 0. Then we make it explicit that no XP is intentional, or at least preferable status-quo.
