### ISSUE TITLE
Reduce geometry a bit for the Supply Piles

### ISSUE THREAD

**Issue by Jundiyy** [TheSuperHackers/GeneralsGamePatch#550]
It's always been quite big but what makes it worse is when you try to build at an angle or the Supply Pile is angled itself.

No angle
![Supply01](https://user-images.githubusercontent.com/79164303/136806684-56ab724f-27a0-4a77-b63b-e9519bf62ecc.PNG)
Angled
![Supply02](https://user-images.githubusercontent.com/79164303/136806689-bb0fa200-c478-48f8-a386-999bfd7e6cc8.PNG)
Distance
![Supply 2](https://user-images.githubusercontent.com/79164303/136806695-d484b97e-5797-4c27-9194-4572fc600bcf.PNG)

This also means other buildings can't be built close by as well.

**Comment by xezon** [comment]
How does new look like?

**Comment by Jundiyy** [comment]
Something like this might be okay.
Normal
![Supply 01](https://user-images.githubusercontent.com/79164303/136851521-c8070a6c-21de-4a3a-ad2d-dabfeb25e882.PNG)
Angled
![Supply 02](https://user-images.githubusercontent.com/79164303/136851536-e01d5970-8899-4913-be41-b3523abfa612.PNG)
Built
![Supply 03](https://user-images.githubusercontent.com/79164303/136851549-81be1a6a-071c-486c-bcce-c3fa5176f03b.PNG)
```  GeometryMajorRadius   = 16.0```
Change this to 3 or 5. The pictures above are set to 3.

**Comment by ExiLe-ZH** [comment]
well if it denies you to place your china supply too close, that be of great help for noobie players and maybe should be a thing on all supplies :D

**Comment by Jundiyy** [comment]
Lol yep that is true but it also means you can't build anything near it from any side.
Plus takes away the skill factor of knowing how close or far to build.

**Comment by ExiLe-ZH** [comment]
> 
> 
> Lol yep that is true but it also means you can't build anything near it from any side. Plus takes away the skill factor of knowing how close or far to build.

I meant it sarcastically :P 

Though maybe it's not even all that bad to take out the human factor out of it. Pros and experts also make these mistakes unnecessarily at times and it can hurt quite a bit.

And if you want to tackle the problem of not being to able to box anymore, instead maybe enlarge the geometry of the supply center itself (by adding the collection area to it).

**Comment by RisingZH** [comment]
Reducing it as per your second set of pictures looks good to me.

**Comment by EnigmaZift** [comment]
I think this is a certain design choice to make sure that units have to travel some short distance to get to the supply boxes. Best not to mess with it. Especially in changing the geometry of the supply box itself.

**Comment by commy2** [comment]
Could we hack together an octagonal shape geometry? That'd solve the "angled" scenario.

**Comment by xezon** [comment]
I think Enlima29 said there are 2 types: Box and Cylinder.

**Comment by commy2** [comment]
![shot_20211022_221132_1](https://user-images.githubusercontent.com/6576312/138517029-15961c1b-b27f-4bd6-b17e-e790a570c01a.jpg)
![shot_20211022_221136_2](https://user-images.githubusercontent.com/6576312/138517038-39b4f4f8-5f96-426e-8f6c-034eedb65be7.jpg)


There is a different geometry used for Supply Centers/Stashes vs every other building.

**Comment by Jundiyy** [comment]
Yes, I said it wrong before sorry. It should be SupplyBuildBorder mentioned by Hanfield in GameData.ini

**Comment by ReLaX82** [comment]
Placing supplies as the right Spot is part of still and experience.

A lower distance is fine!
