### ISSUE TITLE
Player Cannot Build Over Vehicles With Portable Structures

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#569]
<details><summary>Avenger</summary>

https://user-images.githubusercontent.com/6576312/137590610-7b5c64eb-a373-41ff-bab5-b09ab64774a9.mp4

</details>

<details><summary>Upgraded Overlords</summary>

https://user-images.githubusercontent.com/6576312/137590614-db42b9a3-b3a6-4aef-95e0-1276d6460070.mp4

</details>

**Comment by EnigmaZift** [comment]
NProject fixes this.

**Comment by commy2** [comment]
> NProject fixes this.

What are the implications of that?

**Comment by EnigmaZift** [comment]
None as far as I know. I recall it has to do with the KINDOF selection that the Turrets have...? For all intents and purposes it should have no unintentional/negative gameplay effect.

**Comment by xezon** [comment]
Fixed with #630
