### ISSUE TITLE
ICBM Superweapon has no Powers Shortcut

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#579]
ICBM Superweapon has no shortcut. It is used on some custom maps.

**Comment by EnigmaZift** [comment]
Well the button definitely exists. The thing is, it's not possible to have as many shortcut buttons as you want. There's a limit and so it's best to fill them up with buttons that are actually used by the faction.

**Comment by xezon** [comment]
commy2:
> Engine [and UI] only allows 11 superpower shortcuts per faction. Airforce General already uses all 11 (Carpet Bomber). There is no way of adding either the ICBM or the China & GLA super weapons to every faction.
