### ISSUE TITLE
Demo GLA Bike Explodes, Deal Damage After Rider Evacuates

### ISSUE THREAD

**Issue by EnigmaZift** [TheSuperHackers/GeneralsGamePatch#584]
I'm pretty certain this is unintentional, although probably well known. If a terrorist on a bike gets off the bike, the bike will destroy itself, dealing damage, then the terrorist suicide himself. Effectively dealing double damage.
I have no idea if this is fixable, probably with some janky workarounds.

**Comment by xezon** [comment]
This makes Demo strong, but it is not a problem per se. Apart from Demo Bikes being banned in "Pro Rules", pro players do not take issue with this mechanic as far as i am aware.

**Comment by EnigmaZift** [comment]
With this mechanic, a single biker can deal at least around 1400 explosive damage (depending on upgrades, positioning etc.), which is enough to bring a Supply Center to 6% HP. If pros actually abused this mechanic, it would be beyond broken 🤷

**Comment by xezon** [comment]
Pros use it. With this mechanic one bike is enough to kill USA Supply Drop Zone.

**Comment by commy2** [comment]
This bug requires the Demolitions upgrade to be used.

**Comment by Jundiyy** [comment]
Yes, this is always used, it's not really seen as a problem.

**Comment by xezon** [comment]
I will close this for the time being. Demo General is very strong with Demo Upgrade and this trick certainly helps a lot, however it is generally not seen as a problem in the overall balance, so it is not strictly requires to touch this for the sake of our main re-balancing goals.
