### ISSUE TITLE
Jarmen snipe ability sometimes doesn’t reload properly

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#589]
Sometimes takes abnormally long, might have something to do with guard mode?

**Comment by Madrageeeeee** [comment]
Always felt it had to do something with going inside a tunnel as well?

**Comment by Jundiyy** [comment]
This has already been brought up? Anything which effects ROF will reset it, this is with every unit apart from the Nuke Cannon. Which gets free shots.
So in case of Jarmen, it would be vetting up and Enthusiasm (in range of a Speaker Tower).
You can test the Enthusiasm very easily with any unit, get a Scud Launcher, shoot then go in and out of the Speaker Tower range and see it never reload.

**Comment by commy2** [comment]
duplicate of https://github.com/xezon/GeneralsGamePatch/issues/149 ?

**Comment by ExiLe-ZH** [comment]
> This has already been brought up? Anything which effects ROF will reset it, this is with every unit apart from the Nuke Cannon. Which gets free shots.
> So in case of Jarmen, it would be vetting up and Enthusiasm (in range of a Speaker Tower).
> You can test the Enthusiasm very easily with any unit, get a Scud Launcher, shoot then go in and out of the Speaker Tower range and see it never reload.

So what affects ROF in a GLA mirror?

**Comment by commy2** [comment]
> So what affects ROF in a GLA mirror?

Vetting up by killshot or vetting up by walking over scrap. Nothing else.

**Comment by ExiLe-ZH** [comment]
> duplicate of TheSuperHackers/GeneralsGameCode#30 ?

Ah yes. Same.

I searched for it before making but didn’t find this one.
