### ISSUE TITLE
USA AI Can Order Fuel Air Bomb And Para Drop From Supply Drop Zone Planes

### ISSUE THREAD

**Issue by Battlefieldkille** [TheSuperHackers/GeneralsGamePatch#599]
After playing a lot against AI in this game, on a few rare occasions I would have my units/base get randomly exploded out of nowhere. 

Then to only figure out that an enemy Fuel Air Bomb literally spawned inside my base, this does not seem to happen with any other USA faction.

The AI only needs to unlock the Fuel Air Bomb ability to use it in this way, even after destroying AI's Command Center, the Fuel Air Bomb will keep spawning in your base on its usual timer until the AI is defeated.

https://www.youtube.com/watch?v=-Vygld5QE6A
^ A video showing how this looks like, the video has been edited to speed up the waiting time. ( I knew where the Fuel Air Bomb was going to spawn because I saved the game prior to it spawning. )

USA Laser AI was set on Hard difficulty, I don't know if this would happen on other difficulties.

**Comment by xezon** [comment]
It would be useful to attach Replay in Zip file too.

**Comment by commy2** [comment]
This is definitely a thing. Also happens in the GC against Leang, usually when camping her base entrance on the bridge.

**Comment by Battlefieldkille** [comment]
Sure, glad I didnt delete it.
[00000002.zip](https://github.com/xezon/GeneralsGamePatch/files/7421570/00000002.zip)

**Comment by Madrageeeeee** [comment]
was the weird dynamics of a fuel air bomb also mentioned somewhere already? Similar to the alpha aurora bomb it detonates very erratically. Sometimes it has a significant delay and weird visuals when detonating.

**Comment by ExiLe-ZH** [comment]
> was the weird dynamics of a fuel air bomb also mentioned somewhere already? Similar to the alpha aurora bomb it detonates very erratically. Sometimes it has a significant delay and weird visuals when detonating.

Was looking for this one but only found your comment here, don’t think it is.

**Comment by Battlefieldkille** [comment]
***UPDATE***
Seems like I was wrong in thinking this only happens with Laser, played lots against other USAs now and apparently Fuel Air Bomb along with Para Drop ( ranger drop ) can spawn directly above your base, but its very inconsistent, it seems that its dependant on whatever map is being played for some reason.

**Comment by ThePredatorBG** [comment]
Check `AmericaJetB52`
It has:
```
  ;SCRIPTED SUPPORT: These special powers are triggered directly 
  ;from the transport without creating a transport. This is done 
  ;via new code support and CreateLocation USE_OWNER_OBJECT -- 
  ;which also prevents creating the payload transport.
  Behavior    = OCLSpecialPower ModuleTag_04
    SpecialPowerTemplate = SuperweaponDaisyCutter  ;@@KRIS@@
    OCL                  = SUPERWEAPON_DaisyCutter
    CreateLocation       = USE_OWNER_OBJECT
    ScriptedSpecialPowerOnly = Yes
  End
  Behavior    = OCLSpecialPower ModuleTag_05
    SpecialPowerTemplate = SuperweaponParadropAmerica
    UpgradeOCL           = SCIENCE_Paradrop3 SUPERWEAPON_Paradrop3
    UpgradeOCL           = SCIENCE_Paradrop2 SUPERWEAPON_Paradrop2
    OCL                  = SUPERWEAPON_Paradrop1
    CreateLocation       = USE_OWNER_OBJECT
    ScriptedSpecialPowerOnly = Yes
  End 
  Behavior    = OCLSpecialPower ModuleTag_06
    SpecialPowerTemplate = SuperweaponCarpetBomb
    OCL                  = SUPERWEAPON_CarpetBomb
    CreateLocation       = USE_OWNER_OBJECT
    ScriptedSpecialPowerOnly = Yes
  End
  ```

Commenting these out should fix it.

**Comment by commy2** [comment]
Why would removing those fix this? I don't understand. Are you guessing?

**Comment by xezon** [comment]
Let him guess please, it worked for the Button issue :D

**Comment by commy2** [comment]
I demand an explanation. If this really is the cause, then that is wild.

**Comment by Jundiyy** [comment]
> Let him guess please, it worked for the Button issue :D

lol haha

**Comment by ThePredatorBG** [comment]
> Why would removing those fix this? I don't understand. Are you guessing?

I'm not guessing. It's a bug I fixed in the past in Contra the same way.

**Comment by commy2** [comment]
Can confirm this with a savegame. 30 seconds after load, AI drops Fuel Air Bomb on army. If I remove the abilities from the cargo plane, that no longer happens.


https://user-images.githubusercontent.com/6576312/185790244-b58a6ce3-ecfe-45e6-8468-203b58305c0d.mp4

**Comment by commy2** [comment]
USA Command Center:
```
  Behavior           = OCLSpecialPower ModuleTag_20
    SpecialPowerTemplate = SuperweaponDaisyCutter
    UpgradeOCL           = SCIENCE_MOAB SUPERWEAPON_MOAB
    OCL                  = SUPERWEAPON_DaisyCutter
    CreateLocation       = CREATE_AT_EDGE_NEAR_SOURCE
  End
```

Any big plane:
```
  Behavior    = OCLSpecialPower ModuleTag_04
    SpecialPowerTemplate = SuperweaponDaisyCutter  ;@@KRIS@@
    OCL                  = SUPERWEAPON_DaisyCutter
    CreateLocation       = USE_OWNER_OBJECT
    ScriptedSpecialPowerOnly = Yes
  End
```
- note CreateLocation `CREATE_AT_EDGE_NEAR_SOURCE` vs `USE_OWNER_OBJECT`.
- this allows the AI to call support powers without CC
- this does not appear to be needed for the abilities to function, so removing seems safe
