### ISSUE TITLE
Alpha aurora’s fuel air bomb delayed or not exploding at all

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#603]
It seems to be the angle of firing and happens very often when targeting buildings. Force firing is often used to target buildings as it’s more reliable.

**Comment by xezon** [comment]
Duplicate of
* #15

?

**Comment by ExiLe-ZH** [comment]
> Duplicate of
> 
> * [Sometimes Aurora Alpha fuel bomb does not happen after initial bomb it dropped on target #15](https://github.com/xezon/GeneralsGamePatch/issues/15)
> 
> ?

Ah yes, I only searched for open cases is why I didn’t find this one

**Comment by xezon** [comment]
Already fixed.
