### ISSUE TITLE
Infantry Helix Can't Transport Vehicles

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#611]
An idea just came to me: do you know that lame situation when you have the whole map and well established china army against a camping late game sw general and all he does is sending a bunch of alphas killing all your dozers + CC and hunt you?

I was thinking and actually found a counter to that: just put a dozer in a lix, he'll think you're hunted and suddenly you strike back, hah!

3000 IQ move

Unless...

You were china inf...

Inf lixes should be able to carry vehicles!
(With the exception of outposts and troop crawlers, like all the other chinas)

Imo gives inf more options as well like dragon drops and saving dozer ofc

Related to this report #524

**Comment by EnigmaZift** [comment]
I haven't tried this, but this _might_ lead to the same bug that the Combat Chinook has - vehicles firing from inside air transports. While that issue, I think is tied to the Chinook's AI rather than anything else. Just note that. But furthermore, isn't the entire point of China Infantry General to be that guy that doesn't like vehicles? So surely he doesn't care if his vehicles are transportable 😛

**Comment by MTKing4** [comment]
other china helixes have that ability and not they don't have that chinook's bug you're talking about, so it's definitely possible to implement to inf as well. 

Regarding inf general, he doesn't like vehicles, but he has them, so might as well make some use to them :> 
it makes sense from a design point at least, that it will be consistent with other helixes

**Comment by Jundiyy** [comment]
Even though the idea sounds good, I don't think the consistency rule works here. Inf Helix is already very different, more transport slots and no primary upgrades. There is no harm in it not transporting vehicles, it's extra slots replace the vehicle count. 
I do like the Dozer idea though.

**Comment by MTKing4** [comment]
My point is that It still looks the same as normal helix, same cameo same voiceline same unit name, just slight differences. But all in all yeah it would be good, as to how many slots each unit would take it would be up to debate, we could make it just like other helixes

**Comment by Jundiyy** [comment]
I don't think we should make the Helix the same as the others, that's quite a big of a change for the patch. Especially just for the sake of transporting units.
If it's kept the same and only allows for Dozer pick ups, that could be a small thing.

**Comment by MTKing4** [comment]
I understand that it could have balance implications for like dragon drops, but it wouldn't make sense to the player why it will only transport one unit type, but like i said it's up for debate and I'm interested to see what others think of it

**Comment by Madrageeeeee** [comment]
Difficult one but think I would keep it as is. 

Inf lixes cant get speakertower or gatling either. Think the dozer pickup in the described situation is very niche / edge case. Hardly know any 1v1 game where it was a problem / caused a different outcome. 

Also would need testing, you could perhaps do a 4-5 tankhunter + flamer in helixnattack on china/gla. Kill the first quads then unload and kill entire based with remaining flamer and the ths.

Also, in that stage of the game where swg has enough alphas to completely kill ur cc and hunt you i think you couldve also made 2ccs prior to that point or 3 for that matter if you have all the map.

**Comment by MTKing4** [comment]
There's a recent game where dominator had 3-4 CCs and 3-4 dozers and have all the map and still lost to alphas even though he killed so many of them

Having all the map doesn't change anything, alpha auroras will still get you

Again worst case scenario is we give it only to dozers like what Jundiyy said

**Comment by commy2** [comment]
> I haven't tried this, but this might lead to the same bug that the Combat Chinook has

It won't, because that issue is tied to the `TransportContain` module, and does not happen with the `HelixContain` module. Unfortunately, changing the Combat Chinook to use the `HelixContain` module is not possible, since that breaks the rope behaviour of the `ChinookAIUpdate` module.

**Comment by commy2** [comment]
Related issue: Should the Combat Chinook be made unable to transport vehicles, considering that it is kind of similar to a Inf Bunkerlix? That would get rid of the Combat Chinook bug too.

**Comment by xezon** [comment]
> Related issue: Should the Combat Chinook be made unable to transport vehicles, considering that it is kind of similar to a Inf Bunkerlix? That would get rid of the Combat Chinook bug too.

I would not change that. Then sure it would be consistent with Infantry Helix, but would be inconsistent with Normal Chinook and Normal Helix. Player expects that car can enter Chinook. Taking that away could be awkward for some players.

**Comment by ExiLe-ZH** [comment]
Chinooks saving dozers, we see it all the time, I really like the idea of being able to put a Dozer in a Lix. It's still gonna be more rare than the this example ofcourse, but very useful when you get the opportunity to do so, or even a tactical decision for specific situations. I literally don't see any negatives for having this option, other than "it's not the same anymore". 

As for putting other vehicles in an Inf Lix, I don't think that should be a thing.

**Comment by commy2** [comment]
Inf General = bad with vehicles = forgot how to transport them

Sort of makes sense. It's a shame that the supposed "Attack Helix" is literally just a normal Helix, model wise.

**Comment by ReLaX82** [comment]
Keep as it is.

**Comment by xezon** [comment]
User Lithe noted that Infantry Helix perhaps cannot load vehicles because loading Troopcrawlers is bugged. The Troopcrawler vehicle dies on destruction but the passengers will survive and fall off the helicopter.

* TheSuperHackers/GeneralsGameCode#184
