### ISSUE TITLE
Shall USA and China be able to collect scrap?

### ISSUE THREAD

**Issue by ReLaX82** [TheSuperHackers/GeneralsGamePatch#641]
Looks wired in the first place, but it could change a bit the scrap up effectiveness of GLA.
USA/China could collect without having a direct benefit (not scrapping up) from it. May puts more skill into the game.
Your comment are welcome.

**Comment by xezon** [comment]
It's a feature request. Does that address any existing problem?

**Comment by ZekeDlyoung** [comment]
I don't see the point in this tbh, except maybe annoying all the GLA players.

EDIT: Didn't we already have a discussion about scaffolds deleting scrap?

**Comment by Stubbjax** [comment]
I don't see the logic behind this suggestion at all. You'll obviously have a balanced game if you make every faction the same, but that's not fun at all. Scrap is mechanically and thematically unique to GLA and should remain that way.

**Comment by ReLaX82** [comment]
It can allow USA or China to collect it before GLA does. So it changes balance, means nerfs GLA.

I can add Details, but just think about a few scenarios where units are closer together and China get this scrap with units insread of scaffolds bwfore gla does.

But Overall not worth the effort I think.

**Comment by xezon** [comment]
So you mean instead of placing a scaffold over it, player must drive over it with unit and collect it? That is a reasonable suggestion when paired with the removal of scaffold dropping to remove scrap.

Here is the test branch for that:
* #1105

**Comment by ReLaX82** [comment]
Just another idea, but in Reality not much occasions are there where that works as in most cases china's units are destroyed and gla collects scrap.

Can also discuss how long scrap Stays on the battlefield.

**Comment by MTKing4** [comment]
A legitimate way of scrap deny, i like it!

**Comment by ReLaX82** [comment]
Before someone gets in bloody detail, I would like to hear what others say.

**Comment by ZekeDlyoung** [comment]
I feel like if this is going to be a thing then US and China should get money from picking up scrap at least.

Consider it a discount from being able to successfully recover spare parts in the field.

**Comment by ReLaX82** [comment]
Get money or nothing, whatever first best.

**Comment by Jundiyy** [comment]
It does make a good way to scrap deny but I don't think it fits them, should stay for GLA.

**Comment by ReLaX82** [comment]
I think ZekeDlyoung has a point here. In 1on1 it doesnt matter much if you get money for it, but in teamgames it can.

**Comment by ExiLe-ZH** [comment]
Or instead of cash you make them ‘crushable’, not sure how infantry would then interact with them though.

I just don’t like the idea of china/usa collecting cash from scraps. It’s one of those things that makes the armies more unique.

**Comment by ReLaX82** [comment]
The uniqueness would also force to make it only disappear.

**Comment by DoMiNaToRuk2** [comment]
No need to do this

**Comment by xezon** [comment]
It is possible to implement without Thyme. Prototype: #1677. But too risky. Closed.
