### ISSUE TITLE
USA Paladin Tank requires a General Promotion, but is not better than Crusader Tank

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#645]
Related:
* #409

USA Paladin Tank is not used much. It requires using a General Promotion at Rank 1. Should this be changed?

### Proposal 1
Match the armor buff of Paladin with the armor buff of the Crusader, so the Paladin remains the better tank after the upgrade.

**Comment by ExiLe-ZH** [comment]
It is used quite a bit more nowadays, mainly vs GLA where they are dropped early game into supply lines, it can be quite a pain and micro-intensive to deal with.

You also see them dropped (in pairs) with big Vee pushes later, this makes dealing with the push a whole lot harder if the GLA only got Techs.

I would be a fan of making them a bit better in some way, but it can be easily overdone. In any case I think it should remain locked behind the promotion.

**Comment by xezon** [comment]
If Paladin Tank was much better than Crusader, the General Promotion might be justified. But it is not. It is more expensive and has less health. The Infantry Zap is good, but does it justify the whole thing?

**Comment by ExiLe-ZH** [comment]
> If Paladin Tank was much better than Crusader, the General Promotion might be justified. But it is not. It is more expensive and has less health. The Infantry Zap is good, but does it justify the whole thing?

It is somewhat justified, the normal or laser crusader is useless for the first case scenario I mentioned. And much less effective than the second case.

I would still like to see improvements to make the Paladin also viable for other scenarios like USA vs Tank where Crusaders are already used currently.

Not sure how we can do that without making it OP against GLA though.

**Comment by ReLaX82** [comment]
On 1.06 we had Paladin powerful agsinst GLA.
Wouldnt go that far, but in this Direktion.

**Comment by ZekeDlyoung** [comment]
> If Paladin Tank was much better than Crusader, the General Promotion might be justified. But it is not. It is more expensive and has less health. The Infantry Zap is good, but does it justify the whole thing?

It having more health is more of a bug imo. Also, it zaps missiles, so under certain conditions, it can survive longer than Crusaders.

I wouldn't mind a few buffs for the Paladin, perhaps making it cost the same as the Crusader to make a more valid alternative. As I assume this is the purpose for most Rank 1 unit GPs, picking an alternate unit (i.e. Crusader or Paladin, SF or Raptor, Nuke Cannon or Inferno) as opposed to getting more GP abilities.

**Comment by Jundiyy** [comment]
I would leave it locked, even in its current state it can be a big problem early game. As Exile has already mentioned, we've seen this happen on streams many times.

Paladin is a better tank than the Crusader until the Composite Armour upgrade. We already discussed Crusaders elsewhere and kept the extra hp but removed the code so it's not a mistake anymore. Don't think Crusader should be touched but if needs be, we could increase Paladin hp after the upgrade to be close or match the Crusader's. And as Zeke mentioned, the PDL would make it survive longer in some situations, it's also a better anti inf unit as it can zap them, including Terrorists (although you have to be careful as they can blow up close to the tank).

**Comment by xezon** [comment]
After internal discussion it was outlined, that the Paladin Zap is worth the premium in Build Cost, Build Time and General Promotion. Other than the Zap, the Crusader Tank is a much better deal however.

> commy2 commented on Sep 24, 2021

> The Paladin tank is better than a Crusader in that it starts with 20 extra HP (+4.2%, not much) and a slow firing PDL that can target infantry, especially GLA Workers when dropped by Chinook into a boxed in Supply Stash.

> In general, it is not worth the extra $200 and 2 second build-time. After Composite Armor, it has much less HP than a Crusader to the point where the Crusader survives longer against 2 rocket infantries than a Paladin does despite the PDL.

> 1.04
> Crusader $900 13.25 seconds
> Paladin $1100 15.25 seconds

**Comment by DoMiNaToRuk2** [comment]
Make composite armour double up on the paladin like on crusader

**Comment by xezon** [comment]
I agree with adding double armor to match Crusader behavior. This way Paladin will remain better than Crusader.

**Comment by xezon** [comment]
1 Proposal added.

**Comment by ExiLe-ZH** [comment]
Proposal: Should the Paladins PDL be 100% reliable vs exactly 1 TH/RPG/MD (without LL)?

With this and the armor buff I don't think it needs any price or build time improvement anymore then.

**Comment by DoMiNaToRuk2** [comment]
I like that idea. Boost the PDL and see what happens. 

Just gotta be careful about paladin drop rushes vs gla. Don't want it becoming OP, needs test

**Comment by xezon** [comment]
```
Weapon PaladinPointDefenseLaser
  PrimaryDamage       = 100.0
  PrimaryDamageRadius = 0.0
  AttackRange         = 65.0
  DelayBetweenShots   = 1000         ; time between shots, msec

Weapon AirF_PointDefenseLaser
  PrimaryDamage       = 100.0
  PrimaryDamageRadius = 0.0
  AttackRange         = 65.0
  DelayBetweenShots   = 250         ; time between shots, msec

Weapon AvengerPointDefenseLaserOne
  PrimaryDamage       = 100.0
  PrimaryDamageRadius = 0.0
  AttackRange         = 100.0
  DelayBetweenShots   = 500         ; time between shots, msec
```

**Comment by ExiLe-ZH** [comment]
> ```
> Weapon PaladinPointDefenseLaser
>   PrimaryDamage       = 100.0
>   PrimaryDamageRadius = 0.0
>   AttackRange         = 65.0
>   DelayBetweenShots   = 1000         ; time between shots, msec
> 
> Weapon AirF_PointDefenseLaser
>   PrimaryDamage       = 100.0
>   PrimaryDamageRadius = 0.0
>   AttackRange         = 65.0
>   DelayBetweenShots   = 250         ; time between shots, msec
> 
> Weapon AvengerPointDefenseLaserOne
>   PrimaryDamage       = 100.0
>   PrimaryDamageRadius = 0.0
>   AttackRange         = 100.0
>   DelayBetweenShots   = 500         ; time between shots, msec
> ```

vs RPG/TH/MD delay?

**Comment by xezon** [comment]
DelayBetweenShots

**Comment by ExiLe-ZH** [comment]
> DelayBetweenShots

Is what I mean yes, how these statistics compare to TH/MD/RPGs.

This:

```Weapon ChinaInfantryTankHunterMissileLauncher
  PrimaryDamage = 40.0            
  PrimaryDamageRadius = 5.0      
  ScatterRadiusVsInfantry     = 10.0     ;When this weapon is used against infantry, it can randomly miss by as much as this distance.
  AttackRange = 175.0
  MinimumAttackRange = 5.0  ; Rockets take some distance to target, and you don't want them to blow up in your face.
  DamageType = INFANTRY_MISSILE   ;ignored for projectile weapons
  DeathType = EXPLODED
  WeaponSpeed = 600               ; ignored for projectile weapons
  ProjectileObject = TankHunterMissile
  ProjectileExhaust           = MissileExhaust
  VeterancyProjectileExhaust  = HEROIC HeroicMissileExhaust
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
  ScatterRadius = 0      ; This weapon will scatter somewhere within a circle of this radius, instead of hitting someone directly
  DelayBetweenShots = 1000  ; time between shots, msec```



```Weapon TunnelDefenderRocketWeapon
  PrimaryDamage               = 40.0            
  PrimaryDamageRadius         = 5.0      
  ScatterRadiusVsInfantry     = 10.0     ;When this weapon is used against infantry, it can randomly miss by as much as this distance.
  AttackRange                 = 175.0
  MinimumAttackRange          = 5.0 ; Rockets take some distance to target, and you don't want them to blow up in your face.
  DamageType                  = INFANTRY_MISSILE  ; ignored for projectile weapons
  DeathType                   = EXPLODED
  WeaponSpeed                 = 600               ; ignored for projectile weapons
  ProjectileObject            = TunnelDefenderMissile
  ProjectileExhaust           = MissileExhaust
  VeterancyProjectileExhaust  = HEROIC HeroicMissileExhaust
  RadiusDamageAffects         = ALLIES ENEMIES NEUTRALS
  ScatterRadius               = 0      ; This weapon will scatter somewhere within a circle of this radius, instead of hitting someone directly
  DelayBetweenShots           = 1000  ; time between shots, msec```

*Editing this on phone is so dreadful

**Comment by xezon** [comment]
Paladin has 4 times slower Laser than Airforce Chinook.

**Comment by Jundiyy** [comment]
I think it's fine, any better and would become too strong. With the armour buff it becomes a super early unit and a late game unit.
Paladins are already a problem for GLAs, especially when not expected, then it makes it super hard. We've seen experts losing games due to the drop.

**Comment by MTKing4** [comment]
No for the PDL buff
