### ISSUE TITLE
Should double scrapped Marauder and Technical be touched (nerfed)?

### ISSUE THREAD

**Issue by ReLaX82** [TheSuperHackers/GeneralsGamePatch#647]
Double scrapped Marauder and Technical are basically in some states at the game unstoppable as a ground unit.
It is discussable if that needs to stay or not.

Pros: The player which got this unit scrapped needs effectively 2 scraps, which he only gets through killing units. That forces opponents whatever faction to be careful on not aggressiv. So definately doesn't come from nothing. On top of that seeing the China buffs it harder now for techs in specific and marauders also quite a bit. Also Marauder needs a GP point.

Cons: Game is mostly over if no hard counter is applied or at least the its hard to recover so its winnable in the end.

I am totally neutral to this one as it already is tackled through buffing China in general.

### Linked to that question is also:
#592: Trucks and dozers leaving scrap
#641: Shall USA/China be able to collect scrap
#56: Quad vetted/scrapped 
#648: Scrap deny allowed or not?

**Comment by Jundiyy** [comment]
No need to touch, as Rage has mentioned before, we start removing the good stuff people like then they won't prefer it anymore, he said that's what happened to 1.06 and it slowed down the game.
I don't think there is a need to touch the units.

**Comment by xezon** [comment]
I think it's a big risk for gameplay to make these scrapped units weaker. It would be safer to strengthen China instead, because China struggles vs both GLA and USA in many setups.

**Comment by DoMiNaToRuk2** [comment]
Buff the weak shit. 

Don’t nerf strong shit

**Comment by ECBVovin** [comment]
Double scrapped marauder may(?) have a bit of a reload bug. The delay between shots is 750ms, but the clip reload is only 100ms. This makes it so the second and third shots are much faster than the first and second. This being said, it would probably be better to leave marauders and super techs alone.

**Comment by commy2** [comment]
Scrap 1 Marauder has 1 shot clip and 1500 msec reload time.
Scrap 2 Marauder has 2 shot clip and 750 msec reload time.

Pretty sure the intend was to double the ROF. Effectively, this quadruples it though.
I agree with Dominator that this is should stay. As stupid as it is, it's fun and makes the unit viable.

**Comment by xezon** [comment]
Close?

**Comment by MTKing4** [comment]
I'd say close, and reopen later if we felt like it
