### ISSUE TITLE
Reduce RPG Trooper Vision Range?

### ISSUE THREAD

**Issue by penfriendz** [TheSuperHackers/GeneralsGamePatch#651]
Suggestion: Reduce RPG Trooper vision range to be the same as a Tank Hunter.
Rationale:
Contextual/conceptual:
- Way more vision than most infantry. It has comparable vision to the Ranger, which (to me) only makes sense on the Ranger.

Concrete/Actual implications:
- Currently this extra vision makes it very easy to react to threats coming towards your tunnel. If you park an RPG Trooper outside a tunnel, you have ample time to react to a dragon tank coming.
- Without the extra vision, you need to pay more attention to threats around tunnels, increasing skill ceiling while nerfing tunnels in a meaningful but very low touch way.

I am pretty confident this is a nerf that the tunnels could do with and this would certainly not reduce the skill cap or change the game's feel - in fact it would probably increase the skill gap. It also, in my opinion, makes thematic sense.

**Comment by ReLaX82** [comment]
Fine to me.

Why should a ranger have more vision btw?

**Comment by Stubbjax** [comment]
> Why should a ranger have more vision btw?

For a few simple reasons:

1. It is how rangers in the US military operate in the real world. Rangers, by definition, are relatively mobile and lightly armoured skirmisher troops intended for screening, scouting and other tactical roles unsuited to soldiers carrying heavier loads (e.g. rocket launchers).

2. It is preferable that different units specialise in different areas / roles to encourage strategic diversity and enrich gameplay.

**Comment by xezon** [comment]
I have never read any pro player complain about this aspect being too good or too bad, so likely it is ok to just leave it as is. It does read like this change would have a big impact on GLA play, potentially boosting USA strength significantly in return. USA Humvees already drive quite quickly, so reducing RPG Vision should make USA Humvee attacks on tunnels and other bases defenses more successful, if a nearby RPG Trooper can no longer scout as far.

**Comment by DoMiNaToRuk2** [comment]
If it ain't broke. don't fix it.

Don't touch this

**Comment by xezon** [comment]
I will close this. Yes reduced range would help China, but it would also help USA at the same time, and USA does not need this help against GLA.
