### ISSUE TITLE
China Helix does not evac passengers on snipe

### ISSUE THREAD

**Issue by Madrageeeeee** [TheSuperHackers/GeneralsGamePatch#661]
<img width="445" alt="Schermafbeelding 2022-03-25 om 13 03 29" src="https://user-images.githubusercontent.com/90477402/160117468-72584212-5a64-4e35-a990-3bf4d31acf00.png">

bug where a helix that has infantry inside of its bunker that gets sniped by jarmen can not be recaptured.

Unsure if this was reported prior.

**Comment by xezon** [comment]
I suspect it cannot be recaptured because it does hold the cargo infantry. Perhaps fixing TheSuperHackers/GeneralsGameCode#35 will fix this issue too.

**Comment by xezon** [comment]
In Patch, Helix can be recaptured. The only issue is that its cargo does not evacuate on snipe, but on recapture only.

| Object             | Units evac   |
|--------------------|--------------|
| USA Chinook        | On Snipe     |
| USA Combat Chinook | On Snipe     |
| China Helix        | On Recapture |

**Comment by xezon** [comment]
Duplicate of TheSuperHackers/GeneralsGameCode#35
