### ISSUE TITLE
USA King Raptor does not gain armor buff from Countermeasures upgrade

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#677]
USA King Raptor does not gain armor buff from Countermeasures upgrade, unlike other USA aircraft. Check if change is reasonable.

**Comment by xezon** [comment]
Giving King Raptor more armor would make it more difficult to kill for Gattling, Quad and Avenger, which may not be desirable, because it already is a strong unit in its current setup.

**Comment by DoMiNaToRuk2** [comment]
True better leave this as king rap is a nice unit already. No need to be stronger

**Comment by ExiLe-ZH** [comment]
I believe the double health buff is a bug actually, Counter Measures is supposed to only provide protection vs missiles by deploying flares, which is visually represented in the game aswell. Ingame description also suggests this.

That said, aircraft+upgrades balance is fine as is, shouldn't touch.
