### ISSUE TITLE
China Hacker gives large amount of XP when killed

### ISSUE THREAD

**Issue by ECBVovin** [TheSuperHackers/GeneralsGamePatch#689]
Currently, Hackers give 50, 100, 150 and 400 exp when killed at each respective rank.  Super Hackers give the same amount. Compared to other infantry and secondary eco, this is extremely high.
Vet 3 Ranger: 60 exp
Black Market: 200 exp
SDZ: 200 exp
A GLA Scud Storm will also give you 400 exp for destroying it.

Not only are Hackers the weakest form of secondary eco, but you're getting a Scud Storm's worth of exp for each one you kill. Combined with a weak Internet Center and up to eight Hackers, the leveling potential for your enemy is insane.

Should Hackers give less exp when killed?

**Comment by ExiLe-ZH** [comment]
Holy moly, knew it was bad, but not THIS bad. Should be rebalanced 100%

**Comment by xezon** [comment]
I agree. It is too much XP. Around 5 hackers cost as much as a Drop Zone, so maybe a hacker should give 40 XP on average.

**Comment by Jundiyy** [comment]
Whilst I do agree it is a lot, I can understand why or how it happened.
Black Markets and Drop Zones give 200xp and cost £2500, 4 Hackers cost the same price so 4 of them also give 200xp. Then because they can vet up, they give more xp like everything else.
Again, not saying it's done well, just an explanation.
Although I do think they should give more than basic infantry. And perhaps not 400 once fully vetted.

**Comment by xezon** [comment]
We could narrow or null the veteran XP increment.

**Comment by Jundiyy** [comment]
Perhaps 40, 80, 120, 160?

I think Hackers still need a few buffs, without too much change. 

Faster build time, cheaper price + less xp

Or

Faster BT, cheaper, less xp/faster vet up.


-----
Adding less xp + faster vet up might be too much together. 
Hackers were already better with just the price and BT of 1.04+, so they will just need a bit more help.

**Comment by xezon** [comment]
Hackers are much easier to kill than Drop Zone and Black Market. They also come in more quantities. So I still think 160 is too much. Let's gather full EXP values from Drop Zone + Black Market + other Infantry to get a better picture first.

**Comment by Jundiyy** [comment]
Yes true, maybe between a Ranger and a Pathfinder. Could follow most infantry patterns 
30 30 60 90.
Or is it really fair to give it 20 20 40 60?

Ranger 20 20 40 60
Missile Defenders 20 20 40 60
Pathfinder 40 40 60 80
Burton 50 100 100 150

Red Guard 5 5 10 20
Tank Hunter 20 20 40 60
Lotus 50 100 150 400

Rebel 15 15 30 40
RPG 20 20 40 60
Kell 50 50 100 150

**Comment by ExiLe-ZH** [comment]
> 

30/30/60/90 sounds fair.

They should be treated like infantry and not buildings indeed.

Them being infantry is already a downside because of the vulnerability, upside should be that the enemy doesn't gain heaps of xp for killing them.

**Comment by xezon** [comment]
How much money does hacker generate on each veterancy level?

**Comment by Jundiyy** [comment]
$5, $6, $8, $10
I wouldn't like to change this, it's too big of a change imo. Although if they gave more money from the beginning of ZH, they prob wouldn't need touching now.

**Comment by xezon** [comment]
Ok. I suggest following XP values. They scale more closely to the amount of money the hackers make.

40/50/65/80

**Comment by ExiLe-ZH** [comment]
> $5, $6, $8, $10 I wouldn't like to change this, it's too big of a change imo. Although if they gave more money from the beginning of ZH, they prob wouldn't need touching now.

Well one problem is that you need so many hackers for you have a decent moneyflow and in real games it's always super hard to get a good amount if you're playing vs good opponents (mostly impossible and can't compete vs gla/usa in ffa campgames either).

Making hackers themselves cheaper and faster building proved to be helpful in 1.04+ test already. However what about experimenting with the collection rate instead? Then you don't have to change these values either. 

What is the current rate exactly?

*Anyways, it's another discussion, maybe needs a new topic or be discussed in another existing topic.

**Comment by xezon** [comment]
Yeah boosting income rate sounds like reasonable parameter to tweak if necessary.
