### ISSUE TITLE
China Black Lotus requires and gives more EXP than other Heros

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#718]
China Black Lotus requires and gives more EXP than other Heros. Does this need tweaking?

```
ChinaInfantryBlackLotus
  ExperienceValue       = 50 100 150 400 ;Experience point value at each level
  ExperienceRequired    = 0 150 450 900  ;Experience points needed to gain each level

AmericaInfantryColonelBurton
  ExperienceValue     = 50 100 100 150  ; Experience point value at each level
  ExperienceRequired  = 0 200 300 600   ; Experience points needed to gain each level

GLAInfantryJarmenKell
  ExperienceValue     = 50 50 100 150  ;Experience point value at each level
  ExperienceRequired  = 0 100 200 400  ;Experience points needed to gain each level
```

**Comment by ExiLe-ZH** [comment]
Maybe the reason is that Lotus can capture buildings that are worth this amount of xp aswell.

**Comment by commy2** [comment]
See; https://github.com/TheSuperHackers/GeneralsGamePatch/pull/413

> Lotus requires to hack (steal or capture) 8, 23 and 45 buildings to vet up, which is impossible in any serious game beyond vet 1 in very rare cases.
> A vetted Lotus grants insane amounts of experience. At vet 3, it grants as much as [18 vet 0/1 Gatling tanks] / [9 vet 1/2 Battle Masters] / [180 vet 0/1 Red Guards] / [1.5 vet 3 Overlords].

Also related: https://github.com/TheSuperHackers/GeneralsGamePatch/issues/416

**Comment by ExiLe-ZH** [comment]
Can this one be reopened for discussion aswell? I don't see a reason to open a duplicate.

Anyways, my proposal would only be to reduce the Hero value to 300xp. Lotus can steal/make the enemy sell high value buildings so the base values are kind of alright and nerfing would be bad? The jump from Elite to Hero just doesn't make much sense.

**Comment by xezon** [comment]
To reopen this you need to proof that the changes in

* #807

are not appropriate.

**Comment by ExiLe-ZH** [comment]
> To reopen this you need to proof that the changes in
> 
> 
> 
> * #807
> 
> 
> 
> are not appropriate.

Requirements do seem appropriate, no suggestions there.

Proposal is about reward for killing lotus.

**Comment by xezon** [comment]
I don't understand what you mean.

**Comment by ExiLe-ZH** [comment]
> I don't understand what you mean.

The commit/discussion you just referred to is about experience requirements, not about value reward. 

This current topic is the only one addressing this issue?

Or does this one address it?
https://github.com/TheSuperHackers/GeneralsGamePatch/pull/413

**Comment by xezon** [comment]
Lotus ExperienceValue = 50 50 100 150 ; From 50 100 150 400

**Comment by ExiLe-ZH** [comment]
Ok, that's from the merge I just mentioned?

I would like to further discuss this change because there might be a few solid reasons why the original values are higher than other hero's.

We can discuss here?

**Comment by xezon** [comment]
That was changed with
* #413

**Comment by ExiLe-ZH** [comment]
Ok, so at first it may sound like a no brainer to reduce Lotus XP to the same values as Jarmen and Burton. Buffs over nerfs right?

However lotus can change games very quick by just capping one building, this could be a SW or CC (plus hunt). Burton and Demo Jarmen don't have the ability to destroy high value buildings with 1 click and she doesn't rely on veterancy to be able to do this.

Trading $1500 and 50xp (100xp for Super Lotus or max 150xp at vet 3) for such crucial damage does sound way too low indeed.

Her new veterancy potential and disabling range should improve her survivability aswell. Therefore it might be justified to increase the reward for catching her.

Maybe all hero's are simply too low, because Burton and Jarmen become tough to stop aswell when vetted up (they rely more on this than Lotus).

Maybe this would be a justified for all hero's:
75 100 150 300

Remember that a simple non-vetted Tank is/was also rewarded with 100xp! Original 50xp is nothing.

**Comment by xezon** [comment]
Returning different XP rewards for different Hero's would imply they are varying in strength. E.g. if Lotus would return twice as much as Burton, then Lotus is expected to be twice as good. Is that true? Rewarding same XP for all Hero's sounds reasonable, as preferably all Hero's are as useful as another.

**Comment by ExiLe-ZH** [comment]
In my post I did suggest to make all hero's higher.

150xp for a Vet 3 Hero doesn't make too much sense when you compare it to a standard Tank, which already is 100xp.

**Comment by xezon** [comment]
I suggest to update Experience Sheet fully with all current patched values and then take another deep look.
* #1126

**Comment by xezon** [comment]
75 100 150 300 Hero kill XP looks like a lot. It would mean that a Quad and Gattling would become 3 Star after killing a Vet 3 Hero. Is this desired?

**Comment by MTKing4** [comment]
I think it's fine, if you kill a lotus after she captured 20 of your buildings then it won't really matter would it :D

**Comment by xezon** [comment]
Perhaps we can agree on a smaller XP reward increase? For example from 50 50 100 150 to 75 100 150 200?

**Comment by MTKing4** [comment]
Maybe, i do think it's weird that the only odd one out is lotus, having more even though it can't attack, i think normalizing it to 50 50 100 150 or 50 100 100 150 would be better

**Comment by xezon** [comment]
This report has run its course. Continue in #2025.
