### ISSUE TITLE
Damaged stealth buildings are visible due to smoke effects

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#736]
Most common with empty outposts used as scouts.

Need fixing?

**Comment by commy2** [comment]
Related: https://github.com/TheSuperHackers/GeneralsGamePatch/pull/261

I _think_ (but I would have to double check) that this happens only for buildings (Stealthgen Camo Netting) as well as the Listening Outpost in 1.04.

**Comment by xezon** [comment]
commy2 fixed these already no?

**Comment by commy2** [comment]
#261 is merged, thus the smoke effect disappears after repairing an Outpost.

I do not know for certain if smoke on vehicles is visible while in damaged state. What I do know is, that smoke is visible for damaged stealthed buildings. E.g. a camo netted Black Market in orange health is visible to the enemy by smoke colums coming from apparently nowhere.

**Comment by xezon** [comment]
I think this was an issue on Outpost only. Other vehicles should be normal.

**Comment by commy2** [comment]
Assigning controversial, because a potential fix would affect gameplay balance vs Stealthgen and isn't just "cosmetic".

**Comment by RisingZH** [comment]
Seems logical to me that a damaged stealthed vehicle wouldn't be fully invisible.
