### ISSUE TITLE
Internet Center with Satellite Hack I does not spy on newly constructed Command Centers

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#748]
Internet Center with Satellite Hack I does not spy on newly constructed Command Centers.

**Comment by commy2** [comment]
Hanfield:
> fixable with fireweaponupdate that fires an ocl that is keyed to spy on command centers

**Comment by xezon** [comment]
Enlima29:
> Another thing is the satellite hack 1 bug. The fix is basically moving the reveal module to a slaved dummy object that is being killed and respawned every few seconds, this way the power can refresh properly and detect the newly built enemy command centers. However due to this the previously permanent reveal will be shut down every time the dummy object dies, at least until the new dummy is spawned to replace it automatically, which creates the "reload time" for the reveal power. It can be prevented by giving the dummy longer lifetime than the respawn time so it can creates an illusion of permanent reveal, but I'm not sure if letting more than one reveal power object at a time can cause further issues (as it is hinted by the Internet Center build limit comments) so I decided to make it a periodical reveal instead.

**Comment by Jundiyy** [comment]
Isn't it possible to just have an upgrade which auto refreshes? Just like Hack 2? It auto scans so why can't Hack 1 auto scan every 30-60 seconds?

**Comment by USA-Bruce** [comment]
So why not take Hanfields fix? Sounds solid enough

**Comment by commy2** [comment]
Because I work during the week T_T
