### ISSUE TITLE
China Inf Hacker can be heard hacking by opponent player while stealth

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#753]
China Inf Hackers can be heard hacking by opponent player while stealth. Is this a problem?

**Comment by xezon** [comment]
Stealth Super Hackers are very good despite this. Stealth helicopters can also be heard. Not necessary to change anything here.

**Comment by ExiLe-ZH** [comment]
Maybe reduce sound volume, like proposed for commies?
