### ISSUE TITLE
Anthrax poison kills first Worker in GLA SCUD Storm Rebuild

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#757]
Anthrax poison kills first Worker in GLA SCUD Storm Rebuild. This looks silly. It would be more logical to have the Worker spawn after the Poison disappeared.

![shot_20220725_191421_4](https://user-images.githubusercontent.com/4720891/180838209-8b11286d-162e-4320-a8ee-fb6c0647bf0f.jpg)

![shot_20220725_191426_7](https://user-images.githubusercontent.com/4720891/180838228-580eb3e4-19e9-400c-b6ac-e882f2be6084.jpg)

**Comment by xezon** [comment]
Maybe another solution would be to kill the first worker quicker by making the poison very strong at the center of the hole. When the worker dies quickly, he will be deeper in the scaffold and less visible.

**Comment by commy2** [comment]
You hear him scream, get a "unit lost" E.V.A. message, and a "Worker under attack" message in the top left.

**Comment by xezon** [comment]
F.

Would it be possible to spawn a different dummy worker in SCUD Storm Hole that does not scream?

**Comment by Jundiyy** [comment]
As far as I know, yes. Each hole has it owns defined Worker. So you can create a copy and edit the voice files. Although some Worker stuff is hard coded. 

But my question is, why do we need to do this in the first place? I haven't understood that just yet.

**Comment by xezon** [comment]
It is similar to the USA Cargo planes getting attacked and causing irritation. Ideally worker does not spawn into home made toxins.

**Comment by Jundiyy** [comment]
Ah right, okay. Well what if you make a dummy worker which has no sound, but spawn it the same as usual, so then there is no sound for it, but the Scud still starts building?
Actually, EVA sounds...not sure if you can disable them per unit?

**Comment by MTKing4** [comment]
Can you make that toxin cloud just not do damage? And be cosmetic only.

**Comment by commy2** [comment]
That would be weird, and would make all Scud Storms rebuild 20 seconds faster.

**Comment by MTKing4** [comment]
Wasn't that the point? So that all scud storms build as quick as the demo one?

**Comment by commy2** [comment]
Okay then let me try this: Why would this be the only poison cloud that does not damage anything at all? May as well never spawn a poison cloud. But that means Scud Stroms rebuild 20 seconds faster in this patch compared to 1.04, which seems just wrong.

**Comment by MTKing4** [comment]
What does it damage other than the worker? The way i see it is it's a toxic waste of your own weapon, people who built it probably know how to protect themselves from it, otherwise what other options do we have to fix this?

About the 20 seconds faster, can't you just delay the worker to pop up after 20 seconds?

**Comment by xezon** [comment]
That is what commy did in his Pull Request. It is linked above.

**Comment by MTKing4** [comment]
I think what commy did was that worker respawn rate is longer, so everytime he dies he'll take longer to respawn, I'm asking for a different thing, only delay the first spawn, meaning letting the cycle start a bit later, which assuming from your answer isn't possible?

**Comment by commy2** [comment]
MTKing, that would be ideal, but it is not possible without engine changes.

**Comment by Jundiyy** [comment]
I can't think of a way for this, very hard. Whilst it might look or seem silly, it causes 2 problems. Firstly, no health on the scaffold, so the Scud is easier to destroy.
And a delay on the next Worker if the first is killed.
