### ISSUE TITLE
Demo GLA Scud Storm rebuilds around 20 seconds quicker than all other SCUD Storms

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#758]
Demo GLA Scud Storm rebuilds around 20 seconds quicker than all other SCUD Storms.

Potentially introduced with
* #70

Related to
* #757

## Toxin SCUD Is Killed

![shot_20220725_191259_2](https://user-images.githubusercontent.com/4720891/180837170-8f6dc16c-4b41-439d-b9e6-a1321ee01e77.jpg)

## Toxin SCUD Starts Rebuild

![shot_20220725_191318_3](https://user-images.githubusercontent.com/4720891/180837222-3e5ee420-ee9b-4f94-b8a3-27cd3c26f5ef.jpg)

## Demo SCUD Is Killed

![shot_20220725_191616_8](https://user-images.githubusercontent.com/4720891/180837251-958e8ebf-3d43-4258-966e-1e882d389f6c.jpg)

## Demo SCUD Starts Rebuild

![shot_20220725_191627_9](https://user-images.githubusercontent.com/4720891/180837327-dd276091-f7a7-434b-b4c3-494bb3c46466.jpg)

**Comment by DoMiNaToRuk2** [comment]
Doesn't make sense to put a toxin field there on demo since it doesn't fire toxin at all.
