### ISSUE TITLE
Smoke effect of USA Airforce Comanche is visible when damaged and stealthed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#762]
Smoke effect of USA Airforce Comanche is visible when damaged and stealthed.

Related issues:
* #261
* #736
* #763

**Comment by DoMiNaToRuk2** [comment]
Keep it like it is

**Comment by commy2** [comment]
This and https://github.com/TheSuperHackers/GeneralsGamePatch/issues/763 should be one issue. 

I would not change this behaviour.
