### ISSUE TITLE
Investigate whether or not damaged vehicle smoke effect visible to enemy on GPS scrambled units

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#763]
Investigate whether or not damaged vehicle smoke effect visible to enemy on GPS scrambled units.

Related issues:
* #261
* #736
* #762

**Comment by xezon** [comment]
It becomes a bit of a design question whether or not we want to change smoke on stealthed units. Currently it does nerf stealthed units and buildings a bit. It also adds gameplay depth, because the owner of the stealthed things needs take action to repair or heal his units if he wants to recover full stealth.

As for Comanche, it is good that they can be discovered this way, because they are very strong. On the other hand they are audible when stealthed, so there is already another way to detect them without stealth detection.

From gameplay perspective it appears to play ok, but surely does look silly. It is not clear to me what to do. But would be good it it were consistent.

**Comment by xezon** [comment]
Another point: Low Spec player with reduced particle count could not enjoy this sneaky gameplay advantage, meaning a High Spec player with particles could see smokes and engage in stealh battles, but Low Spec player cannot.

**Comment by MTKing4** [comment]
Another important aspect where this matters is gla stealth buildings, especially palace, when not damaged, there's zero indicator that there's a building there without scanning

**Comment by ExiLe-ZH** [comment]
> Another important aspect where this matters is gla stealth buildings, especially palace, when not damaged, there's zero indicator that there's a building there without scanning

Well, isn't that the point? :D

**Comment by MTKing4** [comment]
> > Another important aspect where this matters is gla stealth buildings, especially palace, when not damaged, there's zero indicator that there's a building there without scanning
> 
> Well, isn't that the point? :D

For ZH devs, it was 😄 
But it's not a good game design, having all the advantages with no disadvantages for the opposing faction to respond to it.

**Comment by ExiLe-ZH** [comment]
> > > Another important aspect where this matters is gla stealth buildings, especially palace, when not damaged, there's zero indicator that there's a building there without scanning
> > 
> > 
> > Well, isn't that the point? :D
> 
> For ZH devs, it was 😄 But it's not a good game design, having all the advantages with no disadvantages for the opposing faction to respond to it.

So then...  remove all the stealth/stealth-detection mechanics from the game? 

Or make stuff visible and invisible at the same time, like "invisivisible"? 😄 

Or install speakerstowers on stuff to announce it's presence? like "ssshhsst, I'm demo trap and I'm right here" 

Sorry too much joking, but I'm failing to understand?

**Comment by MTKing4** [comment]
> > > > Another important aspect where this matters is gla stealth buildings, especially palace, when not damaged, there's zero indicator that there's a building there without scanning
> > > 
> > > 
> > > Well, isn't that the point? :D
> > 
> > 
> > For ZH devs, it was 😄 But it's not a good game design, having all the advantages with no disadvantages for the opposing faction to respond to it.
> 
> So then... remove all the stealth/stealth-detection mechanics from the game?
> 
> Or make stuff visible and invisible at the same time, like "invisivisible"? 😄
> 
> Or install speakerstowers on stuff to announce it's presence? like "ssshhsst, I'm demo trap and I'm right here"
> 
> Sorry too much joking, but I'm failing to understand?

See how other RTS games are made to understand.

**Comment by ZekeDlyoung** [comment]
Personally, I don't think this is much of a problem. I don't hear many complaints about this, so it is assumed that either people acknowledge it and just play around it, or they never noticed it in the first place.

I only ever saw this bug once, and that was while fighting Stealth General in challenge mode, it was how I ended up finding his last Palace to win the match 😛 

As for the specific points raised:
1. GLA has junk repair, so getting stealth vehicles back to full stealth isn't that hard to achieve
2. Agreed with the Comanche they are pretty strong already
3. Yes it looks silly, but you can say that about a lot of things in the game 🙃 

If people do insist on doing something about it. Perhaps we can make damage fx particles only appear for a few seconds after reaching the damaged state and then stop, similar to how damage smoke from RA2 units goes away after a while.

It is kinda silly how damaged buildings just constantly burn without taking additional damage, or how the building personnel would just leave the fire burning without trying to put them out 🤷 

EDIT: Making the particles temporary will have the secondary effect of making game performance slightly better

**Comment by commy2** [comment]
@ above
? Wrong issue? 
This is about GPS scrambled units. Have we even confirmed their smoke columns are visible when damaged?

**Comment by DoMiNaToRuk2** [comment]
Keep like it is
