### ISSUE TITLE
GLA Demo Bike applies damage to ALLIES before Demo Upgrade

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#775]
GLA Demo Bikes applies damage to ALLIES before Demo Upgrade

|                       |  Damages ALLIES |
|-|-|
| Demo Terrorist without Upgrade  |  |
| Demo Terrorist with Upgrade  |  |
| Demo Bike without Upgrade  | x  |
| Demo Bike with Upgrade  |  |
| Regular Terrorist  | x |
| Regular Terror Bike | x |
| Stealth Terror Bike | x |

### Proposal 1
Demo Bike without Upgrade no longer damages allies.

### Proposal 2
Demo Terrorist without Upgrade damages allies.

**Comment by commy2** [comment]
So does the Bomb Truck. Not sure that isn't the preferred behaviour.

**Comment by xezon** [comment]
I am ok with that, but then should the Demo Terrorist apply friendly damage before upgrade too. Right now behavior is inconsistent.

**Comment by commy2** [comment]
I agree that would make for a better game, but it is a departure from what people are used to about Demogen. Suicide Demolitions upgrade does not damage allies either.

**Comment by ExiLe-ZH** [comment]
> I am ok with that, but then should the Demo Terrorist apply friendly damage before upgrade too. Right now behavior is inconsistent.

Only tox terrorists deal friendly damage on each other, this is used to tech terror moving armies really easy. Can just drive in without needing to forcefire.

Doesn't make sense tox has it, should be rather demo, though at same time it causes terrorists to explode prematurely causing buildings not to die (everyone knows this one and we discussed widely already). But this isn't exactly an advantage so I guess none of the terrorists should do this. Also for consistency.

**Comment by xezon** [comment]
### Proposal 1
Demo Bike without Upgrade no longer damages allies.

### Proposal 2
Demo Terrorist without Upgrade damages allies.

**Comment by MTKing4** [comment]
Proposal 1, Consistency

**Comment by Jundiyy** [comment]
Yep, think proposal 1. Although not 100% sure.

**Comment by ExiLe-ZH** [comment]
So what about the other balancing proposal of making DB's chain react? Then only proposal 2 works and it would inflict damage on all allies right?

**Comment by DoMiNaToRuk2** [comment]
Proposal 1
