### ISSUE TITLE
China Satellite Hack II has no indicator as to when it reveals the shroud

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#782]
China Satellite Hack II has no indicator as to when it reveals the shroud.

### Proposal 1
Implement a countdown indicator (not possible).

### Proposal 2
Make Satellite Hack II an interactive Special Power like USA Satellite Scan.

**Comment by commy2** [comment]
Sathack 1 is always on. It's just bugged and never reveals Command Centers that were build after the upgrade or Internet Center with upgrade was build.

I like the idea of turning Sathack 2 into a carbon copy of the Strategy Center CIA Intelligence, but that seems to be a rather big change. Although I can't really think of anyone that likes how it's seemingly random currently.

**Comment by MTKing4** [comment]
I think it would be welcomed by many if it was like the USA CIA scan, so i go with Proposal 2

**Comment by Jundiyy** [comment]
Yes true,
Although that does bring more questions.
Would a side button be made?
If so, then would there be enough slots?
Would it break GC maps and other mission maps?

Perhaps a button in the IC alone would be enough?

**Comment by xezon** [comment]
Button Slots are enough. USA Airforce is the only General that can use all 11 in theory.

**Comment by Jundiyy** [comment]
Yes, I would prefer button alone.

**Comment by MTKing4** [comment]
If a side button doesn't have side effects or break anything then it is preferred, otherwise just having it in IC is fine as well
