### ISSUE TITLE
Anthrax Beta Decreases Radius of Effect of Small Poison Clouds

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#794]
The small green poison cloud has a radius of 12:

https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Weapon.ini#L3458
https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Object/System.ini#L1927

The small blue and pink poison clouds have a radius of 7.5.

https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Weapon.ini#L3543
https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Weapon.ini#L5478
https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Object/System.ini#L2088
https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Object/GC_Chem_GLASystem.ini#L158
https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Object/ChemicalGeneral.ini#L19515

This means that green poison can affect more units in a blob.
Doesn't sound like much of a difference, but because radius goes into area squared, the green cloud is actually 2.56 times larger than the blue and pink poison clouds.

(Note that GC_Chem_PoisonFieldGammaSmall is created for Toxin General in skirmish and multiplayer, while Chem_PoisonFieldGammaSmall is unused.)

Small poison clouds are created mainly by Toxin Shells.

**Comment by xezon** [comment]
What units create green clouds and what units create blue clouds?

**Comment by commy2** [comment]
Small poison clouds are created by Toxin Shells (Scorpion and Marauder) and the Toxin General Terrorist. They are also created when a Toxin Truck is blown up.

The color for these depends only on the upgrades and __not__ on faction:

```
If Anthrax Gamma 
    -> pink
elif Anthrax Beta 
    -> blue 
else
    -> green
```

- Demo Scorpion and Demo Marauder cannot use Toxin Shells.
- In 1.04, the Toxin  Terrorist creates no poison cloud without Anthrax Beta or Gamma, but that is fixed in main [it's green now].
- If a vGLA, Stealth or Demo Toxin Truck is vet 3, it will create a small blue poison cloud even without Anthrax Beta [main]
- If a Toxin General Toxin Truck is vet 3, it will create a small pink poison cloud even without Anthrax Gamma [main]

**Comment by MTKing4** [comment]
What about toxin tractor?

**Comment by xezon** [comment]
### Proposal 1
Make green small poison as large as blue small poison (7.5, 7.5, 7.5)

### Proposal 2
Make blue, pink small poison as large as green small poison (12, 12, 12)

### Proposal 3
Take a middle value of 12, 7.5, 7.5 and make them all the same size (9, 9, 9)

### Proposal 4
Swap green small poison size with pink small poison size (7.5, 7.5, 12)

**Comment by commy2** [comment]
> What about toxin tractor?

The stream weapon will not create any poison cloud. The sprinkler creates a medium sized poison cloud, not a small one. It will however create a small poison cloud when blown up.

**Comment by commy2** [comment]
Realistically, this affects only vGLA, because blown up Toxin Trucks really don't matter, and the green Toxin Terrorist will never happen in a serious game in the next 10 thousand years.

**Comment by MTKing4** [comment]
Bomb truck, scud launcher?

**Comment by commy2** [comment]
Bomb Truck and Scud Launcher both create a medium sized poison cloud, which is not affected by this.

**Comment by penfriendz** [comment]
No buffs to tox. Nerfs are ok for gla. Proposal 1.
