### ISSUE TITLE
Anthrax Gamma Poison Clouds Deal Same Damage As Anthrax Beta Poison Clouds

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#799]
In 1.04, Anthrax Gamma does not increase the damage of poison fields.

| Damage       | Green | Beta/ Blue | Gamma/ Pink |
|--------------|-------|------------|-------------|
| Small        | 2     | 2.5        | 2.5         |
| Medium       | 2     | 2.5        | 2.5         |
| Large        | 15    | 25         | 25          |
| Anthrax Bomb | -     | 40         | 40          |

This means that Scorpoins and Marauders benefit in no way from Anthrax Gamma, even though the Toxin Shells change their colour. As far as poison fields go, the upgrade is entirely cosmetic.

**Comment by commy2** [comment]
- Related to: https://github.com/TheSuperHackers/GeneralsGamePatch/issues/794

**Comment by xezon** [comment]
## Proposal 1
| Damage       | Green | Beta/ Blue | Gamma/ Pink |
|--------------|-------|------------|-------------|
| Small        | 2     | 2.25       | 2.5         |
| Medium       | 2     | 2.25       | 2.5         |
| Large        | 15    | 20         | 25          |
| Anthrax Bomb | 35    | 37.5       | 40          |

## Proposal 2
| Damage       | Green | Beta/ Blue | Gamma/ Pink |
|--------------|-------|------------|-------------|
| Small        | 2     | 2.5        | 3           |
| Medium       | 2     | 2.5        | 3           |
| Large        | 15    | 20         | 25          |
| Anthrax Bomb | 30    | 35         | 40          |

## Proposal 3
| Damage       | Green | Beta/ Blue | Gamma/ Pink |
|--------------|-------|------------|-------------|
| Small        | 1.5   | 2          | 2.5         |
| Medium       | 1.5   | 2          | 2.5         |
| Large        | 15    | 20         | 25          |
| Anthrax Bomb | 30    | 35         | 40          |

**Comment by xezon** [comment]
Real Gamma Upgrade Bonuses are (in Original 1.04):
```
+25% damage for Toxin Rebels
+30% damage for RPG Trooper
-29% damage for Terrorists (yes minus)
+25% damage for Toxin Tunnels
+64% damage for Toxin Trucks
+10% damage for Scud Storms
+100% damage for Stinger Sites vs ground
+66% damage for Stinger Sites vs air
- no change for Bomb Truck
- no change for Scud Launcher
- no change for Tox Demo Trap
```
