### ISSUE TITLE
Nationalism and Patriotism Work Without Horde

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#810]
Nationalism and Patriotism are a +25% RATE_OF_FIRE bonus for all units that can horde (Battle Master, Red Guard, Minigunner, Tank Hunter) regardless of whether they are currently horded or not. A single Tank Hunter will fire faster once Nationalism has been upgraded, no horde needed.

**Comment by ZekeDlyoung** [comment]
Afaik, this can't really be fixed. Mods who found it simply modified the upgrade's description to inform players about it

**Comment by xezon** [comment]
How do we know HORDE should have been a requirement for both of these to be active?

**Comment by MTKing4** [comment]
That is actually a huge buff, and big Hidden trick that not even experts know about 😄 , i always get Nationalism/Patriotism. Good to know

**Comment by commy2** [comment]
> How do we know HORDE should have been a requirement for both of these to be active?

1. The tooltip say so: "+25% to Horde bonus for Red Guard, Tank Hunter and Battlemaster" and "Additional +25% to Horde bonus"
2. Because with Nationalism, the Horde decal gets yellow circle, and with Patriotism it gets a white star.

> i always get Nationalism/Patriotism

It's +25% DPS for Tank Hunters flat. If you get AP Rockets as GLA for RPG Soldiers, then you should also get Nationalism/Patriotism for Tank Hunters.

> Afaik, this can't really be fixed.

Best idea I can come up with is making Nationalism an upgrade to the weapon set, and then giving the upgraded weapon a HORDE RATE_OF_FIRE bonus of 175, which, together with the 125 of gamedata.ini, averages to 150. But that won't work well with Patriotism on top of that. I am for just updating the tooltip.

**Comment by xezon** [comment]
Updating the tooltip sounds ok to me.

**Comment by xezon** [comment]
So just reword both to

"+25% damage bonus for Red Guard, Tank Hunter and Battlemaster"

?

Is there any functional difference between Nationalism and Patriotism ?

**Comment by ZekeDlyoung** [comment]
Nationalism increases rate of fire not damage, Frenzy is the one that increases damage

Nationalism and Patriotism are essentially the same (+25% RoF), but Patriotism stacks with Nationalism giving 50% overall RoF increase

**Comment by commy2** [comment]
I would expect it to be +56.25% ROF, because multiplication.

**Comment by xezon** [comment]
Doesn't a 25% increase in Rate of Fire result in 25 % more damage (DPS)?

**Comment by commy2** [comment]
> Doesn't a 25% increase in Rate of Fire result in 25 % more damage (DPS)?

It does. Things become more complicated once you consider firing while moving or kiting battles like anything vs Vees.

**Comment by ZekeDlyoung** [comment]
Is the translation from RoF to Damage really so direct?

I assumed there would be differences depending on the weapon 🤔

**Comment by commy2** [comment]
> I assumed there would be differences depending on the weapon

damage/time = damage/shot * shots/time

Assuming no frame cap issues (i.e. slow firing weapon), DAMAGE bonus == RATE_OF_FIRE bonus in terms of DPS.

**Comment by xezon** [comment]
So labeling it with with +25% damage is fine, or is there a precedent where a tool tip explicitly specified Rate Of Fire?

**Comment by commy2** [comment]
> Laser-lock improves missile rate of fire

> Battlemaster receives an increased rate of fire (Autoloader)

> Heals your forces and increases firing speed\n\nPower Required: 1 (Speaker Tower)

**Comment by xezon** [comment]
Ok then we can use rate of fire wording.
