### ISSUE TITLE
China Nuke Cannon has weak armor

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#811]
China Nuke Cannon has weak armor. It appears small things like a Rocket Buggy or a lousy RPG Trooper can take it out in no time. Coupled with the deployment times and the small movement speed, this makes the units very vulnerable. Maybe this should be looked into.

## Stats

WIP

**Comment by commy2** [comment]
Tomahawk 180 health TruckArmor
Inferno Cannon 120 health TankArmor
Nuke Launcher 240 health TankArmor
Scud Launcher 180 health TruckArmor

```
Armor TankArmor
  Armor = SMALL_ARMS         25%
  Armor = GATTLING           10%      ;resistant to gattling tank
  Armor = INFANTRY_MISSILE  100%
  Armor = COMANCHE_VULCAN    25%
  Armor = FLAME              25%
  Armor = RADIATION          50%      ;Radiation does less damage to tanks.
  Armor = POISON             25%      ;Poison does a little damage, just for balance reasons.

Armor TruckArmor
  Armor = SMALL_ARMS        50%
  Armor = GATTLING          50%    ;resistant to gattling tank
  Armor = COMANCHE_VULCAN   50%
  Armor = INFANTRY_MISSILE  50%
  Armor = FLAME             100%
  Armor = RADIATION         100%
  Armor = POISON            50%
```
If anything, I think the Inferno is too fragile. It takes 3 RPG missiles to kill an Inferno, but 9 to kill a SCUD Launcher/Tomahawk.

**Comment by MTKing4** [comment]
How much do buggies have?

**Comment by commy2** [comment]
120 TruckArmor, so 6 RPG missiles.

**Comment by xezon** [comment]
Maybe a new "ArtilleryArmor" for China Artillery?

```
Armor ArtilleryArmor
  Armor = SMALL_ARMS         25%
  Armor = GATTLING           10%      ;resistant to gattling tank
  Armor = INFANTRY_MISSILE   50%
  Armor = COMANCHE_VULCAN    25%
  Armor = FLAME              25%
  Armor = RADIATION          50%      ;Radiation does less damage to tanks.
  Armor = POISON             25%      ;Poison does a little damage, just for balance reasons.
```

**Comment by MTKing4** [comment]
> 120 TruckArmor, so 6 RPG missiles.

Then so should the inferno tank the same, 6 RPG missiles, as they're considered the Chinese counterpart of buggies.

I assume Xezon's suggestion does just that, so it sounds good to me, if it's possible.

**Comment by xezon** [comment]
Yeah basically doubling Armor against RPG so that

Inferno kill with 6 RPG
NukeCannon kill with 12 RPG
Tomahawk/SCUD with 9 RPG

**Comment by ExiLe-ZH** [comment]
> Maybe a new "ArtilleryArmor" for China Artillery?
> ```
> Armor ArtilleryArmor
>   Armor = SMALL_ARMS         25%
>   Armor = GATTLING           10%      ;resistant to gattling tank
>   Armor = INFANTRY_MISSILE   50%
>   Armor = COMANCHE_VULCAN    25%
>   Armor = FLAME              25%
>   Armor = RADIATION          50%      ;Radiation does less damage to tanks.
>   Armor = POISON             25%      ;Poison does a little damage, just for balance reasons.
> ```

Thats kinda cool idea actually, think it should be same as tank armor, but with truck rpg resistance.

Edit: ah that's exactly what you did

**Comment by xezon** [comment]
Pure Diff.

```
Armor TankArmor
  Armor = SMALL_ARMS         25%
  Armor = GATTLING           10%
  Armor = COMANCHE_VULCAN    25%
  Armor = FLAME              25%
  Armor = INFANTRY_MISSILE  100%
  Armor = RADIATION          50%
  Armor = POISON             25%
End
```

```
Armor TruckArmor
  Armor = SMALL_ARMS         50%
  Armor = GATTLING           50%
  Armor = COMANCHE_VULCAN    50%
  Armor = FLAME             100%
  Armor = INFANTRY_MISSILE   50%
  Armor = RADIATION         100%
  Armor = POISON             50%
End
```

```
TankArmor is 100% better vs SMALL_ARMS
TankArmor is 400% better vs GATTLING
TankArmor is 100% better vs COMANCHE_VULCAN
TankArmor is 300% better vs FLAME
TankArmor is 100% worse  vs INFANTRY_MISSILE
TankArmor is 100% better vs RADIATION
TankArmor is 100% better vs POISON
```

**Comment by xezon** [comment]
Nothing needs to be changed.
