### ISSUE TITLE
GLA Toxin Tractor does not change model correctly when scrapped

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#814]
GLA Toxin Tractor does not change model correctly when scrapped.

Enlima29
> It is supposed to be like this. Bigger side barrels on first salvage. Is easily fixable through ini coding.

![gla_toxin_tractor_upgrades](https://user-images.githubusercontent.com/4720891/182851206-4ff90fc2-a61e-4a7e-94e2-97d794cd3d5f.jpg)

**Comment by commy2** [comment]
pimp my tractor
