### ISSUE TITLE
China Propaganda Tower is rarely used

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#818]
China Propaganda Tower is rarely used.

## Stats
BuildCost 500
BuildTime 10
Requires 1 Power (1/10 of Power Plant)
Requires Propaganda Center

## Why is it not used so much?
It is used much less than Tunnel Networks, Bunkers and Firebases. Rarely it is dropped at a defensive line near a forward supply stash as extra defensive boost. For Infantry General it is next to useless, because all Outposts emit Propaganda already. The Propaganda Center requirement means it is not eligible for early game. And 500 cost is not particularly cheap to spam with. It also does not take much to destroy it.

## What would making it more accessible mean?
Propaganda Tower would mainly boost China defense if it was more accessible. It can be placed next to Warfactory to defend against powerful Humvee or Combat Chinook rushes. It can be placed next to Airfield to repair Migs and Helixes faster. It can be placed next to Bunkers to make Rocket Soldiers shoot more. It can be placed at strategic positions in Home Base to boost defensive units.

Related:
* #640
* #745

### Proposal 1
Reduce Propaganda Tower cost.

### Proposal 2
Change Propaganda Center requirement to Warfactory or Airfield requirement. Other Propaganda things can also be build before Center, for example Infantry Outpost and Helix Propaganda Upgrade.

### Proposal 3
Make Speaker Tower repair structures after Subliminal upgrade.

**Comment by ZekeDlyoung** [comment]
Unpopular suggestion: Make Speaker Towers able to repair buildings after Subliminal Messaging upgrade

**Comment by ExiLe-ZH** [comment]
It's a good building already, no need to buff it in any way, it's on the players themselves to underrate it.

**Comment by ExiLe-ZH** [comment]
Smart players like excal already use it

**Comment by commy2** [comment]
Do nothing. Works fine as is. It already heals twice as fast as other speaker towers (except Assault Troop Crawler).

In main, you can equip it with mines.

**Comment by penfriendz** [comment]
What's its radius? Can we remove the power requirement?

**Comment by ExiLe-ZH** [comment]
You can downvote xezon but it's the truth, it is a valuable building. Not having a (some sort of) Speakertower with your main army or defensive perimeters is surely a mistake.

For other purposes like having one near each Supply or Airfield the investment might be a bit much (while it's already useful), so maybe a price reduction to 400 might be justified  (matching a Demo Trap).

Anyways, I do like the idea of using it in the early game to defend against Humvee rushes, self healing Gats would definitely help, because currently a Gat is completely out of the battle when going for repairs. It usually goes downhill fast for China when he losses/misses like 2 Gats. Low health Gats are also useless (below 70% health), they're picked off too easy.

**Comment by xezon** [comment]
I down-voted your comments because they are misleading for the purpose of our work. Claiming something is good as is on the basis of the best player in the game using them in some matches to defend with China against weaker opponents is a poor statement to make. There is no doubt that the best player will make it look effortlessly as he plays with any faction, as his opponents will naturally be weaker players.

There is no evidence that Propaganda Towers are widely used in competitive matches. I think I have not seen one of them in any World Series tournament match I have observed. And World Series is the highest competition, surely they would be used there by the best players if they were so good.

As we can see by the opening post, they are not very accessible, so by the time a player can build Overlord, he might as well just buy a Propaganda Tower on the Overlord for 500 instead of an immobile Tower in his home base. And with China Infantry it makes almost no sense to build them, as all Outposts have it.

**Comment by commy2** [comment]
> What's its radius? 

All speaker towers are 150, except Infantry Attack Outpost, which is only 75 and Assault Troop Crawler which is 100.

It's also worth noting that Speaker Tower building as well as Assault Troop Crawler heal twice as fast as other speaker towers do.

> Can we remove the power requirement?

Technically feasible.

**Comment by ExiLe-ZH** [comment]
> I down-voted your comments because they are misleading for the purpose of our work. Claiming something is good as is on the basis of the best player in the game using them in some matches to defend with China against weaker opponents is a poor statement to make. There is no doubt that the best player will make it look effortlessly as he plays with any faction, as his opponents will naturally be weaker players.

And it's exactly because of details like this why Excal is better than opponents. 

> There is no evidence that Propaganda Towers are widely used in competitive matches. I think I have not seen one of them in any World Series tournament match I have observed. And World Series is the highest competition, surely they would be used there by the best players if they were so good.

It's not a flaw of the game if good stuff isn't utilized. Players themselves need to do better research on their own and be more creative in experimenting with unpopular stuff. Or they simply need to look at better players, naming Excal as example again.

> As we can see by the opening post, they are not very accessible, so by the time a player can build Overlord, he might as well just buy a Propaganda Tower on the Overlord for 500 instead of an immobile Tower in his home base. And with China Infantry it makes almost no sense to build them, as all Outposts have it.

This is true, maybe there's some sort of advantage needed over Proplords/AOP's. That said, vOverlords/Emperors are just too slow and easily sniped by Jarmen (and insta capped with ambush), vs GLA Proptowers are definitely better.

**Comment by xezon** [comment]
No doubt Prop Tower is good. But it is inaccessible.

**Comment by MTKing4** [comment]
I Think lower down the build requirements to WF or Airfields should be enough to make it useful, i think it is needed the most in early battles Vs Vees and when Pushing GLA.

**Comment by ExiLe-ZH** [comment]
> No doubt Prop Tower is good. But it is inaccessible.

Just as (in)accessible as any other post tech unit/building/upgrade.

But it's interesting to test improved accessibility, as potential counter candidate for USA No Eco's.

Rebalancing idea: Pre-tech available, but smaller radius, Subliminal messaging increases radius again (maybe bigger than original, to support bigger armies late game).
