### ISSUE TITLE
China Battlemaster is rarely used

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#819]
China Battlemaster is rarely used. It drives slow.

Change that is good for Battlemaster already:
* #412
* #1815

## Original Movement Stats

| Object                              | Speed |
|-------------------------------------|-------|
| China Battlemaster                  | 25    |
| China Battlemaster Upgraded         | 35    |
| Tank China Battlemaster             | 25    |
| Tank China Battlemaster Upgraded    | 35    |
| Nuke China Battlemaster             | 45    |
| China Overlord                      | 20    |
| China Overlord Upgraded             | 30    |
| Tank China Emperor                  | 20    |
| Tank China Emperor Upgraded         | 30    |
| Nuke China Overlord                 | 40    |
| China Dragon Tank                   | 30    |
| China Gattling                      | 40    |
| China Outpost                       | 40    |
| China ECM                           | 40    |
| USA Crusader                        | 30    |
| USA Humvee                          | 60    |

## Original Weapon Stats

DPS based on damage since they all have similar RoF and all
DPU = depleted uranium shells
AL = autoloaders
WGU = weapons grade uranium shells (cut upgrade)

| Object                               | DPS                     |
|--------------------------------------|-------------------------|
| China Battlemaster                   | 60                      |
| China Battlemaster + DPU             | 75                      |
| Tank China Battlemaster              | 60                      |
| Tank China Battlemaster + DPU        | 75                      |
| Tank China Battlemaster + AL         | 120 (40x3)              |
| Tank China Battlemaster + AL + DPU   | 150 (50x3)              |
| Nuke China Battlemaster              | 60 + Radiation          |
| China Overlord                       | 160 ( 80x2)             |
| China Overlord + DPU                 | 200 (100x2)             |
| Tank China Emperor                   | 160 ( 80x2)             |
| Nuke China Overlord                  | 160 ( 80x2) + Radiation |

### Proposal 1

Increase movement speed. Done with
* #1815

### Proposal 2

Increase movement speed with Nuclear Tanks upgrade. Done with
* #1815

### Proposal 3

Add radiation puddle with Uranium Shells upgrade.

### Proposal 4

Reduce cost

**Comment by xezon** [comment]
Looks safe to me to raise movement speed to at least 29 to match China Tank Battlemaster.

**Comment by commy2** [comment]
(fixed an error in OP - Tank Emperor w/o upgrade)

**Comment by commy2** [comment]
25 is unfortunate for BM, as its main use is countering flanking Dragons, but they can escape, because they are faster.

**Comment by MTKing4** [comment]
I think making:
Vchina BM 30 upgrading to 35
Overload 25 upgrading to 30
Would be a good change

**Comment by ExiLe-ZH** [comment]
About 20% increase for both Vanilla BM & Overlord.

vBM 30 to 40 upgraded.
vOverlord 25 to 35 upgraded.

> I think making: Vchina BM 30 upgrading to 35 Overload 25 upgrading to 30 Would be a good change

I feel the upgrade difference (+5) is a bit too small.
If my numbers (+10) are too big then +7.5 could also maybe feel right.

**Comment by MTKing4** [comment]
Maybe, we could start with any of these numbers and dial back if it's too much then

**Comment by xezon** [comment]
> I think making: Vchina BM 30 upgrading to 35 Overload 25 upgrading to 30 Would be a good change

This also looks reasonable to me, however, where would that leave Tank General? He still would be as slow as before, and Vanilla China is better.

**Comment by ExiLe-ZH** [comment]
> > I think making: Vchina BM 30 upgrading to 35 Overload 25 upgrading to 30 Would be a good change
> 
> This also looks reasonable to me, however, where would that leave Tank General? He still would be as slow as before, and Vanilla China is better.

Should receive exact same treatment, so we have to be careful. With proposed changes (including my own) Tank might become too scary.

I'm actually changing my proposal: 

BM 27.5 > 36.5
OL/EMP 23.5 > 32.5

I know numbers are kind of odd, but I think it would feel right.

**Comment by xezon** [comment]
Weapon Stats added.

**Comment by xezon** [comment]
Enlima29
> my proposal for speed, adjust nuke general tank speed to be equal with Nuclear Tank upgraded speed, and give them the old speed with revived Fusion Reactor upgrade exclusive for Tao

> vanilla BM: 25
upgraded BM: 35 (nuclear tank upgrade)
Nuke BM: 35
Nuke upgraded BM: 45 (fusion reactor upgrade)

> vanilla overlord: 20
upgraded overlord: 30 (nuclear tank upgrade)
Nuke overlord: 30
Nuke upgraded overlord: 40 (new, fusion reactor upgrade)

Enlima29
> for some reason nuke general tanks didn't get dmg bonus from the free DPU because the bonus module is set to the wrong upgrade (WGU instead DPU)
some might argue that they got radiation fields in return, but since my goal here to make them equal to the upgraded china tanks stats, I propose to revive the WGU upgrade to mitigate the "lost" benefits
there are two ways I can think of:
> 1. keep the current weapon damage as is, then use the new WGU upgrade to make these tanks gets the missing +25% damage bonus post upgrade
Nuke BM: 60 + radiation
Nuke WGU BM: 75 + radiation
Nuke overlord: 160 (80x2) + radiation
Nuke WGU overlord: 200 (100x2) + radiation

> 2. make the nuke tanks damage same as DPU tanks damage (so it stays true to the nuke general perk description), but remove the radiation. then use the WGU upgrade to give them the radiation fields back
Nuke BM: 75
Nuke WGU BM: 75 + radiation
Nuke overlord: 200 (100x2)
Nuke WGU overlord: 200 (100x2) + radiation

> for me personally, I implemented the first one in my mod, but the second one feels more right for leveled upgrade progression
unless if you think the current stats is good then fine I guess

**Comment by MTKing4** [comment]
> > I think making: Vchina BM 30 upgrading to 35 Overload 25 upgrading to 30 Would be a good change
> 
> This also looks reasonable to me, however, where would that leave Tank General? He still would be as slow as before, and Vanilla China is better.

The same can be applied to tank of course

**Comment by Jundiyy** [comment]
Think Exile and MTKing have got it. Small increase for both but as mentioned, Tank night become too good.

**Comment by EnigmaZift** [comment]
30 speed would be perfect for the Battlemaster

**Comment by ExiLe-ZH** [comment]
Make price the same as Tank BM, think it's the least controversial thing to start with. Looking into pricing after other buffs makes no sense, it's a balance value just the EXP changes we did.

Do the same with Dragons and you have more competitive army already (will help vs GLA).

**Comment by commy2** [comment]
> the least controversial thing to start with

Uh, Tank is supposed to have the cheapest tanks. And there is nothing wrong with the price of Dragon Tanks either imo.

**Comment by ExiLe-ZH** [comment]
> > the least controversial thing to start with
> 
> Uh, Tank is supposed to have the cheapest tanks. And there is nothing wrong with the price of Dragon Tanks either imo.

That's true, however you could also say technology wise there's no difference between Tank and ChinaV, Tank just has the more experienced Tank crew. Nuke does have the better technology, so that could explain the higher price (same as the Nuclear Reactor as quick example).

700 Dragons would help alot vs all GLA's and a little bit vs Inf (in ChinaV mirror it's offset by cheaper BM again).

**Comment by ExiLe-ZH** [comment]
Overall Tank produces Gats the most, so there you can use the argument that Tank can produce them cheaper because it sources the materials for those units in higher quantities. < Gotta be bit creative with the logic sometimes :D

**Comment by xezon** [comment]
I think it is better to look at prices later. For Flame Tank we still need to look into Flame EXP.

**Comment by xezon** [comment]
Battlemaster drives faster now. Anything else we need to do or close?

**Comment by ExiLe-ZH** [comment]
Is it worth $800 now? If it is, then yes. 

Otherwise a price reduction is still optional.

**Comment by xezon** [comment]
Ok apart from price reduction, anything else to do?

**Comment by ExiLe-ZH** [comment]
maybe vet0 xp reduction, but that should be for all tanks from all factions, this doesn't affect tank gen.

**Comment by xezon** [comment]
Not clear to me if 700 price is ok. Looks cheap compared to the other tanks.

**Comment by ExiLe-ZH** [comment]
Same as Tank BM, but without the veterancy, so theoretically should be ok?

**Comment by xezon** [comment]
Cheap and vetted tanks is the main perk of Tank General, at the expense of no artillery units, expensive infantry and aircraft. Regular China has none of these penalties. We gave China already many other buffs, perhaps it is ok as is for now?

**Comment by ExiLe-ZH** [comment]
Not sure if it's needed for China as a faction, but what direct buffs has the vBM gotten so far? Only the speed one right? (the XP buff affects Tank mainly). Do we expect it to be used more often now? 

Now EA intended it to be a main battle tank, but ofcourse that shouldn't be our goal because that would be a complete meta change.

**Comment by xezon** [comment]
Perhaps we should compare key stats with the Crusader Tank to evaluate its relative strength.

**Comment by ExiLe-ZH** [comment]
We have to be careful not buffing Tank too much, because pretty much all stats are shared, except XP values.

**Comment by ExiLe-ZH** [comment]
I forgot vet0 was already -30% less with the general XP reduction for tanks. Then perhaps it could be closed for now, if price reduction is off the table.

**Comment by MTKing4** [comment]
I think that is it for now, I think the speed had a major role in its lack of use, maybe now it'll be more useful, if not we can visit the price reduction in the future
