### ISSUE TITLE
No Audio Visual Difference Between Suicide And Regular Death With Demolitions Upgrade.

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#850]
Background Demogen mechanics:
After Demolitions upgrade, if a Demogen unit is killed, it explodes with a small 50 damage that only hurts enemies and neutrals.
Alternatively, the player can suicide which does 500 instead and also only hurts enemies and neutrals.

The issue from a UI perspective is that there is almost no audio-visual difference between the two explosions. The same particle effects are used and the same explosion sound is played. One difference is that infantry will be flung into the air when suicided, but just collapse as normal when killed.

Since the damage is 50 vs 500, I think there should be better feedback given to the players what happened. I think the explosion should be smaller when killed.

Thoughts?

**Comment by Jundiyy** [comment]
Doesn't hurt me. Fine to show the difference.

**Comment by ExiLe-ZH** [comment]
> Doesn't hurt me. Fine to show the difference.

Doesn't hurt terrorist either. He's with 70 virgins.

**Comment by xezon** [comment]
The same applies to crushed explosion.
