### ISSUE TITLE
Faction Superweapon timers are inconsistent

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#853]
Faction Superweapon timers are inconsistent. The China Nuke Missile has the longest countdown timer. Is this a problem?

Other Superweapon reports
* #846
* #235
* #674
* #410

# Stats

## USA Particle Cannon
**Pros:**
* Best Countdown time of 4:00
* Good vs Buildings
* (Cheap for Superweapon General: 2500)

**Cons:**
* Requires Power
* Just OK vs Units

## China Nuke
**Pros:**
* Good vs Units

**Cons:**
* Worst Countdown time of 6:00
* Requires Power
* Just OK vs Buildings, ~~Bad vs GLA buildings~~

## GLA SCUD Storm
**Pros:**
* Good vs Buildings
* Good vs Units
* Does not reveal if its ready to fire
* (Camo Netting for Stealth General)

**Cons:**
* Takes twice as long to build with 120 seconds

**Neutral:**
* Countdown time of 5:00

**Comment by penfriendz** [comment]
1.06 swapped the scud and nuke timer, which imo is a pretty fair change. Making the nuke suck less is another option which can be considered in conjunction or as a substitution to this change.

**Comment by xezon** [comment]
If I am not mistaken timers are 6 minutes for China Nuke, and 5 minutes for the others? Reduction to 5 seems fair, especially because GLA SCUD Storm is much better anyway.

**Comment by penfriendz** [comment]
Yes, that's right.
1.04
Nuke: 6
Scud: 5
Particle cannon: 4

1.06
Scud: 6
Nuke: 5
PC: 4

Nuke needs 10 power (~1k for extra 20% cost), can be annoyed by power shutdowns and flat out sucks to really top it off.

Swapping the timer makes conceptual sense (as it's powered) and it can get a buff cos why not.

**Comment by commy2** [comment]
Scud Storm build time is 120 seconds, while Nuke Silo build time is only 60 seconds. Therefore, time from investment to initial shot is the same for them.

We already changed the Nuke Silo to damage holes on overkill.

I would not change anything about the Nuke further __at this point__.

My personal opinion is that the Demo Scud Storm (and to a certain extend the Gamma Tox Scud Storm) is/are overpowered and that is the actual issue with super weapon balance. However, we also decided that buff > nerf so I punt on this one.

**Comment by penfriendz** [comment]
I agree with your assessment that either the nuke is underpowered or that the demo and tox scud storm is overpowered. I don't think the hole change is enough to flip that but it is a good start. I will also defer

**Comment by Jundiyy** [comment]
I think Scud should be left, Nuke with the new change might be worth the time. We should wait and see.

**Comment by ExiLe-ZH** [comment]
> I think Scud should be left, Nuke with the new change might be worth the time. We should wait and see.

+1

If not, Nuke timer can be changed to 5min.

Should also be noted that buildtime obviously only affects the timing for the first shot. After that Scud can be shot more frequently than the Nuke with current cooldown.

**Comment by ImTimK** [comment]
> > I think Scud should be left, Nuke with the new change might be worth the time. We should wait and see.
> 
> +1
> 
> If not, Nuke timer can be changed to 5min.

Should also be noted that buildtime obviously only affects the timing for the first shot. After that Scud can be shot more frequently than the Nuke with current cooldown.

**Comment by ReLaX82** [comment]
It helped balancing out late game, yes to 1.06 changes.

**Comment by xezon** [comment]
With new Nuke Missile improvements, I think 6:00 Minute timer is okay for now.

**Comment by ExiLe-ZH** [comment]
> With new Nuke Missile improvements, I think 6:00 Minute timer is okay for now.

Agreed.

**Comment by xezon** [comment]
Closing for the time being. Can revisit if future data or feedback would indicates that China still has trouble in Superweapon battles.
