### ISSUE TITLE
China Satellite Hack One is not useful

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#854]
China Satellite Hack One is not useful. It spies permanently on Command Centers only. This discovery does not provide any significant intel on opponent. China Satellite Hack II spies on all enemy structures and units for a certain duration.

Related
* #708
* #837

### Proposal 1

Make Satellite Hack One see Supply Depots too, so it combines better with Cash Hack Generals Power.

### Proposal 2

Turn Satellite Hack One into Spy Power like USA Strategy Scan and have it reveal all structures only for a certain duration.

### Proposal 3

~~Keep all permanent Satellite Hack One benefits after Satellite Hack Two was researched. Can combine with Proposal 1.~~

**Comment by MTKing4** [comment]
I didn't know Sat hack II removes Sat Hack I
So i think proposal 3 for sure
Proposal 1 also seems nice, but might be revealing too much, not sure about it, 

Also Since Sat Hack II now Operates Manually, you can always time that with your cash hack, that being said, what's the cooldown for both?

**Comment by commy2** [comment]
Reveal mechanics in the game use the revealed object's VisionRange to clear fog. Command Centers have a comparatively large VisionRange of 300 compared to other buildings (mostly 200, so 2.25 times larger area than Barracks/Supplies/Factories/etc!). 

The revealed area is huge. Command Centers tend to be located in the back or center of a base, so a lot of structures and units around it are revealed as well.

I am confused by proposal 3. Sathack 2 does not cancel the effect of Sathack 1. Once the timer runs out on Sathack 2, the Command Center stays revealed (as long as it was build after the upgrade or Internet Center)

> I didn't know Sat hack II removes Sat Hack I

It does not.

**Comment by xezon** [comment]
[commy2](https://github.com/commy2) commented [23 minutes ago](https://github.com/TheSuperHackers/GeneralsGamePatch/pull/837#issuecomment-1208933250)

Sathack 2 does not permanently reveal Command Centers.

**Comment by commy2** [comment]
Yes, because Sathack 1 does^^

**Comment by commy2** [comment]
I am a purist on this one. Keep as is, only fix the bug (which already is fixed in main branch).

**Comment by xezon** [comment]
I think we need a screenshot of the Command Center range.

**Comment by Stubbjax** [comment]
My concern with Option 1 is that counterplay options for Cash Hack are already quite limited and removing visibility as a form of mitigation doesn't really leave room for much else.

**Comment by commy2** [comment]
> what's the cooldown for both [Cash Hack and Sat Hack II]?

Both have a cooldown of 4 minutes, so they should have good synergy, especially if both were manually activated and thus could be synched up.

**Comment by Stubbjax** [comment]
> > what's the cooldown for both [Cash Hack and Sat Hack II]?
> 
> Both have a cooldown of 4 minutes, so they should have good synergy, especially if both were manually activated and thus could be synched up.

Which could be a nice little hint for attentive players who hear Cash Hack go off and intuit the enemy having full visibility.

**Comment by xezon** [comment]
commy2:
> Assuming player keeps CC, Sathack 1 reveals 90% of the center spot bases on Defcon 6.
> Also reveals camo netted CC from Stealthgen. Doesn't detect it, but shows the area around it.

**Comment by MTKing4** [comment]
> > what's the cooldown for both [Cash Hack and Sat Hack II]?
> 
> Both have a cooldown of 4 minutes, so they should have good synergy, especially if both were manually activated and thus could be synched up.

Great, So the new Strat will be, once you get cash hack, you get the Sat Hack II upgrade, wait to finish, then use the combo, although it's not that cost effective paying $2500 to get only $1000 back, but that's fine because it will be repaid overtime, and vision is always good, even to combo with other genpowers.

**Comment by xezon** [comment]
Here is image of Satellite Hack One spy.

![shot_20220811_124810_1](https://user-images.githubusercontent.com/4720891/184117611-d726db6f-cafc-4521-81f1-6c97c0d18fb9.jpg)

Conclusion: Can see large area of base, potentially a Supply Stash for Cash Hack too. Can also see incoming General Promotions over the Command Center always. Looks useful.

Closing.

**Comment by ExiLe-ZH** [comment]
Tbh Sathack I should come with the IC for free.

Another cool idea for Sathack II is to make it scramble/disable enemy satellites, a literal takeover hack. Would make it worth the high price. 

Like it's already behind an extra paywall (needing IC) compared to USA, which gets it all for free after teching (following the natural tech tree), whereas China needs to either choose or get both the Prop+IC.

**Comment by MTKing4** [comment]
I wouldn't be totally against a free SatHack I upgrade, or at least a very cheap one, like 200

**Comment by AIR-Z** [comment]
The hack could also highlight the objects and resources being captured
