### ISSUE TITLE
GLA Bomb Truck reveals itself before reaching its attack target

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#855]
If you disguise Bomb truck as a unit then attack an enemy unit, where there's no stealth detection there, the bomb truck will reveal itself before reaching the target

Trick to avoid that is just driving there manually and press detonate when near the target

**Comment by commy2** [comment]
RevealDistanceFromTarget is currently 100 (which is the attack range of a Ranger/Red Guard/Rebel). Reducing this to 0 may remove this altogether.

I think this was added for readability, i.e. it would be strange for a player if apparently one of their units just blows up. I think the Bomb Truck wreck left behind should be obvious enough though.

I'm all for improving rarely used units by smoothing out their mechanics.

**Comment by xezon** [comment]
What happens if a GLA Bomb Truck is killed next to enemy forces?

**Comment by commy2** [comment]
It explodes alongside all units next to it.

**Comment by MTKing4** [comment]
Yes, it is Probably for Readability reasons, but it does render it useless versus many units

And it can be bypassed anyway if you didn't target any unit.

I think removing that reveal issue would make it more useful and used more often.

**Comment by xezon** [comment]
Ok, then this "RevealDistanceFromTarget" seems silly, as the best strategy is to click next to the bomb target, and not right onto it.

**Comment by xezon** [comment]
I think we can go ahead and test with either zeroed or reduced "RevealDistanceFromTarget" to see how this functions.
