### ISSUE TITLE
Only vChina And Nuke Have Cash Hack Promotions Ability

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#856]
China tank and Inf don't have it.

I think this ability is essential and must have on all China armies, similar to cash bounty.

### Proposal 1

Add Cash Hack as Level 5 Power

**Comment by commy2** [comment]
Cash Hack is only for China and Nuke, currently the weakest armies.

Infa and Tank have no space for it, since they have Minigunner and Battle Master paradrop respectively.

For the record, Boss has Bounty instead of Cash Hack too.

**Comment by MTKing4** [comment]
Should we Consider replacing one of the least used abilities with cash hack?
 
Possible replaceables:

**Frenzy
Emergency Repair**

**Comment by xezon** [comment]
I do not think we should do that before making the abilities themselves more useful.

**Comment by penfriendz** [comment]
Does inf have emergency repair? I would keep frenzy as that feels like an inf speciality, although it does need some love.

If inf has emergency repair cash hack could certainly replace it. Perhaps frenzy can also heal?

**Comment by commy2** [comment]
All factions have Emergency Repair (except Boss).
AFG, Stealth, Nuke and Tank have Emergency Repair 1 at rank 1.

**Comment by MTKing4** [comment]
> I do not think we should do that before making the abilities themselves more useful.

They can be made useful for other armies naturally, i just think cash hack is more valuable to have on these two

One possible solution but wouldn't be very consistent but it makes sense i think, depending on the use cases having either ability on either army

| Army | Emergency Repair | Frenzy |
|---------|---------|---------|
| Tank | Keep | Replace |
| Inf | Replace | Keep |

**Comment by penfriendz** [comment]
My proposal is to get rid of emergency repair for inf, replace it with cash hack and merge emergency repair and frenzy (and let frenzy heal infantry).

**Comment by xezon** [comment]
What is the rationale for replacing powers?

**Comment by ZekeDlyoung** [comment]
I'm pretty sure there is enough space on the GP menu for them to have at least one level of Cash Hack

EDIT: Perhaps if Emergency Repair Level 1 was moved to Rank 1, or if Tank/Minigunner drop lvl 3 was moved to rank 5.

Perhaps they can have lvl 3 cash hack at rank 5

**Comment by penfriendz** [comment]
Emergency repair and frenzy both kind of useless. Small buff to Inf by giving Inf more options and an improved frenzy. Difficult to say frenzy with heal will be OP given both frenzy and emergency repair are both not used.

**Comment by commy2** [comment]
As for Emergency Repair, I still favour this change:

https://user-images.githubusercontent.com/6576312/183606062-d778fc92-1e07-4328-92e5-7563cca69b56.mp4

**Comment by xezon** [comment]
We already have issue reports for rarely used Generals Powers. Fixing them by replacing them reads like a drastic strategy to me.

* #707 
* #709

**Comment by ZekeDlyoung** [comment]
Controversial suggestion: Combine emergency repair and frenzy GPs together for Tank and Inf (repair + damage bonus), call it "Intense Fighting Spirit" lvl 1-3 🙃

**Comment by ExiLe-ZH** [comment]
Please don't mess too much with original abilities and the distribution between factions, it already makes sense.

Best to improve the abilities themselves in a way that makes them more attractive and useful, but don't change the gameplay.

**Comment by MTKing4** [comment]
> I'm pretty sure there is enough space on the GP menu for them to have at least one level of Cash Hack
> 
> EDIT: Perhaps if Emergency Repair Level 1 was moved to Rank 1, or if Tank/Minigunner drop lvl 3 was moved to rank 5.
> 
> Perhaps they can have lvl 3 cash hack at rank 5

I think commy meant the Abilities menu won't have enough space, meaning the side cards, not promotions menu

> What is the rationale for replacing powers? 

As said above, Cash hack is the only Extra Help cashwise china gets besides secondary economy, USA has Supply lines, GLA has Worker Shoes + Cash bounty , therefore i think all chinas should have that, preferably without removing anything from the Abilities.

**Comment by xezon** [comment]
Level 5 Cash Hack would be an option, but it certainly would be a new feature, albeit not a big one.

**Comment by commy2** [comment]
> I think commy meant the Abilities menu won't have enough space, meaning the side cards, not promotions menu

I meant the promotions menu. Sidebar only uses 8 slots for both Tank and Nuke. Maximum configured is 10 for them, but an 11th slot can be made by editing the factions config (simple change) and iirc a 12th slot can be opened by making edits to the UI.

**Comment by MTKing4** [comment]
Yes, but can it be implemented?

**Comment by commy2** [comment]
> Yes, but can it be implemented?

It would need some ugly work-arounds, similar to normal&Stealthgen vs Demo vs Tox Rebel Ambush, but should be possible.

**Comment by alanblack166** [comment]
> iirc a 12th slot can be opened by making edits to the UI.
The limit is 11, it's a fixed array that cannot be changed without reverse engineering the entire Controlbar class.

**Comment by MTKing4** [comment]
How many is tank and inf are using on main?

**Comment by commy2** [comment]
8, 9 on the manual Sathack 2 branch.

**Comment by MTKing4** [comment]
Ok so we have 2 free slots for tank and 1 for inf?

**Comment by commy2** [comment]
3 if alan/hanfi is right (likely). 2 if manual Sathack II is accepted.

**Comment by commy2** [comment]
Edit: I was looking at the wrong thing.

**Comment by MTKing4** [comment]
Ok then adding Cash Hack to lvl 5 for tank and inf is possible

I think it's a good change

What do you guys think?

**Comment by Stubbjax** [comment]
Here are a few reasons why I'm not a fan:

1. Too conspicuous.
2. Level 5 should generally be reserved for 'impactful' powers.
3. Cash Hack is already underused at earlier levels.
4. Level 5 is too late for an economy booster.
5. Not an efficient / direct solution to economy issues.
6. Slightly reduces faction diversity.

**Comment by commy2** [comment]
There is a fifth open slot for rank 1 promotions. While rank 1 Cash Hack would be funny, I don't like changing the promotions screen unless there are very good reasons for it. I don't see any here.

I will grant though that it is weird how Infa completely lacks Cash Hack despite the hacking theme going on with Super Hackers and Super Lotus. Guess devs were meh on the ability too when deciding what to discard in favour of Minigunner/Tank Drop and Frenzy.

**Comment by Jundiyy** [comment]
I don't really like it as well, prefer to just make GPs better. Inf not having it doesn't seem that bad anyway, you have Super Hackers.
Not every faction has to have the same GP.

**Comment by xezon** [comment]
Adding a 5th Rank 1 Power will break Control Bar Pro Addon compatibility.

**Comment by MTKing4** [comment]
> Here are a few reasons why I'm not a fan:
> 
> 1. Too conspicuous.
> 2. Level 5 should generally be reserved for 'impactful' powers.
> 3. Cash Hack is already underused at earlier levels.
> 4. Level 5 is too late for an economy booster.
> 5. Not an efficient / direct solution to economy issues.
> 6. Slightly reduces faction diversity.

1. And why is that bad?
2. It does have an impact though, especially at late game stalemate situations.
3. It's pretty much always picked when china or nuke, albeit only at rank 5, when everything that's better already been taken, this statement supports point 2.
4. As i said Earlier, people already use it on Rank 5 right now, for the lack of a better choice, last point always goes to cash hack
5. It's not a solution, just a bit of help, it's Cash Bounty's Counterpart for china
6. That is true

**Comment by Stubbjax** [comment]
1. Higher visibility = more controversy = lower chance of patch acceptance. Subtle changes should be prioritised.
2. By 'impactful' I mean high % game-changers, like EMP Pulse, Sneak Attack, Anthrax Bomb, Fuel Air Bomb, etc.
3. My experience does not match yours. It's most commonly Training / Nuke Cannon + Carpet Bomb + 3 Artillery + Cluster Mines + EMP Pulse.
4. ^
5. Regardless, it is an attempt to address a problem that can be addressed (and has been addressed) in better ways. Generals promotions are not supposed to be used as crutches. Hackers already end up out-earning USA and China as compensation for Cash Bounty / Worker Shoes / Supply Lines (amongst other tradeoffs).

**Comment by xezon** [comment]
Cash Hack Power is not a big deal and Tank + Inf do not necessarily need it. Inf has stealthed Super Hackers and for Tank we already gave cheaper Hackers and other Hacker perks to become competitive. Closing for now to concentrate on more important tasks.
