### ISSUE TITLE
Mob Death Scream Glitches

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#866]
- Both Women scream like GLA male when poisoned.
- No scream when burned.
- Obese man screams like woman, because he is a "reskin" of a woman mobster.

**Comment by commy2** [comment]
Obese guy still screams with female voice. He needs his own ini config.

**Comment by ExiLe-ZH** [comment]
New issue report: Obese guy doesn't lose weight after running 100 miles.

**Comment by Jundiyy** [comment]
Lol haha.
