### ISSUE TITLE
Balancing GLA ambushes?

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#872]
1. Should Tox spawn same amount of Rebels as Demo? Currently it's like so:
GLA, Tox, Stealth: 4/8/16 
Demo: 4/6/10

2. Add self-detonation timer upon spawn for Demo Rebel Ambush, same like a Tank Hunter can't instantly use his TNT charge from the Barracks. Could be fast like half a second, so that:
- Player has to predict where to spawn the Ambush if he decides to Ambush a moving army.
- Vs stationary army the player has to move along or split with the army, if enemy were to react. > Adds a tiny micro element.

3. Do nothing, nerfs are bad.

**Comment by xezon** [comment]
Too many topics for one report.

**Comment by ExiLe-ZH** [comment]
> Too many topics for one report.

Or too many reports for one topic? ^^

**Comment by xezon** [comment]
1. I think it's fine. Toxin Rebel Ambush is fun. Can be crushed and sniped and flamed. It is not as good as Demo Ambush.
2. Maybe this is not necessary with all the buffs we hand out to the competition.

**Comment by ExiLe-ZH** [comment]
> 1. I think it's fine. Toxin Rebel Ambush is fun. Can be crushed and sniped and flamed. It is not as good as Demo Ambush.
> 
>     2. Maybe this is not necessary with all the buffs we hand out to the competition.

Think Tox Rebel Ambush is very overpowered, it can level entire armies within a split second. Like Vees, Avengers, Outposts, Gats, Buggies, Inferno's, even Overlords (especially with Jarmen Combowombo). Besides damage output in these numbers, the disruption it causes makes it much worse (units automatically turning to kill the rebels whilst battling other armies).

Counter argument it's one of the few one-click destructive powers for GLA.

**Comment by Jundiyy** [comment]
Whilst both Ambushes are strong, I don't think we should change. GLA has the Tox Bomb and Ambush that deal actual damage.
Only GLA and Stealth have basic Ambushes. Leaving them with just a Tox Bomb.

**Comment by xezon** [comment]
Can we agree to close this for the time being? It may be better to keep focus on buffing weak things instead of nerfing strong things. As for Toxin General, we did identify other things already that are more universally OP, such as very high Gamma Upgrade bonuses and RPG Stingers.

**Comment by commy2** [comment]
adjourned

**Comment by MTKing4** [comment]
I like the delay idea for demo ambush, but what would make an inconsistency and leads to another question, should all demo units have that detonation delay when created? So that it's more consistent

I think for toxin we could do a similar thing, if possible, make toxin rebels unable to shoot for half a second when first Spawned, that would be ideal

**Comment by ExiLe-ZH** [comment]
Could do demolition delay for every unit upon spawn, same like the TNT-Charge from the TH e.g.

Tox Ambush not being able to shoot for half a second would probably be balanced, like they still distract units which in itself can already change engagements (or steal a sniped unit). However it's also weird at the same time that they can't use their main weapons while all other ambushes can and players might experience it as being unresponsive or buggy.

Maybe some reversed spawn protection could also work, where they do shoot their guns, but inflicting no or less damage within a certain timeframe.
