### ISSUE TITLE
Immortal Stealthed Objects Which Draw Fire Flying Above Townes Base Entrances

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#898]
![shot_20220814_135845_2](https://user-images.githubusercontent.com/6576312/184535745-f711a6ef-d1c3-4cec-91e1-c2c8ed5ab58b.jpg)

Annoying.

**Comment by Jundiyy** [comment]
Agreed. I'm sure it was some mistake, unless they wanted to do prank the players somehow.
