### ISSUE TITLE
Chemical Bunker Toxin Colors

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#899]
This bunker continuously spills blue poison while damaged, and explodes blue when destroyed, but then leaves behind a green cloud.
![shot_20220814_140447_4](https://user-images.githubusercontent.com/6576312/184536141-df5c7afd-fc4f-4748-907f-4bb629a2584b.jpg)
![shot_20220814_140457_7](https://user-images.githubusercontent.com/6576312/184536154-78926331-544e-437c-9adb-2978230418aa.jpg)

**Comment by xezon** [comment]
Which map is this? Do we know the asset name?

**Comment by Jundiyy** [comment]
This looks like challenge mode vs Toxin.

There are 3 types of bunkers, can see a few on ranked maps.

**Comment by commy2** [comment]
> Which map is this?

Toxin Challenge. You can get to him fast by picking Tank.

**Comment by xezon** [comment]
We need to open it in World Builder to inspect the asset name and then search for it in INI.

**Comment by Jundiyy** [comment]
https://www.gamereplays.org/community/index.php?s=&showtopic=1028518&view=findpost&p=10260444

**Comment by commy2** [comment]
Three objects have this setup:

ChemicalBunker
PharmaceuticalFactory
ChemicalFactory

All three spawn small blue clouds when damaged, medium blue clouds when "really damaged" and green Anthrax Bomb cloud when destroyed.

ChemicalBunker and PharmaceuticalFactory use the blue Bio Bomb+ HE Bomb Bomb Truck explosion, while the ChemicalFactory uses the green Bio Bomb+ HE Bomb Bomb Truck explosion.

Now the question is, what color to use? Green or blue?

**Comment by xezon** [comment]
Is there any strong evidence in the mission or on the INI object for Toxin or Anthrax Beta? For example does the enemy General in the Challenge mission use Anthrax? Or is the toxin damage of type Anthrax Beta? If there is no evidence either way, then I would just go with default green.

**Comment by Jundiyy** [comment]
Are we trying to make them all have the same toxins? Why not leave them all different?
Also, one of them is a Nuclear Bunker, so that should stay nuclear.

**Comment by commy2** [comment]
> Is there any strong evidence in the mission or on the INI object for Toxin or Anthrax Beta?

The Bunkers belong to Thrax, which means you have to capture them with a Lotus before you can repair them. Thrax uses Gamma, so neither green nor blue.

> I would just go with default green

That's what I am thinking. Alternatively, we could make them affected by upgrades, so they're pink in Thrax' mission, and mostly green otherwise.

> Why not leave them all different?

The issue is not that they're different, they are pretty much the same, it is that they explode with a blue particle effect and then leave a green cloud, which makes no sense.

> Also, one of them is a Nuclear Bunker

The issue is not about NuclearBunker, which works as intended.

**Comment by xezon** [comment]
If it is no hassle then can make it spill Anthrax according to owner Anthrax Upgrade. Otherwise plain green is fine too, as for Multiplayer maps with Civilian infrastructure, that would be the consequence anyway.

**Comment by MTKing4** [comment]
I think this is unnecessary to change, leave it as it is
