### ISSUE TITLE
Civilian towers destroy everything they fall on

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#909]
Civilian towers destroy everything they fall on. Easily testable on [[RANK] Canyon of the Dead](https://github.com/TheSuperHackers/GeneralsRankedMaps/tree/main/release/maps_1v1_zh/%5BRANK%5D%20Canyon%20of%20the%20Dead%20ZH%20v2). Is this a problem?

**Comment by ExiLe-ZH** [comment]
I like it. It's cool and makes the world more interactive.

**Comment by Jundiyy** [comment]
I don't think it's a problem, think it's quite a nice feature and we should keep it. Have you been hit by a train in ZH? A lot worse. 😂
The only thing I find a bit odd is that it destroys the hole as well, it's just a one time crash, it should really do a one time damage.
Not saying we should remove that part but just feels a bit strange.

**Comment by FiReArM-ZH** [comment]
I'm not saying it to remove completely but to reduce the damage it causes (maybe by 50%?)

**Comment by Stubbjax** [comment]
> I'm not saying it to remove completely but to reduce the damage it causes (maybe by 50%?)

You'd have to reduce it a lot more than 50%.
```
Weapon ToppledStructureWeapon
  PrimaryDamage = 9999.0            
End
```

**Comment by commy2** [comment]
These and the barrels should be used more on maps.

**Comment by MTKing4** [comment]
> > I'm not saying it to remove completely but to reduce the damage it causes (maybe by 50%?)
> 
> You'd have to reduce it a lot more than 50%.
> 
> ```
> Weapon ToppledStructureWeapon
>   PrimaryDamage = 9999.0            
> End
> ```

I liked the 'End' part

Definitely keep it :D

**Comment by FiReArM-ZH** [comment]
How much GLA cc with fortified structure has health including hole health? Can this take it down completely?

**Comment by xezon** [comment]
Heavy structures should have around 5000 Health.
