### ISSUE TITLE
ECM Tank should be able to shut down its missiles spreading ability

### ISSUE THREAD

**Issue by ReLaX82** [TheSuperHackers/GeneralsGamePatch#919]
Originally from Dominator:

ECMs could have a feature that allows them to disable their missile spreading ability. This would allow a china player to have a chance against EMP defences when they have ECM/overlord combo.

Also it would stop A10 from killing whole nuke army and allowing USA to win the game after nuke already struggled to get to a good position.

Probably would be some cons to it though.

**Comment by xezon** [comment]
Already fixed with
* #631

**Comment by ImTimK** [comment]
This is a different suggestion @xezon

**Comment by ZekeDlyoung** [comment]
This isn't really possible though, not unless you make the ECM field into a manual ability like Toxin Tractor's contaminate

**Comment by ReLaX82** [comment]
Ah, okay, that would then be a downgrade more for the ecm Tank.

**Comment by xezon** [comment]
Oh, I misunderstood.

**Comment by ImTimK** [comment]
> This isn't really possible though, not unless you make the ECM field into a manual ability like Toxin Tractor's contaminate

Neither with a similar mechanic like how rangers can switch weapons?

**Comment by ZekeDlyoung** [comment]
> > This isn't really possible though, not unless you make the ECM field into a manual ability like Toxin Tractor's contaminate
> 
> Neither with a similar mechanic like how rangers can switch weapons?

Hmm, I guess that is possible, but then you'll have no choice but to make all ECM tanks auto-acquire targets so that they can properly engage missiles in jammer mode 🤔

**Comment by ReLaX82** [comment]
ECM already auto-disable when in ritaliation Mode right?

**Comment by commy2** [comment]
In 1.04, it depends on your faction. In patch, you can guard mode.

**Comment by ZekeDlyoung** [comment]
Another thing to note about this change is that the AI won't know to switch to anti-missile mode without editing the scripts, if it is even possible

**Comment by xezon** [comment]
My understanding is that the default weapon would have to be the regular behaviour, and the extra weapon would have to be no behaviour. Then AI would have no issues.

**Comment by ReLaX82** [comment]
Yes, makes sense as dragons with AI dont ever use flame wall.

**Comment by ReLaX82** [comment]
Is that technically possible or not?

**Comment by commy2** [comment]
I don't think it is possible without engine modifications.

**Comment by xezon** [comment]
Moved to back log. Closed.
