### ISSUE TITLE
AFG Carpet Bomber may not hit perfectly centered on the target location

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#925]
Carpet Bomber General Powers does not hit target perfectly centered on the target location.

WIP Video

**Comment by ZekeDlyoung** [comment]
I mentioned this before on the discord server, this is because of the "units move faster when moving diagonally" bug, and it affects all GP planes

**Comment by ExiLe-ZH** [comment]
### AFG Carpet bomber test.

**Vertically the first bomb hits the ground too soon and the last bombs will not cover the marker:**

> ![vertical 1](https://user-images.githubusercontent.com/32326277/185180388-625cf067-1e82-4c44-9ea9-f671c43d5a7a.png)
> ![vertical 2](https://user-images.githubusercontent.com/32326277/185180394-6ab80dc2-8c83-4f5e-a4fe-e02315d6d739.png)
> 

**Diagonally the first bomb will hit right on the edge of the marker, but follow up bombs will spread out over a longer area and beyond the marker because it moves faster:**

> ![diagonal 1](https://user-images.githubusercontent.com/32326277/185180075-2613b4f4-8181-43cb-85e6-6f01e15667da.png)
> ![diagonal 2](https://user-images.githubusercontent.com/32326277/185180086-9cab0caf-231d-4832-88c8-90ec3247db3c.png)
> ![diagonal 3](https://user-images.githubusercontent.com/32326277/185180097-2c2f9311-0341-4ac2-a7ea-9f06d54255a5.png)

**Comment by commy2** [comment]
The bomber also makes a sharp turn on diagonal path. The turn also happens for China Bombers and Paradrops, but the B2 locomotor has the turn rate of a Raptor/Mig/Stealth Bomber instead of the one of a large plane.

**Comment by MTKing4** [comment]
Issue title should mention it's AFG Carpet Bomber, to be more descriptive

**Comment by ZekeDlyoung** [comment]
Don't all of AirF Gen's GP planes have a PDL tho?

**Comment by MTKing4** [comment]
We should see if AFG A10/B52/Spectre/C-130 Planes have PDLs too

**Comment by ZekeDlyoung** [comment]
I just realized that I posted this in the wrong thread 🙃

**Comment by commy2** [comment]
> We should see if AFG A10/B52/Spectre/C-130 Planes have PDLs too

None of them have. Only the B2 and only when Carpet Bombing.

**Comment by xezon** [comment]
With fix https://github.com/TheAssemblyArmada/Thyme/pull/752 the drop location is well balanced. This requires no changes. Closing.

![shot_20230410_180150_2](https://user-images.githubusercontent.com/4720891/230941883-113fe4fc-002a-43f3-9683-7367626a9ffb.jpg)
