### ISSUE TITLE
AFG B2 Bomber Has PDL When Calling Carpet Bombing But Not When Calling MOAB

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#926]
This is a strange difference between the two.

I don't think either should have a PDL.

**Comment by ExiLe-ZH** [comment]
Carpet then probably shouldn't have it, it's already a bonus power over the other USA's, so there shouldn't be any reason for anyone to get mad about this.

**Comment by ZekeDlyoung** [comment]
Don't all of AirF Gen's GP planes have a PDL tho?

**Comment by ZekeDlyoung** [comment]
By Commy:

> None of them have. Only the B2 and only when Carpet Bombing.

**Comment by xezon** [comment]
Looks safe and consistent to me to remove. It's also nothing really noticable in regular match.

**Comment by Jundiyy** [comment]
Please add PDL to all GPs.











Not really, think it's safe to remove.
