### ISSUE TITLE
USA Dozer Clearing Mines Animation Looks Off

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#930]
## Original Generals Clearing Mines:

https://user-images.githubusercontent.com/83613147/185665137-b6503b19-4ab7-4135-8f4b-584434947529.mp4

## Zero Hour Clearing Mines:

https://user-images.githubusercontent.com/83613147/185665245-af42f6a0-555b-44b1-a0c3-eab5db545d2e.mp4

As You can See, the sand Is Misaligned in Zero Hour

**Comment by ExiLe-ZH** [comment]
The ccg cursor marker also looks alot nicer

**Comment by commy2** [comment]
It has higher resolution, because all CCG decals have. Neither makes me think of "clearing mines" though.

**Comment by xezon** [comment]
We could make new decal. Same as original, but a mine symbol in the crossed middle.

**Comment by commy2** [comment]
The falling dust particles are missing completely for the damaged US Dozer model.
