### ISSUE TITLE
Game performance continuously drops with playtime until it reaches 0 fps

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#946]
Game performance continuously drops with playtime until it reaches 0 fps. Reproducible with all factions on empty map. Potentially we spawn something every X time that is not cleaned up properly.

**Comment by xezon** [comment]
This issue was introduced with
* #912

**Comment by commy2** [comment]
> Reproducible with all factions on empty map.

Does this mean it is reproducable with, e.g. only vChina factions on the map? Or one map with all factions at the same time?

**Comment by xezon** [comment]
I used this test map:
https://github.com/TheSuperHackers/GeneralsGamePatch/tree/main/Maps/Any/!TestAllFactions

It has all faction Command Centers placed indeed.
