### ISSUE TITLE
Some immortal game objects may never be deleted during map run time

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#952]
Some immortal game objects may never be deleted during map run time.

Here is list of ImmortalBody objects without a DeletionUpdate Behaviour Module.

- [x] GPSScrambler_InvisibleMarker
- [x] WaveGuide
- [x] WaveGuideGLA01
- [ ] VisionObject
- [ ] 300MeterShroudClearObject
- [x] Slth_GLAInfantryAngryMobNexus   (has DestroyDie)
- [x] GLAInfantryAngryMobNexus        (has DestroyDie)
- [x] CINE_GLAInfantryAngryMobNexus   (has DestroyDie)
- [x] Demo_GLAInfantryAngryMobNexus   (has DestroyDie)
- [x] Chem_GLAInfantryAngryMobNexus   (has DestroyDie)
- [x] Boss_InfantryAngryMobNexus      (has DestroyDie)
- [x] AmericaAircraftCarrier          (has empty DestroyDie)
- [x] AmericaBattleshipBogusTarget
- [x] CINE_SnowyMountainScrollingSnow (has DestroyDie)
- [x] CINE_SnowyMountainStatic        (has DestroyDie)
- [x] PlanterRound                    (has DestroyDie)
- [x] PlanterSquare                   (has DestroyDie)
- [x] ToxinRepository
- [x] SupplyPileSmall
- [x] SupplyPile
- [x] SupplyDock
- [x] SupplyWarehouse
- [x] GenericBridge
- [x] GenericBridgeTower
- [x] CruiseMissile

**Comment by commy2** [comment]
GPSScrambler_InvisibleMarker is deleted by GrantStealthBehavior module.

Supplies as well as Bridges are meant to be immortal and undeletable.

ToxinRepository is a supply for the campaign ("Jarmen and the foury thieves").

**Comment by commy2** [comment]
Not an immortal object (just UNATTACKABLE), but `CruiseMissile` is never deleted, because it has no SlowDeathBehaviour module. This also causes the exhaust particles to spawn forever, where the missile impacted.

**Comment by xezon** [comment]
Is CruiseMissile used by anything of importance?

**Comment by commy2** [comment]
No, it is used by the Cruise Missile, a map editor only building that doesn't even appear in the campaign.

**Comment by commy2** [comment]
Some objects are only used in the CCG campaign:

- AmericaBattleshipBogusTarget in USA04 cutscene map
- WaveGuide in China03
- WaveGuideGLA01 in GLA01 (duh)

Not really used anywhere in ZH, but I would still keep them immortal. There is certainly no danger of them flooding the map (with copies of themselves that is).

**Comment by commy2** [comment]
https://github.com/TheSuperHackers/GeneralsGamePatch/assets/6576312/dc055261-67b9-48b4-9887-8e14d7c9d0f1

Mob nexus is properly deleted. I conclude that DestroyDie is sufficient and mark the rest of those.

**Comment by commy2** [comment]
Cruise missile is fixed/will be fixed in https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2122.

I do not think VisionObject and 300MeterShroudClearObject are meant to be destructible. If they linger, then that would be obvious as they reveal an area around them. 

I think we can close.

**Comment by xezon** [comment]
Thank you for checking.
