### ISSUE TITLE
GLA Bomb Truck turn speed is halved when critically damaged

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#959]
GLA Bomb Truck turn speed is halved when critically damaged. But forward speed is not affected.

## Forward

https://user-images.githubusercontent.com/4720891/185979714-593195c6-942e-4610-b434-ee26200915bb.mp4

## Turn

https://user-images.githubusercontent.com/4720891/185979742-c47e0e94-aea9-4c70-91f4-3411d888e228.mp4

### Proposal 1

Bomb Truck turn speed is 100% when critically damaged.

### Proposal 2

Bomb Truck forward speed is 50% when critically damaged.

### Proposal 3

Bomb Truck turn speed and forward speed is 75% when critically damaged.

**Comment by xezon** [comment]
I think the slow turn looks silly in combination with the fast forward speed.

**Comment by ZekeDlyoung** [comment]
Are there videos on what the proposals look like?
