### ISSUE TITLE
China Inferno Cannon does not create fire storm reliably

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#963]
China Inferno Cannon does not create fire storm reliably. This mostly occurs with force-fire on terrain.

Related
* TheSuperHackers/GeneralsGameCode#1760 

## On force fire

https://user-images.githubusercontent.com/4720891/186125980-8f2a1351-3380-4605-bfe4-db888248e739.mp4

## On scaffold

Using 3 infernos to kill the scaffold will not create the firestorm, while other buildings will.

https://user-images.githubusercontent.com/4720891/186126008-c547f4c3-1398-44e1-b087-27913f530c6b.mp4

**Comment by xezon** [comment]
Stubbjax:
> Inferno Cannon can trigger firestorm on force fire, but it takes a lot of attempts, even when left firing at the exact same position. When targeting an actual object, it will create them every time.

Zeke:
> Perhaps some shells are not detonating properly. Like perhaps some of the shells are being accidentally destroyed by the other shells. This was a thing for the Artillery Barrage.

hanfield:
> It is related to weapon template iirc [?]

**Comment by commy2** [comment]
Probably not the limitation here, but there can only ever exist max 3 firestorms at once on a map. This is important when mass attacking with Migs.
