### ISSUE TITLE
USA Scout and Hellfire drone have astonishing Cloud Clearing Range, Battle Drone does not

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#983]
USA Scout and Hellfire drone have astonishing Cloud Clearing Range, Battle Drone does not.

| Object                           | Shroud Clearing Range | Area       |
|----------------------------------|-----------------------|-----------:|
| Original USA Sentry Drone        | 350                   | 384845     |
| Original USA Scout Drone         | 500 (+75+10 wander)   | min 785398 |
| Original USA Battle Drone        | 150 (+75+10 wander)   | 70685      |
| Original USA Hellfire Drone      | 500 (+75+10 wander)   | min 785398 |
| Original USA Humvee              | 320                   | 321699     |
| Original USA Missile Defender    | 400                   | 502654     |
| Original China Outpost           | 500                   | 785398     |
| Original China Lotus             | 400                   | 502654     |

**Comment by commy2** [comment]
This' what happens when you copy paste.

**Comment by ExiLe-ZH** [comment]
It's the purpose of scout drone, nerf hellfire. 

Also buff sentry drone 😀

**Comment by MTKing4** [comment]
Nerf Hellfire to 150
