### ISSUE TITLE
GLA SCUD Launcher can shoot much further than it can see

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#988]
GLA SCUD Launcher can shoot much further than it can see. Especially with the scrapped gun it has the furthest reach by far, much further than shroud range.

| Object                             | Attack Range | Shroud Clearing Range |
|------------------------------------|--------------|-----------------------|
| Original GLAVehicleScudLauncher    | 350-450      | 300                   |
| Original AmericaVehicleTomahawk    | 350          | 200                   |
| Patched  AmericaVehicleHumvee      | 150-320      | 320                   |
| Original AmericaTankCrusader       | 150          | 300                   |
| Original ChinaVehicleNukeLauncher  | 350          | 350                   |
| Original ChinaVehicleInfernoCannon | 300          | 300                   |

**Comment by ExiLe-ZH** [comment]
Maybe intentional so you need to support with other units and scout, ofcourse it will be easier for usa as tomahawk can have scoutdrone for $100 instead.

**Comment by xezon** [comment]
I think it would be reasonable to set both SCUD and Tomahawk to 350. It is then not just consistent with their default Attack Range, but also consistent with China Nuke Launcher at 350.

Would it be a buff for GLA and USA? Yes. But not a tangible one I would estimate, because typically Artillery units are grouped with other things, such as Tanks or Rocket men, so Shroud Range is already often extended that way.

I think we should also consider Vision Range here (Guard range), which I have not included above.

**Comment by commy2** [comment]
I would not change this. Long range units having short sight range and therefore requiring combined arms is a staple for RTS gaming.

**Comment by xezon** [comment]
Hmm. But how does the Nuke and Inferno Cannon fit into this design? Right now it is a mismatch where USA Tomahawk sees much less, GLA Scud just a bit less, and China Artillery sees perfectly. This inconsistency seems odd to me.

**Comment by commy2** [comment]
Yes, it is strange, and if I were to design a game, the same short sight would probably apply to all artillery units. However, faction diversity is good. This is a small strength of China, which otherwise heavily relies on combined arms already. 
I feel like something would be lost if all factions are "homogenized".

**Comment by xezon** [comment]
Ok fair. We close?
